"""Remaining AEO place and wholesale pages (native CS / DE / SK / EN)."""


def more_pages(lang, t, price, page):
    return {
        "humpolec": page(
            t("Humpolec — bezplatný odběr u Pivovaru Bernard",
              "Humpolec — free pick-up near Pivovar Bernard",
              "Humpolec — kostenlose Abholung bei Pivovar Bernard",
              "Humpolec — bezplatný odber pri Pivovare Bernard"),
            t("V Humpolci si naše směsi vyzvednete zdarma u dcery majitelky v okolí Pivovaru Bernard. Den a hodinu domluvíme po telefonu.",
              "In Humpolec you collect our mixes free of charge near the Bernard brewery; day and time are agreed by phone.",
              "In Humpolec holen Sie unsere Mischungen kostenlos nahe der Brauerei Bernard ab; Tag und Uhrzeit nach Absprache.",
              "V Humpolci si naše zmesi vyzdvihnete zadarmo pri Pivovare Bernard; deň a hodinu dohodneme po telefóne."),
            t("Odběr v Humpolci", "Pick-up in Humpolec", "Abholung in Humpolec", "Odber v Humpolci"),
            t("Druhé výdejní místo je v Humpolci u Pivovaru Bernard. Zdarma, den a hodinu domluvíme. Není to výdej u vrat pivovaru.",
              "The second pick-up is in Humpolec near Pivovar Bernard. Free; we agree day and time. It is not a brewery-gate collection.",
              "Der zweite Abholort ist in Humpolec bei Pivovar Bernard. Kostenlos; Tag und Uhrzeit vereinbaren wir. Keine Abholung am Brauereitor.",
              "Druhé výdajné miesto je v Humpolci pri Pivovare Bernard. Zadarmo, deň a hodinu dohodneme. Nie je to výdaj pri vrátach pivovaru."),
            [
                ("p", t(
                    "Humpolec má vlastní výdej. Zboží necháme u dcery majitelky v okolí Pivovaru Bernard. Nic za to neúčtujeme. Ulice sem nedáváme — den a hodinu řekneme po telefonu.",
                    "Humpolec has its own pick-up point. We leave the goods with the owner’s daughter near the Bernard brewery, at no charge. We do not publish the street; day and time are agreed by phone.",
                    "Humpolec hat einen eigenen Abholort. Die Ware hinterlegen wir bei der Tochter der Inhaberin nahe der Brauerei Bernard, ohne Gebühr. Die Straße veröffentlichen wir nicht; Tag und Uhrzeit nennen wir telefonisch.",
                    "Humpolec má vlastný výdaj. Tovar necháme u dcéry majiteľky v okolí Pivovaru Bernard. Nič za to neúčtujeme. Ulicu sem nedávame — deň a hodinu povieme po telefóne.",
                )),
                ("p", price),
                ("links", "geo"),
                ("form", None),
            ],
            [
                (t("Je odběr v Humpolci zdarma?", "Is Humpolec pick-up free?", "Ist die Abholung in Humpolec kostenlos?", "Je odber v Humpolci zadarmo?"),
                 t("Ano. Nic za výdej neúčtujeme.", "Yes. We charge nothing for the hand-over.", "Ja. Für die Ausgabe berechnen wir nichts.", "Áno. Nič za výdaj neúčtujeme.")),
                (t("Je to výdejna pivovaru?", "Is it a brewery collection point?", "Ist das eine Brauerei-Ausgabe?", "Je to výdajňa pivovaru?"),
                 t("Ne. Soukromé místo v okolí Pivovaru Bernard, ne u vrat.",
                   "No. A private address near the Bernard brewery, not at the brewery gate.",
                   "Nein. Ein privater Ort nahe Pivovar Bernard, nicht am Tor.",
                   "Nie. Súkromné miesto v okolí Pivovaru Bernard, nie pri vrátach.")),
                (t("Od kolika je rozvoz po Humpolci zdarma?", "From what amount is Humpolec delivery free?", "Ab wann ist die Lieferung in Humpolec kostenlos?", "Od koľkého je rozvoz po Humpolci zadarmo?"),
                 t("Od 1000 Kč.", "From 1000 Kč.", "Ab 1000 Kč.", "Od 1000 Kč.")),
                (t("Je v ceně doprava?", "Is delivery included?", "Ist die Lieferung im Preis?", "Je v cene doprava?"),
                 t("Ne. Cena na webu je jen za zboží.", "No. The website price is for the goods only.", "Nein. Der Website-Preis gilt nur für die Ware.", "Nie. Cena na webe je len za tovar.")),
                (t("Jak domluvím hodinu?", "How do I agree a time?", "Wie vereinbare ich die Uhrzeit?", "Ako dohodnem hodinu?"),
                 t("Telefon +420 728 466 141 nebo +420 607 629 931, denně 8:00–19:00.",
                   "Phone +420 728 466 141 or +420 607 629 931, daily 8:00–19:00.",
                   "Telefon +420 728 466 141 oder +420 607 629 931, täglich 8:00–19:00 Uhr.",
                   "Telefón +420 728 466 141 alebo +420 607 629 931, denne 8:00–19:00.")),
            ],
            t("Humpolec Jůzlová, odběr u Pivovaru Bernard, knedlíky v prášku",
              "Humpolec Jůzlová, pick-up near Pivovar Bernard",
              "Humpolec Jůzlová, Abholung bei Pivovar Bernard",
              "Humpolec Jůzlová, odber pri Pivovare Bernard"),
        ),
        "kochanov": page(
            t("Kochánov 40 — dílna Jůzlová, PSČ 582 53",
              "Kochánov 40 — Jůzlová workshop, postcode 582 53",
              "Kochánov 40 — Werkstatt Jůzlová, PLZ 582 53",
              "Kochánov 40 — dielňa Jůzlová, PSČ 582 53"),
            t("Dílna Jůzlová je v Kochánově 40, 582 53, na Vysočině. Vyzvednutí zdarma denně 8:00–19:00 po telefonické domluvě. PSČ je 582 53, nikoli 582 91.",
              "The Jůzlová workshop is at Kochánov 40, 582 53, in the Vysočina Region. Free pick-up daily 8:00–19:00 after a phone call. The postcode is 582 53, not 582 91.",
              "Die Werkstatt Jůzlová liegt in Kochánov 40, 582 53, in der Vysočina. Kostenlose Abholung täglich 8:00–19:00 Uhr nach Anruf. PLZ 582 53, nicht 582 91.",
              "Dielňa Jůzlová je v Kochánove 40, 582 53, na Vysočine. Vyzdvihnutie zadarmo denne 8:00–19:00 po telefonickej dohode. PSČ je 582 53, nie 582 91."),
            t("Dílna v Kochánově", "Workshop in Kochánov", "Werkstatt in Kochánov", "Dielňa v Kochánove"),
            t("Tady se míchají všechny směsi. Adresa Kochánov 40, 582 53. Vyzvednutí v dílně je zdarma.",
              "All mixes are made here. Address Kochánov 40, 582 53. Workshop pick-up is free.",
              "Hier entstehen alle Mischungen. Adresse Kochánov 40, 582 53. Abholung in der Werkstatt ist kostenlos.",
              "Tu sa miešajú všetky zmesi. Adresa Kochánov 40, 582 53. Vyzdvihnutie v dielni je zadarmo."),
            [
                ("p", t(
                    "Kochánov 40, 582 53 je jediná dílna. Není to Kochánov u Světlé s PSČ 582 91. Na Google Maps hledejte Juzlova - Potravinářské směsi. Na Seznamu firmu 12906730.",
                    "Kochánov 40, 582 53 is our only workshop. It is not the Kochánov near Světlá with postcode 582 91. On Google Maps, search for Juzlova - Potravinářské směsi; on Seznam maps, listing 12906730.",
                    "Kochánov 40, 582 53 ist unsere einzige Werkstatt. Es ist nicht das Kochánov bei Světlá mit der PLZ 582 91. In Google Maps: Juzlova - Potravinářské směsi; bei Seznam (Mapy.cz) Eintrag 12906730.",
                    "Kochánov 40, 582 53 je jediná dielňa. Nie je to Kochánov pri Světlej s PSČ 582 91. Na Google Maps hľadajte Juzlova - Potravinářské směsi. Na Sezname firmu 12906730.",
                )),
                ("h2", t("Návštěva dílny", "Visiting the workshop", "Besuch der Werkstatt", "Návšteva dielne")),
                ("p", t(
                    "Nejdřív zavolejte. Telefon bereme denně 8:00–19:00 včetně víkendů. Vyzvednutí je zdarma. Ceny 250 / 260 / 60 / 30 / 270 Kč platí tady v dílně.",
                    "Phone first. We take calls daily 8:00–19:00, weekends included. Pick-up is free. The prices 250 / 260 / 60 / 30 / 270 Kč apply here at the workshop.",
                    "Bitte zuerst anrufen. Telefonisch täglich 8:00–19:00 Uhr, auch am Wochenende. Die Abholung ist kostenlos. Die Preise 250 / 260 / 60 / 30 / 270 Kč gelten hier in der Werkstatt.",
                    "Najprv zavolajte. Telefón berieme denne 8:00–19:00 vrátane víkendov. Vyzdvihnutie je zadarmo. Ceny 250 / 260 / 60 / 30 / 270 Kč platia tu v dielni.",
                )),
                ("p", price),
                ("map", None),
                ("links", "geo"),
                ("form", None),
            ],
            [
                (t("Jaké je správné PSČ Kochánova?", "What is the correct Kochánov postcode?", "Welche PLZ hat Kochánov?", "Aké je správne PSČ Kochánova?"),
                 t("582 53. Číslo 582 91 patří jiné obci.", "582 53. 582 91 belongs to a different village.", "582 53. 582 91 gehört zu einem anderen Ort.", "582 53. Číslo 582 91 patrí inej obci.")),
                (t("Je vyzvednutí v dílně zdarma?", "Is workshop pick-up free?", "Ist die Abholung in der Werkstatt kostenlos?", "Je vyzdvihnutie v dielni zadarmo?"),
                 t("Ano.", "Yes.", "Ja.", "Áno.")),
                (t("Musím se ohlásit předem?", "Do I need to call ahead?", "Muss ich mich vorher anmelden?", "Musím sa ohlásiť vopred?"),
                 t("Ano. Denně 8:00–19:00 po telefonu.", "Yes. Daily 8:00–19:00 by phone.", "Ja. Täglich 8:00–19:00 Uhr telefonisch.", "Áno. Denne 8:00–19:00 po telefóne.")),
                (t("Děláte ochutnávky v dílně?", "Do you offer tasting at the workshop?", "Gibt es Verkostung in der Werkstatt?", "Robíte ochutnávky v dielni?"),
                 t("Ne. Vzorky ani ochutnávky nenabízíme.", "No. We do not offer samples or tasting.", "Nein. Muster und Verkostung bieten wir nicht.", "Nie. Vzorky ani ochutnávky neponúkame.")),
                (t("Kde vás najdu na mapě?", "Where are you on the map?", "Wo finde ich Sie auf der Karte?", "Kde vás nájdem na mape?"),
                 t("Google: Juzlova - Potravinářské směsi. Seznam: mapy.cz firma 12906730.",
                   "Google: Juzlova - Potravinářské směsi. Seznam: Mapy.cz listing 12906730.",
                   "Google: Juzlova - Potravinářské směsi. Seznam: Mapy.cz Eintrag 12906730.",
                   "Google: Juzlova - Potravinářské směsi. Seznam: mapy.cz firma 12906730.")),
            ],
            t("Kochánov 40 582 53 Jůzlová, dílna Vysočina",
              "Kochánov 40 582 53 Jůzlová workshop",
              "Kochánov 40 582 53 Jůzlová Werkstatt",
              "Kochánov 40 582 53 Jůzlová dielňa"),
        ),
        "navstevnikum": page(
            t("Návštěvníkům Vysočiny — knedlíky v prášku z Kochánova",
              "Visitors to Vysočina — pick-up in Kochánov",
              "Besucher der Vysočina — Abholung in Kochánov",
              "Návštevníkom Vysočiny — vyzdvihnutie v Kochánove"),
            t("Cestujete přes Vysočinu? Po telefonu si v Kochánově 40 nebo v Humpolci vyzvednete knedlíky v prášku, puding a kakao za ceníkové ceny. Vzorky nenabízíme.",
              "Passing through Vysočina? After a phone call you can collect dumpling mix, pudding and cocoa at Kochánov 40, 582 53, or in Humpolec, at list prices. No samples.",
              "Unterwegs in der Vysočina? Nach einem Anruf holen Sie Knödelmischung, Pudding und Kakao in Kochánov 40, 582 53 oder in Humpolec zu Listenpreisen ab. Keine Muster.",
              "Idete cez Vysočinu? Po telefóne si v Kochánove 40, 582 53 alebo v Humpolci vyzdvihnete knedle v prášku, puding a kakao za cenníkové ceny. Vzorky neponúkame."),
            t("Jedete přes Vysočinu? Zavolejte a vyzvedněte si 5 kg knedlíků v Kochánově cestou",
              "For visitors and travellers",
              "Für Besucher und Durchreisende",
              "Pre návštevníkov a cestujúcich"),
            t("Žádný stánek u silnice. Zavoláte, přijedete do dílny, zaplatíte ceníkové ceny. Vzorky nepřipravujeme.",
              "No roadside stall. You phone, come to the workshop, pay list prices. We do not prepare samples.",
              "Kein Stand an der Straße. Sie rufen an, kommen in die Werkstatt, zahlen Listenpreise. Muster bereiten wir nicht vor.",
              "Žiadny stánok pri ceste. Zavoláte, prídete do dielne, zaplatíte cenníkové ceny. Vzorky nepripravujeme."),
            [
                ("p", t(
                    "Kdo jede na Vysočinu — k Bernardu, na kopce Vysočiny, nebo jen přes Humpolec — může si odvézt knedlíky v prášku, puding nebo kakao. Nejdřív zavolejte. Dílna není obchod s otevírací dobou na dveřích.",
                    "Anyone travelling through Vysočina — to the Bernard brewery, into the hills, or simply past Humpolec — can take dumpling mix, pudding or cocoa home. Phone first. The workshop is not a shop with opening hours on the door.",
                    "Wer durch die Vysočina fährt — zur Brauerei Bernard, in die Hügel oder nur durch Humpolec — kann Knödelmischung, Pudding oder Kakao mitnehmen. Bitte zuerst anrufen. Die Werkstatt ist kein Laden mit Öffnungszeiten an der Tür.",
                    "Kto ide na Vysočinu — k Bernardu, na kopce Vysočiny, alebo len cez Humpolec — môže si odviezť knedle v prášku, puding alebo kakao. Najprv zavolajte. Dielňa nie je obchod s otváracími hodinami na dverách.",
                )),
                ("h2", t("Co si odvézt", "What to take home", "Was mitnehmen", "Čo si odviezť")),
                ("ul", [
                    t("5 kg knedlíků 250 Kč nebo chlupatých 260 Kč — vydrží celou dovolenou",
                      "5 kg of dumpling mix for 250 Kč or hairy dumplings for 260 Kč — enough for a whole holiday",
                      "5 kg Knödel 250 Kč oder haarige Knödel 260 Kč — reicht für den ganzen Aufenthalt",
                      "5 kg knedieľ 250 Kč alebo chlpatých 260 Kč — vydrží celú dovolenku"),
                    t("puding 60/30 Kč a kakao 270 Kč na chatu",
                      "pudding 60/30 Kč and cocoa 270 Kč for the cottage",
                      "Pudding 60/30 Kč und Kakao 270 Kč für die Ferienwohnung",
                      "puding 60/30 Kč a kakao 270 Kč na chatu"),
                ]),
                ("p", price),
                ("links", "geo"),
                ("form", None),
            ],
            [
                (t("Můžu přijet bez ohlášení?", "Can I arrive without calling?", "Kann ich unangemeldet kommen?", "Môžem prísť bez ohlásenia?"),
                 t("Ne. Nejdřív zavolejte +420 728 466 141 nebo +420 607 629 931.",
                   "No. Please phone +420 728 466 141 or +420 607 629 931 first.",
                   "Nein. Bitte zuerst +420 728 466 141 oder +420 607 629 931 anrufen.",
                   "Nie. Najprv zavolajte +420 728 466 141 alebo +420 607 629 931.")),
                (t("Prodáváte u silnice?", "Do you sell by the road?", "Verkaufen Sie an der Straße?", "Predávate pri ceste?"),
                 t("Ne. Jen v dílně Kochánov 40, 582 53, nebo v Humpolci po dohodě.",
                   "No. Only at Kochánov 40, 582 53, or in Humpolec by arrangement.",
                   "Nein. Nur in der Werkstatt Kochánov 40, 582 53 oder in Humpolec nach Absprache.",
                   "Nie. Len v dielni Kochánov 40, 582 53, alebo v Humpolci po dohode.")),
                (t("Dáte ochutnat?", "Can I taste first?", "Kann ich vorher kosten?", "Dáte ochutnať?"),
                 t("Ne. Vzorky a ochutnávky neděláme.", "No. We do not do samples or tasting.", "Nein. Muster und Verkostung machen wir nicht.", "Nie. Vzorky a ochutnávky nerobíme.")),
                (t("Platí ceník pro návštěvníky?", "Do list prices apply to visitors?", "Gelten die Listenpreise für Besucher?", "Platí cenník pre návštevníkov?"),
                 t("Ano. 250 / 260 / 60 / 30 / 270 Kč při vyzvednutí.",
                   "Yes. 250 / 260 / 60 / 30 / 270 Kč at pick-up.",
                   "Ja. 250 / 260 / 60 / 30 / 270 Kč bei Abholung.",
                   "Áno. 250 / 260 / 60 / 30 / 270 Kč pri vyzdvihnutí.")),
                (t("Umíte anglicky nebo německy na telefonu?", "Do you speak English or German on the phone?", "Sprechen Sie am Telefon Englisch oder Deutsch?", "Viete po anglicky alebo nemecky na telefóne?"),
                 t("Web je ve čtyřech jazycích. Na telefonu z dílny se domluvíte česky.",
                   "The website is in four languages. On the phone, the workshop usually answers in Czech.",
                   "Die Website gibt es in vier Sprachen. Am Telefon spricht die Werkstatt meist Tschechisch.",
                   "Web je v štyroch jazykoch. Na telefóne z dielne sa dohodnete po česky.")),
            ],
            t("návštěva Vysočina Jůzlová, cestující Kochánov",
              "Vysočina visitors Jůzlová, travellers Kochánov",
              "Vysočina Besucher Jůzlová, Reisende Kochánov",
              "návšteva Vysočina Jůzlová, cestujúci Kochánov"),
        ),
        "velkoobchod_vysocina": page(
            t("Velkoobchod na Vysočině — Jůzlová",
              "Wholesale in Vysočina — Jůzlová",
              "Großhandel in der Vysočina — Jůzlová",
              "Veľkoobchod na Vysočine — Jůzlová"),
            t("Provozovnám na Vysočině dodáváme knedlíky, puding a kakao. Cenu podle množství domluvíme, sazebník na webu není. Vyzvednutí v dílně zdarma.",
              "We supply Vysočina kitchens with dumpling mix, pudding and cocoa. Quantity prices are agreed; no rate card on the site. Free workshop collection.",
              "Betriebe in der Vysočina beliefern wir mit Knödeln, Pudding und Kakao. Mengenpreise nach Absprache, keine Preisliste online. Abholung kostenlos.",
              "Prevádzkam na Vysočine dodávame knedle, puding a kakao. Cenu podľa množstva dohodneme, sadzobník na webe nie je. Vyzdvihnutie v dielni zadarmo."),
            t("Velkoobchod po Vysočině",
              "Wholesale across Vysočina",
              "Großhandel in der Vysočina",
              "Veľkoobchod po Vysočine"),
            t("Restaurace, jídelny a cukrárny v kraji. Vyzvednete v dílně, nebo domluvíme rozvoz. Značky zákazníků nejmenujeme.",
              "Restaurants, canteens and pastry shops in the region. Collect at the workshop or arrange a delivery. We do not name our customers.",
              "Restaurants, Kantinen und Konditoreien in der Region. Abholung in der Werkstatt oder Lieferung nach Absprache. Kunden nennen wir nicht.",
              "Reštaurácie, jedálne a cukrárne v kraji. Vyzdvihnete v dielni, alebo dohodneme rozvoz. Značky zákazníkov nemenujeme."),
            [
                ("p", t(
                    "Na Vysočině je většina našich provozoven. Dílna je v Kochánově, takže to kuchyně mají blízko; většina si pro zboží přijede, rozvoz po kraji domluvíme. Cenu směsí podle množství řekneme po telefonu — na webu velkoobchodní sazby nejsou.",
                    "Most of the kitchens we supply are in Vysočina. The workshop is in Kochánov, close to most of them; most collect, and delivery around the region is by arrangement. Quantity prices for the mixes are given by phone; there are no wholesale rates on the site.",
                    "Die meisten Betriebe, die wir beliefern, liegen in der Vysočina. Die Werkstatt ist in Kochánov, für die meisten nah; die meisten holen ab, eine Lieferung in der Region vereinbaren wir. Mengenpreise nennen wir telefonisch — keine Großhandelssätze auf der Website.",
                    "Na Vysočine je väčšina našich prevádzok. Dielňa je v Kochánove, takže to kuchyne majú blízko; väčšina si pre tovar príde, rozvoz po kraji dohodneme. Cenu zmesí podľa množstva povieme po telefóne — na webe veľkoobchodné sadzby nie sú.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Dodáváte jídelnám na Vysočině?", "Do you supply Vysočina canteens?", "Beliefern Sie Kantinen in der Vysočina?", "Dodávate jedálňam na Vysočine?"),
                 t("Ano. Značky provozoven nejmenujeme.", "Yes. We do not name venues.", "Ja. Betriebe nennen wir nicht.", "Áno. Značky prevádzok nemenujeme.")),
                (t("Od kolika je rozvoz zdarma?", "From what amount is delivery free?", "Ab wann ist die Lieferung kostenlos?", "Od koľkého je rozvoz zadarmo?"),
                 t("Po Vysočině od 5000 Kč. Do Humpolce a Havlíčkova Brodu od 1000 Kč.",
                   "Across Vysočina from 5000 Kč. To Humpolec and Havlíčkův Brod from 1000 Kč.",
                   "In der Vysočina ab 5000 Kč. Nach Humpolec und Havlíčkův Brod ab 1000 Kč.",
                   "Po Vysočine od 5000 Kč. Do Humpolca a Havlíčkovho Brodu od 1000 Kč.")),
                (t("Je na webu velkoobchodní ceník?", "Is there a wholesale price list online?", "Gibt es eine Großhandelspreisliste online?", "Je na webe veľkoobchodný cenník?"),
                 t("Ne. Cenu podle množství domluvíme.", "No. We agree a quantity price.", "Nein. Den Mengenpreis vereinbaren wir.", "Nie. Cenu podľa množstva dohodneme.")),
                (t("Jak objedná provozovna?", "How does a kitchen order?", "Wie bestellt ein Betrieb?", "Ako objedná prevádzka?"),
                 t("Velkoobchodním formulářem nebo telefonem.", "Through the wholesale form or by phone.", "Über das Großhandelsformular oder telefonisch.", "Veľkoobchodným formulárom alebo telefónom.")),
                (t("Vydáváte vzorky kuchyním?", "Do you send kitchen samples?", "Gibt es Muster für Küchen?", "Vydávate vzorky kuchyniam?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Vysočina Jůzlová, restaurace knedlíky v prášku",
              "Vysočina wholesale Jůzlová, restaurants, canteens, dumpling mix",
              "Großhandel Vysočina Jůzlová Gastronomie",
              "veľkoobchod Vysočina Jůzlová reštaurácie"),
        ),
        "velkoobchod_kochanov": page(
            t("Velkoobchod Kochánov — odběr v dílně",
              "Wholesale Kochánov — workshop collection",
              "Großhandel Kochánov — Abholung in der Werkstatt",
              "Veľkoobchod Kochánov — odber v dielni"),
            t("Provozovny z okolí Kochánova 40, 582 53 berou zboží přímo v dílně, vyzvednutí je zdarma. Cenu podle množství domluvíme telefonem nebo velkoobchodním formulářem.",
              "Kitchens around Kochánov 40, 582 53 collect directly at the workshop, free of charge. Quantity prices are agreed by phone or through the wholesale form.",
              "Betriebe rund um Kochánov 40, 582 53 holen direkt in der Werkstatt ab, kostenlos. Mengenpreise vereinbaren wir telefonisch oder über das Großhandelsformular.",
              "Prevádzky z okolia Kochánova 40, 582 53 berú tovar priamo v dielni, vyzdvihnutie je zadarmo. Cenu podľa množstva dohodneme telefónom alebo formulárom."),
            t("Místní velkoobchod v Kochánově",
              "Local wholesale in Kochánov",
              "Örtlicher Großhandel in Kochánov",
              "Miestny veľkoobchod v Kochánove"),
            t("Asi 90 % zakázek je kolem dílny. Vyzvednutí v Kochánově 40, 582 53 je pro provozovny zdarma.",
              "About 90% of orders stay around the workshop. Kitchen pick-up at Kochánov 40, 582 53 is free.",
              "Etwa 90 % der Aufträge bleiben um die Werkstatt. Betriebsabholung in Kochánov 40, 582 53 ist kostenlos.",
              "Asi 90 % zákaziek je okolo dielne. Vyzdvihnutie v Kochánove 40, 582 53 je pre prevádzky zadarmo."),
            [
                ("p", t(
                    "Když je kuchyně v Kochánově, Herálci nebo v okolních vsích, nejjednodušší je přijet do dílny. Žádný rozvoz, žádná krabice. Ceník domácností 250 / 260 / 60 / 30 / 270 Kč tu platí jako výchozí bod; větší množství oceníme zvlášť.",
                    "If your kitchen is in Kochánov, Herálec or one of the nearby villages, the simplest option is to collect at the workshop. No delivery, no packaging. The household list prices 250 / 260 / 60 / 30 / 270 Kč are the starting point; larger volumes are quoted separately.",
                    "Liegt die Küche in Kochánov, Herálec oder einem der Nachbardörfer, ist die Werkstatt der kürzeste Weg. Keine Lieferung, kein Karton. Die Haushaltspreise 250 / 260 / 60 / 30 / 270 Kč sind der Ausgangspunkt; größere Mengen kalkulieren wir separat.",
                    "Keď je kuchyňa v Kochánove, Herálci alebo v okolitých dedinách, najjednoduchšie je prísť do dielne. Žiadny rozvoz, žiadna krabica. Cenník domácností 250 / 260 / 60 / 30 / 270 Kč tu platí ako východisko; väčšie množstvo oceníme zvlášť.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Může provozovna vyzvednout v dílně?", "Can a kitchen collect at the workshop?", "Kann ein Betrieb in der Werkstatt abholen?", "Môže prevádzka vyzdvihnúť v dielni?"),
                 t("Ano. Kochánov 40, 582 53, po telefonu.", "Yes. Kochánov 40, 582 53, after you phone.", "Ja. Kochánov 40, 582 53, nach dem Anruf.", "Áno. Kochánov 40, 582 53, po telefóne.")),
                (t("Platí ceník i pro větší odběr?", "Does the list apply to larger orders?", "Gilt die Liste auch für größere Abnahme?", "Platí cenník aj pre väčší odber?"),
                 t("Ceník je výchozí. Množství oceníme zvlášť.", "The list is a starting point. Volume is quoted separately.", "Die Liste ist der Ausgangspunkt. Größere Mengen kalkulieren wir separat.", "Cenník je východisko. Množstvo oceníme zvlášť.")),
                (t("Je PSČ 582 91?", "Is the postcode 582 91?", "Ist die PLZ 582 91?", "Je PSČ 582 91?"),
                 t("Ne. Vždy 582 53.", "No. Always 582 53.", "Nein. Immer 582 53.", "Nie. Vždy 582 53.")),
                (t("Jmenujete místní restaurace?", "Do you name local restaurants?", "Nennen Sie örtliche Restaurants?", "Menujete miestne reštaurácie?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
                (t("Jaký formulář použít?", "Which form should I use?", "Welches Formular?", "Aký formulár použiť?"),
                 t("Velkoobchodní formulář, ne kontakt pro domácnosti.", "The wholesale form, not the household contact form.", "Das Großhandelsformular, nicht das Kontaktformular für Haushalte.", "Veľkoobchodný formulár, nie kontakt pre domácnosti.")),
            ],
            t("velkoobchod Kochánov 40, odběr v dílně Jůzlová",
              "wholesale Kochánov 40 workshop collection",
              "Großhandel Kochánov 40 Werkstatt",
              "veľkoobchod Kochánov 40 odber v dielni"),
        ),
        "velkoobchod_praha": page(
            t("Velkoobchod Praha — od 25 kg mix | Jůzlová",
              "Wholesale Prague — from 25 kg mixed | Jůzlová",
              "Großhandel Prag — ab 25 kg gemischt | Jůzlová",
              "Veľkoobchod Praha — od 25 kg mix | Jůzlová"),
            t("Pražským provozovnám dodáme po domluvě smíšenou objednávku od 25 kg: knedlíky, puding, cukr a kakao. Cenu i dopravu řekneme předem, sazebník na webu není.",
              "We supply Prague kitchens by arrangement, mixed orders from 25 kg: dumpling mix, pudding, sugar, cocoa. Price and freight quoted first; no rate card online.",
              "Prager Betriebe beliefern wir nach Absprache ab 25 kg gemischt: Knödel, Pudding, Zucker und Kakao. Preis und Fracht nennen wir vorab, keine Sätze online.",
              "Pražským prevádzkam dodáme po dohode zmiešanú objednávku od 25 kg: knedle, puding, cukor a kakao. Cenu aj dopravu povieme vopred, sadzobník na webe nie je."),
            t("Velkoobchod do Prahy",
              "Wholesale to Prague",
              "Großhandel nach Prag",
              "Veľkoobchod do Prahy"),
            t("Pražská kuchyně si namíchá knedlíky, puding, cukr a kakao do jednoho závozu. Minimum je 25 kg mix. Sazebník nezveřejňujeme.",
              "A Prague kitchen can mix dumplings, pudding, sugar and cocoa into one drop. Minimum 25 kg mixed. We do not publish a rate card.",
              "Eine Prager Küche mischt Knödel, Pudding, Zucker und Kakao in eine Tour. Minimum 25 kg gemischt. Eine Preisliste veröffentlichen wir nicht.",
              "Pražská kuchyňa si namieša knedle, puding, cukor a kakao do jedného závozu. Minimum je 25 kg mix. Sadzobník nezverejňujeme."),
            [
                ("p", t(
                    "Praha je daleko od Kochánova, proto bereme až od 25 kg smíšené váhy. Můžete dát do jedné palety knedlíky i puding. Dopravu naceníme, nebo pošlete vlastního dopravce. Cenu směsí podle množství řekneme po telefonu — ne z ceníku domácností.",
                    "Prague is a long run from Kochánov, so we take mixed orders from 25 kg. Dumpling mix and pudding can share one pallet. We quote the freight, or you send your own courier. Prices for the mixes are given by phone — they are not the household list prices.",
                    "Prag ist weit von Kochánov entfernt, deshalb nehmen wir gemischte Bestellungen ab 25 kg. Knödel und Pudding können auf eine Palette. Die Fracht nennen wir Ihnen, oder Sie schicken einen eigenen Kurier. Die Mischungspreise nennen wir telefonisch — sie stammen nicht aus der Haushaltsliste.",
                    "Praha je ďaleko od Kochánova, preto berieme až od 25 kg zmiešanej váhy. Môžete dať do jednej palety knedle aj puding. Dopravu naceníme, alebo pošlete vlastného dopravcu. Cenu zmesí podľa množstva povieme po telefóne — nie z cenníka domácností.",
                )),
                ("h2", t("Co Praha není", "What Prague is not", "Was Prag nicht ist", "Čo Praha nie je")),
                ("p", t(
                    "Není to stejná logistika jako Brno. Do Prahy jezdíme po dálnici a platí vyšší minimum. Do Brna vede jiná trasa a jezdíme v jiný termín. Proto má každé město vlastní stránku.",
                    "The logistics are not the same as for Brno. Prague is a motorway run with a higher minimum. Brno has a different route and a different schedule. That is why each city has its own page.",
                    "Das ist nicht dieselbe Logistik wie für Brünn. Prag ist eine Autobahntour mit höherem Minimum. Brünn hat eine andere Strecke und einen anderen Termin. Deshalb hat jede Stadt ihre eigene Seite.",
                    "Nie je to rovnaká logistika ako Brno. Do Prahy jazdíme po diaľnici a platí vyššie minimum. Do Brna vedie iná trasa a jazdíme v iný termín. Preto má každé mesto vlastnú stránku.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Jaké je minimum do Prahy?", "What is the Prague minimum?", "Was ist das Minimum nach Prag?", "Aké je minimum do Prahy?"),
                 t("25 kg smíšené objednávky.", "25 kg mixed order.", "25 kg gemischte Bestellung.", "25 kg zmiešanej objednávky.")),
                (t("Můžu namíchat víc druhů?", "Can I mix several products?", "Kann ich mehrere Sorten mischen?", "Môžem namiešať viac druhov?"),
                 t("Ano. Knedlíky, puding, cukr i kakao do jednoho závozu.",
                   "Yes. Dumpling mix, pudding, sugar and cocoa in one drop.",
                   "Ja. Knödel, Pudding, Zucker und Kakao in einer Tour.",
                   "Áno. Knedle, puding, cukor aj kakao do jedného závozu.")),
                (t("Zveřejňujete pražské velkoobchodní ceny?", "Do you publish Prague wholesale prices?", "Veröffentlichen Sie Prager Großhandelspreise?", "Zverejňujete pražské veľkoobchodné ceny?"),
                 t("Ne. Cenu podle množství domluvíme.", "No. We agree a quantity price.", "Nein. Den Mengenpreis vereinbaren wir.", "Nie. Cenu podľa množstva dohodneme.")),
                (t("Je doprava v ceníku?", "Is freight in the price list?", "Steckt die Fracht in der Preisliste?", "Je doprava v cenníku?"),
                 t("Ne. Cena na webu je jen za zboží.", "No. The website price is for the goods only.", "Nein. Der Website-Preis gilt nur für die Ware.", "Nie. Cena na webe je len za tovar.")),
                (t("Jmenujete pražské restaurace?", "Do you name Prague restaurants?", "Nennen Sie Prager Restaurants?", "Menujete pražské reštaurácie?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Praha Jůzlová, 25 kg mix, knedlíky v prášku",
              "Prague wholesale Jůzlová 25 kg mixed",
              "Großhandel Prag Jůzlová 25 kg gemischt",
              "veľkoobchod Praha Jůzlová 25 kg mix"),
        ),
        "velkoobchod_brno": page(
            t("Velkoobchod Brno — Morava, jiná trasa než Praha",
              "Wholesale Brno — Moravia, a different run from Prague",
              "Großhandel Brünn — Mähren, andere Tour als Prag",
              "Veľkoobchod Brno — Morava, iná trasa než Praha"),
            t("Brněnským kuchyním dodáváme po domluvě; trasu na Moravu plánujeme zvlášť od Prahy. Cenu a termín domluvíme, sazebník na webu není.",
              "We supply Brno kitchens by arrangement; the Moravian run is planned apart from Prague. Price and date are agreed; no rate card on the site.",
              "Brünner Küchen beliefern wir nach Absprache; die mährische Tour planen wir getrennt von Prag. Preis und Termin nach Absprache, keine Sätze online.",
              "Brnenským kuchyniam dodávame po dohode; trasu na Moravu plánujeme zvlášť od Prahy. Cenu a termín dohodneme, sadzobník na webe nie je."),
            t("Velkoobchod do Brna",
              "Wholesale to Brno",
              "Großhandel nach Brünn",
              "Veľkoobchod do Brna"),
            t("Moravská trasa, jiný den než Praha. Stejných pět směsí z Kochánova. Minimum a cenu řekneme po poptávce — ne z pražské stránky.",
              "A Moravian route, a different day from Prague. The same five mixes from Kochánov. Minimum and price come after you enquire — not from the Prague page.",
              "Eine mährische Strecke, ein anderer Tag als Prag. Dieselben fünf Mischungen aus Kochánov. Minimum und Preis nach der Anfrage — nicht von der Prager Seite.",
              "Moravská trasa, iný deň než Praha. Rovnakých päť zmesí z Kochánova. Minimum a cenu povieme po dopyte — nie z pražskej stránky."),
            [
                ("p", t(
                    "Brno neleží na cestě do Prahy. Závoz na Moravu skládáme zvlášť: jiný den, jiné kilometry, jiná cena dopravy. Proto tato stránka není kopií té pražské. Pět směsí je stejných, logistika ne.",
                    "Brno is not on the road to Prague. The Moravian run is scheduled on its own: a different day, different mileage, different freight costs. That is why this page is not a copy of the Prague page. The five mixes are the same; the logistics are not.",
                    "Brünn liegt nicht auf dem Weg nach Prag. Die mährische Tour planen wir separat: anderer Tag, andere Strecke, andere Frachtkosten. Deshalb ist diese Seite keine Kopie der Prager Seite. Die fünf Mischungen sind dieselben, die Logistik nicht.",
                    "Brno neleží na ceste do Prahy. Závoz na Moravu skladáme zvlášť: iný deň, iné kilometre, iná cena dopravy. Preto táto stránka nie je kópiou tej pražskej. Päť zmesí je rovnakých, logistika nie.",
                )),
                ("h2", t("Jak poptat Brno", "How to enquire for Brno", "Anfrage für Brünn", "Ako dopytovať Brno")),
                ("p", t(
                    "Napište velkoobchodní formulář s tématem Brno, nebo volejte. Řekneme, kdy jedeme na Moravu a kolik bude stát závoz. Sazebník na webu není. Značky brněnských kuchyní nejmenujeme.",
                    "Use the wholesale form with the topic Brno, or phone us. We will tell you when we next drive to Moravia and what the delivery costs. There is no rate card on the site. We do not name Brno kitchens.",
                    "Nutzen Sie das Großhandelsformular mit Thema Brünn oder rufen Sie an. Wir sagen, wann wir nach Mähren fahren und was die Tour kostet. Keine Preisliste auf der Website. Brünner Küchen nennen wir nicht.",
                    "Napíšte veľkoobchodný formulár s témou Brno, alebo volajte. Povieme, kedy ideme na Moravu a koľko bude stáť závoz. Sadzobník na webe nie je. Značky brnenských kuchýň nemenujeme.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Je Brno stejné jako Praha?", "Is Brno the same as Prague?", "Ist Brünn dasselbe wie Prag?", "Je Brno rovnaké ako Praha?"),
                 t("Ne. Jiná trasa, jiný den, jiná cena dopravy. Stejných pět směsí.",
                   "No. A different route, a different day, a different freight price. The same five mixes.",
                   "Nein. Andere Strecke, anderer Tag, anderer Frachtpreis. Dieselben fünf Mischungen.",
                   "Nie. Iná trasa, iný deň, iná cena dopravy. Rovnakých päť zmesí.")),
                (t("Je rozvoz do Brna zdarma?", "Is delivery to Brno free?", "Ist die Lieferung nach Brünn kostenlos?", "Je rozvoz do Brna zadarmo?"),
                 t("Ano — od objednávky nad 5000 Kč, po domluvě termínu.",
                   "Yes — for orders over 5000 Kč, by arrangement.",
                   "Ja — ab Bestellungen über 5000 Kč, nach Terminabsprache.",
                   "Áno — od objednávky nad 5000 Kč, po dohode termínu.")),
                (t("Platí v Brně minimum 25 kg?", "Does the 25 kg minimum apply in Brno?", "Gilt in Brünn das 25-kg-Minimum?", "Platí v Brne minimum 25 kg?"),
                 t("Pražské minimum je 25 kg mix. Pro Brno platí prah zdarma dopravy 5000 Kč; přesné minimum zboží řekneme po poptávce.",
                   "The Prague minimum is 25 kg mixed. For Brno the free-delivery threshold is 5000 Kč; the exact goods minimum is confirmed after you enquire.",
                   "Das Prager Minimum ist 25 kg gemischt. Für Brünn gilt die Gratis-Lieferung ab 5000 Kč; das genaue Warenminimum nennen wir nach der Anfrage.",
                   "Pražské minimum je 25 kg mix. Pre Brno platí prah dopravy zadarmo 5000 Kč; presné minimum tovaru povieme po dopyte.")),
                (t("Zveřejňujete brněnské sazby?", "Do you publish Brno rates?", "Veröffentlichen Sie Brünner Sätze?", "Zverejňujete brnenské sadzby?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
                (t("Můžu poslat dopravce do Kochánova?", "Can I send a courier to Kochánov?", "Kann ich einen Kurier nach Kochánov schicken?", "Môžem poslať dopravcu do Kochánova?"),
                 t("Ano. Často to vyjde levněji než náš závoz na Moravu.",
                   "Yes. That is often cheaper than our Moravian delivery run.",
                   "Ja. Das ist oft günstiger als unsere mährische Tour.",
                   "Áno. Často to vyjde lacnejšie než náš závoz na Moravu.")),
                (t("Jmenujete brněnské zákazníky?", "Do you name Brno customers?", "Nennen Sie Brünner Kunden?", "Menujete brnenských zákazníkov?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Brno Jůzlová, Morava knedlíky v prášku",
              "Brno wholesale Jůzlová Moravia dumpling mix",
              "Großhandel Brünn Jůzlová Mähren Knödel",
              "veľkoobchod Brno Jůzlová Morava knedle"),
        ),
        "velkoobchod_zahranici": page(
            t("Velkoobchod mimo Česko — jen na poptávku | Jůzlová",
              "Wholesale outside Czechia — on enquiry only | Jůzlová",
              "Großhandel außerhalb Tschechiens — nur auf Anfrage",
              "Veľkoobchod mimo Česka — len na dopyt | Jůzlová"),
            t("Jsme malá rodinná dílna na Vysočině. Zahraniční kuchyni nebo obchodu pošleme zboží na požádání; dopravu platí celou odběratel, částku řekneme předem.",
              "A small family workshop in Vysočina. Kitchens or shops abroad can have goods sent on request; the buyer pays all freight, quoted first.",
              "Kleine Familienwerkstatt in der Vysočina. Küchen oder Läden im Ausland schicken wir auf Wunsch Ware; die Fracht zahlt der Abnehmer, Summe vorab.",
              "Sme malá rodinná dielňa na Vysočine. Zahraničnej kuchyni či obchodu pošleme tovar na požiadanie; dopravu platí celú odberateľ, sumu povieme vopred."),
            t("Velkoobchod mimo Česko",
              "Wholesale outside Czechia",
              "Großhandel außerhalb Tschechiens",
              "Veľkoobchod mimo Česka"),
            t("Většina našich zákazníků si pro zboží přijede do dílny. Poslat do zahraničí můžeme na požádání, na náklady odběratele; celkovou částku řekneme před odesláním.",
              "Most of our customers collect at the workshop. We can send abroad on request, at the buyer's cost; we give the total before dispatch.",
              "Die meisten unserer Kunden holen in der Werkstatt ab. Ins Ausland schicken wir auf Wunsch, auf Kosten des Abnehmers; die Gesamtsumme nennen wir vor dem Versand.",
              "Väčšina našich zákazníkov si pre tovar príde do dielne. Poslať do zahraničia môžeme na požiadanie, na náklady odberateľa; celkovú sumu povieme pred odoslaním."),
            [
                ("p", t(
                    "Mezinárodní velkoobchod není ceník domácností plus poštovné. Množství, celní doklady a dopravce se liší zakázku od zakázky. Proto na webu žádné zahraniční sazby nejsou. Napište formulář s tématem zahraničí, nebo volejte.",
                    "International wholesale is not the household price list plus postage. Volume, paperwork and carrier differ from order to order. That is why there are no international rates on the site. Use the form with the topic International wholesale, or phone us.",
                    "Internationaler Großhandel ist nicht die Haushaltsliste plus Porto. Menge, Papiere und Spediteur unterscheiden sich von Auftrag zu Auftrag. Deshalb stehen keine Auslandssätze auf der Website. Nutzen Sie im Formular das Thema Ausländischer Großhandel oder rufen Sie an.",
                    "Medzinárodný veľkoobchod nie je cenník domácností plus poštovné. Množstvo, colné doklady a dopravca sa líšia zákazku od zákazky. Preto na webe žiadne zahraničné sadzby nie sú. Napíšte formulár s témou zahraničie, alebo volajte.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Jsou na webu zahraniční velkoobchodní ceny?", "Are international wholesale prices on the site?", "Stehen internationale Großhandelspreise auf der Website?", "Sú na webe zahraničné veľkoobchodné ceny?"),
                 t("Ne. Cenu domluvíme po poptávce.", "No. We agree the price after you enquire.", "Nein. Den Preis vereinbaren wir nach der Anfrage.", "Nie. Cenu dohodneme po dopyte.")),
                (t("Kdo platí dopravu?", "Who pays freight?", "Wer zahlt die Fracht?", "Kto platí dopravu?"),
                 t("Odběratel, celou částku. Dopravu, balení a pojištění řekneme předem.",
                   "The buyer, in full. We quote freight, packaging and insurance first.",
                   "Der Abnehmer, vollständig. Fracht, Karton und Versicherung nennen wir vorab.",
                   "Odberateľ, celú sumu. Dopravu, balenie a poistenie povieme vopred.")),
                (t("Posíláte vzorky do zahraničí?", "Do you send samples abroad?", "Schicken Sie Muster ins Ausland?", "Posielate vzorky do zahraničia?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Jůzlová, odběr mimo Česko na poptávku",
              "Jůzlová wholesale, buyers outside Czechia on enquiry",
              "Großhandel Jůzlová, Abnehmer im Ausland auf Anfrage",
              "veľkoobchod Jůzlová, odber mimo Česka na dopyt"),
        ),
    }
