"""Remaining AEO place and wholesale pages (native CS / DE / SK / EN)."""


def more_pages(lang, t, price, page):
    return {
        "humpolec": page(
            t("Humpolec — bezplatný odběr u Pivovaru Bernard",
              "Humpolec — free pick-up near Pivovar Bernard",
              "Humpolec — kostenlose Abholung bei Pivovar Bernard",
              "Humpolec — bezplatný odber pri Pivovare Bernard"),
            t("V Humpolci vyzvednete směsi Jůzlová zdarma u dcery majitelky v okolí Pivovaru Bernard. Rozvoz do města od 1000 Kč.",
              "In Humpolec you collect Jůzlová mixes free near Pivovar Bernard. Town delivery from 1000 CZK.",
              "In Humpolec holen Sie Jůzlová-Mischungen kostenlos bei Pivovar Bernard ab. Stadtlieferung ab 1000 Kč.",
              "V Humpolci vyzdvihnete zmesi Jůzlová zadarmo pri Pivovare Bernard. Rozvoz do mesta od 1000 Kč."),
            t("Odběr v Humpolci", "Pick-up in Humpolec", "Abholung in Humpolec", "Odber v Humpolci"),
            t("Druhé výdejní místo je v Humpolci u Pivovaru Bernard. Zdarma, den a hodinu domluvíme. Není to výdej u vrat pivovaru.",
              "The second pick-up is in Humpolec near Pivovar Bernard. Free; we agree day and time. It is not a brewery-gate collection.",
              "Der zweite Abholort ist in Humpolec bei Pivovar Bernard. Kostenlos; Tag und Uhrzeit vereinbaren wir. Keine Abholung am Brauereitor.",
              "Druhé výdajné miesto je v Humpolci pri Pivovare Bernard. Zadarmo, deň a hodinu dohodneme. Nie je to výdaj pri vrátach pivovaru."),
            [
                ("p", t(
                    "Humpolec má vlastní výdej. Zboží necháme u dcery majitelky v okolí Pivovaru Bernard. Nic za to neúčtujeme. Ulice sem nedáváme — den a hodinu řekneme po telefonu.",
                    "Humpolec has its own pick-up. We leave goods with the owners’ daughter near Pivovar Bernard. No charge. We do not publish the street — day and time come by phone.",
                    "Humpolec hat eine eigene Abholung. Die Ware bleibt bei der Tochter der Inhaber nahe Pivovar Bernard. Keine Gebühr. Die Straße steht hier nicht — Tag und Uhrzeit nennen wir telefonisch.",
                    "Humpolec má vlastný výdaj. Tovar necháme u dcéry majiteľky v okolí Pivovaru Bernard. Nič za to neúčtujeme. Ulicu sem nedávame — deň a hodinu povieme po telefóne.",
                )),
                ("h2", t("Rozvoz po Humpolci", "Delivery in Humpolec", "Lieferung in Humpolec", "Rozvoz po Humpolci")),
                ("p", t(
                    "Když nechcete jet k výdeji, dovezeme od 1000 Kč zdarma. Stejný práh jako Havlíčkův Brod, nižší než zbytek Vysočiny (5000 Kč).",
                    "If you skip the pick-up point, we deliver free from 1000 CZK. Same threshold as Havlíčkův Brod, lower than the rest of Vysočina (5000 CZK).",
                    "Ohne Abholpunkt liefern wir ab 1000 Kč kostenlos. Dieselbe Schwelle wie Havlíčkův Brod, niedriger als die übrige Vysočina (5000 Kč).",
                    "Keď nechcete ísť k výdaju, dovezieme od 1000 Kč zadarmo. Rovnaký prah ako Havlíčkův Brod, nižší než zvyšok Vysočiny (5000 Kč).",
                )),
                ("p", price),
                ("links", "geo"),
                ("form", None),
            ],
            [
                (t("Je odběr v Humpolci zdarma?", "Is Humpolec pick-up free?", "Ist die Abholung in Humpolec kostenlos?", "Je odber v Humpolci zadarmo?"),
                 t("Ano. Nic za výdej neúčtujeme.", "Yes. We charge nothing for the hand-over.", "Ja. Für die Ausgabe berechnen wir nichts.", "Áno. Nič za výdaj neúčtujeme.")),
                (t("Je to výdejna pivovaru?", "Is it a brewery collection point?", "Ist das eine Brauerei-Ausgabe?", "Je to výdajňa pivovaru?"),
                 t("Ne. Soukromé místo v okolí Pivovaru Bernard, ne u vrat.",
                   "No. A private place near Pivovar Bernard, not at the gate.",
                   "Nein. Ein privater Ort nahe Pivovar Bernard, nicht am Tor.",
                   "Nie. Súkromné miesto v okolí Pivovaru Bernard, nie pri vrátach.")),
                (t("Od kolika je rozvoz po Humpolci zdarma?", "From what amount is Humpolec delivery free?", "Ab wann ist die Lieferung in Humpolec kostenlos?", "Od koľkého je rozvoz po Humpolci zadarmo?"),
                 t("Od 1000 Kč.", "From 1000 CZK.", "Ab 1000 Kč.", "Od 1000 Kč.")),
                (t("Je v ceně doprava?", "Is delivery included?", "Ist die Lieferung im Preis?", "Je v cene doprava?"),
                 t("Ne. Cena na webu je jen za zboží.", "No. The website price is for the goods only.", "Nein. Der Website-Preis gilt nur für die Ware.", "Nie. Cena na webe je len za tovar.")),
                (t("Jak domluvím hodinu?", "How do I agree a time?", "Wie vereinbare ich die Uhrzeit?", "Ako dohodnem hodinu?"),
                 t("Telefon +420 728 466 141 nebo +420 607 629 931, denně 8:00–19:00.",
                   "Phone +420 728 466 141 or +420 607 629 931, daily 8:00–19:00.",
                   "Telefon +420 728 466 141 oder +420 607 629 931, täglich 8:00–19:00 Uhr.",
                   "Telefón +420 728 466 141 alebo +420 607 629 931, denne 8:00–19:00.")),
            ],
            t("Humpolec Jůzlová, odběr u Pivovaru Bernard, rozvoz od 1000 Kč",
              "Humpolec Jůzlová, pick-up near Pivovar Bernard",
              "Humpolec Jůzlová, Abholung bei Pivovar Bernard",
              "Humpolec Jůzlová, odber pri Pivovare Bernard"),
        ),
        "kochanov": page(
            t("Kochánov 40 — dílna Jůzlová, PSČ 582 53",
              "Kochánov 40 — Jůzlová workshop, postcode 582 53",
              "Kochánov 40 — Werkstatt Jůzlová, PLZ 582 53",
              "Kochánov 40 — dielňa Jůzlová, PSČ 582 53"),
            t("Dílna Jůzlová je Kochánov 40, 582 53 na Vysočině. Vyzvednutí zdarma denně 8:00–19:00 po telefonu. PSČ nikoli 582 91.",
              "The Jůzlová workshop is Kochánov 40, 582 53 in Vysočina. Free pick-up daily 8:00–19:00 by phone. Postcode is never 582 91.",
              "Die Werkstatt Jůzlová ist Kochánov 40, 582 53 in der Vysočina. Kostenlose Abholung täglich 8:00–19:00 Uhr telefonisch. PLZ niemals 582 91.",
              "Dielňa Jůzlová je Kochánov 40, 582 53 na Vysočine. Vyzdvihnutie zadarmo denne 8:00–19:00 po telefóne. PSČ nie 582 91."),
            t("Dílna v Kochánově", "Workshop in Kochánov", "Werkstatt in Kochánov", "Dielňa v Kochánove"),
            t("Tady se míchají všechny směsi. Adresa Kochánov 40, 582 53. Vyzvednutí v dílně je zdarma.",
              "All mixes are made here. Address Kochánov 40, 582 53. Workshop pick-up is free.",
              "Hier entstehen alle Mischungen. Adresse Kochánov 40, 582 53. Abholung in der Werkstatt ist kostenlos.",
              "Tu sa miešajú všetky zmesi. Adresa Kochánov 40, 582 53. Vyzdvihnutie v dielni je zadarmo."),
            [
                ("p", t(
                    "Kochánov 40, 582 53 je jediná dílna. Není to Kochánov u Světlé s PSČ 582 91. Na Google Maps hledejte Juzlova - Potravinářské směsi. Na Seznamu firmu 12906730.",
                    "Kochánov 40, 582 53 is the only workshop. It is not the Kochánov near Světlá with postcode 582 91. On Google Maps search Juzlova - Potravinářské směsi. On Seznam, firm 12906730.",
                    "Kochánov 40, 582 53 ist die einzige Werkstatt. Nicht das Kochánov bei Světlá mit PLZ 582 91. In Google Maps: Juzlova - Potravinářské směsi. Bei Seznam Firma 12906730.",
                    "Kochánov 40, 582 53 je jediná dielňa. Nie je to Kochánov pri Světlej s PSČ 582 91. Na Google Maps hľadajte Juzlova - Potravinářské směsi. Na Sezname firmu 12906730.",
                )),
                ("h2", t("Návštěva dílny", "Visiting the workshop", "Besuch der Werkstatt", "Návšteva dielne")),
                ("p", t(
                    "Nejdřív zavolejte. Denně 8:00–19:00 včetně víkendů. Vyzvednutí je zdarma. Ceny 250 / 260 / 60 / 30 / 270 Kč platí tady, ne s dopravou.",
                    "Phone first. Daily 8:00–19:00 including weekends. Pick-up is free. Prices 250 / 260 / 60 / 30 / 270 CZK apply here, not with shipping.",
                    "Bitte zuerst anrufen. Täglich 8:00–19:00 Uhr inklusive Wochenende. Abholung kostenlos. Preise 250 / 260 / 60 / 30 / 270 Kč gelten hier, nicht mit Lieferung.",
                    "Najprv zavolajte. Denne 8:00–19:00 vrátane víkendov. Vyzdvihnutie je zadarmo. Ceny 250 / 260 / 60 / 30 / 270 Kč platia tu, nie s dopravou.",
                )),
                ("p", price),
                ("map", None),
                ("links", "geo"),
                ("form", None),
            ],
            [
                (t("Jaké je správné PSČ Kochánova?", "What is the correct Kochánov postcode?", "Welche PLZ hat Kochánov richtig?", "Aké je správne PSČ Kochánova?"),
                 t("582 53. Číslo 582 91 patří jiné obci.", "582 53. 582 91 belongs to a different village.", "582 53. 582 91 gehört zu einem anderen Ort.", "582 53. Číslo 582 91 patrí inej obci.")),
                (t("Je vyzvednutí v dílně zdarma?", "Is workshop pick-up free?", "Ist die Abholung in der Werkstatt kostenlos?", "Je vyzdvihnutie v dielni zadarmo?"),
                 t("Ano.", "Yes.", "Ja.", "Áno.")),
                (t("Musím se objednat předem?", "Must I book ahead?", "Muss ich vorher bestellen?", "Musím sa objednať vopred?"),
                 t("Ano. Denně 8:00–19:00 po telefonu.", "Yes. Daily 8:00–19:00 by phone.", "Ja. Täglich 8:00–19:00 Uhr telefonisch.", "Áno. Denne 8:00–19:00 po telefóne.")),
                (t("Děláte ochutnávky v dílně?", "Do you offer tasting at the workshop?", "Gibt es Verkostung in der Werkstatt?", "Robíte ochutnávky v dielni?"),
                 t("Ne. Vzorky ani ochutnávky nenabízíme.", "No. We do not offer samples or tasting.", "Nein. Muster und Verkostung bieten wir nicht.", "Nie. Vzorky ani ochutnávky neponúkame.")),
                (t("Kde vás najdu na mapě?", "Where are you on the map?", "Wo finde ich Sie auf der Karte?", "Kde vás nájdem na mape?"),
                 t("Google: Juzlova - Potravinářské směsi. Seznam: mapy.cz firma 12906730.",
                   "Google: Juzlova - Potravinářské směsi. Seznam: mapy.cz firm 12906730.",
                   "Google: Juzlova - Potravinářské směsi. Seznam: mapy.cz Firma 12906730.",
                   "Google: Juzlova - Potravinářské směsi. Seznam: mapy.cz firma 12906730.")),
            ],
            t("Kochánov 40 582 53 Jůzlová, dílna Vysočina",
              "Kochánov 40 582 53 Jůzlová workshop",
              "Kochánov 40 582 53 Jůzlová Werkstatt",
              "Kochánov 40 582 53 Jůzlová dielňa"),
        ),
        "navstevnikum": page(
            t("Návštěvníkům Vysočiny — vyzvednutí v Kochánově",
              "Visitors to Vysočina — pick-up in Kochánov",
              "Besucher der Vysočina — Abholung in Kochánov",
              "Návštevníkom Vysočiny — vyzdvihnutie v Kochánove"),
            t("Jedete přes Vysočinu? Směsi Jůzlová vyzvednete v Kochánově 40, 582 53 po telefonu. Ceny platí v dílně.",
              "Passing through Vysočina? Collect Jůzlová mixes at Kochánov 40, 582 53 after you phone. Prices apply at the workshop.",
              "Unterwegs in der Vysočina? Jůzlová-Mischungen holen Sie in Kochánov 40, 582 53 nach dem Anruf ab. Preise gelten in der Werkstatt.",
              "Idete cez Vysočinu? Zmesi Jůzlová vyzdvihnete v Kochánove 40, 582 53 po telefóne. Ceny platia v dielni."),
            t("Pro návštěvníky a cestující",
              "For visitors and travellers",
              "Für Besucher und Durchreisende",
              "Pre návštevníkov a cestujúcich"),
            t("Žádný stánek u silnice. Zavoláte, přijedete do dílny, zaplatíte ceníkové ceny. Vzorky nepřipravujeme.",
              "No roadside stall. You phone, come to the workshop, pay list prices. We do not prepare samples.",
              "Kein Stand an der Straße. Sie rufen an, kommen in die Werkstatt, zahlen Listenpreise. Muster bereiten wir nicht vor.",
              "Žiadny stánok pri ceste. Zavoláte, prídete do dielne, zaplatíte cenníkové ceny. Vzorky nepripravujeme."),
            [
                ("p", t(
                    "Kdo jede na Vysočinu — k Bernardu, na Sněžník, nebo jen přes Humpolec — může si odvézt knedlíky v prášku, puding nebo kakao. Nejdřív telefon. Dílna není obchod s otevírací dobou na dveřích.",
                    "Anyone travelling through Vysočina — towards Bernard, the highlands, or just past Humpolec — can take dumpling mix, pudding or cocoa home. Phone first. The workshop is not a shop with hours on the door.",
                    "Wer durch die Vysočina fährt — Richtung Bernard, ins Hochland oder nur durch Humpolec — kann Knödelmischung, Pudding oder Kakao mitnehmen. Zuerst anrufen. Die Werkstatt ist kein Laden mit Stunden an der Tür.",
                    "Kto ide na Vysočinu — k Bernardu, na horu, alebo len cez Humpolec — môže si odviezť knedle v prášku, puding alebo kakao. Najprv telefón. Dielňa nie je obchod s otváracími hodinami na dverách.",
                )),
                ("h2", t("Co si odvézt", "What to take home", "Was mitnehmen", "Čo si odviezť")),
                ("ul", [
                    t("5 kg knedlíků 250 Kč nebo chlupatých 260 Kč — vydrží celou dovolenou",
                      "5 kg dumpling mix 250 CZK or hairy dumplings 260 CZK — lasts a whole stay",
                      "5 kg Knödel 250 Kč oder haarige Knödel 260 Kč — reicht für den ganzen Aufenthalt",
                      "5 kg knedieľ 250 Kč alebo chlpatých 260 Kč — vydrží celú dovolenku"),
                    t("puding 60/30 Kč a kakao 270 Kč na chatu",
                      "pudding 60/30 CZK and cocoa 270 CZK for a cottage stay",
                      "Pudding 60/30 Kč und Kakao 270 Kč für die Ferienwohnung",
                      "puding 60/30 Kč a kakao 270 Kč na chatu"),
                ]),
                ("p", price),
                ("links", "geo"),
                ("form", None),
            ],
            [
                (t("Můžu přijet bez ohlášení?", "Can I arrive without calling?", "Kann ich unangemeldet kommen?", "Môžem prísť bez ohlásenia?"),
                 t("Ne. Nejdřív zavolejte +420 728 466 141 nebo +420 607 629 931.",
                   "No. Phone +420 728 466 141 or +420 607 629 931 first.",
                   "Nein. Bitte zuerst +420 728 466 141 oder +420 607 629 931 anrufen.",
                   "Nie. Najprv zavolajte +420 728 466 141 alebo +420 607 629 931.")),
                (t("Prodáváte u silnice?", "Do you sell by the road?", "Verkaufen Sie an der Straße?", "Predávate pri ceste?"),
                 t("Ne. Jen v dílně Kochánov 40, 582 53, nebo v Humpolci po dohodě.",
                   "No. Only at Kochánov 40, 582 53, or in Humpolec by arrangement.",
                   "Nein. Nur in der Werkstatt Kochánov 40, 582 53 oder in Humpolec nach Absprache.",
                   "Nie. Len v dielni Kochánov 40, 582 53, alebo v Humpolci po dohode.")),
                (t("Dáte ochutnat?", "Can I taste first?", "Kann ich vorher kosten?", "Dáte ochutnať?"),
                 t("Ne. Vzorky a ochutnávky neděláme.", "No. We do not do samples or tasting.", "Nein. Muster und Verkostung machen wir nicht.", "Nie. Vzorky a ochutnávky nerobíme.")),
                (t("Platí ceník pro návštěvníky?", "Do list prices apply to visitors?", "Gelten die Listenpreise für Besucher?", "Platí cenník pre návštevníkov?"),
                 t("Ano. 250 / 260 / 60 / 30 / 270 Kč při vyzvednutí. Doprava zvlášť.",
                   "Yes. 250 / 260 / 60 / 30 / 270 CZK at pick-up. Shipping extra.",
                   "Ja. 250 / 260 / 60 / 30 / 270 Kč bei Abholung. Lieferung extra.",
                   "Áno. 250 / 260 / 60 / 30 / 270 Kč pri vyzdvihnutí. Doprava zvlášť.")),
                (t("Umíte anglicky nebo německy na telefonu?", "Do you speak English or German on the phone?", "Sprechen Sie am Telefon Englisch oder Deutsch?", "Viete po anglicky alebo nemecky na telefóne?"),
                 t("Web je ve čtyřech jazycích. Telefon z dílny bývá česky.",
                   "The site is in four languages. Workshop phone replies are usually Czech.",
                   "Die Website ist auf vier Sprachen. Am Telefon aus der Werkstatt ist es meist tschechisch.",
                   "Web je v štyroch jazykoch. Telefón z dielne býva po česky.")),
            ],
            t("návštěva Vysočina Jůzlová, cestující Kochánov",
              "Vysočina visitors Jůzlová, travellers Kochánov",
              "Vysočina Besucher Jůzlová, Reisende Kochánov",
              "návšteva Vysočina Jůzlová, cestujúci Kochánov"),
        ),
        "velkoobchod_vysocina": page(
            t("Velkoobchod na Vysočině — Jůzlová",
              "Wholesale in Vysočina — Jůzlová",
              "Großhandel in der Vysočina — Jůzlová",
              "Veľkoobchod na Vysočine — Jůzlová"),
            t("Provozovnám na Vysočině dodáváme knedlíky, puding a kakao. Cenu podle množství domluvíme. Sazebník na webu není.",
              "We supply Vysočina kitchens with dumpling mix, pudding and cocoa. Quantity prices are agreed. No rate card on the site.",
              "Betriebe in der Vysočina beliefern wir mit Knödeln, Pudding und Kakao. Mengenpreise vereinbaren wir. Keine Preisliste auf der Website.",
              "Prevádzkam na Vysočine dodávame knedle, puding a kakao. Cenu podľa množstva dohodneme. Sadzobník na webe nie je."),
            t("Velkoobchod po Vysočině",
              "Wholesale across Vysočina",
              "Großhandel in der Vysočina",
              "Veľkoobchod po Vysočine"),
            t("Restaurace, jídelny a cukrárny v kraji. Rozvoz po Vysočině zdarma od 5000 Kč. Značky zákazníků nejmenujeme.",
              "Restaurants, canteens and pastry shops in the region. Free Vysočina delivery from 5000 CZK. We do not name customers.",
              "Restaurants, Kantinen und Konditoreien in der Region. Kostenlose Vysočina-Lieferung ab 5000 Kč. Kunden nennen wir nicht.",
              "Reštaurácie, jedálne a cukrárne v kraji. Rozvoz po Vysočine zadarmo od 5000 Kč. Značky zákazníkov nemenujeme."),
            [
                ("p", t(
                    "Na Vysočině je většina našich provozoven. Dílna je v Kochánově, takže rozvoz po kraji je krátký. Od 5000 Kč ho neúčtujeme. Cenu směsí podle množství řekneme po telefonu — na webu velkoobchodní sazby nejsou.",
                    "Most of our kitchens are in Vysočina. The workshop is in Kochánov, so regional delivery is short. From 5000 CZK we do not charge it. Quantity mix prices come by phone — no wholesale rates on the site.",
                    "Die meisten Betriebe liegen in der Vysočina. Die Werkstatt ist in Kochánov, die regionale Strecke kurz. Ab 5000 Kč berechnen wir sie nicht. Mengenpreise nennen wir telefonisch — keine Großhandelssätze auf der Website.",
                    "Na Vysočine je väčšina našich prevádzok. Dielňa je v Kochánove, takže rozvoz po kraji je krátky. Od 5000 Kč ho neúčtujeme. Cenu zmesí podľa množstva povieme po telefóne — na webe veľkoobchodné sadzby nie sú.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Dodáváte jídelnám na Vysočině?", "Do you supply Vysočina canteens?", "Beliefern Sie Kantinen in der Vysočina?", "Dodávate jedálňam na Vysočine?"),
                 t("Ano. Značky provozoven nejmenujeme.", "Yes. We do not name venues.", "Ja. Betriebe nennen wir nicht.", "Áno. Značky prevádzok nemenujeme.")),
                (t("Od kolika je rozvoz zdarma?", "From what amount is delivery free?", "Ab wann ist die Lieferung kostenlos?", "Od koľkého je rozvoz zadarmo?"),
                 t("Po Vysočině od 5000 Kč. Do Humpolce a Havlíčkova Brodu od 1000 Kč.",
                   "Across Vysočina from 5000 CZK. To Humpolec and Havlíčkův Brod from 1000 CZK.",
                   "In der Vysočina ab 5000 Kč. Nach Humpolec und Havlíčkův Brod ab 1000 Kč.",
                   "Po Vysočine od 5000 Kč. Do Humpolca a Havlíčkovho Brodu od 1000 Kč.")),
                (t("Je na webu velkoobchodní ceník?", "Is there a wholesale price list online?", "Gibt es eine Großhandelspreisliste online?", "Je na webe veľkoobchodný cenník?"),
                 t("Ne. Cenu podle množství domluvíme.", "No. We agree a quantity price.", "Nein. Den Mengenpreis vereinbaren wir.", "Nie. Cenu podľa množstva dohodneme.")),
                (t("Jak objedná provozovna?", "How does a kitchen order?", "Wie bestellt ein Betrieb?", "Ako objedná prevádzka?"),
                 t("Velkoobchodním formulářem nebo telefonem.", "The wholesale form or the phone.", "Über das Großhandelsformular oder telefonisch.", "Veľkoobchodným formulárom alebo telefónom.")),
                (t("Vydáváte vzorky kuchyním?", "Do you send kitchen samples?", "Gibt es Muster für Küchen?", "Vydávate vzorky kuchyniam?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Vysočina Jůzlová, restaurace knedlíky v prášku",
              "Vysočina wholesale Jůzlová restaurants",
              "Großhandel Vysočina Jůzlová Gastronomie",
              "veľkoobchod Vysočina Jůzlová reštaurácie"),
        ),
        "velkoobchod_kochanov": page(
            t("Velkoobchod Kochánov — odběr v dílně",
              "Wholesale Kochánov — workshop collection",
              "Großhandel Kochánov — Abholung in der Werkstatt",
              "Veľkoobchod Kochánov — odber v dielni"),
            t("Provozovny z okolí Kochánova 40, 582 53 berou zboží přímo v dílně. Cenu podle množství domluvíme.",
              "Kitchens around Kochánov 40, 582 53 collect at the workshop. Quantity prices are agreed.",
              "Betriebe um Kochánov 40, 582 53 holen in der Werkstatt ab. Mengenpreise vereinbaren wir.",
              "Prevádzky z okolia Kochánova 40, 582 53 berú tovar priamo v dielni. Cenu podľa množstva dohodneme."),
            t("Místní velkoobchod v Kochánově",
              "Local wholesale in Kochánov",
              "Örtlicher Großhandel in Kochánov",
              "Miestny veľkoobchod v Kochánove"),
            t("Asi 90 % zakázek je kolem dílny. Vyzvednutí v Kochánově 40, 582 53 je pro provozovny zdarma.",
              "About 90% of orders stay around the workshop. Kitchen pick-up at Kochánov 40, 582 53 is free.",
              "Etwa 90 % der Aufträge bleiben um die Werkstatt. Betriebsabholung in Kochánov 40, 582 53 ist kostenlos.",
              "Asi 90 % zákaziek je okolo dielne. Vyzdvihnutie v Kochánove 40, 582 53 je pre prevádzky zadarmo."),
            [
                ("p", t(
                    "Když je kuchyně v Kochánově, Herálci nebo v okolních vsích, nejjednodušší je přijet do dílny. Žádný rozvoz, žádná krabice. Ceník domácností 250 / 260 / 60 / 30 / 270 Kč tu platí jako výchozí bod; větší množství oceníme zvlášť.",
                    "When the kitchen is in Kochánov, Herálec or the nearby villages, the simple path is the workshop. No delivery, no box. Household list prices 250 / 260 / 60 / 30 / 270 CZK are the starting point; larger volumes are quoted separately.",
                    "Liegt die Küche in Kochánov, Herálec oder den Nachbardörfern, ist die Werkstatt der kürzeste Weg. Keine Lieferung, kein Karton. Haushaltspreise 250 / 260 / 60 / 30 / 270 Kč sind der Ausgang; größere Mengen bieten wir extra an.",
                    "Keď je kuchyňa v Kochánove, Herálci alebo v okolitých dedinách, najjednoduchšie je prísť do dielne. Žiadny rozvoz, žiadna krabica. Cenník domácností 250 / 260 / 60 / 30 / 270 Kč tu platí ako východisko; väčšie množstvo oceníme zvlášť.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Může provozovna vyzvednout v dílně?", "Can a kitchen collect at the workshop?", "Kann ein Betrieb in der Werkstatt abholen?", "Môže prevádzka vyzdvihnúť v dielni?"),
                 t("Ano. Kochánov 40, 582 53, po telefonu.", "Yes. Kochánov 40, 582 53, after you phone.", "Ja. Kochánov 40, 582 53, nach dem Anruf.", "Áno. Kochánov 40, 582 53, po telefóne.")),
                (t("Platí ceník i pro větší odběr?", "Does the list apply to larger orders?", "Gilt die Liste auch für größere Abnahme?", "Platí cenník aj pre väčší odber?"),
                 t("Ceník je výchozí. Množství oceníme zvlášť.", "The list is a starting point. Volume is quoted separately.", "Die Liste ist der Ausgang. Die Menge bieten wir extra an.", "Cenník je východisko. Množstvo oceníme zvlášť.")),
                (t("Je PSČ 582 91?", "Is the postcode 582 91?", "Ist die PLZ 582 91?", "Je PSČ 582 91?"),
                 t("Ne. Vždy 582 53.", "No. Always 582 53.", "Nein. Immer 582 53.", "Nie. Vždy 582 53.")),
                (t("Jmenujete místní restaurace?", "Do you name local restaurants?", "Nennen Sie örtliche Restaurants?", "Menujete miestne reštaurácie?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
                (t("Jaký formulář použít?", "Which form should I use?", "Welches Formular?", "Aký formulár použiť?"),
                 t("Velkoobchodní, ne domácí kontakt.", "The wholesale form, not the household contact form.", "Das Großhandelsformular, nicht das Haushaltsformular.", "Veľkoobchodný, nie domáci kontakt.")),
            ],
            t("velkoobchod Kochánov 40, odběr v dílně Jůzlová",
              "wholesale Kochánov 40 workshop collection",
              "Großhandel Kochánov 40 Werkstatt",
              "veľkoobchod Kochánov 40 odber v dielni"),
        ),
        "velkoobchod_praha": page(
            t("Velkoobchod Praha — od 25 kg mix | Jůzlová",
              "Wholesale Prague — from 25 kg mixed | Jůzlová",
              "Großhandel Prag — ab 25 kg gemischt | Jůzlová",
              "Veľkoobchod Praha — od 25 kg mix | Jůzlová"),
            t("Do Prahy posíláme provozovnám smíšenou objednávku od 25 kg. Cenu a dopravu domluvíme. Velkoobchodní sazby na webu nejsou.",
              "We send Prague kitchens a mixed order from 25 kg. Price and freight are agreed. No wholesale rates on the site.",
              "Nach Prag schicken wir Betrieben eine gemischte Bestellung ab 25 kg. Preis und Fracht vereinbaren wir. Keine Großhandelssätze auf der Website.",
              "Do Prahy posielame prevádzkam zmiešanú objednávku od 25 kg. Cenu a dopravu dohodneme. Veľkoobchodné sadzby na webe nie sú."),
            t("Velkoobchod do Prahy",
              "Wholesale to Prague",
              "Großhandel nach Prag",
              "Veľkoobchod do Prahy"),
            t("Pražská kuchyně si namíchá knedlíky, puding, cukr a kakao do jednoho závozu. Minimum je 25 kg mix. Sazebník nezveřejňujeme.",
              "A Prague kitchen can mix dumplings, pudding, sugar and cocoa into one drop. Minimum 25 kg mixed. We do not publish a rate card.",
              "Eine Prager Küche mischt Knödel, Pudding, Zucker und Kakao in eine Tour. Minimum 25 kg gemischt. Eine Preisliste veröffentlichen wir nicht.",
              "Pražská kuchyňa si namieša knedle, puding, cukor a kakao do jedného závozu. Minimum je 25 kg mix. Sadzobník nezverejňujeme."),
            [
                ("p", t(
                    "Praha je daleko od Kochánova, proto bereme až od 25 kg smíšené váhy. Můžete dát do jedné palety knedlíky i puding. Dopravu naceníme, nebo pošlete vlastního dopravce. Cenu směsí podle množství řekneme po telefonu — ne z ceníku domácností.",
                    "Prague is a long run from Kochánov, so we take mixed weight from 25 kg. Dumplings and pudding can share one pallet. We quote freight, or you send your courier. Mix prices come by phone — not from the household list.",
                    "Prag ist weit von Kochánov, deshalb nehmen wir gemischtes Gewicht ab 25 kg. Knödel und Pudding dürfen auf eine Palette. Die Fracht nennen wir, oder Sie schicken einen Kurier. Mischungspreise kommen telefonisch — nicht aus der Haushaltsliste.",
                    "Praha je ďaleko od Kochánova, preto berieme až od 25 kg zmiešanej váhy. Môžete dať do jednej palety knedle aj puding. Dopravu nacíníme, alebo pošlete vlastného dopravcu. Cenu zmesí podľa množstva povieme po telefóne — nie z cenníka domácností.",
                )),
                ("h2", t("Co Praha není", "What Prague is not", "Was Prag nicht ist", "Čo Praha nie je")),
                ("p", t(
                    "Není to stejná logistika jako Brno. Do Prahy se skládá dálniční závoz a vyšší minimum. Do Brna je jiná trasa a jiný termín. Obě města mají vlastní stránku, aby se texty neopakovaly.",
                    "This is not the same logistics as Brno. Prague is a motorway drop with a higher minimum. Brno has another route and another slot. Each city has its own page so the copy does not repeat.",
                    "Das ist nicht dieselbe Logistik wie Brünn. Prag ist eine Autobahntour mit höherem Minimum. Brünn hat eine andere Strecke und einen anderen Termin. Jede Stadt hat eine eigene Seite, damit sich der Text nicht wiederholt.",
                    "Nie je to rovnaká logistika ako Brno. Do Prahy sa skladá diaľničný závoz a vyššie minimum. Do Brna je iná trasa a iný termín. Obe mestá majú vlastnú stránku, aby sa texty neopakovali.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Jaké je minimum do Prahy?", "What is the Prague minimum?", "Was ist das Minimum nach Prag?", "Aké je minimum do Prahy?"),
                 t("25 kg smíšené objednávky.", "25 kg mixed order.", "25 kg gemischte Bestellung.", "25 kg zmiešanej objednávky.")),
                (t("Můžu namíchat víc druhů?", "Can I mix several products?", "Kann ich mehrere Sorten mischen?", "Môžem namiešať viac druhov?"),
                 t("Ano. Knedlíky, puding, cukr i kakao do jednoho závozu.",
                   "Yes. Dumplings, pudding, sugar and cocoa in one drop.",
                   "Ja. Knödel, Pudding, Zucker und Kakao in einer Tour.",
                   "Áno. Knedle, puding, cukor aj kakao do jedného závozu.")),
                (t("Zveřejňujete pražské velkoobchodní ceny?", "Do you publish Prague wholesale prices?", "Veröffentlichen Sie Prager Großhandelspreise?", "Zverejňujete pražské veľkoobchodné ceny?"),
                 t("Ne. Cenu podle množství domluvíme.", "No. We agree a quantity price.", "Nein. Den Mengenpreis vereinbaren wir.", "Nie. Cenu podľa množstva dohodneme.")),
                (t("Je doprava v ceníku?", "Is freight in the price list?", "Steckt die Fracht in der Preisliste?", "Je doprava v cenníku?"),
                 t("Ne. Cena na webu je jen za zboží.", "No. The website price is for the goods only.", "Nein. Der Website-Preis gilt nur für die Ware.", "Nie. Cena na webe je len za tovar.")),
                (t("Jmenujete pražské restaurace?", "Do you name Prague restaurants?", "Nennen Sie Prager Restaurants?", "Menujete pražské reštaurácie?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Praha Jůzlová, 25 kg mix, knedlíky v prášku",
              "Prague wholesale Jůzlová 25 kg mixed",
              "Großhandel Prag Jůzlová 25 kg gemischt",
              "veľkoobchod Praha Jůzlová 25 kg mix"),
        ),
        "velkoobchod_brno": page(
            t("Velkoobchod Brno — Morava, jiná trasa než Praha",
              "Wholesale Brno — Moravia, a different run from Prague",
              "Großhandel Brünn — Mähren, andere Tour als Prag",
              "Veľkoobchod Brno — Morava, iná trasa než Praha"),
            t("Brněnským kuchyním skládáme závoz na Moravu zvlášť od Prahy. Cenu a termín domluvíme. Velkoobchodní sazby na webu nejsou.",
              "Brno kitchens get a Moravian drop, scheduled apart from Prague. Price and date are agreed. No wholesale rates on the site.",
              "Brünner Küchen bekommen eine mährische Tour, getrennt von Prag. Preis und Termin vereinbaren wir. Keine Großhandelssätze auf der Website.",
              "Brnenským kuchyniam skladáme závoz na Moravu zvlášť od Prahy. Cenu a termín dohodneme. Veľkoobchodné sadzby na webe nie sú."),
            t("Velkoobchod do Brna",
              "Wholesale to Brno",
              "Großhandel nach Brünn",
              "Veľkoobchod do Brna"),
            t("Moravská trasa, jiný den než Praha. Stejných pět směsí z Kochánova. Minimum a cenu řekneme po poptávce — ne z pražské stránky.",
              "A Moravian route, a different day from Prague. The same five mixes from Kochánov. Minimum and price come after you enquire — not from the Prague page.",
              "Eine mährische Strecke, ein anderer Tag als Prag. Dieselben fünf Mischungen aus Kochánov. Minimum und Preis nach der Anfrage — nicht von der Prager Seite.",
              "Moravská trasa, iný deň než Praha. Rovnakých päť zmesí z Kochánova. Minimum a cenu povieme po dopyte — nie z pražskej stránky."),
            [
                ("p", t(
                    "Brno neleží na cestě do Prahy. Závoz na Moravu skládáme zvlášť: jiný den, jiná kilometry, jiná cena dopravy. Proto tahle stránka není kopie Prahy. Pět směsí je stejných, logistika ne.",
                    "Brno is not on the road to Prague. The Moravian drop is scheduled on its own: another day, other kilometres, other freight. This page is not a copy of Prague. The five mixes are the same; the logistics are not.",
                    "Brünn liegt nicht auf dem Weg nach Prag. Die mährische Tour steht allein: anderer Tag, andere Kilometer, andere Fracht. Diese Seite ist keine Kopie von Prag. Die fünf Mischungen sind gleich, die Logistik nicht.",
                    "Brno neleží na ceste do Prahy. Závoz na Moravu skladáme zvlášť: iný deň, iné kilometre, iná cena dopravy. Preto táto stránka nie je kópia Prahy. Päť zmesí je rovnakých, logistika nie.",
                )),
                ("p", t(
                    "Rozvoz do Brna je zdarma od objednávky nad 5000 Kč, po domluvě termínu. Pod touto částkou dopravu naceníme, nebo pošlete vlastního dopravce do Kochánova.",
                    "Delivery to Brno is free for orders over 5000 CZK, by arrangement. Below that we quote freight, or you send your own courier to Kochánov.",
                    "Lieferung nach Brünn ist ab Bestellungen über 5000 Kč kostenlos, nach Terminabsprache. Darunter nennen wir die Fracht, oder Sie schicken einen eigenen Kurier nach Kochánov.",
                    "Rozvoz do Brna je zadarmo od objednávky nad 5000 Kč, po dohode termínu. Pod touto sumou dopravu naceníme, alebo pošlete vlastného dopravcu do Kochánova.",
                )),
                ("h2", t("Jak poptat Brno", "How to enquire for Brno", "Anfrage für Brünn", "Ako dopytovať Brno")),
                ("p", t(
                    "Napište velkoobchodní formulář s tématem Brno, nebo volejte. Řekneme, kdy jedeme na Moravu a kolik bude stát závoz. Sazebník na webu není. Značky brněnských kuchyní nejmenujeme.",
                    "Use the wholesale form with the Brno topic, or phone. We will say when we next run to Moravia and what the drop costs. No rate card on the site. We do not name Brno kitchens.",
                    "Nutzen Sie das Großhandelsformular mit Thema Brünn oder rufen Sie an. Wir sagen, wann wir nach Mähren fahren und was die Tour kostet. Keine Preisliste auf der Website. Brünner Küchen nennen wir nicht.",
                    "Napíšte veľkoobchodný formulár s témou Brno, alebo volajte. Povieme, kedy ideme na Moravu a koľko bude stáť závoz. Sadzobník na webe nie je. Značky brnenských kuchýň nemenujeme.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Je Brno stejné jako Praha?", "Is Brno the same as Prague?", "Ist Brünn dasselbe wie Prag?", "Je Brno rovnaké ako Praha?"),
                 t("Ne. Jiná trasa, jiný den, jiná cena dopravy. Stejných pět směsí.",
                   "No. Another route, another day, another freight price. The same five mixes.",
                   "Nein. Andere Strecke, anderer Tag, anderer Frachtpreis. Dieselben fünf Mischungen.",
                   "Nie. Iná trasa, iný deň, iná cena dopravy. Rovnakých päť zmesí.")),
                (t("Je rozvoz do Brna zdarma?", "Is delivery to Brno free?", "Ist die Lieferung nach Brünn kostenlos?", "Je rozvoz do Brna zadarmo?"),
                 t("Ano — od objednávky nad 5000 Kč, po domluvě termínu.",
                   "Yes — for orders over 5000 CZK, by arrangement.",
                   "Ja — ab Bestellungen über 5000 Kč, nach Terminabsprache.",
                   "Áno — od objednávky nad 5000 Kč, po dohode termínu.")),
                (t("Platí v Brně minimum 25 kg?", "Does the 25 kg minimum apply in Brno?", "Gilt in Brünn das 25-kg-Minimum?", "Platí v Brne minimum 25 kg?"),
                 t("Pražské minimum je 25 kg mix. Pro Brno platí prah zdarma dopravy 5000 Kč; přesné minimum zboží řekneme po poptávce.",
                   "The Prague minimum is 25 kg mixed. For Brno the free-delivery threshold is 5000 CZK; exact goods minimum comes after you enquire.",
                   "Das Prager Minimum ist 25 kg gemischt. Für Brünn gilt die Gratis-Lieferung ab 5000 Kč; das genaue Warenminimum nennen wir nach der Anfrage.",
                   "Pražské minimum je 25 kg mix. Pre Brno platí prah dopravy zadarmo 5000 Kč; presné minimum tovaru povieme po dopyte.")),
                (t("Zveřejňujete brněnské sazby?", "Do you publish Brno rates?", "Veröffentlichen Sie Brünner Sätze?", "Zverejňujete brnenské sadzby?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
                (t("Můžu poslat dopravce do Kochánova?", "Can I send a courier to Kochánov?", "Kann ich einen Kurier nach Kochánov schicken?", "Môžem poslať dopravcu do Kochánova?"),
                 t("Ano. Často to vyjde levněji než náš závoz na Moravu.",
                   "Yes. That is often cheaper than our Moravian drop.",
                   "Ja. Das ist oft günstiger als unsere mährische Tour.",
                   "Áno. Často to vyjde lacnejšie než náš závoz na Moravu.")),
                (t("Jmenujete brněnské zákazníky?", "Do you name Brno customers?", "Nennen Sie Brünner Kunden?", "Menujete brnenských zákazníkov?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
            ],
            t("velkoobchod Brno Jůzlová, Morava knedlíky v prášku",
              "Brno wholesale Jůzlová Moravia dumpling mix",
              "Großhandel Brünn Jůzlová Mähren Knödel",
              "veľkoobchod Brno Jůzlová Morava knedle"),
        ),
        "velkoobchod_zahranici": page(
            t("Mezinárodní velkoobchod — poptávka, bez sazeb na webu",
              "International wholesale — enquire, no rates on the site",
              "Internationaler Großhandel — Anfrage, keine Sätze auf der Website",
              "Medzinárodný veľkoobchod — dopyt, bez sadzieb na webe"),
            t("Zahraničním kuchyním posíláme směsi po dohodě. Velkoobchodní sazby nezveřejňujeme. Dopravu, balení a pojištění platí odběratel.",
              "We ship mixes to foreign kitchens by arrangement. We do not publish wholesale rates. The buyer pays freight, boxing and insurance.",
              "An ausländische Küchen schicken wir Mischungen nach Absprache. Großhandelssätze veröffentlichen wir nicht. Fracht, Karton und Versicherung zahlt der Abnehmer.",
              "Zahraničným kuchyniam posielame zmesi po dohode. Veľkoobchodné sadzby nezverejňujeme. Dopravu, balenie a poistenie platí odberateľ."),
            t("Velkoobchod mimo Česko",
              "Wholesale outside Czechia",
              "Großhandel außerhalb Tschechiens",
              "Veľkoobchod mimo Česka"),
            t("Německo, Rakousko, Slovensko, Polsko i dál. Ozvěte se. Cenu směsí a zásilky řekneme před odesláním. Sazebník na webu není.",
              "Germany, Austria, Slovakia, Poland and further. Write. We quote mixes and the parcel before dispatch. No rate card on the site.",
              "Deutschland, Österreich, Slowakei, Polen und weiter. Schreiben Sie. Mischungen und Paket nennen wir vor dem Versand. Keine Preisliste auf der Website.",
              "Nemecko, Rakúsko, Slovensko, Poľsko aj ďalej. Ozvite sa. Cenu zmesí a zásielky povieme pred odoslaním. Sadzobník na webe nie je."),
            [
                ("p", t(
                    "Mezinárodní velkoobchod není ceník domácností plus poštovné. Množství, celní doklady a dopravce se liší zakázku od zakázky. Proto na webu žádné zahraniční sazby nejsou. Napište formulář s tématem zahraničí, nebo volejte.",
                    "International wholesale is not the household list plus postage. Volume, papers and the carrier change order by order. That is why no foreign rates sit on the site. Use the form topic for international wholesale, or phone.",
                    "Internationaler Großhandel ist nicht die Haushaltsliste plus Porto. Menge, Papiere und der Spediteur ändern sich je Auftrag. Deshalb stehen keine Auslandssätze auf der Website. Nutzen Sie das Formular-Thema Ausland oder rufen Sie an.",
                    "Medzinárodný veľkoobchod nie je cenník domácností plus poštovné. Množstvo, colné doklady a dopravca sa líšia zákazku od zákazky. Preto na webe žiadne zahraničné sadzby nie sú. Napíšte formulár s témou zahraničie, alebo volajte.",
                )),
                ("p", t(
                    "Češi v EU, kteří chtějí pár balení domů, mají stránku Češi v EU. Tahle stránka je pro kuchyně a obchody.",
                    "Czechs in the EU who want a few household packs should use the Czechs in the EU page. This page is for kitchens and shops.",
                    "Tschechen in der EU, die ein paar Haushalts Packungen wollen, nutzen die Seite Tschechen in der EU. Diese Seite ist für Küchen und Läden.",
                    "Česi v EÚ, ktorí chcú pár balení domov, majú stránku Česi v EÚ. Táto stránka je pre kuchyne a obchody.",
                )),
                ("p", price),
                ("links", "b2b"),
                ("form_b2b", None),
            ],
            [
                (t("Jsou na webu zahraniční velkoobchodní ceny?", "Are international wholesale prices on the site?", "Stehen internationale Großhandelspreise auf der Website?", "Sú na webe zahraničné veľkoobchodné ceny?"),
                 t("Ne. Cenu domluvíme po poptávce.", "No. We agree the price after you enquire.", "Nein. Den Preis vereinbaren wir nach der Anfrage.", "Nie. Cenu dohodneme po dopyte.")),
                (t("Kdo platí dopravu?", "Who pays freight?", "Wer zahlt die Fracht?", "Kto platí dopravu?"),
                 t("Odběratel. Doprava, balení a pojištění zvlášť.",
                   "The buyer. Freight, boxing and insurance are extra.",
                   "Der Abnehmer. Fracht, Karton und Versicherung extra.",
                   "Odberateľ. Doprava, balenie a poistenie zvlášť.")),
                (t("Posíláte vzorky do zahraničí?", "Do you send samples abroad?", "Schicken Sie Muster ins Ausland?", "Posielate vzorky do zahraničia?"),
                 t("Ne.", "No.", "Nein.", "Nie.")),
                (t("Kam nejčastěji posíláte?", "Where do you ship most often?", "Wohin schicken Sie am häufigsten?", "Kam najčastejšie posielate?"),
                 t("Německo, Rakousko, Slovensko, Polsko. Jinde se ozvěte.",
                   "Germany, Austria, Slovakia, Poland. Write for elsewhere.",
                   "Deutschland, Österreich, Slowakei, Polen. Anderswo bitte anfragen.",
                   "Nemecko, Rakúsko, Slovensko, Poľsko. Inde sa ozvite.")),
                (t("Je to totéž co zásilka Čechům v EU?", "Is this the same as parcels to Czechs in the EU?", "Ist das dasselbe wie Pakete an Tschechen in der EU?", "Je to to isté čo zásielka Čechom v EÚ?"),
                 t("Ne. Češi v EU mají vlastní stránku pro domácnosti. Tady jsou provozovny.",
                   "No. Czechs in the EU have their own household page. This page is for kitchens.",
                   "Nein. Tschechen in der EU haben eine eigene Haushaltsseite. Hier sind Betriebe.",
                   "Nie. Česi v EÚ majú vlastnú stránku pre domácnosti. Tu sú prevádzky.")),
            ],
            t("mezinárodní velkoobchod Jůzlová, export směsí bez ceníku",
              "international wholesale Jůzlová, no published rates",
              "internationaler Großhandel Jůzlová, keine veröffentlichten Sätze",
              "medzinárodný veľkoobchod Jůzlová, bez zverejnených sadzieb"),
        ),
    }
