# Czech content — source of truth. Recovered from the last-live site where possible.
LANG = {
    "code": "cs",
    "locale": "cs_CZ",
    "name": "Čeština",
    "ui": {
        "nav_home": "Úvod", "nav_about": "Kdo jsme", "nav_delivery": "Kde nás najdete",
        "nav_products": "Produkty", "nav_prices": "Ceník", "nav_recipes": "Recepty",
        "nav_faq": "Časté dotazy", "nav_contact": "Kontakt",
        "nav_b2b": "Velkoobchod", "nav_d2c": "Češi v EU",
        "nav_aria": "Hlavní navigace",
        "menu_open": "Otevřít menu",
        "menu_close": "Zavřít menu",
        "hero_img_alt": "Kochánov z ptačí perspektivy",
        "workshop_caption": "Naše dílna v Kochánově — pytle s moukou, váha a balicí linka.",
        "est": "Rodinná dílna · Kochánov · od roku 2004",
        "hero_h1": "Knedlíky jako od babičky. Hotové za 15 minut.",
        "hero_lead": "Poctivé potravinářské směsi z Vysočiny — bramborová těsta, pudingy, vanilínový cukr a kakao. Z mouky oceněné značkou KLASA, bez kompromisů v kvalitě.",
        "hero_cta": "Zavolejte nebo napište",
        "hero_cta2": "Naše produkty",
        "sec_products": "Naše produkty", "sec_products_kicker": "Co vyrábíme",
        "sec_products_lead": "Pět směsí, které od roku 2004 pečeme a balíme pro domácnosti v Čechách i na Moravě.",
        "sec_recipes": "Recepty z našich směsí", "sec_recipes_kicker": "Inspirace do kuchyně",
        "sec_recipes_lead": "Osvědčené recepty, které z našich směsí připravíte rychle a bez práce navíc.",
        "sec_why": "Proč Jůzlová", "sec_why_kicker": "Rodinná výroba",
        "why_1_h": "Suroviny, které známe jménem",
        "why_1_p": "Pšeničná mouka oceněná značkou KLASA pochází z mlýna v Havlíčkově Brodě — 12 km od naší dílny —, který vlastní a vede naše širší rodina. Kukuřičný škrob v pudincích neobsahuje lepek.",
        "why_2_h": "Rychlost bez kompromisů",
        "why_2_p": "Chlupaté knedlíky máte hotové za 15 minut — a chutí je nerozeznáte od knedlíků připravovaných celé odpoledne.",
        "why_3_h": "Proč jsou ceny nízké",
        "ticker_pickup": "Ceny platí při vyzvednutí v provozovně",
        "why_3_p": "Vyrábíme ve vlastní dílně, máme málo vnějších nákladů a jednoduché obaly. Přímý prodej je zhruba o 40 % levnější než přes překupníky. Vyzvednutím v Kochánově ušetříte dopravu. Rozvoz po Vysočině je zdarma od 5000 Kč. Do Humpolce a Havlíčkova Brodu zdarma od 1000 Kč. Do Jihlavy zdarma od 3000 Kč.",
        "sec_b2b": "Pro restaurace a provozovny",
        "sec_b2b_kicker": "Velkoobchod",
        "sec_b2b_lead": "Už zásobujeme řadu restaurací, pekáren, kaváren a škol. Cenu podle množství domluvíme. Značky zákazníků na webu nejmenujeme.",
        "sec_b2b_btn": "Velkoobchodní nabídka",
        "sec_d2c": "Češi v zahraničí (EU)",
        "sec_d2c_kicker": "Zásilka do Evropy",
        "sec_d2c_lead": "Můžete se ozvat. Platíte dopravu, krabici, pojištění a bublinkovou fólii. Cenu pošleme před odesláním.",
        "sec_d2c_btn": "Jak posíláme do EU",
        "nl_h": "Novinky a recepty e-mailem",
        "nl_kicker": "Odběr novinek",
        "nl_lead": "Až 7 nových receptů týdně z našich směsí: české tradiční, rychlé, sezónní (Vánoce, Velikonoce, léto, zima), evropské i restaurační / Instagram.",
        "nl_consent": "Souhlasím se zasíláním novinek na e-mail. Adresu dostane Jůzlová, juzlj@seznam.cz. Souhlas odvoláte e-mailem.",
        "nl_submit": "Přihlásit se",
        "nl_success": "Děkujeme. Jste přihlášeni k novinkám.",
        "nl_need_email": "Vyplňte e-mail a zaškrtněte souhlas.",
        "form_qty": "Množství (balení nebo kg)",
        "form_fulfill": "Jak chcete zboží převzít",
        "form_fulfill_factory": "Vyzvednutí v dílně Kochánov 40, 582 53",
        "form_fulfill_humpolec": "Vyzvednutí v Humpolci u Pivovaru Bernard (zdarma, den a hodinu domluvíme)",
        "form_fulfill_delivery": "Rozvoz (Vysočina zdarma od 5000 Kč; Humpolec a Havlíčkův Brod od 1000 Kč; Jihlava od 3000 Kč; jinak naceníme)",
        "cta_sample_h": "Chcete objednat?",
        "cta_sample_p": "Zavolejte nebo napište — zboží si vyzvednete v Kochánově či Humpolci, nebo je přivezeme až k vám.",
        "cta_sample_btn": "Zavolejte nebo napište",
        "full_price_list": "Kompletní ceník",
        "all_recipes": "Všechny recepty",
        "carousel_label": "Recepty na úvodu",
        "carousel_prev": "Předchozí recept",
        "carousel_next": "Další recept",
        "carousel_status": "Recept {current} z {total}: {name}",
        "carousel_goto": "Přejít na recept {n}: {name}",
        "faq_b2b_hint": "Provozovny a kuchyně: časté dotazy k velkoobchodu jsou jen na stránce Velkoobchod.",
        "all_faq": "Všechny časté dotazy",
        "sec_faq": "Časté dotazy",
        "sec_faq_kicker": "Stručně a jasně",
        "sec_faq_lead": "Odpovědi, které lidé i vyhledávače hledají nejdřív — odkud jsme, jak objednat a co vyrábíme.",
        "rate_label": "Ohodnoťte tento recept",
        "rate_count": "{n} hodnocení",
        "rate_star": "Ohodnotit {n} z 5",
        "rate_thanks": "Děkujeme. Vaše hodnocení je uložené.",
        "rate_already": "Tento recept už jste hodnotili.",
        "rate_error": "Hodnocení se teď nepodařilo uložit. Zkuste to znovu.",
        "detail": "Více",
        "price_label": "Cena",
        "package_label": "Balení",
        "price_board_label": "Ceny při vyzvednutí v dílně",
        "price_pickup_badge": "Cena z dílny",
        "compare_kicker": "Srovnání",
        "compare_h2": "Srovnání ceny s supermarketem?",
        "compare_lead": "Obecný průměr pro stejné množství a podobnou vyšší kvalitu. V běžných obchodech bývají srovnatelné výrobky často asi čtyřikrát dražší nebo ještě více.",
        "compare_us": "U nás v dílně",
        "compare_shop": "Typický supermarket (odhad)",
        "compare_factor": "Asi 4×",
        "compare_keep": "necháte si zhruba",
        "compare_note": "Jde o obecný průměrný odhad, ne o cenu konkrétního řetězce. Značky a kvalita se liší. Naše čísla jsou ceny zboží při vyzvednutí v dílně — doprava se počítá zvlášť.",
        "reviews_kicker": "Hodnocení",
        "reviews_h2": "Recenze na Google a Seznamu",
        "reviews_lead": "Hvězdičky bereme z živých profilů Google Maps a Seznam Firmy.cz. Kliknutím otevřete aktuální hodnocení.",
        "reviews_google": "Google",
        "reviews_seznam": "Seznam",
        "reviews_open": "Otevřít hodnocení",
        "reviews_count": "{n} hodnocení",
        "reviews_rating_of": "{rating} z 5",
        "reviews_note": "Čísla se obnovují při sestavení webu. Google Maps a Firmy.cz zůstávají zdrojem pravdy.",
        "team_kicker": "Lidé",
        "team_h2": "Rodina za směsmi",
        "team_lead": "Kdo u nás stojí za směsmi — potkáte se s námi tady.",
        "team_photo_note": "Fotografie doplníme. Teď jsou na místě neutrální zástupné portréty.",
        "b2b_vis_1_h": "Pro kuchyně",
        "b2b_vis_1_p": "Restaurace, jídelny, pekárny, kavárny, školy a výrobci zmrzliny — stejných pět směsí, cena podle množství.",
        "b2b_vis_2_h": "Odběr třemi cestami",
        "b2b_vis_2_p": "Vyzvednutí v Kochánově, náš rozvoz, nebo váš dopravce. Domluvíme termín telefonem nebo formulářem.",
        "b2b_vis_3_h": "Brno zdarma od 5000 Kč",
        "b2b_vis_3_p": "Do Brna vozíme zdarma při objednávce nad 5000 Kč, po domluvě. Moravská trasa je jiná než Praha.",
        "b2b_vis_4_h": "Bez sazebníku na webu",
        "b2b_vis_4_p": "Velkoobchodní cenu řekneme po poptávce. Značky kuchyní na webu nejmenujeme.",
        "b2b_brno_free": "Brno: rozvoz zdarma od objednávky nad 5000 Kč, po domluvě termínu.",
        "order_info": "Jak objednat",
        "breadcrumb_home": "Úvod",
        "footer_products": "Produkty", "footer_recipes": "Recepty", "footer_company": "Firma",
        "footer_note": "Rodinná výroba potravinářských směsí od roku 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina",
        "open_hours": "Otevřeno denně po telefonické domluvě, 8:00–19:00 (včetně víkendů)",
        "lang_label": "Jazyk",
        "recipe_meta": "Recept z dílny Jůzlová",
        "uses_product": "Použitá směs",
        "more_recipes": "Když vás tohle baví",
        "more_recipes_kicker": "Návrhy k tomuto receptu",
        "more_recipes_lead": "Další recepty, které se k tomu hodí — stejná směs, nebo podobné pečení.",
        "more_recipe_open": "Otevřít recept: {name}",
        "form_h": "Napište nám",
        "form_hint": "Stačí jméno a telefon nebo e-mail. Objednávky také na +420 728 466 141 (Jiřina) a +420 607 629 931 (Jiří).",
        "form_google_pending": "",
        "map_title": "Mapa provozovny Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_addr": "Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_open": "Otevřít v Google Maps",
        "map_nav_google": "Navigovat v Google Maps",
        "map_nav_seznam": "Navigovat v Seznam Mapy",
        "form_name": "Jméno",
        "form_phone": "Telefon",
        "form_email": "E-mail",
        "form_buyer": "Odebíráte pro",
        "form_buyer_home": "Domácnost",
        "form_buyer_pro": "Restauraci, jídelnu nebo cukrárnu",
        "form_products": "O které směsi máte zájem",
        "form_message": "Zpráva",
        "form_submit": "Odeslat zprávu",
        "form_sending": "Odesílám…",
        "form_success": "Děkujeme, zpráva je u nás. Ozveme se vám kvůli objednávce.",
        "form_error": "Zprávu se teď nepodařilo odeslat. Zkuste to znovu, nebo nám zavolejte.",
        "form_captcha": "Ověření se nezdařilo. Obnovte stránku a zkuste to znovu.",
        "form_honeypot": "Toto pole nevyplňujte",
        "form_need_contact": "Vyplňte telefon nebo e-mail.",
        "cookie_aria": "Souhlas s cookies",
        "cookie_text": "Počítání návštěv v Google Analytics používá soubory cookie. Bez souhlasu stránka funguje stejně. Cloudflare počítá návštěvy i bez cookie.",
        "cookie_accept": "Souhlasím",
        "cookie_essential": "Jen nezbytné",
    },
    "meta": {
        "home_title": "Jůzlová — knedlíky v prášku, Kochánov Vysočina",
        "home_desc": "Rodinná dílna v Kochánově na Vysočině. Knedlíky v prášku 5 kg/250 Kč, chlupaté 260 Kč, puding 60 Kč, kakao 270 Kč. Odběr denně 8–19 po telefonu.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Kdo jsme — rodinná dílna Jůzlová od 2004",
            "desc": "Rodinná dílna v Kochánově na Vysočině od roku 2004. Rod Jůzlových, lidé z dílny a recenze na Google a Seznamu.",
            "h1": "Kdo jsme",
            "sub": "Rodinná dílna v Kochánově na Vysočině. Směsi vyrábíme od roku 2004.",
            "body": [
                ("p", "Výrobu potravinářských směsí jsme v malé dílně v Kochánově zahájili v roce 2004. Během let jsme citlivě upravovali receptury, až jsme dosáhli kombinace chuti a kvality, kvůli které nás vyhledávají domácnosti v Čechách i na Moravě."),
                ("p", "Dnes jako obchodní firma „Jůzlová“ stojí za dílnou rodina: Jiřina a Jiří, dcery s partnery a další ruce, které drží výrobu, balení i kontakt se zákazníky. Kochánov je malá obec na Vysočině — kořeny rodu Jůzlových tu sahají stovky let."),
                ("h2", "Náš cíl"),
                ("p", "Držet přímý kontakt a kvalitu, kterou bychom dali i vlastní rodině. Žádný dlouhý řetězec mezi dílnou a vámi."),
                ("team", None),
                ("reviews", None),
            ],
        },
        "kde_nas_najdete": {
            "title": "Kde nás najdete: Kochánov 40 a Humpolec | Jůzlová",
            "desc": "Dílna Kochánov 40, 582 53. Druhý odběr v Humpolci u Pivovaru Bernard, zdarma po domluvě dne a hodiny. Rozvoz po Vysočině zdarma od 5000 Kč.",
            "h1": "Kde nás najdete",
            "sub": "Dílna je Kochánov 40, 582 53, 12 km od Havlíčkova Brodu. Druhé výdejní místo je v Humpolci, v okolí Pivovaru Bernard.",
            "body": [
                ("p", "Asi 90 % zakázek je místních kolem Kochánova 40, 582 53 na Vysočině. Objednáte formulářem nebo telefonem. Vyberete dílnu, Humpolec, nebo rozvoz."),
                ("h2", "Dílna v Kochánově"),
                ("p", "Adresa je Kochánov 40, 582 53. Vyzvednutí v dílně je zdarma. Otevřeno denně 8:00–19:00 po telefonu, včetně víkendů."),
                ("map", None),
                ("h2", "Odběr v Humpolci, zdarma"),
                ("p", "Druhé výdejní místo je v Humpolci u dcery majitelky. Vyzvednutí je zdarma, nic za to neúčtujeme. Místo je v okolí Pivovaru Bernard, ne u vrat pivovaru. Den a hodinu vždy domluvíme. Ulice ani číslo popisné tu neuvádíme."),
                ("h2", "Rozvoz"),
                ("p", "Rozvoz po Vysočině je zdarma u objednávek nad 5000 Kč. Do Humpolce a Havlíčkova Brodu je rozvoz zdarma nad 1000 Kč. Do Jihlavy je rozvoz zdarma nad 3000 Kč. Jinde cenu dopravy naceníme a účtujeme vám. Můžete použít i vlastního dopravce, často vyjde levněji."),
                ("h2", "Možnosti doručení"),
                ("ol", ["Vyzvednutí v dílně Kochánov 40, 582 53, zdarma",
                        "Vyzvednutí v Humpolci v okolí Pivovaru Bernard, zdarma, den a hodinu domluvíme",
                        "Rozvoz po Vysočině zdarma od 5000 Kč; do Humpolce a Havlíčkova Brodu zdarma od 1000 Kč; do Jihlavy zdarma od 3000 Kč",
                        "Jinde rozvoz podle naší nabídky, nebo váš vlastní dopravce",
                        "Zásilka do DE, AT, SK, PL a k Čechům v EU: dopravu, balení a pojištění platíte vy"]),
            ],
        },
        "kontakt": {
            "title": "Kontakt Jůzlová — Kochánov 40, odběr Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) a Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Odběr zboží také v Humpolci.",
            "h1": "Kontakt",
            "sub": "Ozvěte se nám telefonicky nebo e-mailem — domluvíme objednávku, odběr i rozvoz.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("newsletter", None),
                ("h2", "Kde nás najdete"),
                ("map", None),
                ("p", "Dílna: Kochánov 40, 582 53, kraj Vysočina — 12 km od Havlíčkova Brodu. Druhý odběr je v Humpolci v okolí Pivovaru Bernard, zdarma, den a hodinu domluvíme."),
                ("p", "Jůzlová s.r.o. · IČO 45900124"),
            ],
        },
        "ceny": {
            "title": "Ceník knedlíků v prášku — Jůzlová Kochánov",
            "desc": "Ceník při vyzvednutí v Kochánově 40, 582 53: knedlíky 250 Kč, chlupaté 260 Kč, puding 60/30 Kč, cukr 60 Kč, kakao 270 Kč.",
            "h1": "Ceník",
            "sub": "Ceny platí při vyzvednutí v dílně. Kochánov 40, 582 53, Vysočina.",
            "body": [
                ("p", "Ceny platí při vyzvednutí v provozovně Jůzlová, Kochánov 40, 582 53, kraj Vysočina. Bramborové knedlíky v prášku stojí 250 Kč za 5 kg, chlupaté knedlíky (bosáky) 260 Kč za 5 kg, vanilkový puding bez lepku 60 Kč za 1 kg nebo 30 Kč za 400 g, vanilínový cukr 60 Kč za 1 kg a kakao holandského typu 270 Kč za 500 g. Kakaový puding jako hotovou směs nevedeme — čokoládovou chuť smícháte z vanilkového pudingu a kakaa."),
                ("pricetable", None),
                ("p", "Zboží si vyzvednete v Kochánově po telefonu na +420 728 466 141 (Jiřina Jůzlová) nebo +420 607 629 931 (Jiří Jůzl), e-mail juzlj@seznam.cz. Denně 8:00–19:00 včetně víkendů, vždy po předchozí domluvě. Po dohodě je odběr možný i v Humpolci. Starší ceny z roku 2017, které ještě někde na internetu visí, neplatí."),
                ("h2", "Proč jsou ceny nízké"),
                ("p", "Máme vlastní dílnu, málo vnějších nákladů a jednoduché obaly. Přímý prodej je zhruba o 40 % levnější než přes překupníky. Vyzvednutím v Kochánově ušetříte dopravu. Rozvoz po Vysočině zdarma od 5000 Kč. Do Humpolce a Havlíčkova Brodu zdarma od 1000 Kč. Do Jihlavy zdarma od 3000 Kč."),
            ],
        },
        "velkoobchod": {
            "title": "Velkoobchod — restaurace, pekárny, školy | Jůzlová",
            "desc": "Jůzlová dodává restauracím, pekárnám, kavárnám, školám a výrobcům zmrzliny. Cena podle množství. Odběr v dílně, náš rozvoz, nebo váš dopravce.",
            "h1": "Velkoobchod pro provozovny",
            "sub": "Restaurace, pekárny, kavárny, školy i výrobci zmrzliny. Cenu podle množství domluvíme.",
            "body": [
                ("p", "Jůzlová už zásobuje řadu restaurací, pekáren, kaváren a škol. Značky zákazníků tu nejmenujeme. Asi 90 % zakázek je místních kolem Kochánova 40, 582 53 na Vysočině."),
                ("b2b_showcase", None),
                ("h2", "Komu dodáváme"),
                ("ul", [
                    "restauracím a jídelnám — knedlíky a puding na výdej",
                    "pekárnám a cukrárnám — puding, vanilínový cukr, kakao",
                    "kavárnám a coffee shopům — kakao a puding",
                    "školám — směsi na dětská jídla",
                    "výrobcům zmrzliny — kakao holandského typu",
                ]),
                ("h2", "Cena a objednávka"),
                ("p", "Cenu podle množství domluvíme. Napište formulář s výrobky a množstvím, nebo volejte +420 728 466 141 (Jiřina) a +420 607 629 931 (Jiří)."),
                ("h2", "Odběr a doprava"),
                ("ol", [
                    "Vyzvednutí v dílně v Kochánově",
                    "Náš rozvoz — cenu dopravy naceníme a účtujeme vám",
                    "Váš vlastní dopravce — často vyjde levněji",
                ]),
                ("p", "Do Brna je rozvoz zdarma od objednávky nad 5000 Kč, po domluvě termínu. Do Německa, Rakouska, Slovenska a Polska posíláme velkoobchodní zásilky na náklady zákazníka."),
                ("form_b2b", None),
            ],
        },
        "do_eu": {
            "title": "Zásilky Čechům v EU — doprava na vaše náklady | Jůzlová",
            "desc": "Češi v EU si můžou objednat směsi Jůzlová. Platíte dopravu, krabici, pojištění a bublinkovou fólii. Cenu pošleme před odesláním.",
            "h1": "Češi v zahraničí (EU)",
            "sub": "Můžete se ozvat. Zásilku pošleme po nákupu dopravy, balení a pojištění. Cenu uvidíte před odesláním.",
            "body": [
                ("p", "Češi v Evropské unii si můžou zboží Jůzlová objednat. Platíte dopravu, krabici, pojištění a bublinkovou fólii. Částku pošleme před odesláním — nic neposíláme naslepo."),
                ("p", "Nejčastěji posíláme do Německa, Rakouska, Slovenska a Polska. Jinde v EU se ozvěte, nacíníme dopravu."),
                ("p", "Ceny na ceníku platí při vyzvednutí v Kochánově. K zásilce se připočte doprava, balení a pojištění."),
                ("form", None),
            ],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Bramborové knedlíky v prášku",
            "short": "Náš nejvyhledávanější výrobek. Klasické knedlíky, šišky, krokety i gnocchi z jednoho těsta.",
            "price": "5 kg / 250 Kč",
            "title": "Bramborové knedlíky v prášku — 5 kg / 250 Kč",
            "desc": "Bramborové těsto v prášku z mouky oceněné značkou KLASA a sušených bramborových vloček. Na knedlíky klasické i plněné, šišky s mákem, krokety a gnocchi.",
            "body": [
                ("p", "Bramborové těsto v prášku je náš nejvyhledávanější výrobek. Používáme kvalitní pšeničnou mouku oceněnou značkou KLASA z blízkého mlýna v Havlíčkově Brodě, který vlastní a vede naše širší rodina; typickou chuť a konzistenci zajišťují sušené bramborové vločky."),
                ("h2", "Co z těsta připravíte"),
                ("ul", ["klasické bramborové knedlíky k pečenému masu",
                        "knedlíky plněné masem nebo ovocem",
                        "šišky s mákem", "fritované krokety", "domácí gnocchi"]),
                ("p", "Na přirozené chuti poznáte, že v těstě není nic navíc — jen to, co do bramborového knedlíku patří."),
            ],
            "faq": [
                ("Jak dlouho trvá příprava?", "Těsto stačí smíchat s vodou, vytvarovat a povařit — knedlíky máte na stole do 20 minut."),
                ("Kolik porcí je z 5kg balení?", "Z pětikilogramového balení připravíte přílohu zhruba pro 60–70 porcí."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Chlupaté knedlíky v prášku",
            "short": "Bosáky podle tradiční receptury. Hotové za 15 minut, chutí k nerozeznání od domácích.",
            "price": "5 kg / 260 Kč",
            "title": "Chlupaté knedlíky (bosáky) v prášku — 5 kg / 260 Kč",
            "desc": "Chlupaté knedlíky podle tradiční receptury: za 15 minut hotové, oblíbené v jídelnách i restauracích. Balení 5 kg za 260 Kč.",
            "body": [
                ("p", "Chlupaté knedlíky v prášku (bosáky) stojí 260 Kč za 5 kg při vyzvednutí v dílně Jůzlová, Kochánov 40, 582 53, Vysočina. Hotové jsou za 15 minut: směs smícháte s vodou, vytvarujete a povaříte. Vyrábíme je podle tradiční receptury, proto je berou jídelny i domácnosti. Chuť nerozeznáte od knedlíků ze syrových brambor. Objednávka na +420 728 466 141 nebo +420 607 629 931, e-mail juzlj@seznam.cz, denně 8:00–19:00 po telefonu. Kakaový puding jako hotovou směs nevedeme — to je jiný výrobek."),
                ("p", "Hodí se se zelím a uzeným, s cibulkou a škvarky, nebo sladce s mákem a cukrem. Cena 260 Kč platí při odběru v Kochánově; po dohodě i v Humpolci. Starší internetové ceny z roku 2017 neplatí."),
            ],
            "faq": [
                ("K čemu se chlupaté knedlíky hodí?", "Tradičně se podávají se zelím a uzeným masem, s cibulkou a škvarky, nebo sladce s mákem a cukrem."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Vanilkový puding bez lepku",
            "short": "Kukuřičný škrob bez lepku, přirozená vanilková chuť. Na dezerty i pečení.",
            "price": "1 kg / 60 Kč · 400 g / 30 Kč",
            "title": "Vanilkový puding bez lepku — 1 kg / 60 Kč",
            "desc": "Instantní vanilkový puding z kukuřičného škrobu bez lepku. Přirozená chuť bez chemických odstínů, vhodný i pro bezlepkovou dietu. 1 kg / 60 Kč, 400 g / 30 Kč.",
            "body": [
                ("p", "Vanilkový puding bez lepku stojí 60 Kč za 1 kg nebo 30 Kč za 400 g při vyzvednutí v Jůzlové, Kochánov 40, 582 53. Základem je kukuřičný škrob bez lepku — hodí se na dezerty i do pečení. Kakaový puding jako hotovou směs neprodáváme. Čokoládovou chuť smícháte z tohoto vanilkového pudingu a našeho kakaa holandského typu (500 g / 270 Kč). Objednávka telefonem +420 728 466 141 nebo +420 607 629 931, e-mail juzlj@seznam.cz, denně 8:00–19:00 po domluvě."),
                ("p", "Chuť je přirozená, bez chemických odstínů. Ceny platí při odběru v dílně. Starší ceníky z roku 2017 na internetu neplatí."),
            ],
            "faq": [
                ("Je puding opravdu bez lepku?", "Ano. Základem je čistý kukuřičný škrob, který lepek neobsahuje."),
                ("Vyrábíte i čokoládovou variantu?", "Kakaový puding jako hotovou směs nevedeme. Čokoládovou chuť dáte vanilkovému pudingu kakaem holandského typu, které prodáváme samostatně."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holandského typu",
            "short": "Tmavé cukrářské kakao třídy 21 % tuku. Červenohnědá barva, krémová chuť, bez přidaného cukru.",
            "price": "500 g / 270 Kč",
            "title": "Kakao holandského typu 21 % tuku — 500 g / 270 Kč",
            "desc": "Tmavé cukrářské kakao holandského typu s 20–22 % kakaového másla. Bez přidaného cukru, veganské, bez 14 alergenů EU. 500 g / 270 Kč.",
            "body": [
                ("p", "Nabízíme tmavé cukrářské kakao holandského typu — alkalizovaný prášek z bobů Theobroma cacao, třídy 21 % tuku. Plné čokoládové tělo, krémová chuť a sytá červenohnědá barva, která drží v suchém stavu i v receptu."),
                ("h2", "Odkud kakao přichází"),
                ("p", "Kakaové boby pomalu dosychají na slunci ve střední západní Africe. Přirozeně kvasí v banánových listech — tak se rodí hluboká čokoládová chuť, kterou alkalizací zjemníme do kakaa holandského typu."),
                ("h2", "Tuk 20–22 %: proč na něm záleží"),
                ("p", "Kakaové máslo držíme v rozmezí 20,0–22,0 %. Je to víc tuku než u hubených supermarketových kakaí (často 10–12 %). Víc másla znamená víc vlhkosti v těstě, kulatější pocit v ústech a plnější čokoládový dojem — proto ho cukráři berou jako třídu 21 %."),
                ("h2", "Bez přidaného cukru"),
                ("p", "Cukr do kakaa nepřidáváme. Jediné cukry, které v něm najdete — 0,9 g na 100 g — vznikly v kakaovém bobu samy."),
                ("cocoa_sensory", None),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
            ],
            "showcase": {
                "sensory_h": "Chuťový profil",
                "sensory_lead": "Plná kakaová intenzita, krémová čokoládová chuť a pražené tóny. Barva je sytě červenohnědá — v prášku i v hotovém moučníku.",
                "axes": [
                    {"label": "Intenzita", "value": 92},
                    {"label": "Krémovost", "value": 88},
                    {"label": "Pražení", "value": 78},
                    {"label": "Barva", "value": 94},
                    {"label": "Jemnost", "value": 86},
                ],
                "apps_h": "Kam kakao patří",
                "apps": [
                    {"title": "Pečení", "text": "Perník, koláče a těsta, která mají zůstat sytě kakaová i po upečení."},
                    {"title": "Nápoje", "text": "Mléčné kakao a koktejly — v mléce drží barvu i krémovou chuť."},
                    {"title": "Krémy", "text": "Náplně, krémy a lehké dezerty, kde chcete čokoládu bez přidaného cukru v prášku."},
                    {"title": "Posyp", "text": "Hotové řezy, rolády a bebe dezerty — tmavý, jemný prach, který se nesráží."},
                    {"title": "S vanilkovým pudingem", "text": "Zamíchejte do našeho vanilkového pudingu: vznikne čokoládový krém z jedné směsi."},
                    {"title": "Kaše a cereálie", "text": "Snídaňové kaše a cereálie, které mají chutnat po čokoládě, ne po hořkém prášku."},
                ],
                "nutri_h": "Co v kakau je",
                "nutri_lead": "Na 100 g: hodně vlákniny a bílkovin, přirozeně málo cukru, žádný přidaný cukr.",
                "nutri_extra": "K tomu hořčík 490 mg, draslík 4 400 mg a železo 31 mg na 100 g.",
                "nutri_note": "Orientační údaje na 100 g podle nařízení EU 1169/2011. Kakao používáte po lžících — hodnoty na porci jsou zlomkem tabulky.",
                "bars": [
                    {"label": "Energie", "text": "379 kcal / 1 570 kJ", "pct": 19},
                    {"label": "Tuk", "text": "21,0 g  ·  nasycené 13,0 g", "pct": 30},
                    {"label": "Vláknina", "text": "28,4 g", "pct": 100},
                    {"label": "Bílkoviny", "text": "19,5 g", "pct": 39},
                    {"label": "Cukry", "text": "0,9 g  ·  přidané 0 g", "pct": 2},
                    {"label": "Železo", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technické údaje",
                "facts": [
                    {"label": "Kakaové máslo", "value": "20,0–22,0 %"},
                    {"label": "pH (10% roztok)", "value": "7,8–8,2"},
                    {"label": "Jemnost", "value": "min. 99,5 % pod 75 µm"},
                    {"label": "Vlhkost", "value": "max. 5,0 %"},
                    {"label": "Slupky", "value": "max. 1,75 %"},
                    {"label": "Alergeny EU", "value": "žádné ze 14"},
                    {"label": "Lepek", "value": "< 20 ppm"},
                    {"label": "Strava", "value": "veganské, vegetariánské"},
                ],
            },
            "faq": [
                ("Čím se liší kakao holandského typu?", "Alkalizací — je tmavší, méně kyselé a lépe se rozpouští než přírodní kakao. S 20–22 % tuku patří k nejkvalitnějším cukrářským kakaům."),
                ("Přidáváte cukr?", "Ne. Přidaný cukr je 0 g. Přirozené cukry z bobu jsou 0,9 g na 100 g."),
                ("Je kakao bez lepku a alergenů?", "Ano. Neobsahuje žádný ze 14 alergenů EU. Lepek je pod 20 ppm. Je veganské a vegetariánské — bez surovin živočišného původu."),
                ("Jak kakao skladovat?", "V suchu, mimo silné pachy, ideálně při 15–20 °C a vlhkosti pod 50 %."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilínový cukr",
            "short": "Jemně mletý cukr s vanilínovým aroma. Do těsta i na posyp cukroví.",
            "price": "1 kg / 60 Kč",
            "title": "Vanilínový cukr — 1 kg / 60 Kč",
            "desc": "Vanilínový cukr z jemně mletého cukru s vanilínovým aroma. Na koláče, zákusky i vánoční cukroví — do těsta i na posyp. 1 kg / 60 Kč.",
            "body": [
                ("p", "Vanilínový cukr stojí 60 Kč za 1 kg při vyzvednutí v dílně Jůzlová, Kochánov 40, 582 53, Vysočina. Je to jemně mletý cukr s vanilínovým aroma — do těsta i na posyp cukroví, ne lusk vanilky. Objednáte na +420 728 466 141 (Jiřina) nebo +420 607 629 931 (Jiří), e-mail juzlj@seznam.cz, denně 8:00–19:00 po telefonu. Nejde o kakaový puding; ten jako hotovou směs nevedeme."),
                ("p", "Hodí se do koláčů, zákusků a vánočního cukroví. Cena 60 Kč platí při odběru v Kochánově. Starší ceny z roku 2017 neplatí."),
            ],
            "faq": [
                ("Hodí se vanilínový cukr do vánočního cukroví?",
                 "Ano. Do těsta i na posyp hotového cukroví. Balení 1 kg / 60 Kč."),
                ("Je to vanilka, nebo vanilin?",
                 "Vanilínový cukr: jemně mletý cukr s vanilínovým aroma, ne lusk vanilky."),
            ],
        },
    },
    "recipes_intro": "Vyzkoušejte osvědčené recepty z našich směsí — od nedělních knedlíků po nepečené dezerty.",
    "faq_page": {
        "title": "Časté dotazy — objednávky, dodání, směsi Jůzlová",
        "desc": "Odpovědi na nejčastější otázky o Jůzlové: kde sídlíme, jak objednat, ceny, bezlepkový puding, kakao holandského typu a rozvoz na Vysočině.",
        "h1": "Časté dotazy",
        "sub": "Krátké, přímé odpovědi — pro lidi, Google, Seznam.cz i jazykové modely.",
    },
    "recipes": {},  # filled from archive after workflow completes
}
