# German content — full translation of content_cs.py (de_DE, Sie form).
LANG = {
    "code": "de",
    "locale": "de_DE",
    "name": "Deutsch",
    "ui": {
        "nav_home": "Startseite", "nav_about": "Über uns", "nav_delivery": "Lieferung",
        "nav_products": "Produkte", "nav_prices": "Preisliste", "nav_recipes": "Rezepte",
        "nav_contact": "Kontakt",
        "nav_aria": "Hauptnavigation",
        "skip_label": "Zum Inhalt springen",
        "menu_open": "Menü öffnen",
        "menu_close": "Menü schließen",
        "hero_img_alt": "Kochánov aus der Luft",
        "brand_tag": "Lebensmittelmischungen · Vysočina, Tschechien",
        "workshop_caption": "Unsere Werkstatt in Kochánov — Mehlsäcke, Waage und Abfülllinie.",
        "est": "Familienbetrieb · Kochánov · seit 2004",
        "hero_h1": "Knödel wie bei Großmutter. Fertig in 15 Minuten.",
        "hero_lead": "Ehrliche Lebensmittelmischungen aus der Vysočina (Böhmisch-Mährische Höhe) — Kartoffelteige, Pudding, Vanillinzucker und Kakao. Aus Mehl mit dem tschechischen Gütesiegel KLASA, ohne Kompromisse bei der Qualität.",
        "hero_cta": "Anrufen oder schreiben",
        "hero_cta2": "Unsere Produkte",
        "sec_products": "Unsere Produkte", "sec_products_kicker": "Was wir herstellen",
        "sec_products_lead": "Sechs Mischungen, die wir seit 2004 an Haushalte, Restaurants, Kantinen und Konditoreien in Böhmen und Mähren liefern.",
        "sec_recipes": "Rezepte mit unseren Mischungen", "sec_recipes_kicker": "Inspiration für die Küche",
        "sec_recipes_lead": "Bewährte Rezepte, die Sie mit unseren Mischungen schnell und ohne Mehraufwand zubereiten.",
        "sec_why": "Warum Jůzlová", "sec_why_kicker": "Familienproduktion",
        "why_1_h": "Zutaten, die wir beim Namen kennen",
        "why_1_p": "Unser Weizenmehl mit dem tschechischen Gütesiegel KLASA stammt aus einer Mühle in Havlíčkův Brod, 12 km von unserer Werkstatt entfernt. Die Maisstärke in unseren Puddings ist glutenfrei.",
        "why_2_h": "Schnell, ohne Kompromisse",
        "why_2_p": "Haarige Knödel (Bosáky) sind in 15 Minuten fertig — und geschmacklich nicht von Knödeln zu unterscheiden, an denen man den ganzen Nachmittag arbeitet.",
        "why_3_h": "Günstiger als im Supermarkt",
        "why_3_p": "Wir bieten Qualität zu einem Preis unter dem von Supermarktprodukten unklarer Herkunft. Kartoffelknödel: 5 kg für 165 Kč.",
        "cta_sample_h": "Möchten Sie bestellen?",
        "cta_sample_p": "Rufen Sie an oder schreiben Sie uns — holen Sie die Ware in Kochánov oder Humpolec ab, oder wir liefern sie zu Ihnen.",
        "cta_sample_btn": "Anrufen oder schreiben",
        "full_price_list": "Komplette Preisliste",
        "all_recipes": "Alle Rezepte",
        "detail": "Mehr",
        "price_label": "Preis",
        "package_label": "Verpackung",
        "order_info": "So bestellen Sie",
        "breadcrumb_home": "Startseite",
        "footer_products": "Produkte", "footer_recipes": "Rezepte", "footer_company": "Unternehmen",
        "footer_note": "Familienproduktion von Lebensmittelmischungen seit 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina, Tschechien",
        "open_hours": "Täglich geöffnet nach telefonischer Absprache, 8:00–19:00 Uhr (auch am Wochenende)",
        "lang_label": "Sprache",
        "recipe_meta": "Ein Rezept aus der Werkstatt Jůzlová",
        "uses_product": "Verwendete Mischung",
        "form_h": "Schreiben Sie uns",
        "form_hint": "Das ist ein natives Google-Formular. Antworten gehen an das in Google Forms hinterlegte Postfach (juzlj@seznam.cz).",
        "form_google_pending": "Das Google-Formular ist noch nicht verbunden. Rufen Sie +420 728 466 141 an, oder kopieren Sie in Google Forms unter Senden → Einbetten die iframe-URL und setzen Sie GOOGLE_FORM_EMBED_URL.",
        "form_name": "Name",
        "form_phone": "Telefon",
        "form_email": "E-Mail",
        "form_products": "Welche Mischungen möchten Sie bestellen",
        "form_message": "Nachricht",
        "form_submit": "Nachricht senden",
        "form_sending": "Wird gesendet…",
        "form_success": "Danke, Ihre Nachricht ist bei uns. Wir melden uns zu Ihrer Bestellung.",
        "form_error": "Die Nachricht konnte gerade nicht gesendet werden. Bitte erneut versuchen oder anrufen.",
        "form_captcha": "Die Prüfung ist fehlgeschlagen. Bitte die Seite neu laden und erneut versuchen.",
        "form_honeypot": "Dieses Feld leer lassen",
    },
    "meta": {
        "home_title": "Jůzlová — Knödelmischungen, Pudding & Kakao aus Vysočina",
        "home_desc": "Familienproduktion seit 2004: Knödelmischungen, glutenfreier Vanille- und Kakaopudding, Vanillinzucker und Kakao holländischer Art. Kochánov, Vysočina.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Über uns — Familienbetrieb seit 2004",
            "desc": "Seit 2004 stellen wir in Kochánov (Vysočina) Lebensmittelmischungen her. Wir beliefern Haushalte, Restaurants, Kantinen und Konditoreien in Böhmen und Mähren.",
            "h1": "Über uns",
            "sub": "Ein Familienbetrieb in Kochánov in der Vysočina (Böhmisch-Mährische Höhe). Lebensmittelmischungen stellen wir seit 2004 her.",
            "body": [
                ("p", "Mit der Herstellung von Lebensmittelmischungen haben wir 2004 in einer kleinen Werkstatt in Kochánov begonnen. Über die Jahre haben wir unsere Rezepturen behutsam verfeinert und die besten Rohstofflieferanten ausgewählt, bis wir jene Verbindung von Geschmack und Qualität erreicht hatten, für die uns Kunden in ganz Böhmen und Mähren schätzen."),
                ("p", "Heute beliefern wir unter dem Firmennamen „Jůzlová“ nicht nur Haushalte, sondern auch zahlreiche Restaurants, Kantinen und Konditoreien. Unsere Kunden schätzen vor allem den traditionellen, hausgemachten Geschmack — und zugleich die Geschwindigkeit, mit der aus unseren Instantmischungen ausgezeichnete Beilagen und Desserts entstehen."),
                ("h2", "Kartoffelteig in Pulverform — unser gefragtestes Produkt"),
                ("p", "Dafür verwenden wir hochwertiges Weizenmehl, das mit dem tschechischen Gütesiegel KLASA ausgezeichnet wurde, aus der nahegelegenen Mühle in Havlíčkův Brod. Getrocknete Kartoffelflocken sorgen für den typischen Geschmack und die charakteristische Konsistenz. Der Teig eignet sich für Kartoffelknödel — klassisch oder mit Fleisch bzw. Obst gefüllt —, für Mohnnudeln, Kroketten und Gnocchi."),
                ("h2", "Glutenfreier Pudding"),
                ("p", "Unser Instant-Vanille- und Schokoladenpudding eignet sich hervorragend für leichte Desserts. Die Basis ist hochwertige Maisstärke, die kein Gluten enthält — der Pudding ist daher auch für eine glutenfreie Ernährung geeignet. In den Kakaopudding mischen wir hochwertigen Kakao holländischer Art mit 21 % Fett, der ihm einen ausgeprägten Schokoladengeschmack verleiht."),
                ("h2", "Unser Ziel"),
                ("p", "Lebensmittelmischungen höchster Qualität herzustellen — zu einem Preis unter dem von Supermarktprodukten unklarer Herkunft. Wir verwenden Rohstoffe bester Güte, weil wir überzeugt sind, dass unsere Kunden nur das Beste verdienen. Wir legen Wert auf den direkten Kontakt zu unseren Kunden und richten uns stets nach ihren Bedürfnissen."),
                ("p", "Möchten Sie bestellen? Melden Sie sich — wir vereinbaren Abholung in Kochánov oder Humpolec, oder Lieferung."),
            ],
        },
        "kde_nas_najdete": {
            "title": "Lieferung und Abholung — Kochánov, Humpolec und Umgebung",
            "desc": "Kostenlose Abholung in Kochánov oder Humpolec, Gratislieferung rund um Havlíčkův Brod, Světlá nad Sázavou und Jihlava, oder Versand per Paketdienst Ihrer Wahl.",
            "h1": "Lieferung",
            "sub": "Unsere Werkstatt liegt in Kochánov, 12 km von Havlíčkův Brod entfernt. Wir sind täglich von 8:00 bis 19:00 Uhr für Sie da, auch am Wochenende.",
            "body": [
                ("p", "Wir wissen, dass für unsere Kunden neben der Qualität auch der Preis zählt. Da Versandkosten unsere Produkte verteuern können, bieten wir die Abholung direkt in unserer Betriebsstätte in Kochánov an. Melden Sie sich einfach vorab — wir stellen Ihre Ware jederzeit zur Abholung bereit."),
                ("p", "Nach vorheriger Absprache können Sie Ihre Ware auch in Humpolec abholen. Derzeit liefern wir in und um Havlíčkův Brod, Humpolec, Světlá nad Sázavou und Jihlava — und nach individueller Absprache bringen wir die Ware auch direkt zu Ihnen nach Hause."),
                ("h2", "Liefermöglichkeiten"),
                ("ol", ["Abholung in unserer Betriebsstätte in Kochánov oder in Humpolec — kostenlos",
                        "Gratislieferung in der Umgebung von Havlíčkův Brod, Světlá nad Sázavou und Jihlava",
                        "Paketdienst Ihrer Wahl (Versandkosten laut Preisliste des Anbieters)"]),
                ("h2", "Wann Sie vorbeikommen können"),
                ("p", "Täglich geöffnet nach telefonischer Absprache: Montag–Sonntag, 8:00–19:00 Uhr."),
            ],
        },
        "kontakt": {
            "title": "Kontakt — Jůzlová, Kochánov 40, Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) und Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-Mail juzlj@seznam.cz. Abholung auch in Humpolec möglich.",
            "h1": "Kontakt",
            "sub": "Rufen Sie uns an oder schreiben Sie uns — wir vereinbaren Bestellung, Abholung oder Lieferung.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("h2", "So finden Sie uns"),
                ("p", "Betriebsstätte: Kochánov 40, 582 53, Region Vysočina, Tschechien — 12 km von Havlíčkův Brod entfernt. Nach vorheriger Absprache ist die Abholung auch in Humpolec möglich."),
                ("p", "Jůzlová s.r.o. · Unternehmens-ID (IČO) 45900124"),
            ],
        },
        "ceny": {
            "title": "Preisliste — Knödelmischungen, Pudding, Zucker, Kakao",
            "desc": "Preise: Kartoffelknödel 5 kg / 165 Kč, Haarige Knödel 5 kg / 185 Kč, Vanillepudding ab 17 Kč, Kakaopudding ab 22 Kč, Vanillinzucker 38 Kč, Kakao 100 Kč.",
            "h1": "Preisliste",
            "sub": "Qualität zu Preisen unter Supermarktniveau. Die Preise gelten bei Abholung in Kochánov oder Humpolec.",
            "body": [("pricetable", None),
                     ("p", "Für Restaurants, Kantinen und Konditoreien erstellen wir individuelle Angebote je nach Abnahmemenge — sprechen Sie uns an.")],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Kartoffelknödel-Mischung",
            "short": "Unser gefragtestes Produkt. Klassische Knödel, Mohnnudeln, Kroketten und Gnocchi aus einem Teig.",
            "price": "5 kg / 165 Kč",
            "title": "Kartoffelknödel-Mischung — 5 kg / 165 Kč",
            "desc": "Kartoffelteig-Pulver aus KLASA-Mehl (tschechisches Gütesiegel) und Kartoffelflocken. Für klassische und gefüllte Knödel, Mohnnudeln, Kroketten und Gnocchi.",
            "body": [
                ("p", "Kartoffelteig in Pulverform ist unser gefragtestes Produkt. Wir verwenden hochwertiges Weizenmehl mit dem tschechischen Gütesiegel KLASA aus der nahegelegenen Mühle in Havlíčkův Brod; getrocknete Kartoffelflocken sorgen für den typischen Geschmack und die Konsistenz."),
                ("h2", "Was Sie aus dem Teig zubereiten können"),
                ("ul", ["klassische Kartoffelknödel zu Braten",
                        "mit Fleisch oder Obst gefüllte Knödel",
                        "Mohnnudeln (šišky s mákem)", "frittierte Kroketten", "hausgemachte Gnocchi"]),
                ("p", "Am natürlichen Geschmack erkennen Sie: In diesem Teig steckt nichts Überflüssiges — nur das, was in einen Kartoffelknödel gehört."),
            ],
            "faq": [
                ("Wie lange dauert die Zubereitung?", "Einfach das Pulver mit Wasser vermengen, formen und kochen — die Knödel stehen in 20 Minuten auf dem Tisch."),
                ("Wie viele Portionen ergibt der 5-kg-Beutel?", "Aus einem 5-kg-Beutel bereiten Sie eine Beilage für etwa 60–70 Portionen zu."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Haarige Knödel (Bosáky) — Fertigmischung",
            "short": "Bosáky nach traditioneller Rezeptur. Fertig in 15 Minuten, geschmacklich wie hausgemacht.",
            "price": "5 kg / 185 Kč",
            "title": "Haarige Knödel (Bosáky) — Mischung, 5 kg / 185 Kč",
            "desc": "Haarige Kartoffelknödel (Bosáky) nach traditioneller Rezeptur: in 15 Minuten fertig, beliebt in Kantinen und Restaurants. 5-kg-Beutel für 185 Kč.",
            "body": [
                ("p", "Haarige Knödel, in Tschechien auch als Bosáky bekannt, zählen zu unseren beliebtesten Produkten. Wir stellen sie nach traditioneller Rezeptur her."),
                ("p", "Dank der schnellen, einfachen Zubereitung sind sie in Kantinen und Restaurants beliebt — und überzeugen mit Geschmack und Konsistenz auch zu Hause. Sie sind in 15 Minuten fertig und geschmacklich nicht von Knödeln zu unterscheiden, die auf traditionelle Weise aus rohen Kartoffeln zubereitet werden."),
            ],
            "faq": [
                ("Wozu passen Haarige Knödel?", "Traditionell zu Kraut und Geräuchertem, mit Röstzwiebeln und Grieben — oder süß mit Mohn und Zucker."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Glutenfreier Vanillepudding",
            "short": "Glutenfreie Maisstärke, natürlicher Vanillegeschmack. Für Desserts und zum Backen.",
            "price": "1 kg / 34 Kč · 400 g / 17 Kč",
            "title": "Glutenfreier Vanillepudding — 1 kg / 34 Kč",
            "desc": "Instant-Vanillepudding aus glutenfreier Maisstärke. Natürlicher Geschmack ohne chemische Noten, für glutenfreie Ernährung geeignet. 1 kg / 34 Kč, 400 g / 17 Kč.",
            "body": [
                ("p", "Vanillepudding gehört zu unseren traditionellen Produkten. Er eignet sich hervorragend für leichte Desserts und zum Backen."),
                ("p", "Die Basis ist hochwertige Maisstärke, die kein Gluten enthält — der Pudding ist daher auch für eine glutenfreie Ernährung geeignet. Probieren Sie seinen natürlichen Geschmack ohne chemische Noten, und Sie werden zu den gängigen Supermarktmarken nicht mehr zurückkehren."),
            ],
            "faq": [
                ("Ist der Pudding wirklich glutenfrei?", "Ja. Die Basis ist reine Maisstärke, die kein Gluten enthält."),
                ("Gibt es auch eine Schokoladenvariante?", "Ja — Kakaopudding mit Kakao holländischer Art (1 kg / 44 Kč, 400 g / 22 Kč). Er hat eine eigene Seite in der Preisliste und im Menü Produkte."),
            ],
        },
        "kakaovy_pudink": {
            "name": "Glutenfreier Kakaopudding",
            "short": "Fertig in fünf Minuten. Leichtes Dessert, Diätcremes oder Backen — mit Kakao holländischer Art.",
            "price": "1 kg / 44 Kč · 400 g / 22 Kč",
            "title": "Glutenfreier Kakaopudding — 1 kg / 44 Kč",
            "desc": "Instant-Kakaopudding aus glutenfreier Maisstärke und Kakao holländischer Art mit 21 % Fett. 1 kg / 44 Kč, 400 g / 22 Kč.",
            "body": [
                ("p", "Unser Kakaopudding ist in fünf Minuten fertig. Er eignet sich als leichtes Dessert, als Basis für Diätcremes oder zum Backen."),
                ("p", "Die Basis ist glutenfreie Maisstärke. Wir mischen denselben Kakao holländischer Art mit 21 % Fett ein, den wir auch einzeln verkaufen."),
                ("h2", "So kochen Sie ihn"),
                ("p", "Von einem halben Liter Milch ein Drittel abnehmen und darin 40 g Zucker und 40 g Pudding verrühren. Die restliche Milch aufkochen. Die angerührte Mischung zugeben und unter Rühren weitere 2 Minuten kochen."),
            ],
            "faq": [
                ("Ist der Pudding glutenfrei?", "Ja. Die Basis ist reine Maisstärke."),
                ("Worin unterscheidet er sich vom Vanillepudding?", "In den Kakaopudding mischen wir Kakao holländischer Art mit 21 % Fett — der Geschmack ist deutlich schokoladig."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holländischer Art",
            "short": "Dunkler Konditorkakao mit 21 % Fett. Kräftige Farbe und voller Geschmack für Kuchen und Getränke.",
            "price": "500 g / 100 Kč",
            "title": "Kakao holländischer Art, 21 % Fett — 500 g / 100 Kč",
            "desc": "Dunkler Konditorkakao holländischer Art mit 21 % Fett. Satte Kakaofarbe und voller Geschmack für Kuchen; ideal auch für Milchshakes und Cremes. 500 g / 100 Kč.",
            "body": [
                ("p", "Wir bieten einen ausgezeichneten dunklen Konditorkakao holländischer Art mit 21 % Fett an."),
                ("p", "Er kommt in Kuchen und Gebäck besonders zur Geltung und verleiht ihnen eine satte, dunkle Kakaofarbe und vollen Geschmack. Auch köstliche Milchshakes und Cremes gelingen damit. Denselben Kakao mischen wir in unseren Kakaopudding."),
            ],
            "faq": [
                ("Was unterscheidet Kakao holländischer Art?", "Die Alkalisierung — er ist dunkler, weniger säuerlich und löst sich besser auf als naturbelassener Kakao. Mit 21 % Fett zählt er zu den hochwertigsten Konditorkakaos."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanillinzucker",
            "short": "Fein gemahlener Zucker mit Vanillinaroma. Für den Teig und zum Bestreuen von Gebäck.",
            "price": "1 kg / 38 Kč",
            "title": "Vanillinzucker — 1 kg / 38 Kč",
            "desc": "Vanillinzucker aus fein gemahlenem Zucker mit Vanillinaroma. Für Kuchen, Desserts und Weihnachtsgebäck — im Teig und zum Bestreuen. 1 kg / 38 Kč.",
            "body": [
                ("p", "Unser Vanillinzucker enthält neben fein gemahlenem Zucker ein Vanillinaroma, das ihm einen angenehmen, unverwechselbaren Vanilleduft verleiht."),
                ("p", "Sie werden ihn beim Backen von Kuchen, Torten und anderen Desserts zu schätzen wissen. Besonders gut eignet er sich für Weihnachtsgebäck — nicht nur als Zutat im Teig, sondern auch zum Bestreuen des fertigen Gebäcks."),
            ],
            "faq": [],
        },
    },
    "recipes_intro": "Probieren Sie bewährte Rezepte mit unseren Mischungen — vom Sonntagsknödel bis zum Dessert ohne Backen.",
    "recipes": {},
}
