# Czech content — source of truth. Recovered from the last-live site where possible.
LANG = {
    "code": "cs",
    "locale": "cs_CZ",
    "name": "Čeština",
    "ui": {
        "nav_home": "Úvod", "nav_about": "Kdo jsme", "nav_delivery": "Dodání",
        "nav_products": "Produkty", "nav_prices": "Ceník", "nav_recipes": "Recepty",
        "nav_faq": "Časté dotazy", "nav_contact": "Kontakt",
        "nav_aria": "Hlavní navigace",
        "menu_open": "Otevřít menu",
        "menu_close": "Zavřít menu",
        "hero_img_alt": "Kochánov z ptačí perspektivy",
        "workshop_caption": "Naše dílna v Kochánově — pytle s moukou, váha a balicí linka.",
        "est": "Rodinná dílna · Kochánov · od roku 2004",
        "hero_h1": "Knedlíky jako od babičky. Hotové za 15 minut.",
        "hero_lead": "Poctivé potravinářské směsi z Vysočiny — bramborová těsta, pudingy, vanilínový cukr a kakao. Z mouky oceněné značkou KLASA, bez kompromisů v kvalitě.",
        "hero_cta": "Zavolejte nebo napište",
        "hero_cta2": "Naše produkty",
        "sec_products": "Naše produkty", "sec_products_kicker": "Co vyrábíme",
        "sec_products_lead": "Pět směsí, které od roku 2004 dodáváme domácnostem, restauracím, jídelnám i cukrárnám v Čechách i na Moravě.",
        "sec_recipes": "Recepty z našich směsí", "sec_recipes_kicker": "Inspirace do kuchyně",
        "sec_recipes_lead": "Osvědčené recepty, které z našich směsí připravíte rychle a bez práce navíc.",
        "sec_why": "Proč Jůzlová", "sec_why_kicker": "Rodinná výroba",
        "why_1_h": "Suroviny, které známe jménem",
        "why_1_p": "Pšeničná mouka oceněná značkou KLASA pochází z mlýna v Havlíčkově Brodě, 12 km od naší dílny. Kukuřičný škrob v pudincích neobsahuje lepek.",
        "why_2_h": "Rychlost bez kompromisů",
        "why_2_p": "Chlupaté knedlíky máte hotové za 15 minut — a chutí je nerozeznáte od knedlíků připravovaných celé odpoledne.",
        "why_3_h": "Cena pod úrovní supermarketu",
        "why_3_p": "Vyrábíme kvalitu za cenu nižší než „supermarketové“ výrobky nejistého původu. Bramborové knedlíky: 5 kg za 250 Kč.",
        "cta_sample_h": "Chcete objednat?",
        "cta_sample_p": "Zavolejte nebo napište — zboží si vyzvednete v Kochánově či Humpolci, nebo je přivezeme až k vám.",
        "cta_sample_btn": "Zavolejte nebo napište",
        "full_price_list": "Kompletní ceník",
        "all_recipes": "Všechny recepty",
        "all_faq": "Všechny časté dotazy",
        "sec_faq": "Časté dotazy",
        "sec_faq_kicker": "Stručně a jasně",
        "sec_faq_lead": "Odpovědi, které lidé i vyhledávače hledají nejdřív — odkud jsme, jak objednat a co vyrábíme.",
        "rate_label": "Ohodnoťte tento recept",
        "rate_count": "{n} hodnocení",
        "rate_star": "Ohodnotit {n} z 5",
        "rate_thanks": "Děkujeme. Vaše hodnocení je uložené.",
        "rate_already": "Tento recept už jste hodnotili.",
        "rate_error": "Hodnocení se teď nepodařilo uložit. Zkuste to znovu.",
        "detail": "Více",
        "price_label": "Cena",
        "package_label": "Balení",
        "order_info": "Jak objednat",
        "breadcrumb_home": "Úvod",
        "footer_products": "Produkty", "footer_recipes": "Recepty", "footer_company": "Firma",
        "footer_note": "Rodinná výroba potravinářských směsí od roku 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina",
        "open_hours": "Otevřeno denně po telefonické domluvě, 8:00–19:00 (včetně víkendů)",
        "lang_label": "Jazyk",
        "recipe_meta": "Recept z dílny Jůzlová",
        "uses_product": "Použitá směs",
        "more_recipes": "Když vás tohle baví",
        "more_recipes_kicker": "Návrhy k tomuto receptu",
        "more_recipes_lead": "Další recepty, které se k tomu hodí — stejná směs, nebo podobné pečení.",
        "more_recipe_open": "Otevřít recept: {name}",
        "form_h": "Napište nám",
        "form_hint": "Vyplňte jméno, e-mail a zprávu — ozveme se vám na zadaný e-mail. Objednávky také na +420 728 466 141.",
        "form_google_pending": "",
        "map_title": "Mapa provozovny Jůzlová, Kochánov 40, 582 53",
        "form_name": "Jméno",
        "form_phone": "Telefon",
        "form_email": "E-mail",
        "form_products": "O které směsi máte zájem",
        "form_message": "Zpráva",
        "form_submit": "Odeslat zprávu",
        "form_sending": "Odesílám…",
        "form_success": "Děkujeme, zpráva je u nás. Ozveme se vám kvůli objednávce.",
        "form_error": "Zprávu se teď nepodařilo odeslat. Zkuste to znovu, nebo nám zavolejte.",
        "form_captcha": "Ověření se nezdařilo. Obnovte stránku a zkuste to znovu.",
        "form_honeypot": "Toto pole nevyplňujte",
    },
    "meta": {
        "home_title": "Jůzlová — poctivé potravinářské směsi z Vysočiny | knedlíky, pudingy, kakao",
        "home_desc": "Rodinná výroba potravinářských směsí od roku 2004: bramborové a chlupaté knedlíky v prášku, vanilkový puding bez lepku, vanilínový cukr a kakao holandského typu. Kochánov, Vysočina.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Kdo jsme — rodinná výroba směsí od roku 2004",
            "desc": "Výrobu potravinářských směsí jsme zahájili v roce 2004 v malé dílně v Kochánově na Vysočině. Dodáváme domácnostem, restauracím, jídelnám a cukrárnám v Čechách i na Moravě.",
            "h1": "Kdo jsme",
            "sub": "Rodinná dílna v Kochánově na Vysočině. Potravinářské směsi vyrábíme od roku 2004.",
            "body": [
                ("p", "Výrobu potravinářských směsí jsme v malé dílně v Kochánově zahájili v roce 2004. Během let jsme citlivě upravovali receptury a vybírali nejkvalitnější dodavatele surovin, až jsme dosáhli jedinečné kombinace chuti a kvality, kvůli které nás vyhledávají zákazníci v Čechách i na Moravě."),
                ("p", "Dnes jako obchodní firma „Jůzlová“ dodáváme nejen do domácností, ale do řady restaurací, jídelen a cukráren. Naši zákazníci oceňují především tradiční domácí chuť a zároveň rychlost, se kterou je možné z našich instantních výrobků připravit výborné přílohy a dezerty."),
                ("h2", "Bramborové těsto v prášku — náš nejvyhledávanější výrobek"),
                ("p", "Při jeho výrobě používáme kvalitní a značkou KLASA oceněnou pšeničnou mouku z blízkého mlýna v Havlíčkově Brodě. Typickou chuť a charakteristickou konzistenci zajišťují sušené bramborové vločky. Těsto se hodí pro přípravu bramborových knedlíků, ať už klasických, plněných masem nebo ovocem, šišek, kroket či gnocchi."),
                ("h2", "Puding bez lepku"),
                ("p", "Instantní vanilkový puding je skvělý na přípravu sladkých dezertů. Základem je kvalitní kukuřičný škrob, který neobsahuje lepek, takže je vhodný i pro bezlepkovou dietu. Čokoládovou chuť mu dodáte naším kakaem holandského typu s 21 % tuku."),
                ("h2", "Náš cíl"),
                ("p", "Vyrábět potravinářské směsi nejvyšší kvality za cenu pod úrovní „supermarketových“ výrobků nejistého původu. Používáme suroviny nejvyšší jakosti, protože věříme, že naši zákazníci si zaslouží jen to nejlepší. Klademe důraz na přímý kontakt se zákazníky a vždy se snažíme přizpůsobit jejich potřebám."),
                ("p", "Chcete objednat? Ozvěte se — domluvíme odběr v Kochánově či Humpolci, nebo rozvoz."),
            ],
        },
        "kde_nas_najdete": {
            "title": "Dodání zboží a odběrná místa — Kochánov, Humpolec a rozvoz",
            "desc": "Vyzvednutí zdarma v Kochánově nebo Humpolci, bezplatný rozvoz v okolí Havlíčkova Brodu, Světlé nad Sázavou a Jihlavy, nebo zaslání smluvním dopravcem.",
            "h1": "Dodání zboží",
            "sub": "Naše dílna je v Kochánově, 12 km od Havlíčkova Brodu. Jsme vám k dispozici každý den od 8:00 do 19:00, včetně víkendů.",
            "body": [
                ("p", "Uvědomujeme si, že pro naše zákazníky je vedle vysoké kvality výrobků důležitá i cena. Protože ceny smluvních dopravců mohou naše výrobky prodražit, nabízíme možnost vyzvednutí zboží přímo u nás v provozovně v Kochánově. Stačí se předem ozvat a zboží vám kdykoli připravíme k odběru."),
                ("p", "Po předchozí domluvě si zboží můžete vyzvednout také v Humpolci. V současné době rozvážíme v Havlíčkově Brodě, Humpolci, Světlé nad Sázavou, Jihlavě a okolí — a po individuální domluvě přivezeme zboží i přímo k vám domů."),
                ("h2", "Možnosti doručení"),
                ("ol", ["Vyzvednutí zboží na provozovně v Kochánově nebo v Humpolci — zdarma",
                        "Bezplatný závoz zboží v okolí Havlíčkova Brodu, Světlé nad Sázavou a Jihlavy",
                        "Smluvní dopravce dle vašeho výběru (poštovné dle ceníku dopravce)"]),
                ("h2", "Kdy se můžete zastavit"),
                ("p", "Otevřeno denně po telefonické domluvě: pondělí–neděle 8:00–19:00."),
                ("h2", "Provozovna v Kochánově"),
                ("map", None),
            ],
        },
        "kontakt": {
            "title": "Kontakt — Jůzlová, Kochánov 40, Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) a Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Odběr zboží také v Humpolci.",
            "h1": "Kontakt",
            "sub": "Ozvěte se nám telefonicky nebo e-mailem — domluvíme objednávku, odběr i rozvoz.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("h2", "Kde nás najdete"),
                ("map", None),
                ("p", "Provozovna: Kochánov 40, 582 53, kraj Vysočina — 12 km od Havlíčkova Brodu. Po předchozí domluvě je možné vyzvednutí zboží také v Humpolci."),
                ("p", "Jůzlová s.r.o. · IČO 45900124"),
            ],
        },
        "ceny": {
            "title": "Ceník potravinářských směsí — knedlíky, pudingy, cukr, kakao",
            "desc": "Aktuální ceny: bramborové knedlíky 5 kg / 250 Kč, chlupaté knedlíky 5 kg / 260 Kč, vanilkový puding od 30 Kč, vanilínový cukr 60 Kč, kakao 270 Kč.",
            "h1": "Ceník",
            "sub": "Kvalita za cenu pod úrovní supermarketu. Ceny platí při odběru v Kochánově či Humpolci.",
            "body": [("pricetable", None),
                     ("p", "Pro restaurace, jídelny a cukrárny připravíme individuální nabídku podle odebíraného množství — ozvěte se nám.")],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Bramborové knedlíky v prášku",
            "short": "Náš nejvyhledávanější výrobek. Klasické knedlíky, šišky, krokety i gnocchi z jednoho těsta.",
            "price": "5 kg / 250 Kč",
            "title": "Bramborové knedlíky v prášku — 5 kg / 250 Kč",
            "desc": "Bramborové těsto v prášku z mouky oceněné značkou KLASA a sušených bramborových vloček. Na knedlíky klasické i plněné, šišky s mákem, krokety a gnocchi.",
            "body": [
                ("p", "Bramborové těsto v prášku je náš nejvyhledávanější výrobek. Používáme kvalitní pšeničnou mouku oceněnou značkou KLASA z blízkého mlýna v Havlíčkově Brodě; typickou chuť a konzistenci zajišťují sušené bramborové vločky."),
                ("h2", "Co z těsta připravíte"),
                ("ul", ["klasické bramborové knedlíky k pečenému masu",
                        "knedlíky plněné masem nebo ovocem",
                        "šišky s mákem", "fritované krokety", "domácí gnocchi"]),
                ("p", "Na přirozené chuti poznáte, že v těstě není nic navíc — jen to, co do bramborového knedlíku patří."),
            ],
            "faq": [
                ("Jak dlouho trvá příprava?", "Těsto stačí smíchat s vodou, vytvarovat a povařit — knedlíky máte na stole do 20 minut."),
                ("Kolik porcí je z 5kg balení?", "Z pětikilogramového balení připravíte přílohu zhruba pro 60–70 porcí."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Chlupaté knedlíky v prášku",
            "short": "Bosáky podle tradiční receptury. Hotové za 15 minut, chutí k nerozeznání od domácích.",
            "price": "5 kg / 260 Kč",
            "title": "Chlupaté knedlíky (bosáky) v prášku — 5 kg / 260 Kč",
            "desc": "Chlupaté knedlíky podle tradiční receptury: za 15 minut hotové, oblíbené v jídelnách i restauracích. Balení 5 kg za 260 Kč.",
            "body": [
                ("p", "Chlupaté knedlíky, známé také jako bosáky, patří mezi naše nejoblíbenější výrobky. Vyrábíme je podle tradiční receptury."),
                ("p", "Pro rychlou a snadnou přípravu jsou oblíbené v jídelnách a restauracích, ale svou chutí a konzistencí obstojí i v domácnostech. Hotové jsou za 15 minut a jejich chuť nerozeznáte od knedlíků připravovaných tradičním způsobem ze syrových brambor."),
            ],
            "faq": [
                ("K čemu se chlupaté knedlíky hodí?", "Tradičně se podávají se zelím a uzeným masem, s cibulkou a škvarky, nebo sladce s mákem a cukrem."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Vanilkový puding bez lepku",
            "short": "Kukuřičný škrob bez lepku, přirozená vanilková chuť. Na dezerty i pečení.",
            "price": "1 kg / 60 Kč · 400 g / 30 Kč",
            "title": "Vanilkový puding bez lepku — 1 kg / 60 Kč",
            "desc": "Instantní vanilkový puding z kukuřičného škrobu bez lepku. Přirozená chuť bez chemických odstínů, vhodný i pro bezlepkovou dietu. 1 kg / 60 Kč, 400 g / 30 Kč.",
            "body": [
                ("p", "Vanilkový puding patří mezi naše tradiční produkty. Skvěle se uplatní při přípravě lehkých dezertů i při pečení."),
                ("p", "Základem je kvalitní kukuřičný škrob, který neobsahuje lepek — puding je proto vhodný i pro bezlepkovou dietu. Vyzkoušejte jeho přirozenou chuť bez chemických odstínů a k zavedeným „supermarketovým“ značkám už se nevrátíte."),
            ],
            "faq": [
                ("Je puding opravdu bez lepku?", "Ano. Základem je čistý kukuřičný škrob, který lepek neobsahuje."),
                ("Vyrábíte i čokoládovou variantu?", "Kakaový puding jako hotovou směs nevedeme. Čokoládovou chuť dáte vanilkovému pudingu kakaem holandského typu, které prodáváme samostatně."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holandského typu",
            "short": "Tmavé cukrářské kakao třídy 21 % tuku. Červenohnědá barva, krémová chuť, bez přidaného cukru.",
            "price": "500 g / 270 Kč",
            "title": "Kakao holandského typu 21 % tuku — 500 g / 270 Kč",
            "desc": "Tmavé cukrářské kakao holandského typu s 20–22 % kakaového másla. Bez přidaného cukru, veganské, bez 14 alergenů EU. 500 g / 270 Kč.",
            "body": [
                ("p", "Nabízíme tmavé cukrářské kakao holandského typu — alkalizovaný prášek z bobů Theobroma cacao, třídy 21 % tuku. Plné čokoládové tělo, krémová chuť a sytá červenohnědá barva, která drží v suchém stavu i v receptu."),
                ("h2", "Odkud kakao přichází"),
                ("p", "Kakaové boby pomalu dosychají na slunci ve střední západní Africe. Přirozeně kvasí v banánových listech — tak se rodí hluboká čokoládová chuť, kterou alkalizací zjemníme do kakaa holandského typu."),
                ("h2", "Tuk 20–22 %: proč na něm záleží"),
                ("p", "Kakaové máslo držíme v rozmezí 20,0–22,0 %. Je to víc tuku než u hubených supermarketových kakaí (často 10–12 %). Víc másla znamená víc vlhkosti v těstě, kulatější pocit v ústech a plnější čokoládový dojem — proto ho cukráři berou jako třídu 21 %."),
                ("h2", "Bez přidaného cukru"),
                ("p", "Cukr do kakaa nepřidáváme. Jediné cukry, které v něm najdete — 0,9 g na 100 g — vznikly v kakaovém bobu samy."),
                ("cocoa_sensory", None),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
            ],
            "showcase": {
                "sensory_h": "Chuťový profil",
                "sensory_lead": "Plná kakaová intenzita, krémová čokoládová chuť a pražené tóny. Barva je sytě červenohnědá — v prášku i v hotovém moučníku.",
                "axes": [
                    {"label": "Intenzita", "value": 92},
                    {"label": "Krémovost", "value": 88},
                    {"label": "Pražení", "value": 78},
                    {"label": "Barva", "value": 94},
                    {"label": "Jemnost", "value": 86},
                ],
                "apps_h": "Kam kakao patří",
                "apps": [
                    {"title": "Pečení", "text": "Perník, koláče a těsta, která mají zůstat sytě kakaová i po upečení."},
                    {"title": "Nápoje", "text": "Mléčné kakao a koktejly — v mléce drží barvu i krémovou chuť."},
                    {"title": "Krémy", "text": "Náplně, krémy a lehké dezerty, kde chcete čokoládu bez přidaného cukru v prášku."},
                    {"title": "Posyp", "text": "Hotové řezy, rolády a bebe dezerty — tmavý, jemný prach, který se nesráží."},
                    {"title": "S vanilkovým pudingem", "text": "Zamíchejte do našeho vanilkového pudingu: vznikne čokoládový krém z jedné směsi."},
                    {"title": "Kaše a cereálie", "text": "Snídaňové kaše a cereálie, které mají chutnat po čokoládě, ne po hořkém prášku."},
                ],
                "nutri_h": "Co v kakau je",
                "nutri_lead": "Na 100 g: hodně vlákniny a bílkovin, přirozeně málo cukru, žádný přidaný cukr.",
                "nutri_extra": "K tomu hořčík 490 mg, draslík 4 400 mg a železo 31 mg na 100 g.",
                "nutri_note": "Orientační údaje na 100 g podle nařízení EU 1169/2011. Kakao používáte po lžících — hodnoty na porci jsou zlomkem tabulky.",
                "bars": [
                    {"label": "Energie", "text": "379 kcal / 1 570 kJ", "pct": 19},
                    {"label": "Tuk", "text": "21,0 g  ·  nasycené 13,0 g", "pct": 30},
                    {"label": "Vláknina", "text": "28,4 g", "pct": 100},
                    {"label": "Bílkoviny", "text": "19,5 g", "pct": 39},
                    {"label": "Cukry", "text": "0,9 g  ·  přidané 0 g", "pct": 2},
                    {"label": "Železo", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technické údaje",
                "facts": [
                    {"label": "Kakaové máslo", "value": "20,0–22,0 %"},
                    {"label": "pH (10% roztok)", "value": "7,8–8,2"},
                    {"label": "Jemnost", "value": "min. 99,5 % pod 75 µm"},
                    {"label": "Vlhkost", "value": "max. 5,0 %"},
                    {"label": "Slupky", "value": "max. 1,75 %"},
                    {"label": "Alergeny EU", "value": "žádné ze 14"},
                    {"label": "Lepek", "value": "< 20 ppm"},
                    {"label": "Strava", "value": "veganské, vegetariánské"},
                ],
            },
            "faq": [
                ("Čím se liší kakao holandského typu?", "Alkalizací — je tmavší, méně kyselé a lépe se rozpouští než přírodní kakao. S 20–22 % tuku patří k nejkvalitnějším cukrářským kakaům."),
                ("Přidáváte cukr?", "Ne. Přidaný cukr je 0 g. Přirozené cukry z bobu jsou 0,9 g na 100 g."),
                ("Je kakao bez lepku a alergenů?", "Ano. Neobsahuje žádný ze 14 alergenů EU. Lepek je pod 20 ppm. Je veganské a vegetariánské — bez surovin živočišného původu."),
                ("Jak kakao skladovat?", "V suchu, mimo silné pachy, ideálně při 15–20 °C a vlhkosti pod 50 %."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilínový cukr",
            "short": "Jemně mletý cukr s vanilínovým aroma. Do těsta i na posyp cukroví.",
            "price": "1 kg / 60 Kč",
            "title": "Vanilínový cukr — 1 kg / 60 Kč",
            "desc": "Vanilínový cukr z jemně mletého cukru s vanilínovým aroma. Na koláče, zákusky i vánoční cukroví — do těsta i na posyp. 1 kg / 60 Kč.",
            "body": [
                ("p", "Vanilínový cukr obsahuje kromě jemně mletého cukru také vanilínové aroma, které mu dodává příjemnou, jedinečnou vůni vanilky."),
                ("p", "Oceníte jej při pečení koláčů, zákusků i ostatních dezertů. Skvěle se hodí při přípravě vánočního cukroví — nejen jako přísada do těsta, ale i pro posyp hotového cukroví."),
            ],
            "faq": [
                ("Hodí se vanilínový cukr do vánočního cukroví?",
                 "Ano. Do těsta i na posyp hotového cukroví. Balení 1 kg / 60 Kč."),
                ("Je to vanilka, nebo vanilin?",
                 "Vanilínový cukr: jemně mletý cukr s vanilínovým aroma, ne lusk vanilky."),
            ],
        },
    },
    "recipes_intro": "Vyzkoušejte osvědčené recepty z našich směsí — od nedělních knedlíků po nepečené dezerty.",
    "faq_page": {
        "title": "Časté dotazy — objednávky, dodání, směsi Jůzlová",
        "desc": "Odpovědi na nejčastější otázky o Jůzlové: kde sídlíme, jak objednat, ceny, bezlepkový puding, kakao holandského typu a rozvoz na Vysočině.",
        "h1": "Časté dotazy",
        "sub": "Krátké, přímé odpovědi — pro lidi, Google, Seznam.cz i jazykové modely.",
    },
    "recipes": {},  # filled from archive after workflow completes
}
