# English content — adaptation of content_cs.py for Czechs abroad and EU buyers (persona 3A).
# Not a literal translation: Czech-only references are dropped, shipping-first framing.
from cocoa_faq import product_cocoa_faq

LANG = {
    "code": "en",
    "locale": "en_US",
    "name": "English",
    "ui": {
        "nav_home": "Home", "nav_about": "About us", "nav_delivery": "Where to find us",
        "nav_products": "Products", "nav_prices": "Prices", "nav_recipes": "Recipes",
        "nav_faq": "FAQ", "nav_contact": "Contact",
        "nav_b2b": "For kitchens", "nav_d2c": "Shipping to the EU",
        "nav_aria": "Main navigation",
        "menu_open": "Open menu",
        "menu_close": "Close menu",
        "hero_img_alt": "Kochánov from the air",
        "workshop_caption": "Our workshop in Kochánov — flour sacks, the scale and the bagging line.",
        "est": "Family workshop · Kochánov, Czechia · since 2004",
        "hero_h1": "Czech potato dumpling mix, gluten-free pudding and cocoa — shipped anywhere in the EU, shipping cost quoted before you pay",
        "hero_lead": "The Jůzl family has mixed these in Kochánov since 2004. Pick up in the Czech Highlands, or we quote a tracked parcel to Germany, Austria, Slovakia, Poland and the rest of the EU.",
        "hero_cta": "Call Jiřina to order",
        "hero_cta2": "See prices",
        "sec_products": "Five mixes. One workshop.", "sec_products_kicker": "What we make",
        "sec_products_lead": "Prices apply at workshop pick-up. Shipping is quoted separately.",
        "sec_recipes": "What you can cook with them", "sec_recipes_kicker": "Recipes",
        "sec_recipes_lead": "Every recipe says how much mix to use, the oven temperature and how many portions it makes.",
        "sec_why": "You know where the flour is from. And who picks up the phone.", "sec_why_kicker": "Why us",
        "why_1_h": "Flour from the family mill",
        "why_1_p": "The wheat flour in our dumpling mixes comes from a mill in Havlíčkův Brod, 12 km from the workshop, with the Czech KLASA quality mark. Our extended family owns and runs the mill.",
        "why_2_h": "You talk to the maker",
        "why_2_p": "Jiřina Jůzlová takes orders daily 8–19. No web shop, no call centre. Replies are in Czech; for German and English we sometimes use a translator.",
        "why_3_h": "Kilo prices, not sachet prices",
        "why_3_p": "Pudding by the kilo, sugar by the kilo, dumpling mix in a 5 kg bag. Simple packaging, sold straight from the workshop.",
        "ticker_pickup": "Prices apply at workshop pick-up",
        "deliver_kicker": "Delivery",
        "deliver_h2": "Pick up, delivered, or posted",
        "deliver_1": "Free pick-up at the workshop in Kochánov or in Humpolec — by phone arrangement.",
        "deliver_2": "Free delivery within the Czech Highlands: Humpolec and Havlíčkův Brod from 1000 CZK, Jihlava from 3000 CZK, the rest of Vysočina from 5000 CZK.",
        "deliver_3": "Parcels anywhere in Czechia and the EU: you pay tracked shipping, box and insurance; we send the total first.",
        "deliver_btn": "Get a shipping quote",
        "sec_b2b": "Cooking for hundreds?",
        "sec_b2b_kicker": "For kitchens",
        "sec_b2b_lead": "Canteens, restaurants, bakeries and gelato makers get the same five mixes at quantity prices. Wholesale parcels to DE, AT, SK and PL at the buyer's shipping cost.",
        "sec_b2b_btn": "Request a kitchen quote",
        "sec_d2c_kicker": "Czechs abroad",
        "sec_d2c": "Living in Germany, Austria or Slovakia?",
        "sec_d2c_lead": "We'll send you a box. Shipping, box and insurance are quoted first — nothing leaves until you approve the total.",
        "sec_d2c_btn": "How EU shipping works",
        "nl_h": "Recipes and news by e-mail",
        "nl_kicker": "Newsletter",
        "nl_lead": "An occasional new recipe from our mixes and seasonal tips before Christmas and Easter. Unsubscribe with one click.",
        "nl_consent": "I agree to receive news by e-mail. Jůzlová (juzlj@seznam.cz) receives my address. I can withdraw consent by e-mail.",
        "nl_submit": "Subscribe to recipes",
        "nl_success": "Thank you. You are subscribed.",
        "nl_need_email": "Enter your e-mail and tick the consent box.",
        "form_qty": "Quantity (packs or kg)",
        "form_fulfill": "How would you like to receive the goods",
        "form_fulfill_factory": "Pick-up at the workshop, Kochánov 40, 582 53",
        "form_fulfill_humpolec": "Pick-up in Humpolec near the Bernard brewery (free, day and time by arrangement)",
        "form_fulfill_delivery": "Delivery or parcel (shipping quoted first)",
        "cta_sample_h": "Ready to order?",
        "cta_sample_p": "Call, or write what you want, how much, and where you are. We arrange the rest.",
        "cta_sample_btn": "Call Jiřina",
        "cta_call": "Call Jiřina",
        "cta_write": "Write to us",
        "cta_order": "Order from Jiřina",
        "cta_pickup": "Where to collect",
        "cta_quote": "Request a kitchen quote",
        "cta_eu": "Get a shipping quote",
        "full_price_list": "Full price list",
        "all_recipes": "All recipes",
        "recipes_h1": "Recipes with our mixes: from Sunday dumplings to choux rings and gingerbread",
        "carousel_label": "Recipes on the home page",
        "carousel_prev": "Previous recipe",
        "carousel_next": "Next recipe",
        "carousel_status": "Recipe {current} of {total}: {name}",
        "carousel_goto": "Go to recipe {n}: {name}",
        "faq_b2b_hint": "Kitchens and shops: quantity pricing and delivery questions are on the For kitchens page.",
        "sec_faq": "Frequently asked questions",
        "rate_label": "Rate this recipe",
        "rate_count": "{n} ratings",
        "rate_star": "Rate {n} out of 5",
        "rate_thanks": "Thank you. Your rating is saved.",
        "rate_already": "You have already rated this recipe.",
        "rate_error": "We could not save your rating. Please try again.",
        "detail": "More",
        "price_label": "Price",
        "package_label": "Pack",
        "price_board_label": "Prices at workshop pick-up",
        "price_pickup_badge": "at workshop pick-up",
        "unit_h2": "Per kilo and per portion",
        "unit_col_product": "Mix",
        "unit_col_unit": "Per kilo / per portion",
        "unit_note": "Portion counts follow the pack instructions. Shipping outside the free zones is quoted separately.",
        "reviews_kicker": "Ratings",
        "reviews_h2": "What customers say",
        "reviews_lead": "Ratings come from our live Google and Firmy.cz profiles. We do not invent stars.",
        "reviews_google": "Google",
        "reviews_seznam": "Firmy.cz",
        "reviews_open": "Open reviews",
        "reviews_count": "{n} reviews",
        "reviews_rating_of": "{rating} of 5",
        "team_kicker": "People",
        "team_h2": "Who is who",
        "team_lead": "When you call or write, you are talking to one of us.",
        "b2b_vis_1_h": "500 portions, three people",
        "b2b_vis_1_p": "Potato dough from water alone: no peeling and grating thirty kilos of potatoes. The same consistency every day.",
        "b2b_vis_2_h": "A short label",
        "b2b_vis_2_p": "Flour and dried potato flakes. We e-mail ingredient lists and labels for your paperwork.",
        "b2b_vis_3_h": "Three ways to get it",
        "b2b_vis_3_p": "Pick-up in Kochánov, our delivery (Brno free from 5000 CZK, Prague from 25 kg), or your carrier — often cheaper.",
        "b2b_vis_4_h": "Cocoa paperwork",
        "b2b_vis_4_p": "A lab certificate for your cocoa batch on request. None of the 14 EU allergens, gluten under 20 ppm.",
        "order_info": "Order",
        "open_hours_short": "daily 8–19",
        "breadcrumb_home": "Home",
        "footer_products": "Products", "footer_recipes": "Recipes", "footer_company": "Company",
        "footer_note": "Family workshop making food mixes since 2004.",
        "footer_addr": "Jůzlová s.r.o. · Company ID 45900124 · Kochánov 40, 582 53 · Vysočina, Czech Republic",
        "open_hours": "Daily 8:00–19:00 by phone, weekends included",
        "lang_label": "Language",
        "lang_cs": "Čeština", "lang_en": "English", "lang_de": "Deutsch", "lang_sk": "Slovenčina",
        "recipe_meta": "Recipe from the Jůzlová workshop",
        "uses_product": "Mix used",
        "more_recipes": "If you liked this one",
        "more_recipes_kicker": "Suggestions for this recipe",
        "more_recipes_lead": "More recipes that go with it — same mix, or similar baking.",
        "more_recipe_open": "Open recipe: {name}",
        "form_h": "Tell us what you need",
        "form_hint": "Your name and a phone number or e-mail is enough. We reply and arrange a date.",
        "form_google_pending": "",
        "map_title": "Map of the workshop Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_addr": "Kochánov 40, 582 53 — not 582 91, that is a different Kochánov",
        "map_open": "Open in Google Maps",
        "map_nav_google": "Navigate with Google Maps",
        "map_nav_seznam": "Navigate with Mapy.cz",
        "form_name": "Name",
        "form_phone": "Phone",
        "form_email": "E-mail",
        "form_buyer": "Buying for",
        "form_buyer_home": "A household",
        "form_buyer_pro": "A restaurant, canteen or pastry shop",
        "form_products": "Which mixes are you interested in",
        "form_message": "Message (what, how much, where you are)",
        "form_submit": "Send and arrange a date",
        "form_sending": "Sending…",
        "form_success": "Thank you, we have your message. We will get back to you about the order.",
        "form_error": "The message could not be sent. Please try again or call us.",
        "form_captcha": "Verification failed. Reload the page and try again.",
        "form_honeypot": "Leave this field empty",
        "form_need_contact": "Enter a phone number or e-mail.",
        "cookie_aria": "Cookie consent",
        "cookie_text": "Google Analytics counts visits with cookies. The site works the same without consent.",
        "cookie_accept": "Accept",
        "cookie_essential": "Essential only",
        "form_b2b_h": "Kitchen enquiry",
        "form_b2b_hint": "This form is for kitchens and shops. Households order via Contact.",
    },
    "meta": {
        "home_title": "Czech potato dumpling mix & gluten-free pudding — family workshop, EU shipping",
        "home_desc": "Potato dumpling mix, raw-potato (bosáky) mix, gluten-free vanilla pudding and Dutch-process cocoa from a family workshop in Vysočina, Czechia. Pick up locally or get a shipping quote for the EU.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "About us — the Jůzlová family workshop, Kochánov, since 2004",
            "desc": "The Jůzl family has made potato dumpling mix, pudding and cocoa in Kochánov, Czechia since 2004. Flour from the family mill in Havlíčkův Brod. No web shop, no middlemen.",
            "nav": "About us",
            "h1": "The Jůzl family of Kochánov: mixing since 2004 the food they cook themselves",
            "sub": "The workshop is at Kochánov 40, twelve kilometres from Havlíčkův Brod. The flour comes from a mill our extended family runs. Jiřina takes the orders.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("h2", "How it started"),
                ("p", "We started making food mixes in a small workshop in Kochánov in 2004 and tuned the recipes over the years. Today households across Bohemia and Moravia buy from us, along with canteens, restaurants and bakeries."),
                ("team", None),
                ("h2", "Where the flour comes from"),
                ("p", "The wheat flour in our dumpling mixes comes from a mill in Havlíčkův Brod, 12 km from the workshop, carrying the Czech KLASA quality mark. Our extended family owns and runs the mill, so we know what goes into the bag."),
                ("h2", "What we don't do"),
                ("ul", [
                    "No web shop. You order by phone, e-mail or the form.",
                    "No samples or tastings.",
                    "No invented stars — ratings come from our live Google and Firmy.cz profiles.",
                    "We reply in Czech; for German and English we sometimes use a translator.",
                ]),
                ("reviews", None),
            ],
        },
        "kde_nas_najdete": {
            "title": "Where to find us — Kochánov 40 and Humpolec, Czech Highlands | Jůzlová",
            "desc": "Workshop at Kochánov 40, 582 53, 12 km from Havlíčkův Brod. Free second pick-up in Humpolec by arrangement. Free delivery in Vysočina from set amounts; parcels to the EU quoted first.",
            "nav": "Where to find us",
            "h1": "Where to find us: the workshop in Kochánov, pick-up in Humpolec, delivery in the Czech Highlands",
            "sub": "Phone first, then drive. The workshop is not a shop with opening hours on the door.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("h2", "The workshop in Kochánov"),
                ("p", "Kochánov 40, 582 53, Vysočina Region, Czechia. Pick-up is free, daily 8:00–19:00 by phone, weekends included. Mind the postcode: 582 91 is a different Kochánov."),
                ("map", None),
                ("h2", "Pick-up in Humpolec"),
                ("p", "A second pick-up point is in Humpolec near the Bernard brewery, free of charge. We give the exact spot, day and time by phone."),
                ("h2", "Delivery and parcels"),
                ("ul", [
                    "Humpolec and Havlíčkův Brod: free delivery from 1000 CZK",
                    "Jihlava: free from 3000 CZK",
                    "Rest of Vysočina: free from 5000 CZK",
                    "Elsewhere in Czechia: parcel, shipping quoted first; you may also send your own courier",
                    "Germany, Austria, Slovakia, Poland and the rest of the EU: you pay shipping, box and insurance; you see the total before we ship",
                ]),
                ("form", None),
            ],
        },
        "kontakt": {
            "title": "Contact Jůzlová — Kochánov 40, Czechia, daily 8–19",
            "desc": "Jiřina Jůzlová +420 728 466 141, Jiří Jůzl +420 607 629 931, juzlj@seznam.cz. Workshop at Kochánov 40, 582 53, Vysočina, Czechia. Pick-up by arrangement; parcels to CZ and the EU.",
            "nav": "Contact",
            "h1": "Call or write to Jiřina or Jiří — daily 8–19, we'll arrange your order and pick-up",
            "sub": "Saturdays and Sundays included, always by prior arrangement. We reply in Czech; for German and English we sometimes use a translator.",
            "cta": None,
            "body": [
                ("contacts", None),
                ("form", None),
                ("h2", "Where to find us"),
                ("map", None),
                ("p", "Workshop: Kochánov 40, 582 53, Vysočina Region, Czechia, 12 km from Havlíčkův Brod. Second pick-up in Humpolec near the Bernard brewery, free, by arrangement."),
            ],
        },
        "ceny": {
            "title": "Prices — Czech dumpling mix, pudding, cocoa from the maker | Jůzlová",
            "desc": "Potato dumpling mix 5 kg 250 CZK, bosáky 260 CZK, gluten-free pudding 60 CZK/kg, cocoa 270 CZK/500 g, vanillin sugar 60 CZK/kg. Ex-workshop prices; EU shipping quoted before you pay.",
            "nav": "Prices",
            "h1": "Prices: five mixes, ex-workshop in Kochánov; shipping quoted separately",
            "sub": "The same price for everyone who collects at the workshop or in Humpolec. Delivery and parcels are added separately — the overview is below the table.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("pricetable", None),
                ("h2", "Delivery"),
                ("ul", [
                    "Pick-up in Kochánov or Humpolec: free",
                    "Humpolec and Havlíčkův Brod: free delivery from 1000 CZK",
                    "Jihlava: free from 3000 CZK · rest of Vysočina: free from 5000 CZK",
                    "Kitchens: Brno free from 5000 CZK, Prague mixed order from 25 kg",
                    "Parcels in Czechia: quoted first · EU: shipping, box, insurance and wrap, total quoted before dispatch",
                ]),
                ("h2", "Kitchens and shops"),
                ("p", "Quantity prices by phone or through the form on the For kitchens page."),
                ("h2", "Old prices online"),
                ("p", "Some websites still show prices from 2017. Only this list applies."),
            ],
        },
        "velkoobchod": {
            "title": "Wholesale Czech dumpling mix, pudding, cocoa — kitchens & bakeries | Jůzlová",
            "desc": "Quantity pricing for canteens, restaurants, bakeries and gelato makers. Pick up in Kochánov, our delivery, or your carrier; wholesale parcels to DE, AT, SK, PL. Cocoa batch certificate on request.",
            "nav": "For kitchens",
            "h1": "Dumpling mix, pudding and cocoa for kitchens: quantity pricing, pick-up or delivery, batch certificate",
            "sub": "We supply canteens, restaurants, bakeries, cafés, schools and ice-cream makers in Czechia, and wholesale parcels to Germany, Austria, Slovakia and Poland at the buyer's shipping cost. Quantity prices by phone; we don't publish customer names.",
            "cta": ("cta_call", None, None),
            "body": [
                ("h2", "Why kitchens use the mix"),
                ("p", "Potato dough for 500 portions without thirty kilos of potatoes to peel. The same consistency every day. The label reads flour and dried potato flakes — what you add to it is up to you."),
                ("b2b_showcase", None),
                ("h2", "What we supply to whom"),
                ("ul", [
                    "canteens and restaurants — dumpling mix and pudding for service",
                    "bakeries and pastry shops — pudding, vanillin sugar, cocoa",
                    "cafés — cocoa and pudding",
                    "schools — mixes for children's meals",
                    "ice-cream makers — Dutch-process cocoa that keeps its colour in the freezer",
                ]),
                ("h2", "How you get it"),
                ("ol", [
                    "Pick-up at the workshop in Kochánov",
                    "Our delivery — quoted first; Brno free from 5000 CZK, Prague mixed order from 25 kg",
                    "Your own carrier — often cheaper",
                ]),
                ("p", "Wholesale parcels to Germany, Austria, Slovakia and Poland ship at the buyer's cost."),
                ("form_b2b", None),
            ],
        },
        "do_eu": {
            "title": "Czech dumpling mix shipped to Germany, Austria, Slovakia — quote first | Jůzlová",
            "desc": "Czechs abroad: order potato dumpling mix, gluten-free pudding and cocoa from Vysočina. Workshop prices plus tracked shipping, box and insurance, quoted before anything ships.",
            "nav": "Shipping to the EU",
            "h1": "Czechs in Germany, Austria and Slovakia: we'll send a box of dumpling mix and pudding — you see the shipping cost before you pay",
            "sub": "Goods at workshop prices. We add tracked shipping, box, insurance and bubble wrap, send you the total, and ship only after you approve it.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("h2", "How it works"),
                ("ol", [
                    "Write what you want and where it should go.",
                    "We price the shipping, box and insurance and send the total.",
                    "You approve and pay.",
                    "We ship with tracking.",
                ]),
                ("h2", "How we pack"),
                ("p", "Bags in bubble wrap, in a sturdy box, insured and tracked. The mixes keep for months — until your next trip home."),
                ("h2", "Tip: a gift for family in Czechia"),
                ("p", "Living abroad and want to send dumpling mix to your parents? We deliver anywhere in Czechia, or they collect in Kochánov or Humpolec."),
                ("form", None),
            ],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Potato dumpling mix",
            "h1": "Czech potato dumpling mix: add water, 20 minutes to the table, and they hold together in the pot",
            "short": "Wheat flour from the family mill in Havlíčkův Brod and dried potato flakes. Nothing else. Add an egg or a grated boiled potato if that's how you like them.",
            "price": "5 kg / 250 CZK",
            "per_unit": "50 CZK/kg · about 4 CZK per portion (60–70 portions)",
            "title": "Czech potato dumpling mix 5 kg — just add water | Jůzlová",
            "desc": "Bramborové knedlíky mix from a Czech family workshop: flour from the family mill, dried potato flakes, water. Holds together, ready in 20 minutes. 5 kg / 250 CZK. EU shipping quoted first.",
            "body": [
                ("h2", "What's in it"),
                ("p", "Wheat flour with the Czech KLASA quality mark from a mill in Havlíčkův Brod, owned and run by our extended family, and dried potato flakes. The flakes give the dough its potato taste and hold it together while it cooks."),
                ("h2", "How to make it"),
                ("ol", [
                    "Mix with water as the bag says.",
                    "Shape dumplings, rolls or croquettes.",
                    "Boil. About 20 minutes from opening the bag to the plate.",
                ]),
                ("tip", "Want it your way? Replace part of the water with milk, add an egg or one boiled, grated potato. Many of our customers do."),
                ("h2", "What one dough makes"),
                ("ul", ["classic potato dumplings for roast meat",
                        "dumplings filled with meat or fruit",
                        "poppy-seed rolls (šišky s mákem)", "fried croquettes", "home-made gnocchi"]),
                ("h2", "How much it is"),
                ("p", "A 5 kg bag makes a side dish for about 60–70 people. Store the bag dry and closed."),
            ],
            "faq": [
                ("Do I have to add an egg?", "No. The dough works with water alone. Add egg or milk if you want a richer taste."),
                ("Will the dumplings hold a fruit filling?", "Yes, the dough keeps its shape; customers make filled dumplings from it."),
                ("Is there a pack smaller than 5 kg?", "No. 5 kg is the only pack; it lasts a season."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Raw-potato dumpling mix (chlupaté knedlíky)",
            "h1": "Chlupaté knedlíky (bosáky) mix: Czech raw-potato dumplings for cabbage and smoked meat in 15 minutes, no grating",
            "short": "Traditional recipe from our workshop. Mix with water, shape, boil. Push it through a colander for Slovak-style halušky.",
            "price": "5 kg / 260 CZK",
            "per_unit": "52 CZK/kg · a season at home, or a week of service",
            "title": "Chlupaté knedlíky (bosáky) mix 5 kg — Czech raw-potato dumplings | Jůzlová",
            "desc": "Traditional Czech raw-potato dumpling mix. Serve with sauerkraut and smoked meat, or make halušky. Ready in 15 minutes, 5 kg / 260 CZK. Shipping to the EU quoted before you pay.",
            "body": [
                ("h2", "What it goes with"),
                ("ul", ["sauerkraut and smoked meat",
                        "fried onion and cracklings",
                        "sweet, with poppy seeds and sugar",
                        "pushed through a colander into boiling water as halušky and strapačky"]),
                ("h2", "How to make it"),
                ("ol", [
                    "Mix with water as the bag says.",
                    "Shape bosáky, or push the dough through a colander.",
                    "Boil. 15 minutes from bag to plate.",
                ]),
                ("h2", "For canteens"),
                ("p", "We supply bosáky to canteens and restaurants too: the same mix, quantity pricing, pick-up in Kochánov, our delivery, or your carrier."),
            ],
            "faq": [
                ("Are chlupaté knedlíky and bosáky the same thing?", "Yes, two names for one dish."),
                ("Can I make halušky from it?", "Yes; push the dough through a colander into boiling water. The strapačky recipe is on the site."),
                ("Is there a pack smaller than 5 kg?", "No. 5 kg is the only pack."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Gluten-free vanilla pudding powder",
            "h1": "Gluten-free vanilla pudding powder by the kilo: corn starch for custard, cake filling and gingerbread — about 25 sachets for 60 CZK",
            "short": "Corn starch contains no gluten. Cook it like any pudding; use it in choux cream, pear cake or cup-measure gingerbread.",
            "price": "1 kg / 60 CZK · 400 g / 30 CZK",
            "per_unit": "60 CZK/kg · about 2.40 CZK per pudding (40 g)",
            "title": "Gluten-free vanilla pudding powder 1 kg / 60 CZK — corn starch | Jůzlová",
            "desc": "Czech vanilla pudding powder made from corn starch, no gluten. One kilo makes about 25 puddings or cream for trays of choux. 1 kg / 60 CZK, 400 g / 30 CZK.",
            "body": [
                ("h2", "Why it is gluten-free"),
                ("p", "We use no wheat starch in the pudding. Corn starch naturally contains no gluten, so the pudding suits a gluten-free diet."),
                ("h2", "How much to use"),
                ("p", "A shop sachet is about 40 g per 500 ml of milk. One kilo makes about 25 puddings, or cream for several trays of cream puffs."),
                ("h2", "Chocolate?"),
                ("p", "We don't make a cocoa pudding. Stir a spoon of our Dutch-process cocoa into the cooked vanilla pudding and you have chocolate cream."),
                ("h2", "Recipes with the pudding"),
                ("ul", ["pear cake with vanilla pudding", "choux rings with vanilla cream",
                        "mini cream puffs", "caramel cream puffs", "cup-measure gingerbread"]),
            ],
            "faq": [
                ("Can I use it 1 : 1 instead of a shop pudding?", "Yes. About 40 g per 500 ml of milk, like a normal sachet."),
                ("Does an opened kilo bag keep?", "Yes, dry and closed. For a first try there is a 400 g pack for 30 CZK."),
                ("Do you make a chocolate version?", "No. For a chocolate taste, stir in our Dutch-process cocoa, sold separately."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Dutch-process cocoa",
            "h1": "Dutch-process cocoa with 20–22 % cocoa butter: colour that stays dark in cakes and ice cream",
            "short": "Alkalised powder from cocoa mass, no added sugar, none of the 14 EU allergens. For gingerbread, creams, drinking cocoa and gelato. Batch lab certificate on request.",
            "price": "500 g / 270 CZK",
            "per_unit": "540 CZK/kg · about 50 spoonfuls per pack",
            "title": "Dutch-process cocoa 20–22 % cocoa butter, 500 g / 270 CZK | Jůzlová",
            "desc": "Dark confectionery cocoa, Dutch-processed, 20–22 % cocoa butter, no added sugar, allergen-free. Holds its colour in baking and ice cream. Batch certificate available. EU shipping quoted first.",
            "body": [
                ("h2", "Why the fat matters"),
                ("p", "Under EU law a powder needs at least 20 % cocoa butter to be called cocoa; below that it is fat-reduced cocoa. Ours has 20–22 %. More cocoa butter means a darker colour, a fuller taste and a smoother cream."),
                ("h2", "Where it comes from"),
                ("p", "Beans from West-Central Africa, fermented in banana leaves and sun-dried. We alkalise with natural salts to pH 7.8–8.2 — hence the deep red-brown colour and a rounded, not sour, taste."),
                ("h2", "What is not in it"),
                ("p", "No added sugar (0.9 g of natural sugars per 100 g). None of the 14 EU allergens, gluten under 20 ppm. Vegan."),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
                ("h2", "Storage"),
                ("p", "Dry, away from strong smells, ideally at 15–20 °C and below 50 % humidity."),
                ("h2", "For pastry shops and gelato makers"),
                ("p", "Quantity pricing, batch certificate, pick-up or delivery. Ask on the For kitchens page."),
            ],
            "showcase": {
                "apps_h": "Where to use it",
                "apps": [
                    {"title": "Baking", "text": "Gingerbread, bundt cake, brownies — batters that should stay deep cocoa after baking."},
                    {"title": "Drinks", "text": "Hot cocoa and shakes — it keeps its colour and creamy taste in milk."},
                    {"title": "Creams", "text": "Fillings and creams without added sugar in the powder."},
                    {"title": "Dusting", "text": "Slices, roulades and biscuit desserts — a dark, fine dust that does not clump."},
                    {"title": "With vanilla pudding", "text": "Stir into our vanilla pudding: chocolate cream from two mixes."},
                    {"title": "Ice cream", "text": "Smooth texture and a dark colour that does not fade in the freezer."},
                ],
                "nutri_h": "What's in the cocoa",
                "nutri_lead": "Per 100 g, from the nutrition table on the pack: lots of fibre and protein, naturally low in sugar, no added sugar.",
                "nutri_extra": "Plus magnesium 490 mg, potassium 4,400 mg and iron 31 mg per 100 g.",
                "nutri_note": "Values per 100 g under EU Regulation 1169/2011. You use cocoa by the spoon — per serving, the figures are a fraction of the table.",
                "bars": [
                    {"label": "Energy", "text": "379 kcal / 1,570 kJ", "pct": 19},
                    {"label": "Fat", "text": "21.0 g  ·  saturates 13.0 g", "pct": 30},
                    {"label": "Fibre", "text": "28.4 g", "pct": 100},
                    {"label": "Protein", "text": "19.5 g", "pct": 39},
                    {"label": "Sugars", "text": "0.9 g  ·  added 0 g", "pct": 2},
                    {"label": "Iron", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technical data",
                "facts": [
                    {"label": "Cocoa butter", "value": "20.0–22.0 %"},
                    {"label": "pH (10 % solution)", "value": "7.8–8.2"},
                    {"label": "Fineness", "value": "min. 99.5 % below 75 µm"},
                    {"label": "Moisture", "value": "max. 5.0 %"},
                    {"label": "Shell", "value": "max. 1.75 %"},
                    {"label": "Heavy metals", "value": "within Regulation (EU) 2023/915"},
                    {"label": "EU allergens", "value": "none of the 14"},
                    {"label": "Gluten", "value": "< 20 ppm"},
                    {"label": "Diet", "value": "vegan, vegetarian"},
                ],
            },
            "faq": product_cocoa_faq("en"),
        },
        "vanilkovy_cukr": {
            "name": "Vanillin sugar",
            "h1": "Vanillin sugar by the kilo: for dough, whipped cream and dusting — one bag instead of a drawer of sachets",
            "short": "It is vanillin, not vanilla pod. We say so up front. Finely ground sugar with vanillin aroma.",
            "price": "1 kg / 60 CZK",
            "per_unit": "60 CZK/kg",
            "title": "Vanillin sugar 1 kg / 60 CZK — baking & dusting | Jůzlová",
            "desc": "Finely ground sugar with vanillin aroma, 1 kg bag. For cakes, Christmas biscuits, whipped cream and dusting. From a Czech family workshop; EU shipping quoted before you pay.",
            "body": [
                ("h2", "What for"),
                ("ul", ["cakes and pastries", "Christmas biscuits — in the dough and for dusting", "whipped cream and creams", "the biscuit slices and mini cream puffs from our recipes"]),
                ("h2", "Storage"),
                ("p", "Dry and closed, so the sugar does not go damp and hard."),
            ],
            "faq": [
                ("Is it the same as shop vanilla sugar?", "Yes, it is vanillin sugar — sugar with vanillin aroma, not ground vanilla pod."),
                ("Do you sell real vanilla?", "No."),
            ],
        },
    },
    "recipes_intro": "Every recipe says how much mix to use, the oven temperature and how many portions it makes.",
    "recipes_desc": "Poppy-seed rolls, strapačky, pear cake with pudding, choux rings, cream horns, cup-measure gingerbread. Recipes with ingredients, temperatures and portions — from the Kochánov mixes.",
    "faq_page": {
        "title": "FAQ — ordering, shipping, what's in the mixes | Jůzlová",
        "desc": "How to order without a web shop, where to collect, what is free, is the pudding gluten-free, how much fat the cocoa has, how to store a 5 kg bag. Answers from the workshop in Kochánov.",
        "h1": "FAQ: ordering, shipping, ingredients and packs",
        "sub": "Short answers. If your question is not here, call us.",
    },
    "recipes": {},
}
