# Slovenský obsah — adaptácia content_cs.py pre slovenského kuchára (halušky, strapačky) a zásielky na Slovensko.
from cocoa_faq import product_cocoa_faq

LANG = {
    "code": "sk",
    "locale": "sk_SK",
    "name": "Slovenčina",
    "ui": {
        "nav_home": "Úvod", "nav_about": "Kto sme", "nav_delivery": "Kde nás nájdete",
        "nav_products": "Produkty", "nav_prices": "Cenník", "nav_recipes": "Recepty",
        "nav_faq": "Časté otázky", "nav_contact": "Kontakt",
        "nav_b2b": "Pre kuchyne", "nav_d2c": "Zásielky na Slovensko",
        "nav_aria": "Hlavná navigácia",
        "menu_open": "Otvoriť menu",
        "menu_close": "Zavrieť menu",
        "hero_img_alt": "Kochánov z vtáčej perspektívy",
        "workshop_caption": "Naša dielňa v Kochánove — vrecia s múkou, váha a balenie.",
        "est": "Rodinná dielňa · Kochánov, Česko · od roku 2004",
        "hero_h1": "Cesto na halušky, strapačky a zemiakové knedle v prášku z rodinnej dielne na Vysočine — múka z vlastného mlyna, stačí voda",
        "hero_lead": "Rodina Jůzlových mieša zmesi v Kochánove od roku 2004. Vyzdvihnutie v dielni alebo poistený balík na Slovensko — cenu dopravy vám povieme pred objednávkou.",
        "hero_cta": "Zavolať Jiřine a objednať",
        "hero_cta2": "Pozrieť cenník",
        "sec_products": "Päť zmesí. Jedno miesto výroby.", "sec_products_kicker": "Čo vyrábame",
        "sec_products_lead": "Ceny platia pri vyzdvihnutí v dielni. Doprava sa počíta zvlášť.",
        "sec_recipes": "Čo z toho uvaríte", "sec_recipes_kicker": "Recepty",
        "sec_recipes_lead": "Každý recept hovorí, koľko zmesi dať, na koľko stupňov piecť a koľko porcií vyjde.",
        "sec_why": "Viete, odkiaľ je múka. A komu voláte.", "sec_why_kicker": "Prečo od nás",
        "why_1_h": "Múka z mlyna našej rodiny",
        "why_1_p": "Pšeničná múka do knedľových zmesí je z mlyna v Havlíčkovom Brode, 12 km od dielne, s českou značkou kvality KLASA. Mlyn vlastní a vedie naša širšia rodina.",
        "why_2_h": "Voláte tej, ktorá to mieša",
        "why_2_p": "Objednávky berie Jiřina Jůzlová, denne 8–19. Žiadny e-shop, žiadne call centrum. Odpovedáme po česky.",
        "why_3_h": "Kilo namiesto vrecúška",
        "why_3_p": "Puding v kile, cukor v kile, knedle v päťkilovom vreci. Balíme jednoducho a predávame priamo z dielne.",
        "ticker_pickup": "Ceny platia pri vyzdvihnutí v dielni",
        "deliver_kicker": "Doprava",
        "deliver_h2": "Vyzdvihnúť, priviezť, alebo poslať",
        "deliver_1": "Zadarmo vyzdvihnete v Kochánove 40 alebo v Humpolci — termín po telefóne.",
        "deliver_2": "Zadarmo privezieme po Vysočine: Humpolec a Havlíčkův Brod od 1000 Kč, Jihlava od 3000 Kč, zvyšok kraja od 5000 Kč.",
        "deliver_3": "Na Slovensko a do celej EÚ posielame poistený balík; dopravu, krabicu a poistenie nacíníme vopred.",
        "deliver_btn": "Zistiť cenu zásielky",
        "sec_b2b": "Varíte pre stovky ľudí?",
        "sec_b2b_kicker": "Pre kuchyne",
        "sec_b2b_lead": "Jedálňam, reštauráciám, pekárňam a zmrzlinárom dodávame rovnakých päť zmesí za množstevnú cenu. Veľkoobchodné zásielky na Slovensko na náklady kupujúceho.",
        "sec_b2b_btn": "Vypýtať cenu pre kuchyňu",
        "sec_d2c_kicker": "Zásielky",
        "sec_d2c": "Bývate na Slovensku?",
        "sec_d2c_lead": "Pošleme vám krabicu. Dopravu, balenie a poistenie nacíníme vopred — nič neodíde, kým cenu neodsúhlasíte.",
        "sec_d2c_btn": "Ako posielame na Slovensko",
        "nl_h": "Recepty a novinky e-mailom",
        "nl_kicker": "Novinky",
        "nl_lead": "Občas pošleme nový recept zo zmesí a sezónne tipy pred Vianocami a Veľkou nocou. Odhlásite sa jedným kliknutím.",
        "nl_consent": "Súhlasím so zasielaním noviniek na e-mail. Adresu dostane Jůzlová, juzlj@seznam.cz. Súhlas odvoláte e-mailom.",
        "nl_submit": "Prihlásiť sa k receptom",
        "nl_success": "Ďakujeme. Ste prihlásení.",
        "nl_need_email": "Vyplňte e-mail a zaškrtnite súhlas.",
        "form_qty": "Množstvo (balenia alebo kg)",
        "form_fulfill": "Ako chcete tovar prevziať",
        "form_fulfill_factory": "Vyzdvihnutie v dielni Kochánov 40, 582 53",
        "form_fulfill_humpolec": "Vyzdvihnutie v Humpolci pri Pivovare Bernard (zadarmo, deň a hodinu dohodneme)",
        "form_fulfill_delivery": "Rozvoz alebo balík (dopravu nacíníme vopred)",
        "cta_sample_h": "Chcete objednať?",
        "cta_sample_p": "Zavolajte, alebo napíšte, čo a koľko chcete a kde ste. Zvyšok dohodneme.",
        "cta_sample_btn": "Zavolať Jiřine",
        "cta_call": "Zavolať Jiřine",
        "cta_write": "Napísať e-mail",
        "cta_order": "Objednať u Jiřiny",
        "cta_pickup": "Kde vyzdvihnúť",
        "cta_quote": "Vypýtať cenu pre kuchyňu",
        "cta_eu": "Zistiť cenu zásielky",
        "full_price_list": "Celý cenník",
        "all_recipes": "Všetky recepty",
        "recipes_h1": "Recepty z našich zmesí: od nedeľných knedieľ po venčeky a perník",
        "carousel_label": "Recepty na úvode",
        "carousel_prev": "Predchádzajúci recept",
        "carousel_next": "Ďalší recept",
        "carousel_status": "Recept {current} z {total}: {name}",
        "carousel_goto": "Prejsť na recept {n}: {name}",
        "faq_b2b_hint": "Kuchyne a prevádzky: otázky k množstevným cenám a dodaniu sú na stránke Pre kuchyne.",
        "sec_faq": "Časté otázky",
        "rate_label": "Ohodnoťte tento recept",
        "rate_count": "{n} hodnotení",
        "rate_star": "Ohodnotiť {n} z 5",
        "rate_thanks": "Ďakujeme. Vaše hodnotenie je uložené.",
        "rate_already": "Tento recept ste už hodnotili.",
        "rate_error": "Hodnotenie sa teraz nepodarilo uložiť. Skúste to znova.",
        "detail": "Viac",
        "price_label": "Cena",
        "package_label": "Balenie",
        "price_board_label": "Ceny pri vyzdvihnutí v dielni",
        "price_pickup_badge": "pri vyzdvihnutí v dielni",
        "unit_h2": "Koľko to je za kilo a za porciu",
        "unit_col_product": "Zmes",
        "unit_col_unit": "Za kilo / za porciu",
        "unit_note": "Počet porcií je orientačný podľa návodu na obale. Doprava mimo bezplatných zón sa počíta zvlášť.",
        "reviews_kicker": "Hodnotenia",
        "reviews_h2": "Čo o nás hovoria zákazníci",
        "reviews_lead": "Hodnotenia preberáme z našich živých profilov na Google a Firmy.cz. Nič si nevymýšľame.",
        "reviews_google": "Google",
        "reviews_seznam": "Firmy.cz",
        "reviews_open": "Otvoriť hodnotenia",
        "reviews_count": "{n} hodnotení",
        "reviews_rating_of": "{rating} z 5",
        "team_kicker": "Ľudia",
        "team_h2": "Kto je kto",
        "team_lead": "Keď zavoláte alebo napíšete, hovoríte s niekým z nás.",
        "b2b_vis_1_h": "500 porcií, traja ľudia",
        "b2b_vis_1_p": "Zemiakové cesto na vodu: odpadá šúpanie a strúhanie tridsiatich kíl zemiakov. Konzistencia je každý deň rovnaká.",
        "b2b_vis_2_h": "Krátka etiketa",
        "b2b_vis_2_p": "Múka a sušené zemiakové vločky. Zloženie a etikety pošleme e-mailom pre vaše papiere.",
        "b2b_vis_3_h": "Tri cesty dodania",
        "b2b_vis_3_p": "Vyzdvihnutie v Kochánove, náš rozvoz (Brno zadarmo od 5000 Kč, Praha od 25 kg), alebo váš dopravca — často lacnejšie.",
        "b2b_vis_4_h": "Papiere ku kakau",
        "b2b_vis_4_p": "Ku kakau pošleme laboratórny certifikát k vašej šarži. Bez 14 alergénov EÚ, lepok pod 20 ppm.",
        "order_info": "Objednávka",
        "open_hours_short": "denne 8–19",
        "breadcrumb_home": "Úvod",
        "footer_products": "Produkty", "footer_recipes": "Recepty", "footer_company": "Firma",
        "footer_note": "Rodinná dielňa potravinárskych zmesí od roku 2004.",
        "footer_addr": "Jůzlová s.r.o. · IČO 45900124 · Kochánov 40, 582 53 · Vysočina, Česko",
        "open_hours": "Denne 8:00–19:00 po telefóne, vrátane víkendov",
        "lang_label": "Jazyk",
        "lang_cs": "Čeština", "lang_en": "English", "lang_de": "Deutsch", "lang_sk": "Slovenčina",
        "recipe_meta": "Recept z dielne Jůzlová",
        "uses_product": "Použitá zmes",
        "more_recipes": "Keď vás toto baví",
        "more_recipes_kicker": "Návrhy k tomuto receptu",
        "more_recipes_lead": "Ďalšie recepty, ktoré sa k tomu hodia — rovnaká zmes, alebo podobné pečenie.",
        "more_recipe_open": "Otvoriť recept: {name}",
        "form_h": "Napíšte, čo potrebujete",
        "form_hint": "Stačí meno a telefón alebo e-mail. Ozveme sa a dohodneme termín.",
        "form_google_pending": "",
        "map_title": "Mapa dielne Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_addr": "Kochánov 40, 582 53 — nie 582 91, to je iný Kochánov",
        "map_open": "Otvoriť v Google Maps",
        "map_nav_google": "Navigovať v Google Maps",
        "map_nav_seznam": "Navigovať v Mapy.cz",
        "form_name": "Meno",
        "form_phone": "Telefón",
        "form_email": "E-mail",
        "form_buyer": "Odoberáte pre",
        "form_buyer_home": "Domácnosť",
        "form_buyer_pro": "Reštauráciu, jedáleň alebo cukráreň",
        "form_products": "O ktoré zmesi máte záujem",
        "form_message": "Správa (čo, koľko, kde ste)",
        "form_submit": "Odoslať a dohodnúť termín",
        "form_sending": "Odosielam…",
        "form_success": "Ďakujeme, správa je u nás. Ozveme sa vám kvôli objednávke.",
        "form_error": "Správu sa teraz nepodarilo odoslať. Skúste to znova, alebo nám zavolajte.",
        "form_captcha": "Overenie sa nepodarilo. Obnovte stránku a skúste to znova.",
        "form_honeypot": "Toto pole nevypĺňajte",
        "form_need_contact": "Vyplňte telefón alebo e-mail.",
        "cookie_aria": "Súhlas s cookies",
        "cookie_text": "Google Analytics počíta návštevy cez cookies. Bez súhlasu web funguje rovnako.",
        "cookie_accept": "Súhlasím",
        "cookie_essential": "Len nevyhnutné",
        "form_b2b_h": "Dopyt pre kuchyňu",
        "form_b2b_hint": "Formulár je pre prevádzky. Domácnosti objednávajú cez Kontakt.",
    },
    "meta": {
        "home_title": "Cesto na halušky a zemiakové knedle v prášku — rodinná dielňa Vysočina",
        "home_desc": "Zemiakové a chlpaté knedle v prášku (na halušky a strapačky), vanilkový puding bez lepku, kakao holandského typu priamo od českého výrobcu. Vyzdvihnutie alebo balík na Slovensko s cenou dopravy vopred.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Kto sme — rodinná dielňa Jůzlová, Kochánov, od roku 2004",
            "desc": "Rodina Jůzlových vyrába knedle v prášku, puding a kakao v Kochánove na Vysočine od roku 2004. Múka z rodinného mlyna v Havlíčkovom Brode. Bez e-shopu, bez prekupníkov.",
            "nav": "Kto sme",
            "h1": "Jůzlovci z Kochánova: rodina, ktorá od roku 2004 mieša zmesi, ktoré si sama varí",
            "sub": "Dielňa je v Kochánove 40, dvanásť kilometrov od Havlíčkovho Brodu. Múku berieme z mlyna, ktorý vedie naša širšia rodina. Objednávky berie Jiřina.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("h2", "Ako to začalo"),
                ("p", "Výrobu potravinárskych zmesí sme v malej dielni v Kochánove začali v roku 2004 a receptúry sme roky ladili. Dnes od nás berú domácnosti v Čechách aj na Morave a k tomu jedálne, reštaurácie a pekárne."),
                ("team", None),
                ("h2", "Odkiaľ je múka"),
                ("p", "Pšeničná múka do knedľových zmesí je z mlyna v Havlíčkovom Brode, 12 km od dielne, s českou značkou kvality KLASA. Mlyn vlastní a vedie naša širšia rodina, takže vieme, čo do vreca sypeme."),
                ("h2", "Čo nerobíme"),
                ("ul", [
                    "Nemáme e-shop. Objednávate telefónom, e-mailom alebo formulárom.",
                    "Nedávame vzorky ani ochutnávky.",
                    "Nevymýšľame si hviezdičky — hodnotenia berieme zo živých profilov Google a Firmy.cz.",
                    "Odpovedáme po česky.",
                ]),
                ("reviews", None),
            ],
        },
        "kde_nas_najdete": {
            "title": "Kde nás nájdete — Kochánov 40 a Humpolec, rozvoz po Vysočine | Jůzlová",
            "desc": "Dielňa Kochánov 40, 582 53, 12 km od Havlíčkovho Brodu. Druhý odber v Humpolci zadarmo po dohode. Rozvoz zadarmo po Vysočine od stanovených súm; balík na Slovensko nacenený vopred.",
            "nav": "Kde nás nájdete",
            "h1": "Kde nás nájdete: dielňa v Kochánove, odber v Humpolci, rozvoz po Vysočine",
            "sub": "Najprv telefón, potom cesta. Dielňa nie je obchod s otváracími hodinami na dverách.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("h2", "Dielňa v Kochánove"),
                ("p", "Kochánov 40, 582 53, kraj Vysočina, Česko. Vyzdvihnutie je zadarmo, denne 8:00–19:00 po telefóne, aj cez víkend. Pozor na PSČ: 582 91 je iný Kochánov."),
                ("map", None),
                ("h2", "Odber v Humpolci"),
                ("p", "Druhé výdajné miesto je v Humpolci v okolí Pivovaru Bernard, zadarmo. Presné miesto, deň a hodinu povieme po telefóne."),
                ("h2", "Rozvoz a zásielky"),
                ("ul", [
                    "Humpolec a Havlíčkův Brod: rozvoz zadarmo od 1000 Kč",
                    "Jihlava: zadarmo od 3000 Kč",
                    "Zvyšok Vysočiny: zadarmo od 5000 Kč",
                    "Inde po Česku: balík, dopravu nacíníme vopred; môžete poslať aj vlastného dopravcu",
                    "Slovensko a ďalšie krajiny EÚ: dopravu, krabicu a poistenie platíte vy, sumu vidíte vopred",
                ]),
                ("form", None),
            ],
        },
        "kontakt": {
            "title": "Kontakt Jůzlová — Kochánov 40, Česko, denne 8–19",
            "desc": "Jiřina Jůzlová +420 728 466 141, Jiří Jůzl +420 607 629 931, juzlj@seznam.cz. Dielňa Kochánov 40, 582 53, Vysočina. Odber po dohode; zásielky na Slovensko.",
            "nav": "Kontakt",
            "h1": "Zavolajte Jiřine alebo Jiřímu — denne 8–19, dohodneme objednávku aj odber",
            "sub": "Vrátane sobôt a nedieľ, vždy po predchádzajúcej dohode. Odpovedáme po česky.",
            "cta": None,
            "body": [
                ("contacts", None),
                ("form", None),
                ("h2", "Kde nás nájdete"),
                ("map", None),
                ("p", "Dielňa: Kochánov 40, 582 53, kraj Vysočina, Česko, 12 km od Havlíčkovho Brodu. Druhý odber v Humpolci v okolí Pivovaru Bernard, zadarmo, po dohode."),
            ],
        },
        "ceny": {
            "title": "Cenník — knedle v prášku, puding, kakao od výrobcu | Jůzlová",
            "desc": "Zemiakové knedle 5 kg 250 Kč, chlpaté 260 Kč, puding bez lepku 60 Kč/kg, kakao 270 Kč/500 g, vanilínový cukor 60 Kč/kg. Ceny v dielni; doprava na Slovensko vopred.",
            "nav": "Cenník",
            "h1": "Cenník: päť zmesí, ceny pri vyzdvihnutí v Kochánove; doprava sa počíta zvlášť",
            "sub": "Rovnaká cena pre každého, kto si tovar vyzdvihne v dielni alebo v Humpolci. Rozvoz a zásielky sa pripočítajú — prehľad je pod tabuľkou.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("pricetable", None),
                ("h2", "Doprava"),
                ("ul", [
                    "Vyzdvihnutie v Kochánove alebo v Humpolci: zadarmo",
                    "Humpolec a Havlíčkův Brod: rozvoz zadarmo od 1000 Kč",
                    "Jihlava: zadarmo od 3000 Kč · zvyšok Vysočiny: zadarmo od 5000 Kč",
                    "Kuchyne: Brno zadarmo od 5000 Kč, Praha zmiešaná objednávka od 25 kg",
                    "Balík po Česku: nacíníme vopred · Slovensko a EÚ: doprava, krabica, poistenie a fólia, suma vopred",
                ]),
                ("h2", "Kuchyne a prevádzky"),
                ("p", "Množstevné ceny povieme po telefóne alebo cez formulár na stránke Pre kuchyne."),
                ("h2", "Staré ceny na internete"),
                ("p", "Na niektorých weboch ešte visia ceny z roku 2017. Platí len tento cenník."),
            ],
        },
        "velkoobchod": {
            "title": "Veľkoobchod knedle v prášku, puding, kakao — jedálne, reštaurácie | Jůzlová",
            "desc": "Množstevné ceny pre školské jedálne, reštaurácie, pekárne a zmrzlinárov. Odber v Kochánove, náš rozvoz alebo váš dopravca; zásielky na Slovensko. Certifikát ku kakau na požiadanie.",
            "nav": "Pre kuchyne",
            "h1": "Knedle, puding a kakao pre jedálne a reštaurácie: množstevná cena, odber alebo rozvoz, certifikát k šarži",
            "sub": "Zásobujeme jedálne, reštaurácie, pekárne, kaviarne, školy a zmrzlinárov; veľkoobchodné zásielky na Slovensko na náklady kupujúceho. Cenu podľa množstva povieme telefonicky; mená zákazníkov nezverejňujeme.",
            "cta": ("cta_call", None, None),
            "body": [
                ("h2", "Prečo kuchyne berú zmes"),
                ("p", "Zemiakové cesto na 500 porcií bez tridsiatich kíl zemiakov na šúpanie. Rovnaká konzistencia každý deň. Na etikete múka a sušené zemiakové vločky — a čo k tomu pridáte, je vaša vec."),
                ("b2b_showcase", None),
                ("h2", "Čo dodávame komu"),
                ("ul", [
                    "jedálňam a reštauráciám — knedle a puding na výdaj",
                    "pekárňam a cukrárňam — puding, vanilínový cukor, kakao",
                    "kaviarňam — kakao a puding",
                    "školám — zmesi na detské jedlá",
                    "zmrzlinárom — kakao holandského typu, ktoré v mraze drží farbu",
                ]),
                ("h2", "Ako to dostanete"),
                ("ol", [
                    "Vyzdvihnutie v dielni v Kochánove",
                    "Náš rozvoz — dopravu nacíníme; do Brna zadarmo od 5000 Kč, do Prahy zmiešaná objednávka od 25 kg",
                    "Váš vlastný dopravca — často vyjde lacnejšie",
                ]),
                ("p", "Na Slovensko, do Nemecka, Rakúska a Poľska posielame veľkoobchodné zásielky na náklady zákazníka."),
                ("form_b2b", None),
            ],
        },
        "do_eu": {
            "title": "Knedle v prášku a puding na Slovensko — cena dopravy vopred | Jůzlová",
            "desc": "Zemiakové a chlpaté knedle v prášku, puding bez lepku a kakao z Vysočiny poisteným balíkom na Slovensko. Ceny ako v dielni plus doprava, krabica a poistenie — všetko vopred.",
            "nav": "Zásielky na Slovensko",
            "h1": "Zásielka na Slovensko: pošleme vám knedle v prášku, puding a kakao — cenu dopravy vidíte skôr, než zaplatíte",
            "sub": "Ceny tovaru ako v dielni. K nim pripočítame sledovanú dopravu, krabicu, poistenie a bublinkovú fóliu, pošleme sumu a odošleme, keď ju odsúhlasíte.",
            "cta": ("cta_call", "kontakt", "cta_write"),
            "body": [
                ("h2", "Ako to prebieha"),
                ("ol", [
                    "Napíšete, čo chcete a kam to má ísť.",
                    "Nacíníme dopravu, krabicu a poistenie a pošleme celkovú sumu.",
                    "Odsúhlasíte a zaplatíte.",
                    "Pošleme so sledovaním zásielky.",
                ]),
                ("h2", "Ako balíme"),
                ("p", "Vrecia do bublinkovej fólie, do pevnej krabice, zásielka poistená a sledovaná. Zmesi sú trvanlivé, vydržia mesiace."),
                ("h2", "Tip: dar rodine v Česku"),
                ("p", "Chcete poslať knedle rodine v Česku? Doručíme kamkoľvek po Česku, alebo si ich vyzdvihnú v Kochánove či Humpolci."),
                ("form", None),
            ],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Zemiakové knedle v prášku",
            "h1": "Zemiakové knedle v prášku: zamiešate vodou, za 20 minút sú na stole a nerozvaria sa",
            "short": "Pšeničná múka z mlyna v Havlíčkovom Brode a sušené zemiakové vločky. Nič iné. Vajce alebo postrúhaný varený zemiak pridáte podľa zvyku.",
            "price": "5 kg / 250 Kč",
            "per_unit": "50 Kč/kg · zhruba 4 Kč na porciu (60–70 porcií)",
            "title": "Zemiakové knedle v prášku 5 kg — stačí voda, hotové za 20 minút | Jůzlová",
            "desc": "Zemiakové cesto v prášku z múky rodinného mlyna a zemiakových vločiek. Nerozvarí sa, hotové za 20 minút. 5 kg / 250 Kč. Zásielka na Slovensko s cenou dopravy vopred.",
            "body": [
                ("h2", "Čo v tom je"),
                ("p", "Pšeničná múka s českou značkou kvality KLASA z mlyna v Havlíčkovom Brode, ktorý vlastní a vedie naša širšia rodina, a sušené zemiakové vločky. Vločky dávajú cestu chuť zemiakov a držia ho pri varení pohromade."),
                ("h2", "Ako to pripravíte"),
                ("ol", [
                    "Zmes zamiešate s vodou podľa návodu na vreci.",
                    "Vytvarujete knedle, šúľance alebo krokety.",
                    "Povaríte. Od otvorenia vreca po tanier zhruba 20 minút.",
                ]),
                ("tip", "Chcete to „svoje“? Časť vody nahraďte mliekom, pridajte vajce alebo jeden uvarený postrúhaný zemiak. Veľa našich zákazníkov to tak robí."),
                ("h2", "Čo z jedného cesta uvaríte"),
                ("ul", ["klasické zemiakové knedle k pečenému mäsu",
                        "knedle plnené mäsom alebo ovocím",
                        "šúľance s makom", "vyprážané krokety", "domáce gnocchi"]),
                ("h2", "Koľko toho je"),
                ("p", "Z 5 kg pripravíte prílohu zhruba pre 60–70 ľudí. Vrece skladujte v suchu a zatvorené."),
            ],
            "faq": [
                ("Musím pridať vajce?", "Nie. Cesto funguje len s vodou. Vajce alebo mlieko pridajte, ak chcete bohatšiu chuť."),
                ("Vydržia knedle plnenie ovocím?", "Áno, cesto drží tvar; zákazníci z neho robia aj plnené knedle."),
                ("Máte menšie balenie než 5 kg?", "Nie. 5 kg je jediné balenie; vystačí na sezónu."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Chlpaté knedle v prášku",
            "h1": "Cesto na halušky a strapačky v prášku: chlpaté knedle (bosáky) bez strúhania zemiakov, hotové za 15 minút",
            "short": "Podľa tradičnej receptúry z našej dielne. Zmiešate s vodou, pretlačíte cez cedník do vriacej vody — halušky. Alebo vytvarujete bosáky ku kapuste.",
            "price": "5 kg / 260 Kč",
            "per_unit": "52 Kč/kg · na sezónu aj pre jedáleň",
            "title": "Cesto na halušky a strapačky v prášku (chlpaté knedle) 5 kg | Jůzlová",
            "desc": "Chlpaté knedle v prášku podľa tradičnej receptúry: pretlačíte na halušky alebo vytvarujete bosáky. Bez strúhania, za 15 minút. 5 kg / 260 Kč. Balík na Slovensko s cenou vopred.",
            "body": [
                ("h2", "Na čo sa hodí"),
                ("ul", ["halušky a strapačky — cesto pretlačené cez cedník do vriacej vody",
                        "bosáky s kapustou a údeným mäsom",
                        "s cibuľkou a škvarkami",
                        "sladko s makom a cukrom"]),
                ("h2", "Príprava"),
                ("ol", [
                    "Zmes zamiešate s vodou podľa návodu.",
                    "Pretlačíte cez cedník, alebo vytvarujete bosáky.",
                    "Povaríte. Od vreca na tanier 15 minút.",
                ]),
                ("h2", "Pre jedálne"),
                ("p", "Bosáky berieme aj pre jedálne a reštaurácie: rovnaká zmes, množstevná cena, odber v Kochánove, náš rozvoz, alebo váš dopravca."),
            ],
            "faq": [
                ("Sú chlpaté knedle a bosáky to isté?", "Áno, sú to dva názvy pre jedno jedlo."),
                ("Dajú sa z toho robiť halušky?", "Áno; cesto pretlačíte cez cedník do vriacej vody. Recept na strapačky s kapustou a slaninou je na webe."),
                ("Máte menšie balenie než 5 kg?", "Nie. 5 kg je jediné balenie."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Vanilkový puding bez lepku",
            "h1": "Vanilkový puding bez lepku v kile: kukuričný škrob na krém, koláč aj perník — asi 25 vrecúšok za 60 Kč",
            "short": "Základ je kukuričný škrob, ktorý lepok neobsahuje. Varíte ho ako každý puding; do krému na veterníky, do hruškového koláča, do hrnčekového perníka.",
            "price": "1 kg / 60 Kč · 400 g / 30 Kč",
            "per_unit": "60 Kč/kg · zhruba 2,40 Kč na jeden puding (40 g)",
            "title": "Vanilkový puding bez lepku 1 kg / 60 Kč — kukuričný škrob | Jůzlová",
            "desc": "Vanilkový puding z kukuričného škrobu bez lepku. Kilo vystačí na cca 25 pudingov alebo krémy na veterníky. 1 kg / 60 Kč, 400 g / 30 Kč. Zásielka na Slovensko.",
            "body": [
                ("h2", "Bez lepku, prečo"),
                ("p", "Pšeničný škrob v pudingu nepoužívame. Kukuričný škrob lepok prirodzene neobsahuje, preto sa puding hodí aj pre bezlepkovú diétu."),
                ("h2", "Koľko dať"),
                ("p", "Bežné vrecúško z obchodu je zhruba 40 g na 500 ml mlieka. Z kila uvaríte asi 25 pudingov, alebo krém do niekoľkých plechov veterníkov."),
                ("h2", "Čokoládový?"),
                ("p", "Kakaový puding nevyrábame. Do uvareného vanilkového pudingu zamiešajte lyžicu nášho kakaa holandského typu a máte čokoládový krém."),
                ("h2", "Recepty s pudingom"),
                ("ul", ["hruškový koláč s vanilkovým pudingom", "venčeky s vanilkovým krémom",
                        "mini veterníky", "karamelové veterníky", "hrnčekový perník"]),
            ],
            "faq": [
                ("Dá sa puding použiť namiesto pudingu z obchodu 1 : 1?", "Áno. Zhruba 40 g na 500 ml mlieka, ako bežné vrecúško."),
                ("Vydrží otvorené kilové vrecko?", "Áno, v suchu a zatvorené. Na prvé vyskúšanie je 400 g balenie za 30 Kč."),
                ("Vyrábate aj čokoládový variant?", "Nie. Čokoládovú chuť dáte vanilkovému pudingu kakaom holandského typu, ktoré predávame samostatne."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holandského typu",
            "h1": "Kakao holandského typu s 20–22 % kakaového masla: tmavá farba, ktorá v bábovke ani zmrzline nevybledne",
            "short": "Alkalizovaný prášok z kakaovej hmoty, bez pridaného cukru, bez 14 alergénov EÚ. Do perníka, krémov, kakaa na pitie a zmrzliny. Certifikát k šarži pošleme na požiadanie.",
            "price": "500 g / 270 Kč",
            "per_unit": "540 Kč/kg · asi 50 lyžíc z balenia",
            "title": "Kakao holandského typu 20–22 % tuku, 500 g / 270 Kč | Jůzlová",
            "desc": "Tmavé cukrárske kakao holandského typu, 20–22 % kakaového masla, bez pridaného cukru, bez alergénov. Farba drží v pečení aj zmrzline. Certifikát k šarži. Zásielka na Slovensko.",
            "body": [
                ("h2", "Prečo záleží na tuku"),
                ("p", "Aby sa prášok smel nazývať kakao, musí podľa práva EÚ obsahovať najmenej 20 % kakaového masla; pod tým je to kakao so zníženým obsahom tuku. Naše má 20–22 %. Viac kakaového masla znamená tmavšiu farbu, plnšiu chuť a hladší krém."),
                ("h2", "Odkiaľ je"),
                ("p", "Bôby zo západnej a strednej Afriky, fermentované v banánových listoch a sušené na slnku. Alkalizujeme prírodnými soľami na pH 7,8–8,2 — preto je farba sýto červenohnedá a chuť okrúhla, nie kyslá."),
                ("h2", "Čo v ňom nie je"),
                ("p", "Žiadny pridaný cukor (prirodzene 0,9 g cukru na 100 g). Žiadny zo 14 alergénov EÚ, lepok pod 20 ppm. Vegánske."),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
                ("h2", "Skladovanie"),
                ("p", "V suchu, mimo silných pachov, ideálne pri 15–20 °C a vlhkosti pod 50 %."),
                ("h2", "Pre cukrárne a zmrzlinárov"),
                ("p", "Množstevná cena, certifikát k šarži, odber alebo doprava. Dopyt na stránke Pre kuchyne."),
            ],
            "showcase": {
                "apps_h": "Kam ho dať",
                "apps": [
                    {"title": "Pečenie", "text": "Perník, bábovka, brownies — cestá, ktoré majú zostať sýto kakaové aj po upečení."},
                    {"title": "Nápoje", "text": "Mliečne kakao a koktaily — v mlieku drží farbu aj krémovú chuť."},
                    {"title": "Krémy", "text": "Náplne a krémy bez pridaného cukru v prášku."},
                    {"title": "Posyp", "text": "Rezy, rolády a bebe dezerty — tmavý, jemný prach, ktorý sa nezráža."},
                    {"title": "S vanilkovým pudingom", "text": "Zamiešajte do nášho vanilkového pudingu: čokoládový krém z dvoch zmesí."},
                    {"title": "Zmrzlina", "text": "Hladká textúra a tmavá farba, ktorá v mraze nevybledne."},
                ],
                "nutri_h": "Čo v kakau je",
                "nutri_lead": "Na 100 g podľa nutričnej tabuľky na obale: veľa vlákniny a bielkovín, prirodzene málo cukru, žiadny pridaný cukor.",
                "nutri_extra": "K tomu horčík 490 mg, draslík 4 400 mg a železo 31 mg na 100 g.",
                "nutri_note": "Údaje na 100 g podľa nariadenia EÚ 1169/2011. Kakao používate po lyžiciach — hodnoty na porciu sú zlomkom tabuľky.",
                "bars": [
                    {"label": "Energia", "text": "379 kcal / 1 570 kJ", "pct": 19},
                    {"label": "Tuk", "text": "21,0 g  ·  nasýtené 13,0 g", "pct": 30},
                    {"label": "Vláknina", "text": "28,4 g", "pct": 100},
                    {"label": "Bielkoviny", "text": "19,5 g", "pct": 39},
                    {"label": "Cukry", "text": "0,9 g  ·  pridané 0 g", "pct": 2},
                    {"label": "Železo", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technické údaje",
                "facts": [
                    {"label": "Kakaové maslo", "value": "20,0–22,0 %"},
                    {"label": "pH (10 % roztok)", "value": "7,8–8,2"},
                    {"label": "Jemnosť", "value": "min. 99,5 % pod 75 µm"},
                    {"label": "Vlhkosť", "value": "max. 5,0 %"},
                    {"label": "Šupky", "value": "max. 1,75 %"},
                    {"label": "Ťažké kovy", "value": "v limitoch nariadenia (EÚ) 2023/915"},
                    {"label": "Alergény EÚ", "value": "žiadne zo 14"},
                    {"label": "Lepok", "value": "< 20 ppm"},
                    {"label": "Strava", "value": "vegánske, vegetariánske"},
                ],
            },
            "faq": product_cocoa_faq("sk"),
        },
        "vanilkovy_cukr": {
            "name": "Vanilínový cukor",
            "h1": "Vanilínový cukor v kile: do cesta aj na posypanie — jedno vrece namiesto zásuvky vrecúšok",
            "short": "Nie je to vanilka zo struku — je to jemne mletý cukor s vanilínovou arómou. Hovoríme to rovno.",
            "price": "1 kg / 60 Kč",
            "per_unit": "60 Kč/kg",
            "title": "Vanilínový cukor 1 kg / 60 Kč — do cesta aj na posyp | Jůzlová",
            "desc": "Jemne mletý cukor s vanilínovou arómou v kilovom balení. Do koláčov, vianočného pečiva, šľahačky a na posyp. Česká rodinná dielňa, zásielka na Slovensko s cenou vopred.",
            "body": [
                ("h2", "Do čoho"),
                ("ul", ["koláče a zákusky", "vianočné pečivo — do cesta aj na posyp", "šľahačka a krémy", "bebe rezy a mini veterníky z našich receptov"]),
                ("h2", "Skladovanie"),
                ("p", "V suchu a zatvorené, aby cukor nezvlhol a nestvrdol."),
            ],
            "faq": [
                ("Je to to isté čo vanilkový cukor z obchodu?", "Áno, je to vanilínový cukor — cukor s vanilínovou arómou, nie mletý vanilkový struk."),
                ("Predávate aj pravú vanilku?", "Nie."),
            ],
        },
    },
    "recipes_intro": "Každý recept hovorí, koľko zmesi dať, na koľko stupňov piecť a koľko porcií vyjde.",
    "recipes_desc": "Šúľance s makom, strapačky, hruškový koláč s pudingom, venčeky, kremrole, hrnčekový perník. Recepty so surovinami, teplotou a počtom porcií — zo zmesí z Kochánova.",
    "faq_page": {
        "title": "Časté otázky — objednanie, doprava, zloženie zmesí | Jůzlová",
        "desc": "Ako objednať bez e-shopu, kde vyzdvihnúť, čo je zadarmo, je puding bez lepku, koľko tuku má kakao, ako skladovať 5 kg vrece. Odpovede z dielne v Kochánove.",
        "h1": "Časté otázky: objednanie, doprava, zloženie a balenie",
        "sub": "Krátke odpovede. Keď tu vaša otázka nie je, zavolajte.",
    },
    "recipes": {},
}


# --- rev. 5 home, footer and marquee strings (2026-09-17) ---
LANG["ui"].update({
    'h1_main': 'Zemiakové knedle na stole za 20 minút',
    'h1_sub': 'z múky z mlyna 12 km od našej dielne',
    'stat_1': 'zemiakové knedle · 250 Kč',
    'stat_2': 'minút na chlpaté knedle',
    'stat_3': 'rok, keď sme začali miešať',
    'stat_4': 'od dielne k rodinnému mlynu',
    'stat_5': 'tuku v kakau holandského typu',
    'stat_6': 'puding a cukor v kile, nie vo vrecku',
    'journey_h2': 'Ako sa zmes dostane na váš stôl',
    'step_1': 'Pšenica z Vysočiny',
    'step_2': 'Mlyn 12 km od dielne',
    'step_3': 'Miešanie v Kochánove',
    'step_4': 'Vyzdvihnutie alebo rozvoz',
    'step_5': 'Na tanieri za 20 minút',
    'marks': 'Vysočina · rozvoz',
    'cta_short': 'Zavolať',
    'cb_h': 'Potrebujete poradiť s objednávkou?',
    'cb_name': 'Vaše meno',
    'cb_tel': 'Váš telefón',
    'cb_note': 'Zavoláme vám späť v pracovný deň 8–19.',
    'cb_btn': 'Zavolať mi späť',
    'cb_ok': 'Ďakujeme. Zavoláme vám späť v pracovný deň medzi 8. a 19. hodinou.',
    'cb_err': 'Vyplňte meno a telefón (aspoň 9 číslic).',
    'cb_message': 'Prosím o spätné zavolanie (formulár v pätičke).',
    'marquee_label': 'Cenník',
    'marquee_pause': 'Zastaviť pohyb cenníka',
    'marquee_play': 'Spustiť pohyb cenníka',
    'alt_cocoa_pod': 'Rozrezaný kakaový plod s bôbmi',
    'alt_vanilla': 'Kvet vanilky s listami a dvoma strukmi',
    'alt_leaf_banana': 'Banánový list',
    'footer_kitchens': 'Kde rozvážame',
    'sec_reviews_h': 'Čo o nás hovoria zákazníci',
})
