# Slovak content — full translation of content_cs.py.
LANG = {
    "code": "sk",
    "locale": "sk_SK",
    "name": "Slovenčina",
    "ui": {
        "nav_home": "Domov", "nav_about": "Kto sme", "nav_delivery": "Kde nás nájdete",
        "nav_products": "Produkty", "nav_prices": "Cenník", "nav_recipes": "Recepty",
        "nav_faq": "Časté otázky", "nav_contact": "Kontakt",
        "nav_b2b": "Veľkoobchod", "nav_d2c": "Česi v EÚ",
        "nav_aria": "Hlavná navigácia",
        "menu_open": "Otvoriť menu",
        "menu_close": "Zavrieť menu",
        "hero_img_alt": "Kochánov z vtáčej perspektívy",
        "workshop_caption": "Naša dielňa v Kochánove — vrecia s múkou, váha a baliaca linka.",
        "est": "Rodinná dielňa · Kochánov · od roku 2004",
        "hero_h1": "Knedle ako od babičky. Hotové za 15 minút.",
        "hero_lead": "Poctivé potravinárske zmesi z Vysočiny — zemiakové cestá, pudingy, vanilínový cukor a kakao. Z múky ocenenej českou značkou kvality KLASA, bez kompromisov v kvalite.",
        "hero_cta": "Zavolajte alebo napíšte",
        "hero_cta2": "Naše produkty",
        "sec_products": "Naše produkty", "sec_products_kicker": "Čo vyrábame",
        "sec_products_lead": "Päť zmesí, ktoré od roku 2004 pečieme a balíme pre domácnosti v Čechách i na Morave.",
        "sec_recipes": "Recepty z našich zmesí", "sec_recipes_kicker": "Inšpirácia do kuchyne",
        "sec_recipes_lead": "Osvedčené recepty, ktoré z našich zmesí pripravíte rýchlo a bez práce navyše.",
        "sec_why": "Prečo Jůzlová", "sec_why_kicker": "Rodinná výroba",
        "why_1_h": "Suroviny, ktoré poznáme po mene",
        "why_1_p": "Pšeničná múka ocenená českou značkou kvality KLASA pochádza z mlyna v Havlíčkovom Brode — 12 km od našej dielne —, ktorý vlastní a vedie naša širšia rodina. Kukuričný škrob v pudingoch neobsahuje lepok.",
        "why_2_h": "Rýchlosť bez kompromisov",
        "why_2_p": "Chlpaté knedle máte hotové za 15 minút — a chuťou ich nerozoznáte od knedieľ pripravovaných celé popoludnie.",
        "why_3_h": "Prečo sú ceny nízke",
        "ticker_pickup": "Ceny platia pri vyzdvihnutí v prevádzke",
        "why_3_p": "Vyrábame vo vlastnej dielni, máme málo vonkajších nákladov a jednoduché obaly. Priamy predaj je zhruba o 40 % lacnejší než cez prekupníkov. Vyzdvihnutím v Kochánove ušetríte dopravu. Rozvoz po Vysočine zadarmo od 5000 Kč. Do Humpolca a Havlíčkovho Brodu zadarmo od 1000 Kč. Do Jihlavy zadarmo od 3000 Kč.",
        "sec_b2b": "Pre reštaurácie a prevádzky",
        "sec_b2b_kicker": "Veľkoobchod",
        "sec_b2b_lead": "Už zásobujeme množstvo reštaurácií, pekární, kaviarní a škôl. Cenu podľa množstva dohodneme. Značky zákazníkov tu nemenujeme.",
        "sec_b2b_btn": "Veľkoobchodná ponuka",
        "sec_d2c": "Česi v zahraničí (EÚ)",
        "sec_d2c_kicker": "Zásielka do Európy",
        "sec_d2c_lead": "Môžete sa ozvať. Platíte dopravu, krabicu, poistenie a bublinkovú fóliu. Cenu pošleme pred odoslaním.",
        "sec_d2c_btn": "Ako posielame do EÚ",
        "nl_h": "Novinky a recepty e-mailom",
        "nl_kicker": "Odber noviniek",
        "nl_lead": "Až 7 nových receptov týždenne z našich zmesí: české tradičné, rýchle, sezónne (Vianoce, Veľká noc, leto, zima), európske aj reštauračné / Instagram.",
        "nl_consent": "Súhlasím so zasielaním noviniek na e-mail. Adresu dostane Jůzlová, juzlj@seznam.cz. Súhlas odvoláte e-mailom.",
        "nl_submit": "Prihlásiť sa",
        "nl_success": "Ďakujeme. Ste prihlásení k novinkám.",
        "nl_need_email": "Vyplňte e-mail a zaškrtnite súhlas.",
        "form_qty": "Množstvo (balenia alebo kg)",
        "form_fulfill": "Ako chcete tovar prevziať",
        "form_fulfill_factory": "Vyzdvihnutie v dielni Kochánov 40, 582 53",
        "form_fulfill_humpolec": "Vyzdvihnutie v Humpolci pri Pivovare Bernard (zadarmo, deň a hodinu dohodneme)",
        "form_fulfill_delivery": "Rozvoz (Vysočina zadarmo od 5000 Kč; Humpolec a Havlíčkův Brod od 1000 Kč; Jihlava od 3000 Kč; inak naceníme)",
        "cta_sample_h": "Chcete objednať?",
        "cta_sample_p": "Zavolajte alebo napíšte — tovar si vyzdvihnete v Kochánove či Humpolci, alebo vám ho privezieme až domov.",
        "cta_sample_btn": "Zavolajte alebo napíšte",
        "full_price_list": "Kompletný cenník",
        "all_recipes": "Všetky recepty",
        "carousel_label": "Recepty na úvodnej",
        "carousel_prev": "Predchádzajúci recept",
        "carousel_next": "Ďalší recept",
        "carousel_status": "Recept {current} z {total}: {name}",
        "carousel_goto": "Prejsť na recept {n}: {name}",
        "faq_b2b_hint": "Prevádzky a kuchyne: časté otázky k veľkoobchodu sú len na stránke Veľkoobchod.",
        "all_faq": "Všetky časté otázky",
        "sec_faq": "Časté otázky",
        "sec_faq_kicker": "Stručne a jasne",
        "sec_faq_lead": "Odpovede, ktoré ľudia aj vyhľadávače hľadajú najskôr — odkiaľ sme, ako objednať a čo vyrábame.",
        "rate_label": "Ohodnoťte tento recept",
        "rate_count": "{n} hodnotení",
        "rate_star": "Ohodnotiť {n} z 5",
        "rate_thanks": "Ďakujeme. Vaše hodnotenie je uložené.",
        "rate_already": "Tento recept ste už hodnotili.",
        "rate_error": "Hodnotenie sa teraz nepodarilo uložiť. Skúste to znova.",
        "detail": "Viac",
        "price_label": "Cena",
        "package_label": "Balenie",
        "price_board_label": "Ceny pri vyzdvihnutí v dielni",
        "price_pickup_badge": "Cena z dielne",
        "compare_kicker": "Porovnanie",
        "compare_h2": "Porovnanie ceny so supermarketom?",
        "compare_lead": "Všeobecný priemer pre rovnaké množstvo a podobnú vyššiu kvalitu. V bežných obchodoch bývajú porovnateľné výrobky často asi štyrikrát drahšie alebo ešte viac.",
        "compare_us": "U nás v dielni",
        "compare_shop": "Typický supermarket (odhad)",
        "compare_factor": "Asi 4×",
        "compare_keep": "necháte si zhruba",
        "compare_note": "Ide o všeobecný priemerný odhad, nie o cenu konkrétneho reťazca. Značky a kvalita sa líšia. Naše čísla sú ceny tovaru pri vyzdvihnutí v dielni — doprava sa počíta zvlášť.",
        "reviews_kicker": "Hodnotenia",
        "reviews_h2": "Recenzie na Google a Seznamu",
        "reviews_lead": "Hviezdičky berieme z živých profilov Google Maps a Seznam Firmy.cz. Kliknutím otvoríte aktuálne hodnotenia.",
        "reviews_google": "Google",
        "reviews_seznam": "Seznam",
        "reviews_open": "Otvoriť hodnotenia",
        "reviews_count": "{n} hodnotení",
        "reviews_rating_of": "{rating} z 5",
        "reviews_note": "Čísla sa obnovujú pri zostavení webu. Google Maps a Firmy.cz zostávajú zdrojom pravdy.",
        "team_kicker": "Ľudia",
        "team_h2": "Rodina za zmesami",
        "team_lead": "Kto u nás stojí za zmesami — stretnete sa s nami tu.",
        "team_photo_note": "Fotografie doplníme. Teraz sú na mieste neutrálne zástupné portréty.",
        "b2b_vis_1_h": "Pre kuchyne",
        "b2b_vis_1_p": "Reštaurácie, jedálne, pekárne, kaviarne, školy a výrobcovia zmrzliny — rovnakých päť zmesí, cena podľa množstva.",
        "b2b_vis_2_h": "Odber tromi cestami",
        "b2b_vis_2_p": "Vyzdvihnutie v Kochánove, náš rozvoz, alebo váš dopravca. Dohodneme termín telefónom alebo formulárom.",
        "b2b_vis_3_h": "Brno zadarmo od 5000 Kč",
        "b2b_vis_3_p": "Do Brna vozíme zadarmo pri objednávke nad 5000 Kč, po dohode. Moravská trasa je iná než Praha.",
        "b2b_vis_4_h": "Bez sadzobníka na webe",
        "b2b_vis_4_p": "Veľkoobchodnú cenu povieme po dopyte. Značky kuchýň na webe nemenujeme.",
        "b2b_brno_free": "Brno: rozvoz zadarmo od objednávky nad 5000 Kč, po dohode termínu.",
        "order_info": "Ako objednať",
        "breadcrumb_home": "Domov",
        "footer_products": "Produkty", "footer_recipes": "Recepty", "footer_company": "Firma",
        "footer_note": "Rodinná výroba potravinárskych zmesí od roku 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina",
        "open_hours": "Otvorené denne po telefonickom dohovore, 8:00–19:00 (vrátane víkendov)",
        "lang_label": "Jazyk",
        "recipe_meta": "Recept z dielne Jůzlová",
        "uses_product": "Použitá zmes",
        "more_recipes": "Ak vás toto baví",
        "more_recipes_kicker": "Návrhy k tomuto receptu",
        "more_recipes_lead": "Ďalšie recepty, ktoré sa k tomu hodia — rovnaká zmes, alebo podobné pečenie.",
        "more_recipe_open": "Otvoriť recept: {name}",
        "form_h": "Napíšte nám",
        "form_hint": "Stačí meno a telefón alebo e-mail. Objednávky aj na +420 728 466 141 (Jiřina) a +420 607 629 931 (Jiří).",
        "form_google_pending": "",
        "map_title": "Mapa prevádzky Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_addr": "Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_open": "Otvoriť v Google Maps",
        "map_nav_google": "Navigovať v Google Maps",
        "map_nav_seznam": "Navigovať v Seznam Mapy",
        "form_name": "Meno",
        "form_phone": "Telefón",
        "form_email": "E-mail",
        "form_buyer": "Odoberáte pre",
        "form_buyer_home": "Domácnosť",
        "form_buyer_pro": "Reštauráciu, jedáleň alebo cukráreň",
        "form_products": "O ktoré zmesi máte záujem",
        "form_message": "Správa",
        "form_submit": "Odoslať správu",
        "form_sending": "Odosielam…",
        "form_success": "Ďakujeme, správa je u nás. Ozveme sa vám kvôli objednávke.",
        "form_error": "Správu sa teraz nepodarilo odoslať. Skúste to znova, alebo nám zavolajte.",
        "form_captcha": "Overenie zlyhalo. Obnovte stránku a skúste to znova.",
        "form_honeypot": "Toto pole nevyplňujte",
        "form_need_contact": "Vyplňte telefón alebo e-mail.",
        "cookie_aria": "Súhlas so súbormi cookie",
        "cookie_text": "Počítanie návštev v Google Analytics používa súbory cookie. Bez súhlasu stránka funguje rovnako. Cloudflare počíta návštevy aj bez cookie.",
        "cookie_accept": "Súhlasím",
        "cookie_essential": "Len nevyhnutné",
    },
    "meta": {
        "home_title": "Jůzlová — knedle v prášku, Kochánov Vysočina",
        "home_desc": "Rodinná dielňa v Kochánove na Vysočine. Knedle v prášku 5 kg/250 Kč, chlpaté 260 Kč, puding 60 Kč, kakao 270 Kč. Odber denne 8–19 po telefóne.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Kto sme — rodinná dielňa Jůzlová od roku 2004",
            "desc": "Rodinná dielňa v Kochánove na Vysočine od roku 2004. Rod Jůzlových, ľudia z dielne a recenzie na Google a Seznamu.",
            "h1": "Kto sme",
            "sub": "Rodinná dielňa v Kochánove na Vysočine. Zmesi vyrábame od roku 2004.",
            "body": [
                ("p", "Výrobu potravinárskych zmesí sme v malej dielni v Kochánove začali v roku 2004. Počas rokov sme citlivo upravovali receptúry, až sme dosiahli kombináciu chuti a kvality, pre ktorú nás vyhľadávajú domácnosti v Čechách aj na Morave."),
                ("p", "Dnes ako obchodná firma „Jůzlová“ stojí za dielňou rodina: Jiřina a Jiří, dcéry s partnermi a ďalšie ruky, ktoré držia výrobu, balenie aj kontakt so zákazníkmi. Kochánov je malá obec na Vysočine — korene rodu Jůzlových tu siahajú stáročia."),
                ("h2", "Náš cieľ"),
                ("p", "Držať priamy kontakt a kvalitu, ktorú by sme dali aj vlastnej rodine. Žiadny dlhý reťazec medzi dielňou a vami."),
                ("team", None),
                ("reviews", None),
            ],
        },
        "kde_nas_najdete": {
            "title": "Kde nás nájdete: Kochánov 40 a Humpolec | Jůzlová",
            "desc": "Dielňa Kochánov 40, 582 53. Druhý odber v Humpolci pri Pivovare Bernard, zadarmo po dohovore dňa a hodiny. Rozvoz po Vysočine zadarmo od 5000 Kč.",
            "h1": "Kde nás nájdete",
            "sub": "Dielňa je Kochánov 40, 582 53, 12 km od Havlíčkovho Brodu. Druhé výdajné miesto je v Humpolci, v okolí Pivovaru Bernard.",
            "body": [
                ("p", "Asi 90 % zákaziek je miestnych okolo Kochánova 40, 582 53 na Vysočine. Objednáte formulárom alebo telefónom. Vyberiete dielňu, Humpolec, alebo rozvoz."),
                ("h2", "Dielňa v Kochánove"),
                ("p", "Adresa je Kochánov 40, 582 53. Vyzdvihnutie v dielni je zadarmo. Otvorené denne 8:00–19:00 po telefóne, vrátane víkendov."),
                ("map", None),
                ("h2", "Odber v Humpolci, zadarmo"),
                ("p", "Druhé výdajné miesto je v Humpolci u dcéry majiteľky. Vyzdvihnutie je zadarmo. Miesto je v okolí Pivovaru Bernard, nie pri vrátach pivovaru. Deň a hodinu vždy dohodneme. Ulicu ani súpisné číslo tu neuvádzame."),
                ("h2", "Rozvoz"),
                ("p", "Rozvoz po Vysočine je zadarmo pri objednávkach nad 5000 Kč. Do Humpolca a Havlíčkovho Brodu zadarmo nad 1000 Kč. Do Jihlavy je rozvoz zadarmo nad 3000 Kč. Inde cenu dopravy naceníme a účtujeme vám. Môžete použiť aj vlastného dopravcu, často vyjde lacnejšie."),
                ("h2", "Možnosti doručenia"),
                ("ol", ["Vyzdvihnutie v dielni Kochánov 40, 582 53, zadarmo",
                        "Vyzdvihnutie v Humpolci v okolí Pivovaru Bernard, zadarmo, deň a hodinu dohodneme",
                        "Rozvoz po Vysočine zadarmo od 5000 Kč; do Humpolca a Havlíčkovho Brodu zadarmo od 1000 Kč; do Jihlavy zadarmo od 3000 Kč",
                        "Inde rozvoz podľa našej ponuky, alebo váš vlastný dopravca",
                        "Zásielka do DE, AT, SK, PL a k Čechom v EÚ: dopravu, balenie a poistenie platíte vy"]),
            ],
        },
        "kontakt": {
            "title": "Kontakt — Jůzlová, Kochánov 40, Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) a Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Odber tovaru aj v Humpolci.",
            "h1": "Kontakt",
            "sub": "Ozvite sa nám telefonicky alebo e-mailom — dohodneme objednávku, odber aj rozvoz.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("newsletter", None),
                ("h2", "Kde nás nájdete"),
                ("map", None),
                ("p", "Dielňa: Kochánov 40, 582 53, kraj Vysočina — 12 km od Havlíčkovho Brodu. Druhý odber je v Humpolci v okolí Pivovaru Bernard, zadarmo, deň a hodinu dohodneme."),
                ("p", "Jůzlová s.r.o. · IČO 45900124"),
            ],
        },
        "ceny": {
            "title": "Cenník knedieľ v prášku — Jůzlová Kochánov",
            "desc": "Ceny pri odbere v Kochánove 40, 582 53: knedle 250 Kč, chlpaté 260 Kč, puding 60/30 Kč, cukor 60 Kč, kakao 270 Kč.",
            "h1": "Cenník",
            "sub": "Ceny platia pri vyzdvihnutí v dielni. Kochánov 40, 582 53, Vysočina.",
            "body": [
                ("p", "Ceny platia pri vyzdvihnutí v prevádzke Jůzlová, Kochánov 40, 582 53, kraj Vysočina. Zemiakové knedle v prášku stoja 250 Kč za 5 kg, chlpaté knedle (bosáky) 260 Kč za 5 kg, vanilkový puding bez lepku 60 Kč za 1 kg alebo 30 Kč za 400 g, vanilínový cukor 60 Kč za 1 kg a kakao holandského typu 270 Kč za 500 g. Kakaový puding ako hotovú zmes nevedieme — čokoládovú chuť zmiešate z vanilkového pudingu a kakaa."),
                ("pricetable", None),
                ("p", "Tovar si vyzdvihnete v Kochánove po telefóne na +420 728 466 141 (Jiřina Jůzlová) alebo +420 607 629 931 (Jiří Jůzl), e-mail juzlj@seznam.cz. Denne 8:00–19:00 vrátane víkendov, vždy po dohode. Po dohode je odber možný aj v Humpolci. Staršie ceny z roku 2017 na internete neplatia."),
                ("h2", "Prečo sú ceny nízke"),
                ("p", "Máme vlastnú dielňu, málo vonkajších nákladov a jednoduché obaly. Priamy predaj je zhruba o 40 % lacnejší než cez prekupníkov. Vyzdvihnutím v Kochánove ušetríte dopravu. Rozvoz po Vysočine zadarmo od 5000 Kč. Do Humpolca a Havlíčkovho Brodu zadarmo od 1000 Kč. Do Jihlavy zadarmo od 3000 Kč."),
            ],
        },
        "velkoobchod": {
            "title": "Veľkoobchod — reštaurácie, pekárne, školy | Jůzlová",
            "desc": "Jůzlová dodáva reštauráciám, pekárňam, kaviarňam, školám a výrobcom zmrzliny. Cena podľa množstva. Odber v dielni, náš rozvoz, alebo váš dopravca.",
            "h1": "Veľkoobchod pre prevádzky",
            "sub": "Reštaurácie, pekárne, kaviarne, školy aj výrobcovia zmrzliny. Cenu podľa množstva dohodneme.",
            "body": [
                ("p", "Jůzlová už zásobuje množstvo reštaurácií, pekární, kaviarní a škôl. Značky zákazníkov tu nemenujeme. Asi 90 % zákaziek je miestnych okolo Kochánova 40, 582 53 na Vysočine."),
                ("b2b_showcase", None),
                ("h2", "Komu dodávame"),
                ("ul", [
                    "reštauráciám a jedálňam — knedle a puding na výdaj",
                    "pekárňam a cukrárňam — puding, vanilínový cukor, kakao",
                    "kaviarňam a coffee shopom — kakao a puding",
                    "školám — zmesi na detské jedlá",
                    "výrobcom zmrzliny — kakao holandského typu",
                ]),
                ("h2", "Cena a objednávka"),
                ("p", "Cenu podľa množstva dohodneme. Napíšte formulár s výrobkami a množstvom, alebo volajte +420 728 466 141 (Jiřina) a +420 607 629 931 (Jiří)."),
                ("h2", "Odber a doprava"),
                ("ol", [
                    "Vyzdvihnutie v dielni v Kochánove",
                    "Náš rozvoz — cenu dopravy naceníme a účtujeme vám",
                    "Váš vlastný dopravca — často vyjde lacnejšie",
                ]),
                ("p", "Do Brna je rozvoz zadarmo od objednávky nad 5000 Kč, po dohode termínu. Do Nemecka, Rakúska, Slovenska a Poľska posielame veľkoobchodné zásielky na náklady zákazníka."),
                ("form_b2b", None),
            ],
        },
        "do_eu": {
            "title": "Zásielky Čechom v EÚ — doprava na vaše náklady | Jůzlová",
            "desc": "Česi v EÚ si môžu objednať zmesi Jůzlová. Platíte dopravu, krabicu, poistenie a bublinkovú fóliu. Cenu pošleme pred odoslaním.",
            "h1": "Česi v zahraničí (EÚ)",
            "sub": "Môžete sa ozvať. Zásielku pošleme po nákupe dopravy, balenia a poistenia. Cenu uvidíte pred odoslaním.",
            "body": [
                ("p", "Česi v Európskej únii si môžu tovar Jůzlová objednať. Platíte dopravu, krabicu, poistenie a bublinkovú fóliu. Sumu pošleme pred odoslaním — nič neposielame naslepo."),
                ("p", "Najčastejšie posielame do Nemecka, Rakúska, Slovenska a Poľska. Inde v EÚ sa ozvite, nacíníme dopravu."),
                ("p", "Ceny na cenníku platia pri vyzdvihnutí v Kochánove. K zásielke sa pripočíta doprava, balenie a poistenie."),
                ("form", None),
            ],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Zemiakové knedle v prášku",
            "short": "Náš najvyhľadávanejší výrobok. Klasické knedle, šúľance, krokety aj gnocchi z jedného cesta.",
            "price": "5 kg / 250 Kč",
            "title": "Zemiakové knedle v prášku — 5 kg / 250 Kč",
            "desc": "Zemiakové cesto v prášku z múky ocenenej českou značkou kvality KLASA a sušených zemiakových vločiek. Na klasické aj plnené knedle, šúľance, krokety a gnocchi.",
            "body": [
                ("p", "Zemiakové cesto v prášku je náš najvyhľadávanejší výrobok. Používame kvalitnú pšeničnú múku ocenenú českou značkou kvality KLASA z neďalekého mlyna v Havlíčkovom Brode, ktorý vlastní a vedie naša širšia rodina; typickú chuť a konzistenciu zabezpečujú sušené zemiakové vločky."),
                ("h2", "Čo z cesta pripravíte"),
                ("ul", ["klasické zemiakové knedle k pečenému mäsu",
                        "knedle plnené mäsom alebo ovocím",
                        "šúľance s makom", "vyprážané krokety", "domáce gnocchi"]),
                ("p", "Na prirodzenej chuti spoznáte, že v ceste nie je nič navyše — len to, čo do zemiakovej knedle patrí."),
            ],
            "faq": [
                ("Ako dlho trvá príprava?", "Cesto stačí zmiešať s vodou, vytvarovať a povariť — knedle máte na stole do 20 minút."),
                ("Koľko porcií je z 5 kg balenia?", "Z päťkilogramového balenia pripravíte prílohu približne pre 60–70 porcií."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Chlpaté knedle v prášku",
            "short": "Bosáky podľa tradičnej receptúry. Hotové za 15 minút, chuťou na nerozoznanie od domácich.",
            "price": "5 kg / 260 Kč",
            "title": "Chlpaté knedle (bosáky) v prášku — 5 kg / 260 Kč",
            "desc": "Chlpaté knedle podľa tradičnej receptúry: hotové za 15 minút, obľúbené v jedálňach aj reštauráciách. Balenie 5 kg za 260 Kč.",
            "body": [
                ("p", "Chlpaté knedle v prášku (bosáky) stoja 260 Kč za 5 kg pri odbere v dielni Jůzlová, Kochánov 40, 582 53, Vysočina. Hotové sú za 15 minút: zmes zmiešate s vodou, vytvarujete a povaríte. Tradičná receptúra pre jedálne aj domácnosti. Chuťou ich nerozoznáte od knedieľ zo surových zemiakov. Objednávka na +420 728 466 141 alebo +420 607 629 931, e-mail juzlj@seznam.cz, denne 8:00–19:00 po telefóne. Kakaový puding ako hotovú zmes nevedieme."),
                ("p", "Hodia sa s kapustou a údeným, s cibuľkou a škvarkami, alebo nasladko s makom a cukrom. Cena 260 Kč platí pri odbere v Kochánove. Staršie internetové ceny z roku 2017 neplatia."),
            ],
            "faq": [
                ("K čomu sa chlpaté knedle hodia?", "Tradične sa podávajú s kapustou a údeným mäsom, s cibuľkou a škvarkami, alebo nasladko s makom a cukrom."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Vanilkový puding bez lepku",
            "short": "Kukuričný škrob bez lepku, prirodzená vanilková chuť. Na dezerty aj pečenie.",
            "price": "1 kg / 60 Kč · 400 g / 30 Kč",
            "title": "Vanilkový puding bez lepku — 1 kg / 60 Kč",
            "desc": "Instantný vanilkový puding z kukuričného škrobu bez lepku. Prirodzená chuť bez chemických príchutí, vhodný pri bezlepkovej diéte. 1 kg / 60 Kč, 400 g / 30 Kč.",
            "body": [
                ("p", "Vanilkový puding bez lepku stojí 60 Kč za 1 kg alebo 30 Kč za 400 g pri odbere v Jůzlovej, Kochánov 40, 582 53. Základom je kukuričný škrob bez lepku — na dezerty aj do pečenia. Kakaový puding ako hotovú zmes nepredávame. Čokoládovú chuť zmiešate z tohto vanilkového pudingu a nášho kakaa holandského typu (500 g / 270 Kč). Objednávka na +420 728 466 141 alebo +420 607 629 931, e-mail juzlj@seznam.cz, denne 8:00–19:00 po dohode."),
                ("p", "Chuť je prirodzená, bez chemických príchutí. Ceny platia pri odbere v dielni. Staršie cenníky z roku 2017 na internete neplatia."),
            ],
            "faq": [
                ("Je puding naozaj bez lepku?", "Áno. Základom je čistý kukuričný škrob, ktorý lepok neobsahuje."),
                ("Vyrábate aj čokoládový variant?", "Kakaový puding ako hotovú zmes nevedieme. Čokoládovú chuť dáte vanilkovému pudingu kakaom holandského typu, ktoré predávame samostatne."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holandského typu",
            "short": "Tmavé cukrárske kakao triedy 21 % tuku. Červenohnedá farba, krémová chuť, bez pridaného cukru.",
            "price": "500 g / 270 Kč",
            "title": "Kakao holandského typu 21 % tuku — 500 g / 270 Kč",
            "desc": "Tmavé cukrárske kakao holandského typu s 20–22 % kakaového masla. Bez pridaného cukru, vegánske, bez 14 alergénov EÚ. 500 g / 270 Kč.",
            "body": [
                ("p", "Ponúkame tmavé cukrárske kakao holandského typu — alkalizovaný prášok z bôbov Theobroma cacao, triedy 21 % tuku. Plné čokoládové telo, krémová chuť a sýta červenohnedá farba, ktorá drží v suchom stave aj v recepte."),
                ("h2", "Odkiaľ kakao prichádza"),
                ("p", "Kakaové bôby pomaly dosychajú na slnku v strednej západnej Afrike. Prirodzene kvasia v banánových listoch — tak sa rodí hlboká čokoládová chuť, ktorú alkalizáciou zjemníme do kakaa holandského typu."),
                ("h2", "Tuk 20–22 %: prečo na ňom záleží"),
                ("p", "Kakaové maslo držíme v rozmedzí 20,0–22,0 %. Je to viac tuku než pri chudých supermarketových kakaách (často 10–12 %). Viac masla znamená viac vlhkosti v ceste, okrúhlejší pocit v ústach a plnší čokoládový dojem — preto ho cukrári berú ako triedu 21 %."),
                ("h2", "Bez pridaného cukru"),
                ("p", "Cukor do kakaa nepridávame. Jediné cukry, ktoré v ňom nájdete — 0,9 g na 100 g — vznikli v kakaovom bôbe samy."),
                ("cocoa_sensory", None),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
            ],
            "showcase": {
                "sensory_h": "Chuťový profil",
                "sensory_lead": "Plná kakaová intenzita, krémová čokoládová chuť a pražené tóny. Farba je sýto červenohnedá — v prášku aj v hotovom múčniku.",
                "axes": [
                    {"label": "Intenzita", "value": 92},
                    {"label": "Krémovosť", "value": 88},
                    {"label": "Praženie", "value": 78},
                    {"label": "Farba", "value": 94},
                    {"label": "Jemnosť", "value": 86},
                ],
                "apps_h": "Kam kakao patrí",
                "apps": [
                    {"title": "Pečenie", "text": "Perník, koláče a cestá, ktoré majú ostať sýto kakaové aj po upečení."},
                    {"title": "Nápoje", "text": "Mliečne kakao a koktaily — v mlieku drží farbu aj krémovú chuť."},
                    {"title": "Krémy", "text": "Náplne, krémy a ľahké dezerty, kde chcete čokoládu bez pridaného cukru v prášku."},
                    {"title": "Posyp", "text": "Hotové rezy, rolády a bebe dezerty — tmavý, jemný prach, ktorý sa nezráža."},
                    {"title": "S vanilkovým pudingom", "text": "Zamiešajte do nášho vanilkového pudingu: vznikne čokoládový krém z jednej zmesi."},
                    {"title": "Kaše a cereálie", "text": "Raňajkové kaše a cereálie, ktoré majú chutiť po čokoláde, nie po horkom prášku."},
                ],
                "nutri_h": "Čo v kakau je",
                "nutri_lead": "Na 100 g: veľa vlákniny a bielkovín, prirodzene málo cukru, žiadny pridaný cukor.",
                "nutri_extra": "K tomu horčík 490 mg, draslík 4 400 mg a železo 31 mg na 100 g.",
                "nutri_note": "Orientačné údaje na 100 g podľa nariadenia EÚ 1169/2011. Kakao používate po lyžiciach — hodnoty na porciu sú zlomkom tabuľky.",
                "bars": [
                    {"label": "Energia", "text": "379 kcal / 1 570 kJ", "pct": 19},
                    {"label": "Tuk", "text": "21,0 g  ·  nasýtené 13,0 g", "pct": 30},
                    {"label": "Vláknina", "text": "28,4 g", "pct": 100},
                    {"label": "Bielkoviny", "text": "19,5 g", "pct": 39},
                    {"label": "Cukry", "text": "0,9 g  ·  pridané 0 g", "pct": 2},
                    {"label": "Železo", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technické údaje",
                "facts": [
                    {"label": "Kakaové maslo", "value": "20,0–22,0 %"},
                    {"label": "pH (10% roztok)", "value": "7,8–8,2"},
                    {"label": "Jemnosť", "value": "min. 99,5 % pod 75 µm"},
                    {"label": "Vlhkosť", "value": "max. 5,0 %"},
                    {"label": "Šupky", "value": "max. 1,75 %"},
                    {"label": "Alergény EÚ", "value": "žiadne zo 14"},
                    {"label": "Lepok", "value": "< 20 ppm"},
                    {"label": "Strava", "value": "vegánske, vegetariánske"},
                ],
            },
            "faq": [
                ("Čím sa líši kakao holandského typu?", "Alkalizáciou — je tmavšie, menej kyslé a lepšie sa rozpúšťa než prírodné kakao. S 20–22 % tuku patrí medzi najkvalitnejšie cukrárske kakaá."),
                ("Pridávate cukor?", "Nie. Pridaný cukor je 0 g. Prirodzené cukry z bôbu sú 0,9 g na 100 g."),
                ("Je kakao bez lepku a alergénov?", "Áno. Neobsahuje žiadny zo 14 alergénov EÚ. Lepok je pod 20 ppm. Je vegánske a vegetariánske — bez surovín živočíšneho pôvodu."),
                ("Ako kakao skladovať?", "V suchu, mimo silných pachov, ideálne pri 15–20 °C a vlhkosti pod 50 %."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilínový cukor",
            "short": "Jemne mletý cukor s vanilínovou arómou. Do cesta aj na posypanie pečiva.",
            "price": "1 kg / 60 Kč",
            "title": "Vanilínový cukor — 1 kg / 60 Kč",
            "desc": "Vanilínový cukor z jemne mletého cukru s vanilínovou arómou. Na koláče, zákusky aj vianočné pečivo — do cesta aj na posyp. 1 kg / 60 Kč.",
            "body": [
                ("p", "Vanilínový cukor stojí 60 Kč za 1 kg pri odbere v dielni Jůzlová, Kochánov 40, 582 53, Vysočina. Jemne mletý cukor s vanilínovou arómou — do cesta aj na posyp, nie struk vanilky. Objednávka na +420 728 466 141 (Jiřina) alebo +420 607 629 931 (Jiří), e-mail juzlj@seznam.cz, denne 8:00–19:00 po telefóne. Nie je to kakaový puding; ten ako hotovú zmes nevedieme."),
                ("p", "Hodí sa do koláčov, zákuskov a vianočného pečiva. Cena 60 Kč platí pri odbere v Kochánove. Staršie ceny z roku 2017 neplatia."),
            ],
            "faq": [
                ("Hodí sa vanilínový cukor do vianočného pečiva?",
                 "Áno. Do cesta aj na posyp hotového pečiva. Balenie 1 kg / 60 Kč."),
                ("Je to vanilka, alebo vanilín?",
                 "Vanilínový cukor: jemne mletý cukor s vanilínovou arómou, nie struk vanilky."),
            ],
        },
    },
    "recipes_intro": "Vyskúšajte osvedčené recepty z našich zmesí — od nedeľných knedieľ po nepečené dezerty.",
    "faq_page": {
        "title": "Časté otázky — objednávky, dodanie, zmesi Jůzlová",
        "desc": "Odpovede o Jůzlovej: kde sídlime, ako objednať, ceny, bezlepkový puding, kakao holandského typu a rozvoz na Vysočine.",
        "h1": "Časté otázky",
        "sub": "Krátke, priame odpovede — pre ľudí, Google, Seznam.cz aj jazykové modely.",
    },
    "recipes": {},
}
