# English content — full translation of content_cs.py.
LANG = {
    "code": "en",
    "locale": "en_US",
    "name": "English",
    "ui": {
        "nav_home": "Home", "nav_about": "About us", "nav_delivery": "Delivery",
        "nav_products": "Products", "nav_prices": "Price list", "nav_recipes": "Recipes",
        "nav_contact": "Contact",
        "brand_tag": "food mixes · Vysočina, Czechia",
        "workshop_caption": "Our workshop in Kochánov — flour sacks, the scale and the bagging line.",
        "est": "Family workshop · Kochánov · since 2004",
        "hero_h1": "Dumplings like grandma's. Ready in 15 minutes.",
        "hero_lead": "Honest food mixes from the Czech Highlands — potato dumpling doughs, puddings, vanilla sugar and cocoa. Made with KLASA-awarded flour, with no compromise on quality.",
        "hero_cta": "Try a free sample",
        "hero_cta2": "Our products",
        "sec_products": "Our products", "sec_products_kicker": "What we make",
        "sec_products_lead": "Five mixes we have supplied to households, restaurants, canteens and pastry shops across Bohemia and Moravia since 2004.",
        "sec_recipes": "Recipes from our mixes", "sec_recipes_kicker": "Kitchen inspiration",
        "sec_recipes_lead": "Proven recipes you can make from our mixes quickly and without extra work.",
        "sec_why": "Why Jůzlová", "sec_why_kicker": "Family production",
        "why_1_h": "Ingredients we know by name",
        "why_1_p": "Our KLASA-awarded wheat flour comes from a mill in Havlíčkův Brod, 12 km from our workshop. The corn starch in our puddings is gluten-free.",
        "why_2_h": "Speed without compromise",
        "why_2_p": "Hairy dumplings (bosáky) are ready in 15 minutes — and you won't tell them apart from dumplings made the traditional way all afternoon.",
        "why_3_h": "Priced below the supermarket",
        "why_3_p": "We make quality that costs less than supermarket products of uncertain origin. Potato dumplings: 5 kg for 165 CZK.",
        "cta_sample_h": "Would you like a taste?",
        "cta_sample_p": "Get in touch — we'll gladly prepare a free sample. Pick your order up in Kochánov or Humpolec, or we'll deliver it to you.",
        "cta_sample_btn": "Ask for a sample",
        "full_price_list": "Full price list",
        "all_recipes": "All recipes",
        "detail": "More",
        "price_label": "Price",
        "package_label": "Package",
        "order_info": "How to order",
        "breadcrumb_home": "Home",
        "footer_products": "Products", "footer_recipes": "Recipes", "footer_company": "Company",
        "footer_note": "Family production of food mixes since 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina, Czech Republic",
        "open_hours": "Open daily by phone arrangement, 8:00–19:00 (weekends included)",
        "lang_label": "Language",
        "recipe_meta": "A recipe from the Jůzlová workshop",
        "uses_product": "Mix used",
    },
    "meta": {
        "home_title": "Jůzlová — honest Czech food mixes from Vysočina | dumplings, puddings, cocoa",
        "home_desc": "Family production of food mixes since 2004: potato and hairy dumpling mixes, gluten-free vanilla and cocoa pudding, vanilla sugar and Dutch-process cocoa. Kochánov, Vysočina, Czech Republic.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "About us — family mix production since 2004",
            "desc": "We started making food mixes in 2004 in a small workshop in Kochánov, Vysočina. Today we supply households, restaurants, canteens and pastry shops across Bohemia and Moravia.",
            "h1": "About us",
            "sub": "A family workshop in Kochánov in the Czech Highlands. Making food mixes since 2004.",
            "body": [
                ("p", "We began producing food mixes in a small workshop in Kochánov in 2004. Over the years we carefully refined our recipes and chose the best ingredient suppliers, until we reached a combination of taste and quality that customers across Bohemia and Moravia now seek out."),
                ("p", "Today, trading as \"Jůzlová\", we supply not only households but also many restaurants, canteens and pastry shops. Our customers value above all the traditional home-made taste — and the speed with which our instant mixes turn into excellent side dishes and desserts."),
                ("h2", "Potato dough mix — our most sought-after product"),
                ("p", "We make it with quality wheat flour awarded the Czech KLASA mark, from a nearby mill in Havlíčkův Brod. Dried potato flakes give it its typical taste and characteristic texture. The dough suits classic potato dumplings, dumplings filled with meat or fruit, poppy-seed rolls, croquettes and gnocchi."),
                ("h2", "Gluten-free puddings"),
                ("p", "Our instant vanilla and chocolate puddings are ideal for light desserts. The base is quality corn starch, which contains no gluten — so the puddings suit a gluten-free diet too. Into the cocoa pudding we blend high-quality Dutch-process cocoa with 21% fat for a pronounced chocolate taste."),
                ("h2", "Our goal"),
                ("p", "To make food mixes of the highest quality at a price below supermarket products of uncertain origin. We use ingredients of the highest grade, because we believe our customers deserve only the best. We insist on direct contact with our customers and always adapt to their needs."),
                ("p", "Would you like a taste? Get in touch — we'll gladly offer you a free sample."),
            ],
        },
        "kde_nas_najdete": {
            "title": "Delivery and pick-up points — Kochánov, Humpolec and local delivery",
            "desc": "Free pick-up in Kochánov or Humpolec, free delivery around Havlíčkův Brod, Světlá nad Sázavou and Jihlava, or shipping by a carrier of your choice.",
            "h1": "Delivery",
            "sub": "Our workshop is in Kochánov, 12 km from Havlíčkův Brod. We're available every day from 8:00 to 19:00, weekends included.",
            "body": [
                ("p", "We know that alongside quality, price matters to our customers. Because carrier fees can make our products more expensive, we offer pick-up directly at our premises in Kochánov. Just let us know in advance and we'll have your order ready any time."),
                ("p", "By prior arrangement you can also pick up your order in Humpolec. We currently deliver in and around Havlíčkův Brod, Humpolec, Světlá nad Sázavou and Jihlava — and by individual arrangement we'll bring the goods right to your door."),
                ("h2", "Delivery options"),
                ("ol", ["Pick-up at our premises in Kochánov or in Humpolec — free",
                        "Free delivery around Havlíčkův Brod, Světlá nad Sázavou and Jihlava",
                        "A carrier of your choice (shipping per the carrier's price list)"]),
                ("h2", "When to stop by"),
                ("p", "Open daily by phone arrangement: Monday–Saturday, 8:00–19:00."),
            ],
        },
        "kontakt": {
            "title": "Contact — Jůzlová, Kochánov 40, Vysočina, Czech Republic",
            "desc": "Jiřina Jůzlová (+420 728 466 141) and Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Pick-up also available in Humpolec.",
            "h1": "Contact",
            "sub": "Call or e-mail us — we'll arrange a free sample, pick-up or delivery.",
            "body": [
                ("contacts", None),
                ("h2", "Where to find us"),
                ("p", "Premises: Kochánov 40, 582 53, Vysočina Region, Czech Republic — 12 km from Havlíčkův Brod. By prior arrangement, pick-up is also possible in Humpolec."),
                ("p", "Jůzlová s.r.o. · Company ID (IČO) 45900124"),
            ],
        },
        "ceny": {
            "title": "Price list — dumpling mixes, puddings, vanilla sugar, cocoa",
            "desc": "Current prices: potato dumplings 5 kg / 165 CZK, hairy dumplings 5 kg / 185 CZK, vanilla pudding from 17 CZK, cocoa pudding from 22 CZK, vanilla sugar 38 CZK, cocoa 100 CZK.",
            "h1": "Price list",
            "sub": "Quality priced below the supermarket. Prices apply to pick-up in Kochánov or Humpolec.",
            "body": [("pricetable", None),
                     ("p", "For restaurants, canteens and pastry shops we prepare individual offers based on volume — get in touch.")],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Potato dumpling mix",
            "short": "Our most sought-after product. Classic dumplings, poppy-seed rolls, croquettes and gnocchi from one dough.",
            "price": "5 kg / 165 CZK",
            "title": "Potato dumpling mix — 5 kg / 165 CZK",
            "desc": "Potato dough powder made with KLASA-awarded flour and dried potato flakes. For classic and filled dumplings, poppy-seed rolls, croquettes and gnocchi.",
            "body": [
                ("p", "Potato dough powder is our most sought-after product. We use quality wheat flour awarded the KLASA mark from a nearby mill in Havlíčkův Brod; dried potato flakes provide the typical taste and texture."),
                ("h2", "What you can make from the dough"),
                ("ul", ["classic potato dumplings for roast meat",
                        "dumplings filled with meat or fruit",
                        "poppy-seed rolls (šišky s mákem)", "deep-fried croquettes", "homemade gnocchi"]),
                ("p", "The natural taste tells you there's nothing extra in the dough — only what belongs in a potato dumpling."),
            ],
            "faq": [
                ("How long does preparation take?", "Just mix the powder with water, shape and boil — dumplings are on the table within 20 minutes."),
                ("How many servings per 5 kg bag?", "One 5 kg bag makes a side dish for roughly 60–70 servings."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Hairy dumpling mix (bosáky)",
            "short": "Traditional-recipe bosáky. Ready in 15 minutes, indistinguishable from home-made.",
            "price": "5 kg / 185 CZK",
            "title": "Hairy dumpling mix (bosáky) — 5 kg / 185 CZK",
            "desc": "Hairy dumplings made to a traditional recipe: ready in 15 minutes, popular with canteens and restaurants. 5 kg bag for 185 CZK.",
            "body": [
                ("p", "Hairy dumplings, also known as bosáky, are among our most popular products. We make them to a traditional recipe."),
                ("p", "Their quick, easy preparation makes them a favourite of canteens and restaurants, and their taste and texture stand up at home too. They're ready in 15 minutes, and you won't tell them apart from dumplings made the traditional way from raw potatoes."),
            ],
            "faq": [
                ("What do hairy dumplings go with?", "Traditionally with cabbage and smoked meat, with fried onion and cracklings, or sweet with poppy seeds and sugar."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Gluten-free vanilla pudding",
            "short": "Gluten-free corn starch, natural vanilla taste. For desserts and baking.",
            "price": "1 kg / 34 CZK · 400 g / 17 CZK",
            "title": "Gluten-free vanilla pudding — 1 kg / 34 CZK",
            "desc": "Instant vanilla pudding based on gluten-free corn starch. Natural taste with no chemical off-notes, suitable for a gluten-free diet. 1 kg / 34 CZK, 400 g / 17 CZK.",
            "body": [
                ("p", "Vanilla pudding is one of our traditional products. It shines in light desserts and in baking."),
                ("p", "The base is quality corn starch, which contains no gluten — so the pudding suits a gluten-free diet. Try its natural taste, free of chemical off-notes, and you won't go back to the established supermarket brands."),
            ],
            "faq": [
                ("Is the pudding really gluten-free?", "Yes. The base is pure corn starch, which contains no gluten."),
                ("Do you make a chocolate version?", "Yes — cocoa pudding with Dutch-process cocoa (1 kg / 44 CZK, 400 g / 22 CZK)."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Dutch-process cocoa",
            "short": "Dark confectionery cocoa with 21% fat. Rich colour and taste for cakes and drinks.",
            "price": "500 g / 100 CZK",
            "title": "Dutch-process cocoa, 21% fat — 500 g / 100 CZK",
            "desc": "Dark Dutch-process confectionery cocoa with 21% fat. Gives cakes a rich cocoa colour and taste; also great for milkshakes and creams. 500 g / 100 CZK.",
            "body": [
                ("p", "We offer an excellent dark confectionery cocoa of the Dutch type with 21% fat."),
                ("p", "It stands out in cakes, giving them a rich, dark cocoa colour and flavour. It also makes delicious milkshakes and creams. The same cocoa goes into our cocoa pudding."),
            ],
            "faq": [
                ("What makes Dutch-process cocoa different?", "Alkalisation — it is darker, less acidic and dissolves better than natural cocoa. At 21% fat it ranks among the finest confectionery cocoas."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilla sugar",
            "short": "Finely ground sugar with vanillin aroma. For dough and for dusting pastries.",
            "price": "1 kg / 38 CZK",
            "title": "Vanilla sugar — 1 kg / 38 CZK",
            "desc": "Vanilla sugar made of finely ground sugar with vanillin aroma. For cakes, desserts and Christmas cookies — in the dough and as a dusting. 1 kg / 38 CZK.",
            "body": [
                ("p", "Our vanilla sugar combines finely ground sugar with a vanillin aroma that gives it a pleasant, distinctive vanilla scent."),
                ("p", "You'll appreciate it when baking cakes, desserts and other sweets. It's ideal for Christmas cookies — not only in the dough but also for dusting the finished pastry."),
            ],
            "faq": [],
        },
    },
    "recipes_intro": "Try proven recipes from our mixes — from Sunday dumplings to no-bake desserts.",
    "recipes": {},
}
