# English content — full translation of content_cs.py.
LANG = {
    "code": "en",
    "locale": "en_US",
    "name": "English",
    "ui": {
        "nav_home": "Home", "nav_about": "About", "nav_delivery": "Find us",
        "nav_products": "Products", "nav_prices": "Prices", "nav_recipes": "Recipes",
        "nav_faq": "FAQ", "nav_contact": "Contact",
        "nav_b2b": "Wholesale", "nav_d2c": "Czechs in the EU",
        "nav_aria": "Main navigation",
        "menu_open": "Open menu",
        "menu_close": "Close menu",
        "hero_img_alt": "Kochánov from the air",
        "workshop_caption": "Our workshop in Kochánov — flour sacks, the scale and the bagging line.",
        "est": "Family workshop · Kochánov · since 2004",
        "hero_h1": "Dumplings like grandma’s. Ready in 15 minutes.",
        "hero_lead": "Honest food mixes from the Czech Highlands — potato dumpling doughs, puddings, vanilla sugar and cocoa. Made with KLASA-awarded flour, with no compromise on quality.",
        "hero_cta": "Call or write",
        "hero_cta2": "Our products",
        "sec_products": "Our products", "sec_products_kicker": "What we make",
        "sec_products_lead": "Five mixes we have made for households across Bohemia and Moravia since 2004.",
        "sec_recipes": "Recipes from our mixes", "sec_recipes_kicker": "Kitchen inspiration",
        "sec_recipes_lead": "Proven recipes you can make from our mixes quickly and without extra work.",
        "sec_why": "Why Jůzlová", "sec_why_kicker": "Family production",
        "why_1_h": "Ingredients we know by name",
        "why_1_p": "Our KLASA-awarded wheat flour comes from a mill in Havlíčkův Brod, 12 km from our workshop — owned and run by our extended family. The corn starch in our puddings is gluten-free.",
        "why_2_h": "Speed without compromise",
        "why_2_p": "Hairy dumplings (bosáky) are ready in 15 minutes — and you won’t tell them apart from dumplings made the traditional way all afternoon.",
        "why_3_h": "Why our prices stay low",
        "ticker_pickup": "Prices apply at workshop pick-up",
        "why_3_p": "We work in our own workshop, keep outside costs low and use simple packaging. Selling direct is about 40% cheaper than through resellers. Pick-up in Kochánov saves delivery. Free Vysočina delivery from 5000 CZK. Free delivery to Humpolec and Havlíčkův Brod from 1000 CZK. Free delivery to Jihlava from 3000 CZK.",
        "sec_b2b": "For restaurants and kitchens",
        "sec_b2b_kicker": "Wholesale",
        "sec_b2b_lead": "We already supply many restaurants, bakeries, cafés and schools. Quantity prices are agreed case by case. We do not name customer brands here.",
        "sec_b2b_btn": "Wholesale offer",
        "sec_d2c": "Czechs living in the EU",
        "sec_d2c_kicker": "Parcels in Europe",
        "sec_d2c_lead": "You can enquire. You pay shipping, boxing, insurance and bubble wrap. We quote the cost before we send.",
        "sec_d2c_btn": "How we ship in the EU",
        "nl_h": "News and recipes by e-mail",
        "nl_kicker": "Newsletter",
        "nl_lead": "Up to 7 new recipes a week using our mixes: traditional Czech, quick, seasonal (Christmas, Easter, summer, winter), European, and restaurant / Instagram-style.",
        "nl_consent": "I agree to receive news by e-mail. The address goes to Jůzlová, juzlj@seznam.cz. You can withdraw consent by e-mail.",
        "nl_submit": "Subscribe",
        "nl_success": "Thank you. You are subscribed to the news.",
        "nl_need_email": "Enter your e-mail and tick the consent box.",
        "form_qty": "Quantity (packs or kg)",
        "form_fulfill": "How you want the goods",
        "form_fulfill_factory": "Pick-up at the Kochánov 40, 582 53 workshop",
        "form_fulfill_humpolec": "Pick-up in Humpolec near Pivovar Bernard (free; we agree the day and time)",
        "form_fulfill_delivery": "Delivery (free in Vysočina from 5000 CZK; Humpolec and Havlíčkův Brod from 1000 CZK; Jihlava from 3000 CZK; otherwise we quote)",
        "cta_sample_h": "Ready to order?",
        "cta_sample_p": "Call or write — pick up in Kochánov or Humpolec, or we’ll deliver to you.",
        "cta_sample_btn": "Call or write",
        "full_price_list": "Full price list",
        "all_recipes": "All recipes",
        "carousel_label": "Featured recipes",
        "carousel_prev": "Previous recipe",
        "carousel_next": "Next recipe",
        "carousel_status": "Recipe {current} of {total}: {name}",
        "carousel_goto": "Go to recipe {n}: {name}",
        "faq_b2b_hint": "Kitchens and shops: wholesale FAQs live only on the Wholesale page.",
        "all_faq": "All frequently asked questions",
        "sec_faq": "Frequently asked questions",
        "sec_faq_kicker": "Short answers",
        "sec_faq_lead": "The questions people and search engines ask first — who we are, how to order, and what we make.",
        "rate_label": "Rate this recipe",
        "rate_count": "{n} ratings",
        "rate_star": "Rate {n} out of 5",
        "rate_thanks": "Thank you. Your rating is saved.",
        "rate_already": "You have already rated this recipe.",
        "rate_error": "We could not save the rating just now. Please try again.",
        "detail": "More",
        "price_label": "Price",
        "package_label": "Package",
        "price_board_label": "Pick-up prices at the workshop",
        "price_pickup_badge": "Workshop price",
        "compare_kicker": "Comparison",
        "compare_h2": "Comparing price with supermarket?",
        "compare_lead": "A general average for the same quantity and similar higher quality. In ordinary shops, comparable goods are often about four times higher — or more.",
        "compare_us": "At our workshop",
        "compare_shop": "Typical supermarket (estimate)",
        "compare_factor": "About 4×",
        "compare_keep": "you keep roughly",
        "compare_note": "This is a general averaged estimate, not a price from a named chain. Brands and quality vary. Our figures are workshop pick-up prices for the goods only — shipping is separate.",
        "reviews_kicker": "Ratings",
        "reviews_h2": "Google and Seznam reviews",
        "reviews_lead": "Star ratings come from the live Google Maps and Seznam Firmy.cz profiles. Click through to see the current reviews.",
        "reviews_google": "Google",
        "reviews_seznam": "Seznam",
        "reviews_open": "Open reviews",
        "reviews_count": "{n} reviews",
        "reviews_rating_of": "{rating} out of 5",
        "reviews_note": "Numbers refresh when we rebuild the site. Google Maps and Firmy.cz remain the source of truth.",
        "team_kicker": "People",
        "team_h2": "The family behind the mixes",
        "team_lead": "Who stands behind the mixes — you’ll meet us here.",
        "team_photo_note": "Real photos will follow. Neutral placeholder portraits stand in for now.",
        "b2b_vis_1_h": "For kitchens",
        "b2b_vis_1_p": "Restaurants, canteens, bakeries, cafés, schools and ice-cream makers — the same five mixes, price by quantity.",
        "b2b_vis_2_h": "Three ways to receive",
        "b2b_vis_2_p": "Pick-up in Kochánov, our delivery, or your courier. We agree the time by phone or form.",
        "b2b_vis_3_h": "Brno free from 5000 CZK",
        "b2b_vis_3_p": "Delivery to Brno is free for orders over 5000 CZK, by arrangement. The Moravian run is separate from Prague.",
        "b2b_vis_4_h": "No rate card online",
        "b2b_vis_4_p": "Wholesale price comes after you enquire. We do not name kitchen brands on the site.",
        "b2b_brno_free": "Brno: free delivery for orders over 5000 CZK, by arrangement.",
        "order_info": "How to order",
        "breadcrumb_home": "Home",
        "footer_products": "Products", "footer_recipes": "Recipes", "footer_company": "Company",
        "footer_note": "Family production of food mixes since 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina, Czech Republic",
        "open_hours": "Open daily by phone arrangement, 8:00–19:00 (weekends included)",
        "lang_label": "Language",
        "recipe_meta": "A recipe from the Jůzlová workshop",
        "uses_product": "Mix used",
        "more_recipes": "If you like this recipe",
        "more_recipes_kicker": "Suggested for you",
        "more_recipes_lead": "More to try — the same mix, or a similar bake.",
        "more_recipe_open": "Open recipe: {name}",
        "form_h": "Write to us",
        "form_hint": "Name plus a phone or e-mail is enough. You can also call +420 728 466 141 (Jiřina) or +420 607 629 931 (Jiří).",
        "form_google_pending": "",
        "map_title": "Map of Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_addr": "Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_open": "Open in Google Maps",
        "map_nav_google": "Navigate with Google Maps",
        "map_nav_seznam": "Navigate with Seznam Maps",
        "form_name": "Name",
        "form_phone": "Phone",
        "form_email": "E-mail",
        "form_buyer": "Who is ordering",
        "form_buyer_home": "Household",
        "form_buyer_pro": "Restaurant, canteen or pastry shop",
        "form_products": "Which mixes are you ordering",
        "form_message": "Message",
        "form_submit": "Send message",
        "form_sending": "Sending…",
        "form_success": "Thank you — we have your message. We will get back to you about your order.",
        "form_error": "We could not send the message just now. Please try again, or call us.",
        "form_captcha": "Verification failed. Refresh the page and try again.",
        "form_honeypot": "Leave this field empty",
        "form_need_contact": "Please enter a phone number or e-mail.",
        "cookie_aria": "Cookie consent",
        "cookie_text": "Google Analytics uses cookies to count visits. The site works the same without them. Cloudflare already counts visits without cookies.",
        "cookie_accept": "Accept",
        "cookie_essential": "Essential only",
    },
    "meta": {
        "home_title": "Jůzlová — potato dumpling mix, Kochánov Vysočina",
        "home_desc": "Family workshop in Kochánov, Vysočina. Dumpling mix 5 kg/250 CZK, hairy dumplings 260 CZK, pudding 60 CZK, cocoa 270 CZK. Pick-up daily 8–19 by phone.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "About us — Jůzlová family workshop since 2004",
            "desc": "A family workshop in Kochánov, Vysočina, since 2004. The Jůzl family, the people in the workshop, and reviews on Google and Seznam.",
            "h1": "About us",
            "sub": "A family workshop in Kochánov in the Czech Highlands. Food mixes since 2004.",
            "body": [
                ("p", "We began making food mixes in a small workshop in Kochánov in 2004. Over the years we carefully refined our recipes, until we reached a combination of taste and quality that households across Bohemia and Moravia now seek out."),
                ("p", "Today, trading as \"Jůzlová\", the workshop is the family: Jiřina and Jiří, their daughters and partners, and the extra hands that keep production, packing and customer contact going. Kochánov is a small village in Vysočina — the Jůzl family has roots here going back centuries."),
                ("h2", "Our goal"),
                ("p", "Keep direct contact and the quality we would give our own family. No long chain between the workshop and you."),
                ("team", None),
                ("reviews", None),
            ],
        },
        "kde_nas_najdete": {
            "title": "Find us: Kochánov 40 and Humpolec | Jůzlová",
            "desc": "Workshop Kochánov 40, 582 53. Second pick-up in Humpolec near Pivovar Bernard, free by arranged day and time. Free Vysočina delivery from 5000 CZK.",
            "h1": "Find us",
            "sub": "The workshop is Kochánov 40, 582 53, 12 km from Havlíčkův Brod. A second pick-up is in Humpolec, near Pivovar Bernard.",
            "body": [
                ("p", "About 90% of orders are local around Kochánov 40, 582 53 in Vysočina. Order by form or phone. Choose the workshop, Humpolec, or delivery."),
                ("h2", "Workshop in Kochánov"),
                ("p", "The address is Kochánov 40, 582 53. Workshop pick-up is free. Open daily 8:00–19:00 by phone, weekends included."),
                ("map", None),
                ("h2", "Pick-up in Humpolec, free"),
                ("p", "The second pick-up is in Humpolec at the owner’s daughter. Collection is free. The place is near Pivovar Bernard, not a street number on the brewery gate. We always agree the day and time. We do not publish a house number."),
                ("h2", "Delivery"),
                ("p", "Delivery across Vysočina is free on orders over 5000 CZK. Delivery to Humpolec and Havlíčkův Brod is free over 1000 CZK. Delivery to Jihlava is free over 3000 CZK. Elsewhere we quote delivery and bill it to you. You may use your own courier; that is often cheaper."),
                ("h2", "Ways to receive the goods"),
                ("ol", ["Pick-up at Kochánov 40, 582 53, free",
                        "Pick-up in Humpolec near Pivovar Bernard, free, day and time by arrangement",
                        "Free Vysočina delivery from 5000 CZK; free to Humpolec and Havlíčkův Brod from 1000 CZK; free to Jihlava from 3000 CZK",
                        "Elsewhere: our quoted delivery, or your own courier",
                        "Parcels to DE, AT, SK, PL and Czechs in the EU: you pay shipping, boxing and insurance"]),
            ],
        },
        "kontakt": {
            "title": "Contact — Jůzlová, Kochánov 40, Vysočina, Czech Republic",
            "desc": "Jiřina Jůzlová (+420 728 466 141) and Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Pick-up also available in Humpolec.",
            "h1": "Contact",
            "sub": "Call or e-mail us — we’ll arrange your order, pick-up or delivery.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("newsletter", None),
                ("h2", "Where to find us"),
                ("map", None),
                ("p", "Workshop: Kochánov 40, 582 53, Vysočina Region — 12 km from Havlíčkův Brod. Second pick-up is in Humpolec near Pivovar Bernard, free, day and time by arrangement."),
                ("p", "Jůzlová s.r.o. · Company ID (IČO) 45900124"),
            ],
        },
        "ceny": {
            "title": "Price list — dumpling mix, Kochánov Vysočina",
            "desc": "Pick-up prices at Kochánov 40, 582 53: dumpling mix 250 CZK, hairy dumplings 260 CZK, pudding 60/30 CZK, vanilla sugar 60 CZK, cocoa 270 CZK.",
            "h1": "Price list",
            "sub": "Prices apply at workshop pick-up. Kochánov 40, 582 53, Vysočina.",
            "body": [
                ("p", "Prices apply at pick-up from Jůzlová, Kochánov 40, 582 53, Vysočina, Czech Republic. Potato dumpling mix is 250 CZK per 5 kg, hairy dumplings (bosáky) 260 CZK per 5 kg, gluten-free vanilla pudding 60 CZK per 1 kg or 30 CZK per 400 g, vanilla sugar 60 CZK per 1 kg, and Dutch-process cocoa 270 CZK per 500 g. We do not sell a ready-made cocoa pudding mix — chocolate cream is vanilla pudding mixed with our cocoa."),
                ("pricetable", None),
                ("p", "Pick up in Kochánov after calling +420 728 466 141 (Jiřina Jůzlová) or +420 607 629 931 (Jiří Jůzl), or e-mail juzlj@seznam.cz. Daily 8:00–19:00 including weekends, by phone arrangement. Pick-up in Humpolec is possible by agreement. 2017 prices still shown elsewhere on the internet are not valid."),
                ("h2", "Why our prices stay low"),
                ("p", "We work in our own workshop, keep outside costs low and use simple packaging. Selling direct is about 40% cheaper than through resellers. Pick-up in Kochánov saves delivery. Free Vysočina delivery from 5000 CZK. Free delivery to Humpolec and Havlíčkův Brod from 1000 CZK. Free delivery to Jihlava from 3000 CZK."),
            ],
        },
        "velkoobchod": {
            "title": "Wholesale — restaurants, bakeries, schools | Jůzlová",
            "desc": "Jůzlová supplies restaurants, bakeries, cafés, schools and ice-cream makers. Quantity prices by discussion. Pick-up, quoted delivery, or your courier.",
            "h1": "Wholesale for professional kitchens",
            "sub": "Restaurants, bakeries, cafés, coffee shops, schools and ice-cream makers. Quantity prices by discussion.",
            "body": [
                ("p", "Jůzlová already supplies many restaurants, bakeries, cafés and schools. We do not name customer brands here. About 90% of orders are local around Kochánov 40, 582 53 in Vysočina."),
                ("b2b_showcase", None),
                ("h2", "Who we supply"),
                ("ul", [
                    "restaurants and canteens — dumplings and pudding for service",
                    "bakeries and pastry shops — pudding, vanilla sugar, cocoa",
                    "cafés and coffee shops — cocoa and pudding",
                    "schools — mixes for children’s meals",
                    "ice-cream makers — Dutch-process cocoa",
                ]),
                ("h2", "Price and order"),
                ("p", "Quantity prices are agreed by discussion. Use the form with products and quantity, or call +420 728 466 141 (Jiřina) and +420 607 629 931 (Jiří)."),
                ("h2", "Pick-up and delivery"),
                ("ol", [
                    "Pick-up at the workshop in Kochánov",
                    "Our delivery — we quote the cost and bill it to you",
                    "Your own courier — often cheaper",
                ]),
                ("p", "Delivery to Brno is free for orders over 5000 CZK, by arrangement. Wholesale parcels to Germany, Austria, Slovakia and Poland go at the customer’s expense."),
                ("form_b2b", None),
            ],
        },
        "do_eu": {
            "title": "Parcels to Czechs in the EU — you pay shipping | Jůzlová",
            "desc": "Czechs in the EU can order Jůzlová mixes. You pay shipping, boxing, insurance and bubble wrap. We quote before we send.",
            "h1": "Czechs living in the EU",
            "sub": "You can enquire. We send after you accept shipping, boxing and insurance. You see the cost before we send.",
            "body": [
                ("p", "Czechs in the European Union can order Jůzlová goods. You pay shipping, boxing, insurance and bubble wrap. We send the amount before dispatch — nothing goes out blindly."),
                ("p", "We most often ship to Germany, Austria, Slovakia and Poland. Elsewhere in the EU, write and we will quote shipping."),
                ("p", "Price-list amounts apply at pick-up in Kochánov. A parcel adds shipping, packaging and insurance."),
                ("form", None),
            ],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Potato dumpling mix",
            "short": "Our most sought-after product. Classic dumplings, poppy-seed rolls, croquettes and gnocchi from one dough.",
            "price": "5 kg / 250 CZK",
            "title": "Potato dumpling mix — 5 kg / 250 CZK",
            "desc": "Potato dough powder made with KLASA-awarded flour and dried potato flakes. For classic and filled dumplings, poppy-seed rolls, croquettes and gnocchi.",
            "body": [
                ("p", "Potato dough powder is our most sought-after product. We use quality wheat flour awarded the KLASA mark from a nearby mill in Havlíčkův Brod owned and run by our extended family; dried potato flakes provide the typical taste and texture."),
                ("h2", "What you can make from the dough"),
                ("ul", ["classic potato dumplings for roast meat",
                        "dumplings filled with meat or fruit",
                        "poppy-seed rolls (šišky s mákem)", "deep-fried croquettes", "homemade gnocchi"]),
                ("p", "The natural taste tells you there’s nothing extra in the dough — only what belongs in a potato dumpling."),
            ],
            "faq": [
                ("How long does preparation take?", "Just mix the powder with water, shape and boil — dumplings are on the table within 20 minutes."),
                ("How many servings per 5 kg bag?", "One 5 kg bag makes a side dish for roughly 60–70 servings."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Hairy dumpling mix (bosáky)",
            "short": "Traditional-recipe bosáky. Ready in 15 minutes, indistinguishable from home-made.",
            "price": "5 kg / 260 CZK",
            "title": "Hairy dumpling mix (bosáky) — 5 kg / 260 CZK",
            "desc": "Hairy dumplings made to a traditional recipe: ready in 15 minutes, popular with canteens and restaurants. 5 kg bag for 260 CZK.",
            "body": [
                ("p", "Hairy dumpling mix (bosáky) is 260 CZK per 5 kg at pick-up from Jůzlová, Kochánov 40, 582 53, Vysočina. Ready in 15 minutes: mix with water, shape and boil. We follow a traditional recipe, so canteens and home cooks both use it. You will not tell it from dumplings made from raw potatoes. Order on +420 728 466 141 or +420 607 629 931, e-mail juzlj@seznam.cz, daily 8:00–19:00 by phone. We do not sell a ready-made cocoa pudding."),
                ("p", "Serve with cabbage and smoked meat, onion and cracklings, or sweet with poppy seeds and sugar. The 260 CZK price is for workshop pick-up. 2017 internet prices are not valid."),
            ],
            "faq": [
                ("What do hairy dumplings go with?", "Traditionally with cabbage and smoked meat, with fried onion and cracklings, or sweet with poppy seeds and sugar."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Gluten-free vanilla pudding",
            "short": "Gluten-free corn starch, natural vanilla taste. For desserts and baking.",
            "price": "1 kg / 60 CZK · 400 g / 30 CZK",
            "title": "Gluten-free vanilla pudding — 1 kg / 60 CZK",
            "desc": "Instant vanilla pudding based on gluten-free corn starch. Natural taste with no chemical off-notes, suitable for a gluten-free diet. 1 kg / 60 CZK, 400 g / 30 CZK.",
            "body": [
                ("p", "Gluten-free vanilla pudding is 60 CZK per 1 kg or 30 CZK per 400 g at pick-up from Jůzlová, Kochánov 40, 582 53. The base is corn starch with no gluten — for desserts and baking. We do not sell a ready-made cocoa pudding mix. For chocolate flavour, stir this vanilla pudding with our Dutch-process cocoa (500 g / 270 CZK). Order on +420 728 466 141 or +420 607 629 931, e-mail juzlj@seznam.cz, daily 8:00–19:00 by arrangement."),
                ("p", "The taste is natural, without chemical off-notes. Prices apply at the workshop. 2017 price lists online are not valid."),
            ],
            "faq": [
                ("Is the pudding really gluten-free?", "Yes. The base is pure corn starch, which contains no gluten."),
                ("Do you make a chocolate version?", "We do not sell a ready-made cocoa pudding mix. For a chocolate taste, stir Dutch-process cocoa — sold separately — into the vanilla pudding."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Dutch-process cocoa",
            "short": "Dark confectionery cocoa, 21% fat class. Red-brown colour, creamy taste, no added sugar.",
            "price": "500 g / 270 CZK",
            "title": "Dutch-process cocoa, 21% fat — 500 g / 270 CZK",
            "desc": "Dark Dutch-process confectionery cocoa with 20–22% cocoa butter. No added sugar, vegan, free of the 14 EU allergens. 500 g / 270 CZK.",
            "body": [
                ("p", "Our dark confectionery cocoa is Dutch-process — an alkalised powder from Theobroma cacao beans, 21% fat class. Full cocoa body, a creamy chocolate taste and a deep red-brown colour that holds both dry and in the finished recipe."),
                ("h2", "Where the cocoa comes from"),
                ("p", "The beans dry slowly in the sun in Central West Africa. They ferment naturally in banana leaves — that is how the deep chocolate flavour is born, which we then soften by alkalisation into Dutch-process cocoa."),
                ("h2", "Fat 20–22%: why the range matters"),
                ("p", "We keep cocoa butter at 20.0–22.0%. That is more fat than in lean supermarket cocoas (often 10–12%). More butter means more moisture in the dough, a rounder mouthfeel and a fuller chocolate impression — the 21% class pastry cooks look for."),
                ("h2", "No added sugar"),
                ("p", "We add no sugar. The only sugars you will find — 0.9 g per 100 g — occur naturally in the cocoa bean."),
                ("cocoa_sensory", None),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
            ],
            "showcase": {
                "sensory_h": "Sensory profile",
                "sensory_lead": "Full-bodied cocoa intensity, a creamy chocolate flavour and roasted notes. The colour is a deep red-brown — in the powder and in the finished cake.",
                "axes": [
                    {"label": "Intensity", "value": 92},
                    {"label": "Creaminess", "value": 88},
                    {"label": "Roast", "value": 78},
                    {"label": "Colour", "value": 94},
                    {"label": "Softness", "value": 86},
                ],
                "apps_h": "Where it belongs",
                "apps": [
                    {"title": "Baking", "text": "Gingerbread, cakes and doughs that should stay richly cocoa-coloured after baking."},
                    {"title": "Drinks", "text": "Hot cocoa and milkshakes — it holds colour and a creamy taste in milk."},
                    {"title": "Creams", "text": "Fillings, creams and light desserts when you want chocolate without sugar in the powder."},
                    {"title": "Dusting", "text": "Finished slices, roulades and biscuit desserts — a dark, fine dust that does not clump."},
                    {"title": "With vanilla pudding", "text": "Stir it into our vanilla pudding: you get a chocolate cream from one mix."},
                    {"title": "Porridge and cereals", "text": "Breakfast bowls that should taste of chocolate, not of a bitter powder."},
                ],
                "nutri_h": "What is in the cocoa",
                "nutri_lead": "Per 100 g: plenty of fibre and protein, naturally little sugar, no added sugar.",
                "nutri_extra": "Also magnesium 490 mg, potassium 4,400 mg and iron 31 mg per 100 g.",
                "nutri_note": "Indicative values per 100 g under EU Regulation 1169/2011. You use cocoa by the spoon — a serving is a fraction of the table.",
                "bars": [
                    {"label": "Energy", "text": "379 kcal / 1,570 kJ", "pct": 19},
                    {"label": "Fat", "text": "21.0 g  ·  saturates 13.0 g", "pct": 30},
                    {"label": "Fibre", "text": "28.4 g", "pct": 100},
                    {"label": "Protein", "text": "19.5 g", "pct": 39},
                    {"label": "Sugars", "text": "0.9 g  ·  added 0 g", "pct": 2},
                    {"label": "Iron", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technical facts",
                "facts": [
                    {"label": "Cocoa butter", "value": "20.0–22.0%"},
                    {"label": "pH (10% solution)", "value": "7.8–8.2"},
                    {"label": "Fineness", "value": "min. 99.5% through 75 µm"},
                    {"label": "Moisture", "value": "max. 5.0%"},
                    {"label": "Shell", "value": "max. 1.75%"},
                    {"label": "EU allergens", "value": "none of the 14"},
                    {"label": "Gluten", "value": "< 20 ppm"},
                    {"label": "Diet", "value": "vegan, vegetarian"},
                ],
            },
            "faq": [
                ("What makes Dutch-process cocoa different?", "Alkalisation — it is darker, less acidic and dissolves better than natural cocoa. At 20–22% fat it ranks among the finest confectionery cocoas."),
                ("Do you add sugar?", "No. Added sugar is 0 g. Naturally occurring sugars from the bean are 0.9 g per 100 g."),
                ("Is it gluten-free and allergen-free?", "Yes. It contains none of the 14 EU allergens. Gluten is below 20 ppm. It is vegan and vegetarian — no ingredients of animal origin."),
                ("How should I store it?", "Dry, away from strong odours, ideally at 15–20 °C with humidity under 50%."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilla sugar",
            "short": "Finely ground sugar with vanillin aroma. For dough and for dusting pastries.",
            "price": "1 kg / 60 CZK",
            "title": "Vanilla sugar — 1 kg / 60 CZK",
            "desc": "Vanilla sugar made of finely ground sugar with vanillin aroma. For cakes, desserts and Christmas cookies — in the dough and as a dusting. 1 kg / 60 CZK.",
            "body": [
                ("p", "Vanilla sugar is 60 CZK per 1 kg at pick-up from Jůzlová, Kochánov 40, 582 53, Vysočina. It is finely ground sugar with vanillin aroma — for dough and dusting, not vanilla pods. Order on +420 728 466 141 (Jiřina) or +420 607 629 931 (Jiří), e-mail juzlj@seznam.cz, daily 8:00–19:00 by phone. This is not cocoa pudding; we do not sell a ready-made cocoa pudding mix."),
                ("p", "Use it in cakes, desserts and Christmas cookies. The 60 CZK price is for workshop pick-up. 2017 prices are not valid."),
            ],
            "faq": [
                ("Is the vanilla sugar good for Christmas cookies?",
                 "Yes. Use it in the dough and as a dusting on the finished pastry. Pack 1 kg / 60 CZK."),
                ("Is it vanilla bean or vanillin?",
                 "Vanilla sugar: finely ground sugar with vanillin aroma, not vanilla pods."),
            ],
        },
    },
    "recipes_intro": "Try proven recipes from our mixes — from Sunday dumplings to no-bake desserts.",
    "faq_page": {
        "title": "FAQ — ordering, delivery and Jůzlová mixes",
        "desc": "Answers about Jůzlová: where we are, how to order, prices, gluten-free pudding, Dutch-process cocoa and Vysočina delivery.",
        "h1": "Frequently asked questions",
        "sub": "Short, direct answers — for people, Google, Seznam.cz and language models.",
    },
    "recipes": {},
}
