# Czech content — source of truth. Recovered from the last-live site where possible.
LANG = {
    "code": "cs",
    "locale": "cs_CZ",
    "name": "Čeština",
    "ui": {
        "nav_home": "Úvod", "nav_about": "Kdo jsme", "nav_delivery": "Dodání zboží",
        "nav_products": "Produkty", "nav_prices": "Ceník", "nav_recipes": "Recepty",
        "nav_contact": "Kontakt",
        "nav_aria": "Hlavní navigace",
        "skip_label": "Přeskočit na obsah",
        "menu_open": "Otevřít menu",
        "menu_close": "Zavřít menu",
        "hero_img_alt": "Kochánov z ptačí perspektivy",
        "brand_tag": "potravinářské směsi · Vysočina",
        "workshop_caption": "Naše dílna v Kochánově — pytle s moukou, váha a balicí linka.",
        "est": "Rodinná dílna · Kochánov · od roku 2004",
        "hero_h1": "Knedlíky jako od babičky. Hotové za 15 minut.",
        "hero_lead": "Poctivé potravinářské směsi z Vysočiny — bramborová těsta, pudingy, vanilínový cukr a kakao. Z mouky oceněné značkou KLASA, bez kompromisů v kvalitě.",
        "hero_cta": "Zavolejte nebo napište",
        "hero_cta2": "Naše produkty",
        "sec_products": "Naše produkty", "sec_products_kicker": "Co vyrábíme",
        "sec_products_lead": "Šest směsí, které od roku 2004 dodáváme domácnostem, restauracím, jídelnám i cukrárnám v Čechách i na Moravě.",
        "sec_recipes": "Recepty z našich směsí", "sec_recipes_kicker": "Inspirace do kuchyně",
        "sec_recipes_lead": "Osvědčené recepty, které z našich směsí připravíte rychle a bez práce navíc.",
        "sec_why": "Proč Jůzlová", "sec_why_kicker": "Rodinná výroba",
        "why_1_h": "Suroviny, které známe jménem",
        "why_1_p": "Pšeničná mouka oceněná značkou KLASA pochází z mlýna v Havlíčkově Brodě, 12 km od naší dílny. Kukuřičný škrob v pudincích neobsahuje lepek.",
        "why_2_h": "Rychlost bez kompromisů",
        "why_2_p": "Chlupaté knedlíky máte hotové za 15 minut — a chutí je nerozeznáte od knedlíků připravovaných celé odpoledne.",
        "why_3_h": "Cena pod úrovní supermarketu",
        "why_3_p": "Vyrábíme kvalitu za cenu nižší než „supermarketové“ výrobky nejistého původu. Bramborové knedlíky: 5 kg za 165 Kč.",
        "cta_sample_h": "Chcete objednat?",
        "cta_sample_p": "Zavolejte nebo napište — zboží si vyzvednete v Kochánově či Humpolci, nebo je přivezeme až k vám.",
        "cta_sample_btn": "Zavolejte nebo napište",
        "full_price_list": "Kompletní ceník",
        "all_recipes": "Všechny recepty",
        "detail": "Více",
        "price_label": "Cena",
        "package_label": "Balení",
        "order_info": "Jak objednat",
        "breadcrumb_home": "Úvod",
        "footer_products": "Produkty", "footer_recipes": "Recepty", "footer_company": "Firma",
        "footer_note": "Rodinná výroba potravinářských směsí od roku 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina",
        "open_hours": "Otevřeno denně po telefonické domluvě, 8:00–19:00 (včetně víkendů)",
        "lang_label": "Jazyk",
        "recipe_meta": "Recept z dílny Jůzlová",
        "uses_product": "Použitá směs",
        "form_h": "Napište nám",
        "form_hint": "Formulář je nativní Google Form. Odpovědi přijdou na e-mail, který máte v Google Forms nastavený (juzlj@seznam.cz).",
        "form_google_pending": "Google Form ještě není napojený. Zavolejte +420 728 466 141, nebo v Google Forms (Odeslat → Vložit) zkopírujte adresu iframe a nastavte GOOGLE_FORM_EMBED_URL.",
        "form_name": "Jméno",
        "form_phone": "Telefon",
        "form_email": "E-mail",
        "form_products": "O které směsi máte zájem",
        "form_message": "Zpráva",
        "form_submit": "Odeslat zprávu",
        "form_sending": "Odesílám…",
        "form_success": "Děkujeme, zpráva je u nás. Ozveme se vám kvůli objednávce.",
        "form_error": "Zprávu se teď nepodařilo odeslat. Zkuste to znovu, nebo nám zavolejte.",
        "form_captcha": "Ověření se nezdařilo. Obnovte stránku a zkuste to znovu.",
        "form_honeypot": "Toto pole nevyplňujte",
    },
    "meta": {
        "home_title": "Jůzlová — poctivé potravinářské směsi z Vysočiny | knedlíky, pudingy, kakao",
        "home_desc": "Rodinná výroba potravinářských směsí od roku 2004: bramborové a chlupaté knedlíky v prášku, vanilkový a kakaový puding bez lepku, vanilínový cukr a kakao holandského typu. Kochánov, Vysočina.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Kdo jsme — rodinná výroba směsí od roku 2004",
            "desc": "Výrobu potravinářských směsí jsme zahájili v roce 2004 v malé dílně v Kochánově na Vysočině. Dodáváme domácnostem, restauracím, jídelnám a cukrárnám v Čechách i na Moravě.",
            "h1": "Kdo jsme",
            "sub": "Rodinná dílna v Kochánově na Vysočině. Potravinářské směsi vyrábíme od roku 2004.",
            "body": [
                ("p", "Výrobu potravinářských směsí jsme v malé dílně v Kochánově zahájili v roce 2004. Během let jsme citlivě upravovali receptury a vybírali nejkvalitnější dodavatele surovin, až jsme dosáhli jedinečné kombinace chuti a kvality, kvůli které nás vyhledávají zákazníci v Čechách i na Moravě."),
                ("p", "Dnes jako obchodní firma „Jůzlová“ dodáváme nejen do domácností, ale do řady restaurací, jídelen a cukráren. Naši zákazníci oceňují především tradiční domácí chuť a zároveň rychlost, se kterou je možné z našich instantních výrobků připravit výborné přílohy a dezerty."),
                ("h2", "Bramborové těsto v prášku — náš nejvyhledávanější výrobek"),
                ("p", "Při jeho výrobě používáme kvalitní a značkou KLASA oceněnou pšeničnou mouku z blízkého mlýna v Havlíčkově Brodě. Typickou chuť a charakteristickou konzistenci zajišťují sušené bramborové vločky. Těsto se hodí pro přípravu bramborových knedlíků, ať už klasických, plněných masem nebo ovocem, šišek, kroket či gnocchi."),
                ("h2", "Pudingy bez lepku"),
                ("p", "Instantní vanilkový a čokoládový puding je skvělý na přípravu sladkých dezertů. Základem je kvalitní kukuřičný škrob, který neobsahuje lepek, takže je vhodný i pro bezlepkovou dietu. Do kakaového pudingu mícháme vysoce kvalitní kakao holandského typu s 21 % tuku, které dodává výraznou čokoládovou chuť."),
                ("h2", "Náš cíl"),
                ("p", "Vyrábět potravinářské směsi nejvyšší kvality za cenu pod úrovní „supermarketových“ výrobků nejistého původu. Používáme suroviny nejvyšší jakosti, protože věříme, že naši zákazníci si zaslouží jen to nejlepší. Klademe důraz na přímý kontakt se zákazníky a vždy se snažíme přizpůsobit jejich potřebám."),
                ("p", "Chcete objednat? Ozvěte se — domluvíme odběr v Kochánově či Humpolci, nebo rozvoz."),
            ],
        },
        "kde_nas_najdete": {
            "title": "Dodání zboží a odběrná místa — Kochánov, Humpolec a rozvoz",
            "desc": "Vyzvednutí zdarma v Kochánově nebo Humpolci, bezplatný rozvoz v okolí Havlíčkova Brodu, Světlé nad Sázavou a Jihlavy, nebo zaslání smluvním dopravcem.",
            "h1": "Dodání zboží",
            "sub": "Naše dílna je v Kochánově, 12 km od Havlíčkova Brodu. Jsme vám k dispozici každý den od 8:00 do 19:00, včetně víkendů.",
            "body": [
                ("p", "Uvědomujeme si, že pro naše zákazníky je vedle vysoké kvality výrobků důležitá i cena. Protože ceny smluvních dopravců mohou naše výrobky prodražit, nabízíme možnost vyzvednutí zboží přímo u nás v provozovně v Kochánově. Stačí se předem ozvat a zboží vám kdykoli připravíme k odběru."),
                ("p", "Po předchozí domluvě si zboží můžete vyzvednout také v Humpolci. V současné době rozvážíme v Havlíčkově Brodě, Humpolci, Světlé nad Sázavou, Jihlavě a okolí — a po individuální domluvě přivezeme zboží i přímo k vám domů."),
                ("h2", "Možnosti doručení"),
                ("ol", ["Vyzvednutí zboží na provozovně v Kochánově nebo v Humpolci — zdarma",
                        "Bezplatný závoz zboží v okolí Havlíčkova Brodu, Světlé nad Sázavou a Jihlavy",
                        "Smluvní dopravce dle vašeho výběru (poštovné dle ceníku dopravce)"]),
                ("h2", "Kdy se můžete zastavit"),
                ("p", "Otevřeno denně po telefonické domluvě: pondělí–neděle 8:00–19:00."),
            ],
        },
        "kontakt": {
            "title": "Kontakt — Jůzlová, Kochánov 40, Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) a Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Odběr zboží také v Humpolci.",
            "h1": "Kontakt",
            "sub": "Ozvěte se nám telefonicky nebo e-mailem — domluvíme objednávku, odběr i rozvoz.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("h2", "Kde nás najdete"),
                ("p", "Provozovna: Kochánov 40, 582 53, kraj Vysočina — 12 km od Havlíčkova Brodu. Po předchozí domluvě je možné vyzvednutí zboží také v Humpolci."),
                ("p", "Jůzlová s.r.o. · IČO 45900124"),
            ],
        },
        "ceny": {
            "title": "Ceník potravinářských směsí — knedlíky, pudingy, cukr, kakao",
            "desc": "Aktuální ceny: bramborové knedlíky 5 kg / 165 Kč, chlupaté knedlíky 5 kg / 185 Kč, vanilkový puding od 17 Kč, kakaový puding od 22 Kč, vanilínový cukr 38 Kč, kakao 100 Kč.",
            "h1": "Ceník",
            "sub": "Kvalita za cenu pod úrovní supermarketu. Ceny platí při odběru v Kochánově či Humpolci.",
            "body": [("pricetable", None),
                     ("p", "Pro restaurace, jídelny a cukrárny připravíme individuální nabídku podle odebíraného množství — ozvěte se nám.")],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Bramborové knedlíky v prášku",
            "short": "Náš nejvyhledávanější výrobek. Klasické knedlíky, šišky, krokety i gnocchi z jednoho těsta.",
            "price": "5 kg / 165 Kč",
            "title": "Bramborové knedlíky v prášku — 5 kg / 165 Kč",
            "desc": "Bramborové těsto v prášku z mouky oceněné značkou KLASA a sušených bramborových vloček. Na knedlíky klasické i plněné, šišky s mákem, krokety a gnocchi.",
            "body": [
                ("p", "Bramborové těsto v prášku je náš nejvyhledávanější výrobek. Používáme kvalitní pšeničnou mouku oceněnou značkou KLASA z blízkého mlýna v Havlíčkově Brodě; typickou chuť a konzistenci zajišťují sušené bramborové vločky."),
                ("h2", "Co z těsta připravíte"),
                ("ul", ["klasické bramborové knedlíky k pečenému masu",
                        "knedlíky plněné masem nebo ovocem",
                        "šišky s mákem", "fritované krokety", "domácí gnocchi"]),
                ("p", "Na přirozené chuti poznáte, že v těstě není nic navíc — jen to, co do bramborového knedlíku patří."),
            ],
            "faq": [
                ("Jak dlouho trvá příprava?", "Těsto stačí smíchat s vodou, vytvarovat a povařit — knedlíky máte na stole do 20 minut."),
                ("Kolik porcí je z 5kg balení?", "Z pětikilogramového balení připravíte přílohu zhruba pro 60–70 porcí."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Chlupaté knedlíky v prášku",
            "short": "Bosáky podle tradiční receptury. Hotové za 15 minut, chutí k nerozeznání od domácích.",
            "price": "5 kg / 185 Kč",
            "title": "Chlupaté knedlíky (bosáky) v prášku — 5 kg / 185 Kč",
            "desc": "Chlupaté knedlíky podle tradiční receptury: za 15 minut hotové, oblíbené v jídelnách i restauracích. Balení 5 kg za 185 Kč.",
            "body": [
                ("p", "Chlupaté knedlíky, známé také jako bosáky, patří mezi naše nejoblíbenější výrobky. Vyrábíme je podle tradiční receptury."),
                ("p", "Pro rychlou a snadnou přípravu jsou oblíbené v jídelnách a restauracích, ale svou chutí a konzistencí obstojí i v domácnostech. Hotové jsou za 15 minut a jejich chuť nerozeznáte od knedlíků připravovaných tradičním způsobem ze syrových brambor."),
            ],
            "faq": [
                ("K čemu se chlupaté knedlíky hodí?", "Tradičně se podávají se zelím a uzeným masem, s cibulkou a škvarky, nebo sladce s mákem a cukrem."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Vanilkový puding bez lepku",
            "short": "Kukuřičný škrob bez lepku, přirozená vanilková chuť. Na dezerty i pečení.",
            "price": "1 kg / 34 Kč · 400 g / 17 Kč",
            "title": "Vanilkový puding bez lepku — 1 kg / 34 Kč",
            "desc": "Instantní vanilkový puding z kukuřičného škrobu bez lepku. Přirozená chuť bez chemických odstínů, vhodný i pro bezlepkovou dietu. 1 kg / 34 Kč, 400 g / 17 Kč.",
            "body": [
                ("p", "Vanilkový puding patří mezi naše tradiční produkty. Skvěle se uplatní při přípravě lehkých dezertů i při pečení."),
                ("p", "Základem je kvalitní kukuřičný škrob, který neobsahuje lepek — puding je proto vhodný i pro bezlepkovou dietu. Vyzkoušejte jeho přirozenou chuť bez chemických odstínů a k zavedeným „supermarketovým“ značkám už se nevrátíte."),
            ],
            "faq": [
                ("Je puding opravdu bez lepku?", "Ano. Základem je čistý kukuřičný škrob, který lepek neobsahuje."),
                ("Vyrábíte i čokoládovou variantu?", "Ano — kakaový puding s kakaem holandského typu (1 kg / 44 Kč, 400 g / 22 Kč). Má vlastní stránku v ceníku a v menu Produkty."),
            ],
        },
        "kakaovy_pudink": {
            "name": "Kakaový puding bez lepku",
            "short": "Hotový za pět minut. Lehký dezert, dietní krémy i pečení — s kakaem holandského typu.",
            "price": "1 kg / 44 Kč · 400 g / 22 Kč",
            "title": "Kakaový puding bez lepku — 1 kg / 44 Kč",
            "desc": "Instantní kakaový puding z kukuřičného škrobu bez lepku a kakaa holandského typu s 21 % tuku. 1 kg / 44 Kč, 400 g / 22 Kč.",
            "body": [
                ("p", "Náš kakaový puding je hotový během pěti minut a pak skvěle poslouží jako lehký dezert, jako základ dietních krémů, nebo při pečení."),
                ("p", "Základem je kukuřičný škrob bez lepku. Do směsi mícháme totéž kakao holandského typu s 21 % tuku, které prodáváme samostatně."),
                ("h2", "Jak puding uvařit"),
                ("p", "Z půllitru mléka oddělte třetinu, rozmíchejte v ní 40 g cukru a 40 g pudingu. Zbylé mléko přiveďte k varu. Přidejte rozmíchanou směs a za stálého míchání ještě 2 minuty vařte."),
            ],
            "faq": [
                ("Je puding bez lepku?", "Ano. Základem je čistý kukuřičný škrob."),
                ("Čím se liší od vanilkového?", "Do kakaového mícháme kakao holandského typu s 21 % tuku — chuť je výrazně čokoládová."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holandského typu",
            "short": "Tmavé cukrářské kakao s 21 % tuku. Výrazná barva i chuť moučníků a koktejlů.",
            "price": "500 g / 100 Kč",
            "title": "Kakao holandského typu 21 % tuku — 500 g / 100 Kč",
            "desc": "Tmavé cukrářské kakao holandského typu s 21 % tuku. Dodá moučníkům bohatou kakaovou barvu a chuť; hodí se i na mléčné koktejly a krémy. 500 g / 100 Kč.",
            "body": [
                ("p", "Nabízíme výborné tmavé cukrářské kakao holandského typu s 21 % tuku."),
                ("p", "Skvěle se vyjímá v moučnících, kterým dodá bohatou tmavě kakaovou barvu i chuť. Připravíte z něj také chutné mléčné koktejly a krémy. Totéž kakao mícháme do našeho kakaového pudingu."),
            ],
            "faq": [
                ("Čím se liší kakao holandského typu?", "Alkalizací — je tmavší, méně kyselé a lépe se rozpouští než přírodní kakao. S 21 % tuku patří k nejkvalitnějším cukrářským kakaům."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilínový cukr",
            "short": "Jemně mletý cukr s vanilínovým aroma. Do těsta i na posyp cukroví.",
            "price": "1 kg / 38 Kč",
            "title": "Vanilínový cukr — 1 kg / 38 Kč",
            "desc": "Vanilínový cukr z jemně mletého cukru s vanilínovým aroma. Na koláče, zákusky i vánoční cukroví — do těsta i na posyp. 1 kg / 38 Kč.",
            "body": [
                ("p", "Vanilínový cukr obsahuje kromě jemně mletého cukru také vanilínové aroma, které mu dodává příjemnou, jedinečnou vůni vanilky."),
                ("p", "Oceníte jej při pečení koláčů, zákusků i ostatních dezertů. Skvěle se hodí při přípravě vánočního cukroví — nejen jako přísada do těsta, ale i pro posyp hotového cukroví."),
            ],
            "faq": [],
        },
    },
    "recipes_intro": "Vyzkoušejte osvědčené recepty z našich směsí — od nedělních knedlíků po nepečené dezerty.",
    "recipes": {},  # filled from archive after workflow completes
}
