# German content — full translation of content_cs.py (de_DE, Sie form).
LANG = {
    "code": "de",
    "locale": "de_DE",
    "name": "Deutsch",
    "ui": {
        "nav_home": "Start", "nav_about": "Über", "nav_delivery": "Standort",
        "nav_products": "Produkte", "nav_prices": "Preise", "nav_recipes": "Rezepte",
        "nav_faq": "FAQ", "nav_contact": "Kontakt",
        "nav_b2b": "Großhandel", "nav_d2c": "Tschechen in der EU",
        "nav_aria": "Hauptnavigation",
        "menu_open": "Menü öffnen",
        "menu_close": "Menü schließen",
        "hero_img_alt": "Kochánov aus der Luft",
        "workshop_caption": "Unsere Werkstatt in Kochánov — Mehlsäcke, Waage und Abfülllinie.",
        "est": "Familienbetrieb · Kochánov · seit 2004",
        "hero_h1": "Knödel wie bei Großmutter. Fertig in 15 Minuten.",
        "hero_lead": "Ehrliche Lebensmittelmischungen aus der Vysočina (Böhmisch-Mährische Höhe) — Kartoffelteige, Pudding, Vanillinzucker und Kakao. Aus Mehl mit dem tschechischen Gütesiegel KLASA, ohne Kompromisse bei der Qualität.",
        "hero_cta": "Anrufen oder schreiben",
        "hero_cta2": "Unsere Produkte",
        "sec_products": "Unsere Produkte", "sec_products_kicker": "Was wir herstellen",
        "sec_products_lead": "Fünf Mischungen, die wir seit 2004 für Haushalte in Böhmen und Mähren herstellen.",
        "sec_recipes": "Rezepte mit unseren Mischungen", "sec_recipes_kicker": "Inspiration für die Küche",
        "sec_recipes_lead": "Bewährte Rezepte, die Sie mit unseren Mischungen schnell und ohne Mehraufwand zubereiten.",
        "sec_why": "Warum Jůzlová", "sec_why_kicker": "Familienproduktion",
        "why_1_h": "Zutaten, die wir beim Namen kennen",
        "why_1_p": "Unser Weizenmehl mit dem tschechischen Gütesiegel KLASA stammt aus einer Mühle in Havlíčkův Brod, 12 km von unserer Werkstatt — im Besitz und Betrieb unserer erweiterten Familie. Die Maisstärke in unseren Puddings ist glutenfrei.",
        "why_2_h": "Schnell, ohne Kompromisse",
        "why_2_p": "Haarige Knödel (Bosáky) sind in 15 Minuten fertig — und geschmacklich nicht von Knödeln zu unterscheiden, an denen man den ganzen Nachmittag arbeitet.",
        "why_3_h": "Warum die Preise niedrig bleiben",
        "ticker_pickup": "Preise gelten bei Abholung in der Werkstatt",
        "why_3_p": "Wir fertigen in der eigenen Werkstatt, halten Fremdkosten niedrig und nutzen einfache Verpackung. Direktverkauf ist rund 40 % günstiger als über Wiederverkäufer. Abholung in Kochánov spart die Lieferung. Kostenlose Lieferung in der Vysočina ab 5000 Kč. Nach Humpolec und Havlíčkův Brod kostenlos ab 1000 Kč. Nach Jihlava kostenlos ab 3000 Kč.",
        "sec_b2b": "Für Restaurants und Betriebe",
        "sec_b2b_kicker": "Großhandel",
        "sec_b2b_lead": "Wir beliefern bereits viele Restaurants, Bäckereien, Cafés und Schulen. Mengenpreise klären wir im Gespräch. Kundennamen nennen wir hier nicht.",
        "sec_b2b_btn": "Großhandelsangebot",
        "sec_d2c": "Tschechen in der EU",
        "sec_d2c_kicker": "Paket nach Europa",
        "sec_d2c_lead": "Sie können anfragen. Sie zahlen Versand, Karton, Versicherung und Luftpolsterfolie. Die Kosten nennen wir vor dem Versand.",
        "sec_d2c_btn": "So versenden wir in die EU",
        "nl_h": "Neuigkeiten und Rezepte per E-Mail",
        "nl_kicker": "Newsletter",
        "nl_lead": "Bis zu 7 neue Rezepte pro Woche mit unseren Mischungen: traditionell tschechisch, schnell, saisonal (Weihnachten, Ostern, Sommer, Winter), europäisch und restaurant- bzw. Instagram-Stil.",
        "nl_consent": "Ich stimme dem Newsletter per E-Mail zu. Die Adresse erhält Jůzlová, juzlj@seznam.cz. Den Widerruf schicken Sie per E-Mail.",
        "nl_submit": "Anmelden",
        "nl_success": "Danke. Sie sind zum Newsletter angemeldet.",
        "nl_need_email": "Bitte E-Mail eintragen und die Einwilligung ankreuzen.",
        "form_qty": "Menge (Packungen oder kg)",
        "form_fulfill": "Wie möchten Sie die Ware",
        "form_fulfill_factory": "Abholung in der Werkstatt Kochánov 40, 582 53",
        "form_fulfill_humpolec": "Abholung in Humpolec bei Pivovar Bernard (kostenlos; Tag und Uhrzeit nach Absprache)",
        "form_fulfill_delivery": "Lieferung (Vysočina gratis ab 5000 Kč; Humpolec und Havlíčkův Brod ab 1000 Kč; Jihlava ab 3000 Kč; sonst Angebot)",
        "cta_sample_h": "Möchten Sie bestellen?",
        "cta_sample_p": "Rufen Sie an oder schreiben Sie uns — holen Sie die Ware in Kochánov oder Humpolec ab, oder wir liefern sie zu Ihnen.",
        "cta_sample_btn": "Anrufen oder schreiben",
        "full_price_list": "Komplette Preisliste",
        "all_recipes": "Alle Rezepte",
        "carousel_label": "Rezepte auf der Startseite",
        "carousel_prev": "Vorheriges Rezept",
        "carousel_next": "Nächstes Rezept",
        "carousel_status": "Rezept {current} von {total}: {name}",
        "carousel_goto": "Zum Rezept {n}: {name}",
        "faq_b2b_hint": "Betriebe und Küchen: Großhandels-FAQ nur auf der Großhandelsseite.",
        "all_faq": "Alle häufigen Fragen",
        "sec_faq": "Häufige Fragen",
        "sec_faq_kicker": "Kurz und klar",
        "sec_faq_lead": "Die Fragen, die Menschen und Suchmaschinen zuerst stellen — wer wir sind, wie man bestellt, was wir herstellen.",
        "rate_label": "Dieses Rezept bewerten",
        "rate_count": "{n} Bewertungen",
        "rate_star": "{n} von 5 bewerten",
        "rate_thanks": "Danke. Ihre Bewertung ist gespeichert.",
        "rate_already": "Sie haben dieses Rezept bereits bewertet.",
        "rate_error": "Die Bewertung konnte gerade nicht gespeichert werden. Bitte erneut versuchen.",
        "detail": "Mehr",
        "price_label": "Preis",
        "package_label": "Verpackung",
        "price_board_label": "Abholpreise in der Werkstatt",
        "price_pickup_badge": "Werkstattpreis",
        "compare_kicker": "Vergleich",
        "compare_h2": "Preisvergleich mit dem Supermarkt?",
        "compare_lead": "Ein allgemeiner Durchschnitt für die gleiche Menge und ähnliche höhere Qualität. In normalen Läden sind vergleichbare Waren oft etwa viermal teurer — oder mehr.",
        "compare_us": "Bei uns in der Werkstatt",
        "compare_shop": "Typischer Supermarkt (Schätzung)",
        "compare_factor": "Etwa 4×",
        "compare_keep": "Sie behalten etwa",
        "compare_note": "Das ist eine allgemeine Durchschnittsschätzung, kein Preis einer konkreten Kette. Marken und Qualität unterscheiden sich. Unsere Zahlen sind Abholpreise für die Ware — Versand kommt extra.",
        "reviews_kicker": "Bewertungen",
        "reviews_h2": "Google- und Seznam-Bewertungen",
        "reviews_lead": "Die Sterne stammen von den Live-Profilen Google Maps und Seznam Firmy.cz. Klicken Sie durch zu den aktuellen Bewertungen.",
        "reviews_google": "Google",
        "reviews_seznam": "Seznam",
        "reviews_open": "Bewertungen öffnen",
        "reviews_count": "{n} Bewertungen",
        "reviews_rating_of": "{rating} von 5",
        "reviews_note": "Die Zahlen werden beim Neuaufbau der Website aktualisiert. Google Maps und Firmy.cz bleiben die Quelle.",
        "team_kicker": "Menschen",
        "team_h2": "Die Familie hinter den Mischungen",
        "team_lead": "Wer hinter den Mischungen steht — hier treffen Sie uns.",
        "team_photo_note": "Echte Fotos folgen. Neutral Platzhalter-Porträts stehen vorerst.",
        "b2b_vis_1_h": "Für Küchen",
        "b2b_vis_1_p": "Restaurants, Kantinen, Bäckereien, Cafés, Schulen und Speiseeishersteller — dieselben fünf Mischungen, Preis nach Menge.",
        "b2b_vis_2_h": "Drei Wege zur Ware",
        "b2b_vis_2_p": "Abholung in Kochánov, unsere Lieferung oder Ihr Kurier. Termin telefonisch oder per Formular.",
        "b2b_vis_3_h": "Brünn gratis ab 5000 Kč",
        "b2b_vis_3_p": "Lieferung nach Brünn ist ab Bestellungen über 5000 Kč kostenlos, nach Absprache. Die mährische Tour ist getrennt von Prag.",
        "b2b_vis_4_h": "Keine Preisliste online",
        "b2b_vis_4_p": "Den Großhandelspreis nennen wir nach der Anfrage. Küchenmarken nennen wir nicht.",
        "b2b_brno_free": "Brünn: kostenlose Lieferung ab Bestellungen über 5000 Kč, nach Terminabsprache.",
        "order_info": "So bestellen Sie",
        "breadcrumb_home": "Startseite",
        "footer_products": "Produkte", "footer_recipes": "Rezepte", "footer_company": "Unternehmen",
        "footer_note": "Familienproduktion von Lebensmittelmischungen seit 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina, Tschechien",
        "open_hours": "Täglich geöffnet nach telefonischer Absprache, 8:00–19:00 Uhr (auch am Wochenende)",
        "lang_label": "Sprache",
        "recipe_meta": "Ein Rezept aus der Werkstatt Jůzlová",
        "uses_product": "Verwendete Mischung",
        "more_recipes": "Wenn Ihnen dieses Rezept gefällt",
        "more_recipes_kicker": "Passend dazu",
        "more_recipes_lead": "Weitere Rezepte mit derselben Mischung oder ähnlichem Backen.",
        "more_recipe_open": "Rezept öffnen: {name}",
        "form_h": "Schreiben Sie uns",
        "form_hint": "Name und Telefon oder E-Mail genügen. Sie erreichen uns auch unter +420 728 466 141 (Jiřina) oder +420 607 629 931 (Jiří).",
        "form_google_pending": "",
        "map_title": "Karte von Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_addr": "Juzlova - Potravinářské směsi, Kochánov 40, 582 53",
        "map_open": "In Google Maps öffnen",
        "map_nav_google": "Route in Google Maps",
        "map_nav_seznam": "Route in Seznam Mapy",
        "form_name": "Name",
        "form_phone": "Telefon",
        "form_email": "E-Mail",
        "form_buyer": "Wer bestellt",
        "form_buyer_home": "Haushalt",
        "form_buyer_pro": "Restaurant, Kantine oder Konditorei",
        "form_products": "Welche Mischungen möchten Sie bestellen",
        "form_message": "Nachricht",
        "form_submit": "Nachricht senden",
        "form_sending": "Wird gesendet…",
        "form_success": "Danke, Ihre Nachricht ist bei uns. Wir melden uns zu Ihrer Bestellung.",
        "form_error": "Die Nachricht konnte gerade nicht gesendet werden. Bitte erneut versuchen oder anrufen.",
        "form_captcha": "Die Prüfung ist fehlgeschlagen. Bitte die Seite neu laden und erneut versuchen.",
        "form_honeypot": "Dieses Feld leer lassen",
        "form_need_contact": "Bitte Telefon oder E-Mail angeben.",
        "cookie_aria": "Cookie-Einwilligung",
        "cookie_text": "Google Analytics verwendet Cookies, um Besuche zu zählen. Die Seite funktioniert ohne Zustimmung gleich. Cloudflare zählt Besuche bereits ohne Cookies.",
        "cookie_accept": "Zustimmen",
        "cookie_essential": "Nur Notwendiges",
    },
    "meta": {
        "home_title": "Jůzlová — Knödelmischung, Kochánov Vysočina",
        "home_desc": "Familienwerkstatt in Kochánov, Vysočina. Knödelmischung 5 kg/250 Kč, Haarige Knödel 260 Kč, Pudding 60 Kč, Kakao 270 Kč. Abholung täglich 8–19 telefonisch.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Über uns — Familienwerkstatt Jůzlová seit 2004",
            "desc": "Familienwerkstatt in Kochánov, Vysočina, seit 2004. Die Familie Jůzl, die Menschen in der Werkstatt und Bewertungen bei Google und Seznam.",
            "h1": "Über uns",
            "sub": "Eine Familienwerkstatt in Kochánov in der Vysočina. Mischungen seit 2004.",
            "body": [
                ("p", "Mit der Herstellung von Lebensmittelmischungen haben wir 2004 in einer kleinen Werkstatt in Kochánov begonnen. Über die Jahre haben wir unsere Rezepturen behutsam verfeinert, bis wir jene Verbindung von Geschmack und Qualität erreicht hatten, für die uns Haushalte in Böhmen und Mähren schätzen."),
                ("p", "Heute steht hinter „Jůzlová“ die Familie: Jiřina und Jiří, die Töchter mit Partnern und weitere Hände, die Produktion, Verpackung und den Kontakt zu Kunden halten. Kochánov ist ein kleines Dorf in der Vysočina — die Wurzeln der Familie Jůzl reichen hier Jahrhunderte zurück."),
                ("h2", "Unser Ziel"),
                ("p", "Direkten Kontakt und eine Qualität halten, die wir auch der eigenen Familie geben würden. Keine lange Kette zwischen Werkstatt und Ihnen."),
                ("team", None),
                ("reviews", None),
            ],
        },
        "kde_nas_najdete": {
            "title": "Standort: Kochánov 40 und Humpolec | Jůzlová",
            "desc": "Werkstatt Kochánov 40, 582 53. Zweite Abholung in Humpolec bei Pivovar Bernard, kostenlos nach Absprache von Tag und Uhrzeit. Lieferung in der Vysočina gratis ab 5000 Kč.",
            "h1": "So finden Sie uns",
            "sub": "Die Werkstatt ist Kochánov 40, 582 53, 12 km von Havlíčkův Brod. Eine zweite Abholung ist in Humpolec, in der Nähe von Pivovar Bernard.",
            "body": [
                ("p", "Etwa 90 % der Aufträge sind örtlich um Kochánov 40, 582 53 in der Vysočina. Bestellen Sie per Formular oder Telefon. Wählen Sie die Werkstatt, Humpolec oder Lieferung."),
                ("h2", "Werkstatt in Kochánov"),
                ("p", "Die Adresse ist Kochánov 40, 582 53. Die Abholung in der Werkstatt ist kostenlos. Täglich 8:00–19:00 Uhr telefonisch, auch am Wochenende."),
                ("map", None),
                ("h2", "Abholung in Humpolec, kostenlos"),
                ("p", "Die zweite Abholung ist in Humpolec bei der Tochter der Inhaberin. Die Abholung ist kostenlos. Der Ort liegt in der Nähe von Pivovar Bernard, keine genaue Hausnummer am Brauereitor. Tag und Uhrzeit vereinbaren wir immer. Eine Straßennummer nennen wir hier nicht."),
                ("h2", "Lieferung"),
                ("p", "Lieferung in der Vysočina ist ab 5000 Kč kostenlos. Nach Humpolec und Havlíčkův Brod kostenlos ab 1000 Kč. Nach Jihlava kostenlos ab 3000 Kč. Anderswo nennen wir die Lieferkosten und rechnen sie Ihnen. Sie können einen eigenen Kurier nutzen, oft günstiger."),
                ("h2", "Wege zur Ware"),
                ("ol", ["Abholung in Kochánov 40, 582 53, kostenlos",
                        "Abholung in Humpolec bei Pivovar Bernard, kostenlos, Tag und Uhrzeit nach Absprache",
                        "Kostenlose Lieferung in der Vysočina ab 5000 Kč; nach Humpolec und Havlíčkův Brod ab 1000 Kč; nach Jihlava ab 3000 Kč",
                        "Anderswo: unsere Angebotsfahrt oder Ihr eigener Kurier",
                        "Pakete nach DE, AT, SK, PL und an Tschechen in der EU: Sie zahlen Versand, Karton und Versicherung"]),
            ],
        },
        "kontakt": {
            "title": "Kontakt — Jůzlová, Kochánov 40, Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) und Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-Mail juzlj@seznam.cz. Abholung auch in Humpolec möglich.",
            "h1": "Kontakt",
            "sub": "Rufen Sie uns an oder schreiben Sie uns — wir vereinbaren Bestellung, Abholung oder Lieferung.",
            "body": [
                ("contacts", None),
                ("form", None),
                ("newsletter", None),
                ("h2", "So finden Sie uns"),
                ("map", None),
                ("p", "Werkstatt: Kochánov 40, 582 53, Region Vysočina — 12 km von Havlíčkův Brod. Zweite Abholung in Humpolec bei Pivovar Bernard, kostenlos, Tag und Uhrzeit nach Absprache."),
                ("p", "Jůzlová s.r.o. · Unternehmens-ID (IČO) 45900124"),
            ],
        },
        "ceny": {
            "title": "Preisliste — Knödelmischung, Kochánov Vysočina",
            "desc": "Abholpreise in Kochánov 40, 582 53: Knödel 250 Kč, Haarige Knödel 260 Kč, Pudding 60/30 Kč, Zucker 60 Kč, Kakao 270 Kč.",
            "h1": "Preisliste",
            "sub": "Preise gelten bei Abholung in der Werkstatt. Kochánov 40, 582 53, Vysočina.",
            "body": [
                ("p", "Die Preise gelten bei Abholung bei Jůzlová, Kochánov 40, 582 53, Vysočina, Tschechien. Kartoffelknödelmischung kostet 250 Kč je 5 kg, Haarige Knödel (Bosáky) 260 Kč je 5 kg, glutenfreier Vanillepudding 60 Kč je 1 kg oder 30 Kč je 400 g, Vanillinzucker 60 Kč je 1 kg und Kakao holländischer Art 270 Kč je 500 g. Einen fertigen Kakaopudding verkaufen wir nicht — Schokocreme entsteht aus Vanillepudding plus unserem Kakao."),
                ("pricetable", None),
                ("p", "Abholung in Kochánov nach Anruf unter +420 728 466 141 (Jiřina Jůzlová) oder +420 607 629 931 (Jiří Jůzl), E-Mail juzlj@seznam.cz. Täglich 8:00–19:00 Uhr einschließlich Wochenende, nach telefonischer Absprache. Abholung in Humpolec nach Vereinbarung. Internetpreise von 2017 gelten nicht."),
                ("h2", "Warum die Preise niedrig bleiben"),
                ("p", "Wir fertigen in der eigenen Werkstatt, halten Fremdkosten niedrig und nutzen einfache Verpackung. Direktverkauf ist rund 40 % günstiger als über Wiederverkäufer. Abholung in Kochánov spart die Lieferung. Kostenlose Lieferung in der Vysočina ab 5000 Kč. Nach Humpolec und Havlíčkův Brod kostenlos ab 1000 Kč. Nach Jihlava kostenlos ab 3000 Kč."),
            ],
        },
        "velkoobchod": {
            "title": "Großhandel — Restaurants, Bäckereien, Schulen | Jůzlová",
            "desc": "Jůzlová liefert an Restaurants, Bäckereien, Cafés, Schulen und Speiseeishersteller. Mengenpreise im Gespräch. Abholung, Angebotslieferung oder Ihr Kurier.",
            "h1": "Großhandel für Betriebe",
            "sub": "Restaurants, Bäckereien, Cafés, Coffee-Shops, Schulen und Speiseeishersteller. Mengenpreise klären wir im Gespräch.",
            "body": [
                ("p", "Jůzlová beliefert bereits viele Restaurants, Bäckereien, Cafés und Schulen. Kundennamen nennen wir hier nicht. Etwa 90 % der Aufträge sind örtlich um Kochánov 40, 582 53 in der Vysočina."),
                ("b2b_showcase", None),
                ("h2", "Wen wir beliefern"),
                ("ul", [
                    "Restaurants und Kantinen — Knödel und Pudding für die Ausgabe",
                    "Bäckereien und Konditoreien — Pudding, Vanillinzucker, Kakao",
                    "Cafés und Coffee-Shops — Kakao und Pudding",
                    "Schulen — Mischungen für Kinderspeisen",
                    "Speiseeishersteller — Kakao holländischer Art",
                ]),
                ("h2", "Preis und Bestellung"),
                ("p", "Mengenpreise klären wir im Gespräch. Schreiben Sie das Formular mit Produkten und Menge, oder rufen Sie +420 728 466 141 (Jiřina) und +420 607 629 931 (Jiří) an."),
                ("h2", "Abholung und Lieferung"),
                ("ol", [
                    "Abholung in der Werkstatt in Kochánov",
                    "Unsere Lieferung — wir nennen die Kosten und rechnen sie Ihnen",
                    "Ihr eigener Kurier — oft günstiger",
                ]),
                ("p", "Lieferung nach Brünn ist ab Bestellungen über 5000 Kč kostenlos, nach Terminabsprache. Großhandelspakete nach Deutschland, Österreich, die Slowakei und Polen gehen auf Kundenkosten."),
                ("form_b2b", None),
            ],
        },
        "do_eu": {
            "title": "Pakete an Tschechen in der EU — Versand auf Ihre Kosten | Jůzlová",
            "desc": "Tschechen in der EU können Jůzlová-Mischungen bestellen. Sie zahlen Versand, Karton, Versicherung und Luftpolsterfolie. Kosten nennen wir vor dem Versand.",
            "h1": "Tschechen im Ausland (EU)",
            "sub": "Sie können anfragen. Wir senden, nachdem Sie Versand, Karton und Versicherung angenommen haben. Die Kosten sehen Sie vorher.",
            "body": [
                ("p", "Tschechen in der Europäischen Union können Ware von Jůzlová bestellen. Sie zahlen Versand, Karton, Versicherung und Luftpolsterfolie. Den Betrag nennen wir vor dem Versand — nichts geht blind raus."),
                ("p", "Am häufigsten senden wir nach Deutschland, Österreich, die Slowakei und Polen. Anderswo in der EU schreiben Sie uns, wir kalkulieren den Versand."),
                ("p", "Die Listenpreise gelten bei Abholung in Kochánov. Beim Paket kommen Versand, Verpackung und Versicherung dazu."),
                ("form", None),
            ],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Kartoffelknödel-Mischung",
            "short": "Unser gefragtestes Produkt. Klassische Knödel, Mohnnudeln, Kroketten und Gnocchi aus einem Teig.",
            "price": "5 kg / 250 Kč",
            "title": "Kartoffelknödel-Mischung — 5 kg / 250 Kč",
            "desc": "Kartoffelteig-Pulver aus KLASA-Mehl (tschechisches Gütesiegel) und Kartoffelflocken. Für klassische und gefüllte Knödel, Mohnnudeln, Kroketten und Gnocchi.",
            "body": [
                ("p", "Kartoffelteig in Pulverform ist unser gefragtestes Produkt. Wir verwenden hochwertiges Weizenmehl mit dem tschechischen Gütesiegel KLASA aus der nahegelegenen Mühle in Havlíčkův Brod, die unserer erweiterten Familie gehört und von ihr geführt wird; getrocknete Kartoffelflocken sorgen für den typischen Geschmack und die Konsistenz."),
                ("h2", "Was Sie aus dem Teig zubereiten können"),
                ("ul", ["klassische Kartoffelknödel zu Braten",
                        "mit Fleisch oder Obst gefüllte Knödel",
                        "Mohnnudeln (šišky s mákem)", "frittierte Kroketten", "hausgemachte Gnocchi"]),
                ("p", "Am natürlichen Geschmack erkennen Sie: In diesem Teig steckt nichts Überflüssiges — nur das, was in einen Kartoffelknödel gehört."),
            ],
            "faq": [
                ("Wie lange dauert die Zubereitung?", "Einfach das Pulver mit Wasser vermengen, formen und kochen — die Knödel stehen in 20 Minuten auf dem Tisch."),
                ("Wie viele Portionen ergibt der 5-kg-Beutel?", "Aus einem 5-kg-Beutel bereiten Sie eine Beilage für etwa 60–70 Portionen zu."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Haarige Knödel (Bosáky) — Fertigmischung",
            "short": "Bosáky nach traditioneller Rezeptur. Fertig in 15 Minuten, geschmacklich wie hausgemacht.",
            "price": "5 kg / 260 Kč",
            "title": "Haarige Knödel (Bosáky) — Mischung, 5 kg / 260 Kč",
            "desc": "Haarige Kartoffelknödel (Bosáky) nach traditioneller Rezeptur: in 15 Minuten fertig, beliebt in Kantinen und Restaurants. 5-kg-Beutel für 260 Kč.",
            "body": [
                ("p", "Haarige Knödel (Bosáky) kosten 260 Kč je 5 kg bei Abholung bei Jůzlová, Kochánov 40, 582 53, Vysočina. Fertig in 15 Minuten: mit Wasser mischen, formen, kochen. Traditionelle Rezeptur für Kantinen und Haushalte. Geschmacklich wie Knödel aus rohen Kartoffeln. Bestellung unter +420 728 466 141 oder +420 607 629 931, E-Mail juzlj@seznam.cz, täglich 8:00–19:00 Uhr telefonisch. Einen fertigen Kakaopudding führen wir nicht."),
                ("p", "Dazu Kraut und Geräuchertes, Zwiebeln und Grieben, oder süß mit Mohn und Zucker. 260 Kč gelten bei Abholung in der Werkstatt. Internetpreise von 2017 gelten nicht."),
            ],
            "faq": [
                ("Wozu passen Haarige Knödel?", "Traditionell zu Kraut und Geräuchertem, mit Röstzwiebeln und Grieben — oder süß mit Mohn und Zucker."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Glutenfreier Vanillepudding",
            "short": "Glutenfreie Maisstärke, natürlicher Vanillegeschmack. Für Desserts und zum Backen.",
            "price": "1 kg / 60 Kč · 400 g / 30 Kč",
            "title": "Glutenfreier Vanillepudding — 1 kg / 60 Kč",
            "desc": "Instant-Vanillepudding aus glutenfreier Maisstärke. Natürlicher Geschmack ohne chemische Noten, für glutenfreie Ernährung geeignet. 1 kg / 60 Kč, 400 g / 30 Kč.",
            "body": [
                ("p", "Glutenfreier Vanillepudding kostet 60 Kč je 1 kg oder 30 Kč je 400 g bei Abholung bei Jůzlová, Kochánov 40, 582 53. Basis ist Maisstärke ohne Gluten — für Desserts und zum Backen. Einen fertigen Kakaopudding verkaufen wir nicht. Schokogeschmack entsteht aus diesem Vanillepudding plus Kakao holländischer Art (500 g / 270 Kč). Bestellung unter +420 728 466 141 oder +420 607 629 931, E-Mail juzlj@seznam.cz, täglich 8:00–19:00 Uhr nach Absprache."),
                ("p", "Der Geschmack ist natürlich, ohne chemische Noten. Preise gelten in der Werkstatt. Preislisten von 2017 im Internet gelten nicht."),
            ],
            "faq": [
                ("Ist der Pudding wirklich glutenfrei?", "Ja. Die Basis ist reine Maisstärke, die kein Gluten enthält."),
                ("Gibt es auch eine Schokoladenvariante?", "Einen fertigen Kakaopudding führen wir nicht. Für den Schokoladengeschmack rühren Sie Kakao holländischer Art — den wir einzeln verkaufen — in den Vanillepudding."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holländischer Art",
            "short": "Dunkler Konditorkakao der 21-%-Fettklasse. Rotbraun, cremig, ohne Zuckerzusatz.",
            "price": "500 g / 270 Kč",
            "title": "Kakao holländischer Art, 21 % Fett — 500 g / 270 Kč",
            "desc": "Dunkler Konditorkakao holländischer Art mit 20–22 % Kakaobutter. Ohne Zuckerzusatz, vegan, ohne die 14 EU-Allergene. 500 g / 270 Kč.",
            "body": [
                ("p", "Unser dunkler Konditorkakao ist holländischer Art — ein alkalisiertes Pulver aus Theobroma-cacao-Bohnen, Fettklasse 21 %. Voller Kakaokörper, cremiger Schokoladengeschmack und ein sattes Rotbraun, das trocken und im fertigen Rezept hält."),
                ("h2", "Woher der Kakao kommt"),
                ("p", "Die Kakaobohnen trocknen langsam in der Sonne in Zentralwestafrika. Sie gären natürlich in Bananenblättern — so entsteht der tiefe Schokoladengeschmack, den wir durch Alkalisierung zu Kakao holländischer Art mildern."),
                ("h2", "Fett 20–22 %: warum die Spanne zählt"),
                ("p", "Die Kakaobutter halten wir bei 20,0–22,0 %. Das ist mehr Fett als in mageren Supermarktkakaos (oft 10–12 %). Mehr Butter heißt mehr Feuchtigkeit im Teig, ein runderes Mundgefühl und einen volleren Schokoladeeindruck — die 21-%-Klasse, die Konditoren suchen."),
                ("h2", "Ohne Zuckerzusatz"),
                ("p", "Wir setzen keinen Zucker zu. Die einzigen Zucker, die Sie finden — 0,9 g pro 100 g — entstehen von selbst in der Kakaobohne."),
                ("cocoa_sensory", None),
                ("cocoa_apps", None),
                ("cocoa_nutrition", None),
                ("cocoa_facts", None),
            ],
            "showcase": {
                "sensory_h": "Geschmacksprofil",
                "sensory_lead": "Volle Kakao-Intensität, cremiger Schokoladengeschmack und Röstaromen. Die Farbe ist satt rotbraun — im Pulver und im fertigen Kuchen.",
                "axes": [
                    {"label": "Intensität", "value": 92},
                    {"label": "Cremigkeit", "value": 88},
                    {"label": "Röstung", "value": 78},
                    {"label": "Farbe", "value": 94},
                    {"label": "Sanftheit", "value": 86},
                ],
                "apps_h": "Wofür er sich eignet",
                "apps": [
                    {"title": "Backen", "text": "Lebkuchen, Kuchen und Teige, die nach dem Backen satt kakaofarben bleiben sollen."},
                    {"title": "Getränke", "text": "Trinkkakao und Milchshakes — in Milch hält er Farbe und cremigen Geschmack."},
                    {"title": "Cremes", "text": "Füllungen, Cremes und leichte Desserts, wenn Sie Schokolade ohne Zucker im Pulver wollen."},
                    {"title": "Bestäuben", "text": "Fertige Schnitten, Rouladen und Keksdesserts — ein dunkler, feiner Staub, der nicht klumpt."},
                    {"title": "Mit Vanillepudding", "text": "Unter unseren Vanillepudding rühren: daraus wird eine Schokoladencreme aus einer Mischung."},
                    {"title": "Brei und Cerealien", "text": "Frühstücksschalen, die nach Schokolade schmecken sollen, nicht nach bitterem Pulver."},
                ],
                "nutri_h": "Was im Kakao steckt",
                "nutri_lead": "Pro 100 g: viel Ballaststoff und Eiweiß, von Natur aus wenig Zucker, kein zugesetzter Zucker.",
                "nutri_extra": "Dazu Magnesium 490 mg, Kalium 4 400 mg und Eisen 31 mg pro 100 g.",
                "nutri_note": "Richtwerte pro 100 g nach EU-Verordnung 1169/2011. Kakao verwenden Sie löffelweise — eine Portion ist ein Bruchteil der Tabelle.",
                "bars": [
                    {"label": "Energie", "text": "379 kcal / 1 570 kJ", "pct": 19},
                    {"label": "Fett", "text": "21,0 g  ·  gesättigt 13,0 g", "pct": 30},
                    {"label": "Ballaststoffe", "text": "28,4 g", "pct": 100},
                    {"label": "Eiweiß", "text": "19,5 g", "pct": 39},
                    {"label": "Zucker", "text": "0,9 g  ·  zugesetzt 0 g", "pct": 2},
                    {"label": "Eisen", "text": "31 mg", "pct": 100},
                ],
                "facts_h": "Technische Angaben",
                "facts": [
                    {"label": "Kakaobutter", "value": "20,0–22,0 %"},
                    {"label": "pH (10%-Lösung)", "value": "7,8–8,2"},
                    {"label": "Feinheit", "value": "min. 99,5 % unter 75 µm"},
                    {"label": "Feuchte", "value": "max. 5,0 %"},
                    {"label": "Schalen", "value": "max. 1,75 %"},
                    {"label": "EU-Allergene", "value": "keine der 14"},
                    {"label": "Gluten", "value": "< 20 ppm"},
                    {"label": "Ernährung", "value": "vegan, vegetarisch"},
                ],
            },
            "faq": [
                ("Was unterscheidet Kakao holländischer Art?", "Die Alkalisierung — er ist dunkler, weniger säuerlich und löst sich besser auf als naturbelassener Kakao. Mit 20–22 % Fett zählt er zu den hochwertigsten Konditorkakaos."),
                ("Setzen Sie Zucker zu?", "Nein. Zugesetzter Zucker ist 0 g. Natürlich vorkommende Zucker aus der Bohne sind 0,9 g pro 100 g."),
                ("Ist er gluten- und allergenfrei?", "Ja. Er enthält keines der 14 EU-Allergene. Gluten liegt unter 20 ppm. Er ist vegan und vegetarisch — ohne Zutaten tierischen Ursprungs."),
                ("Wie lagere ich ihn?", "Trocken, fern von starken Gerüchen, ideal bei 15–20 °C und unter 50 % Luftfeuchte."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanillinzucker",
            "short": "Fein gemahlener Zucker mit Vanillinaroma. Für den Teig und zum Bestreuen von Gebäck.",
            "price": "1 kg / 60 Kč",
            "title": "Vanillinzucker — 1 kg / 60 Kč",
            "desc": "Vanillinzucker aus fein gemahlenem Zucker mit Vanillinaroma. Für Kuchen, Desserts und Weihnachtsgebäck — im Teig und zum Bestreuen. 1 kg / 60 Kč.",
            "body": [
                ("p", "Vanillinzucker kostet 60 Kč je 1 kg bei Abholung bei Jůzlová, Kochánov 40, 582 53, Vysočina. Fein gemahlener Zucker mit Vanillinaroma — für Teig und zum Bestreuen, keine Vanilleschote. Bestellung unter +420 728 466 141 (Jiřina) oder +420 607 629 931 (Jiří), E-Mail juzlj@seznam.cz, täglich 8:00–19:00 Uhr telefonisch. Das ist kein Kakaopudding; den führen wir nicht als Fertigmischung."),
                ("p", "Für Kuchen, Desserts und Weihnachtsgebäck. 60 Kč gelten bei Abholung in der Werkstatt. Preise von 2017 gelten nicht."),
            ],
            "faq": [
                ("Eignet sich der Vanillinzucker für Weihnachtsgebäck?",
                 "Ja. Im Teig und zum Bestreuen des fertigen Gebäcks. Packung 1 kg / 60 Kč."),
                ("Ist das Vanille oder Vanillin?",
                 "Vanillinzucker: fein gemahlener Zucker mit Vanillinaroma, keine Vanilleschote."),
            ],
        },
    },
    "recipes_intro": "Probieren Sie bewährte Rezepte mit unseren Mischungen — vom Sonntagsknödel bis zum Dessert ohne Backen.",
    "faq_page": {
        "title": "FAQ — Bestellung, Lieferung und Jůzlová-Mischungen",
        "desc": "Antworten zu Jůzlová: Standort, Bestellung, Preise, glutenfreier Pudding, Kakao holländischer Art und Lieferung in der Vysočina.",
        "h1": "Häufige Fragen",
        "sub": "Kurze, direkte Antworten — für Menschen, Google, Seznam.cz und Sprachmodelle.",
    },
    "recipes": {},
}
