# Slovak content — full translation of content_cs.py.
LANG = {
    "code": "sk",
    "locale": "sk_SK",
    "name": "Slovenčina",
    "ui": {
        "nav_home": "Úvod", "nav_about": "Kto sme", "nav_delivery": "Dodanie tovaru",
        "nav_products": "Produkty", "nav_prices": "Cenník", "nav_recipes": "Recepty",
        "nav_contact": "Kontakt",
        "brand_tag": "potravinárske zmesi · Vysočina",
        "est": "Rodinná dielňa · Kochánov · od roku 2004",
        "hero_h1": "Knedle ako od babičky. Hotové za 15 minút.",
        "hero_lead": "Poctivé potravinárske zmesi z Vysočiny — zemiakové cestá, pudingy, vanilínový cukor a kakao. Z múky ocenenej českou značkou kvality KLASA, bez kompromisov v kvalite.",
        "hero_cta": "Ochutnajte zadarmo",
        "hero_cta2": "Naše produkty",
        "sec_products": "Naše produkty", "sec_products_kicker": "Čo vyrábame",
        "sec_products_lead": "Päť zmesí, ktoré od roku 2004 dodávame domácnostiam, reštauráciám, jedálňam aj cukrárňam v Čechách i na Morave.",
        "sec_recipes": "Recepty z našich zmesí", "sec_recipes_kicker": "Inšpirácia do kuchyne",
        "sec_recipes_lead": "Osvedčené recepty, ktoré z našich zmesí pripravíte rýchlo a bez práce navyše.",
        "sec_why": "Prečo Jůzlová", "sec_why_kicker": "Rodinná výroba",
        "why_1_h": "Suroviny, ktoré poznáme po mene",
        "why_1_p": "Pšeničná múka ocenená českou značkou kvality KLASA pochádza z mlyna v Havlíčkovom Brode, 12 km od našej dielne. Kukuričný škrob v pudingoch neobsahuje lepok.",
        "why_2_h": "Rýchlosť bez kompromisov",
        "why_2_p": "Chlpaté knedle máte hotové za 15 minút — a chuťou ich nerozoznáte od knedieľ pripravovaných celé popoludnie.",
        "why_3_h": "Cena pod úrovňou supermarketu",
        "why_3_p": "Vyrábame kvalitu za cenu nižšiu než „supermarketové\" výrobky neistého pôvodu. Zemiakové knedle: 5 kg za 165 Kč.",
        "cta_sample_h": "Máte chuť ochutnať?",
        "cta_sample_p": "Ozvite sa — radi vám pripravíme vzorku zadarmo. Tovar si vyzdvihnete v Kochánove či Humpolci, alebo vám ho privezieme až domov.",
        "cta_sample_btn": "Napíšte si o vzorku",
        "full_price_list": "Kompletný cenník",
        "all_recipes": "Všetky recepty",
        "detail": "Viac",
        "price_label": "Cena",
        "package_label": "Balenie",
        "order_info": "Ako objednať",
        "breadcrumb_home": "Úvod",
        "footer_products": "Produkty", "footer_recipes": "Recepty", "footer_company": "Firma",
        "footer_note": "Rodinná výroba potravinárskych zmesí od roku 2004.",
        "footer_addr": "Jůzlová · Kochánov 40, 582 53 · Vysočina",
        "open_hours": "Otvorené denne po telefonickom dohovore, 8:00–19:00 (vrátane víkendov)",
        "lang_label": "Jazyk",
        "recipe_meta": "Recept z dielne Jůzlová",
        "uses_product": "Použitá zmes",
    },
    "meta": {
        "home_title": "Jůzlová — potravinárske zmesi z Vysočiny | knedle, puding",
        "home_desc": "Rodinná výroba od roku 2004: zemiakové a chlpaté knedle v prášku, bezlepkový vanilkový puding, vanilínový cukor a kakao holandského typu. Kochánov, Vysočina.",
        "site_name": "Jůzlová.cz",
    },
    "pages": {
        "kdo_jsme": {
            "title": "Kto sme — rodinná výroba zmesí od roku 2004",
            "desc": "Potravinárske zmesi vyrábame od roku 2004 v malej dielni v Kochánove na Vysočine. Dodávame domácnostiam, reštauráciám aj cukrárňam v Čechách i na Morave.",
            "h1": "Kto sme",
            "sub": "Rodinná dielňa v Kochánove na Vysočine. Potravinárske zmesi vyrábame od roku 2004.",
            "body": [
                ("p", "Výrobu potravinárskych zmesí sme v malej dielni v Kochánove začali v roku 2004. Počas rokov sme citlivo upravovali receptúry a vyberali si najkvalitnejších dodávateľov surovín, až sme dosiahli jedinečnú kombináciu chuti a kvality, pre ktorú nás vyhľadávajú zákazníci v Čechách aj na Morave."),
                ("p", "Dnes ako obchodná firma „Jůzlová\" dodávame nielen domácnostiam, ale aj mnohým reštauráciám, jedálňam a cukrárňam. Naši zákazníci oceňujú predovšetkým tradičnú domácu chuť a zároveň rýchlosť, s akou možno z našich instantných výrobkov pripraviť výborné prílohy a dezerty."),
                ("h2", "Zemiakové cesto v prášku — náš najvyhľadávanejší výrobok"),
                ("p", "Pri jeho výrobe používame kvalitnú pšeničnú múku ocenenú českou značkou kvality KLASA z neďalekého mlyna v Havlíčkovom Brode. Typickú chuť a charakteristickú konzistenciu zabezpečujú sušené zemiakové vločky. Cesto sa hodí na prípravu zemiakových knedieľ, či už klasických, plnených mäsom alebo ovocím, ďalej šúľancov, krokiet či gnocchi."),
                ("h2", "Pudingy bez lepku"),
                ("p", "Instantný vanilkový a čokoládový puding je skvelý na prípravu sladkých dezertov. Základom je kvalitný kukuričný škrob, ktorý neobsahuje lepok, takže je vhodný aj pri bezlepkovej diéte. Do kakaového pudingu miešame vysokokvalitné kakao holandského typu s 21 % tuku, ktoré mu dodáva výraznú čokoládovú chuť."),
                ("h2", "Náš cieľ"),
                ("p", "Vyrábať potravinárske zmesi najvyššej kvality za cenu pod úrovňou „supermarketových\" výrobkov neistého pôvodu. Používame suroviny najvyššej akosti, pretože veríme, že naši zákazníci si zaslúžia len to najlepšie. Kladieme dôraz na priamy kontakt so zákazníkmi a vždy sa snažíme prispôsobiť ich potrebám."),
                ("p", "Máte chuť ochutnať? Ozvite sa, radi vám ponúkneme vzorku zadarmo."),
            ],
        },
        "kde_nas_najdete": {
            "title": "Dodanie tovaru a odberné miesta — Kochánov a Humpolec",
            "desc": "Vyzdvihnutie zadarmo v Kochánove alebo Humpolci, bezplatný rozvoz v okolí Havlíčkovho Brodu, Světlej nad Sázavou a Jihlavy, alebo zaslanie zmluvným dopravcom.",
            "h1": "Dodanie tovaru",
            "sub": "Naša dielňa je v Kochánove, 12 km od Havlíčkovho Brodu. Sme vám k dispozícii každý deň od 8:00 do 19:00, vrátane víkendov.",
            "body": [
                ("p", "Uvedomujeme si, že pre našich zákazníkov je popri vysokej kvalite výrobkov dôležitá aj cena. Keďže ceny zmluvných dopravcov môžu naše výrobky predražiť, ponúkame možnosť vyzdvihnúť si tovar priamo u nás v prevádzke v Kochánove. Stačí sa vopred ozvať a tovar vám kedykoľvek pripravíme na odber."),
                ("p", "Po predchádzajúcom dohovore si tovar môžete vyzdvihnúť aj v Humpolci. V súčasnosti rozvážame v Havlíčkovom Brode, Humpolci, Světlej nad Sázavou, Jihlave a okolí — a po individuálnom dohovore privezieme tovar aj priamo k vám domov."),
                ("h2", "Možnosti doručenia"),
                ("ol", ["Vyzdvihnutie tovaru v prevádzke v Kochánove alebo v Humpolci — zadarmo",
                        "Bezplatný rozvoz tovaru v okolí Havlíčkovho Brodu, Světlej nad Sázavou a Jihlavy",
                        "Zmluvný dopravca podľa vášho výberu (poštovné podľa cenníka dopravcu)"]),
                ("h2", "Kedy sa u nás môžete zastaviť"),
                ("p", "Otvorené denne po telefonickom dohovore: pondelok–sobota 8:00–19:00."),
            ],
        },
        "kontakt": {
            "title": "Kontakt — Jůzlová, Kochánov 40, Vysočina",
            "desc": "Jiřina Jůzlová (+420 728 466 141) a Jiří Jůzl (+420 607 629 931), Kochánov 40, 582 53. E-mail juzlj@seznam.cz. Odber tovaru aj v Humpolci.",
            "h1": "Kontakt",
            "sub": "Ozvite sa nám telefonicky alebo e-mailom — dohodneme vzorku zadarmo, odber aj rozvoz.",
            "body": [
                ("contacts", None),
                ("h2", "Kde nás nájdete"),
                ("p", "Prevádzka: Kochánov 40, 582 53, kraj Vysočina — 12 km od Havlíčkovho Brodu. Po predchádzajúcom dohovore je možné vyzdvihnutie tovaru aj v Humpolci."),
                ("p", "Jůzlová s.r.o. · IČO 45900124"),
            ],
        },
        "ceny": {
            "title": "Cenník potravinárskych zmesí — knedle, puding, kakao",
            "desc": "Aktuálne ceny: zemiakové knedle 5 kg / 165 Kč, chlpaté knedle 5 kg / 185 Kč, vanilkový puding od 17 Kč, vanilínový cukor 38 Kč, kakao 100 Kč.",
            "h1": "Cenník",
            "sub": "Kvalita za cenu pod úrovňou supermarketu. Ceny platia pri odbere v Kochánove či Humpolci.",
            "body": [("pricetable", None),
                     ("p", "Pre reštaurácie, jedálne a cukrárne pripravíme individuálnu ponuku podľa odoberaného množstva — ozvite sa nám.")],
        },
    },
    "products": {
        "bramborove_knedliky": {
            "name": "Zemiakové knedle v prášku",
            "short": "Náš najvyhľadávanejší výrobok. Klasické knedle, šúľance, krokety aj gnocchi z jedného cesta.",
            "price": "5 kg / 165 Kč",
            "title": "Zemiakové knedle v prášku — 5 kg / 165 Kč",
            "desc": "Zemiakové cesto v prášku z múky ocenenej českou značkou kvality KLASA a sušených zemiakových vločiek. Na klasické aj plnené knedle, šúľance, krokety a gnocchi.",
            "body": [
                ("p", "Zemiakové cesto v prášku je náš najvyhľadávanejší výrobok. Používame kvalitnú pšeničnú múku ocenenú českou značkou kvality KLASA z neďalekého mlyna v Havlíčkovom Brode; typickú chuť a konzistenciu zabezpečujú sušené zemiakové vločky."),
                ("h2", "Čo z cesta pripravíte"),
                ("ul", ["klasické zemiakové knedle k pečenému mäsu",
                        "knedle plnené mäsom alebo ovocím",
                        "šúľance s makom", "vyprážané krokety", "domáce gnocchi"]),
                ("p", "Na prirodzenej chuti spoznáte, že v ceste nie je nič navyše — len to, čo do zemiakovej knedle patrí."),
            ],
            "faq": [
                ("Ako dlho trvá príprava?", "Cesto stačí zmiešať s vodou, vytvarovať a povariť — knedle máte na stole do 20 minút."),
                ("Koľko porcií je z 5 kg balenia?", "Z päťkilogramového balenia pripravíte prílohu približne pre 60–70 porcií."),
            ],
        },
        "chlupate_knedliky": {
            "name": "Chlpaté knedle v prášku",
            "short": "Bosáky podľa tradičnej receptúry. Hotové za 15 minút, chuťou na nerozoznanie od domácich.",
            "price": "5 kg / 185 Kč",
            "title": "Chlpaté knedle (bosáky) v prášku — 5 kg / 185 Kč",
            "desc": "Chlpaté knedle podľa tradičnej receptúry: hotové za 15 minút, obľúbené v jedálňach aj reštauráciách. Balenie 5 kg za 185 Kč.",
            "body": [
                ("p", "Chlpaté knedle, známe aj ako bosáky, patria medzi naše najobľúbenejšie výrobky. Vyrábame ich podľa tradičnej receptúry."),
                ("p", "Pre rýchlu a jednoduchú prípravu sú obľúbené v jedálňach a reštauráciách, no chuťou a konzistenciou obstoja aj v domácnostiach. Hotové sú za 15 minút a chuťou ich nerozoznáte od knedieľ pripravovaných tradičným spôsobom zo surových zemiakov."),
            ],
            "faq": [
                ("K čomu sa chlpaté knedle hodia?", "Tradične sa podávajú s kapustou a údeným mäsom, s cibuľkou a škvarkami, alebo nasladko s makom a cukrom."),
            ],
        },
        "vanilkovy_pudink": {
            "name": "Vanilkový puding bez lepku",
            "short": "Kukuričný škrob bez lepku, prirodzená vanilková chuť. Na dezerty aj pečenie.",
            "price": "1 kg / 34 Kč · 400 g / 17 Kč",
            "title": "Vanilkový puding bez lepku — 1 kg / 34 Kč",
            "desc": "Instantný vanilkový puding z kukuričného škrobu bez lepku. Prirodzená chuť bez chemických príchutí, vhodný pri bezlepkovej diéte. 1 kg / 34 Kč, 400 g / 17 Kč.",
            "body": [
                ("p", "Vanilkový puding patrí medzi naše tradičné produkty. Skvele sa uplatní pri príprave ľahkých dezertov aj pri pečení."),
                ("p", "Základom je kvalitný kukuričný škrob, ktorý neobsahuje lepok — puding je preto vhodný aj pri bezlepkovej diéte. Vyskúšajte jeho prirodzenú chuť bez chemických príchutí a k zabehnutým „supermarketovým\" značkám sa už nevrátite."),
            ],
            "faq": [
                ("Je puding naozaj bez lepku?", "Áno. Základom je čistý kukuričný škrob, ktorý lepok neobsahuje."),
                ("Vyrábate aj čokoládový variant?", "Áno — kakaový puding s kakaom holandského typu (1 kg / 44 Kč, 400 g / 22 Kč)."),
            ],
        },
        "kakao_holandskeho_typu": {
            "name": "Kakao holandského typu",
            "short": "Tmavé cukrárske kakao s 21 % tuku. Výrazná farba aj chuť múčnikov a koktailov.",
            "price": "500 g / 100 Kč",
            "title": "Kakao holandského typu 21 % tuku — 500 g / 100 Kč",
            "desc": "Tmavé cukrárske kakao holandského typu s 21 % tuku. Dodá múčnikom bohatú kakaovú farbu a chuť; hodí sa aj na mliečne koktaily a krémy. 500 g / 100 Kč.",
            "body": [
                ("p", "Ponúkame výborné tmavé cukrárske kakao holandského typu s 21 % tuku."),
                ("p", "Skvele sa vyníma v múčnikoch, ktorým dodá bohatú tmavú kakaovú farbu aj chuť. Pripravíte z neho aj chutné mliečne koktaily a krémy. To isté kakao miešame do nášho kakaového pudingu."),
            ],
            "faq": [
                ("Čím sa líši kakao holandského typu?", "Alkalizáciou — je tmavšie, menej kyslé a lepšie sa rozpúšťa než prírodné kakao. S 21 % tuku patrí medzi najkvalitnejšie cukrárske kakaá."),
            ],
        },
        "vanilkovy_cukr": {
            "name": "Vanilínový cukor",
            "short": "Jemne mletý cukor s vanilínovou arómou. Do cesta aj na posypanie pečiva.",
            "price": "1 kg / 38 Kč",
            "title": "Vanilínový cukor — 1 kg / 38 Kč",
            "desc": "Vanilínový cukor z jemne mletého cukru s vanilínovou arómou. Na koláče, zákusky aj vianočné pečivo — do cesta aj na posyp. 1 kg / 38 Kč.",
            "body": [
                ("p", "Vanilínový cukor obsahuje okrem jemne mletého cukru aj vanilínovú arómu, ktorá mu dodáva príjemnú, jedinečnú vôňu vanilky."),
                ("p", "Oceníte ho pri pečení koláčov, zákuskov aj ostatných dezertov. Skvele sa hodí pri príprave vianočného pečiva — nielen ako prísada do cesta, ale aj na posypanie hotových dobrôt."),
            ],
            "faq": [],
        },
    },
    "recipes_intro": "Vyskúšajte osvedčené recepty z našich zmesí — od nedeľných knedieľ po nepečené dezerty.",
    "recipes": {},
}
