# Czech recipes — recovered from the last-live site (Wayback captures).
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Domácí perník",
        "teaser": "Hrníčkový perník, který si zamilujete pro snadnou přípravu i výbornou chuť. Nepotřebujete váhu — vystačíte si s hrnečkem.",
        "title": "Domácí perník — hrníčkový recept podle Jiřiny Jůzlové",
        "desc": "Domácí hrníčkový perník bez vážení: 10 minut přípravy, 20–25 minut pečení, 25–30 porcí. S vanilkovým pudinkem a kakaem holandského typu.",
        "product": "vanilkovy_pudink",
        "meta": "Příprava 10 min · Pečení 20–25 min · 25–30 porcí",
        "ingredients": [
            "3 hrnečky hladké mouky (hrneček = 200 ml)",
            "2 hrnečky cukru krystal",
            "1 hrneček oleje",
            "2 středně velká vejce",
            "2 vrchovaté polévkové lžíce vanilkového pudinku v prášku",
            "1 prášek do perníku",
            "½ prášku do pečiva",
            "250 ml mléka (1¼ hrnečku)",
            "kakao holandského typu dle chuti",
        ],
        "steps": [
            "Všechny ingredience nasypte do jedné nádoby a důkladně promíchejte mixérem, aby se netvořily hrudky.",
            "Těsto nalijte na vymaštěný plech vysypaný hrubou moukou.",
            "Pečte v troubě předehřáté na 180 °C 20 až 25 minut (podle výšky plechu).",
            "Hotový perník poznáte dřevěným párátkem — po zapíchnutí musí zůstat čisté, bez přilepeného těsta.",
        ],
        "notes": ["Tip: Do těsta můžete podle chuti přidat trochu rumu či rumového aroma, skořici, nahrubo nasekané vlašské ořechy nebo čokoládu."],
    },
    "slehackova-rolada-recept": {
        "name": "Šlehačková roláda",
        "teaser": "Lehký moučník za půl hodiny: kontrast nahořklého kakaa a jemně sladké šlehačky. Bez mouky, tedy i bez lepku.",
        "title": "Šlehačková roláda — bezlepkový recept s kakaem",
        "desc": "Šlehačková roláda bez mouky a bez lepku: 5 vajec, moučkový cukr, kakao holandského typu a šlehačka. Hotová za 30 minut.",
        "product": "kakao_holandskeho_typu",
        "meta": "Příprava cca 30 min · Bez lepku",
        "ingredients": [
            "5 vajec",
            "100 g moučkového cukru",
            "1 lžíce kakaa holandského typu",
            "1 smetana ke šlehání (případně ztužovač smetany)",
        ],
        "steps": [
            "Z bílků ušlehejte tuhý sníh, pak přidejte žloutky a moučkový cukr. Opatrným mísením vznikne hladké těsto.",
            "Nakonec přidejte kakao holandského typu — dodá sytou čokoládovou barvu a výraznou chuť.",
            "Připravte si pečicí papír lehce vymaštěný sádlem (poslouží i olej), aby šla roláda po upečení dobře sbalit.",
            "Pečte v troubě předehřáté na 180 °C asi 8 minut; troubu po celou dobu neotevírejte.",
            "Roládu nechte na plechu vychladnout a opatrně ji sejměte z papíru.",
            "Ušlehejte tuhou šlehačku, roládu potřete a zabalte. Zbylou šlehačkou ozdobte hřbet, na efekt přidejte čokoládové hobliny.",
        ],
        "notes": ["Tip: Roládu ozvláštníte oblíbeným ovocem — jahodami, malinami nebo banánem."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Hruškový koláč s vanilkovým pudinkem",
        "teaser": "Koláč, jehož přípravu si užijí i děti. Pečení baví dvakrát — při přípravě i při ochutnávání.",
        "title": "Hruškový koláč s vanilkovým pudinkem — recept Lucie Kůželové",
        "desc": "Hruškový koláč se zakysanou smetanou a vanilkovým pudinkem: 20 minut přípravy, 45 minut pečení, 8 porcí. Funguje i s jablky, malinami či broskvemi.",
        "product": "vanilkovy_pudink",
        "meta": "Příprava 20 min · Pečení 45 min · 8 porcí",
        "ingredients": [
            "2 vejce",
            "80 g rozehřátého másla",
            "150 g krystalového cukru",
            "200 g hladké mouky (lze kombinovat s celozrnnou nebo špaldovou)",
            "1 kypřicí prášek",
            "2 zakysané smetany",
            "1 smetana ke šlehání (30 %)",
            "40 g vanilkového pudinku v prášku",
            "5 hrušek (lze nahradit jablky, malinami, broskvemi — čerstvým i mraženým ovocem)",
        ],
        "steps": [
            "Smíchejte jedno vejce, máslo, 50 g cukru, mouku a kypřicí prášek. Těsto rukama vypracujte a vtlačte do koláčové formy vyložené pečicím papírem (drolivé těsto nevadí — vymačkejte je do formy).",
            "Okrájené hrušky nakrájejte na plátky a rozprostřete na těsto.",
            "V misce promíchejte zakysanou smetanu, šlehačku, pudink v prášku, 100 g cukru a druhé vejce; směs nalijte na koláč.",
            "Pečte uprostřed vyhřáté trouby na 180 °C asi 45 minut.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Šišky s mákem",
        "teaser": "Tradiční sladká večeře z bramborového těsta: šišky obalené v máku s cukrem, přelité rozpuštěným máslem.",
        "title": "Šišky s mákem z bramborového těsta — recept",
        "desc": "Pečené šišky s mákem z bramborových knedlíků v prášku Jůzlová: dozlatova upečené, spařené a obalené v máku s cukrem a máslem.",
        "product": "bramborove_knedliky",
        "meta": "Z bramborového těsta Jůzlová",
        "ingredients": [
            '400 g bramborových knedlíků v prášku',
            '100 g mletého máku',
            '2 polévkové lžíce moučkového cukru (může být více)',
            '2 polévkové lžíce rozpuštěného másla',
        ],
        "steps": [
            'Bramborové knedlíky v prášku smíchejte s vodou dle návodu a z těsta vytvarujte malé šišky.',
            'Pečte na vymaštěném plechu uprostřed trouby předehřáté na 200 °C; v průběhu pečení šišky jednou otočte, aby měly zlatavou barvu z obou stran.',
            'Po upečení šišky vhoďte do vroucí vody a na 5 minut spařte.',
            'Vložte je do velké mísy, posypte mákem a cukrem, polijte máslem, promíchejte a ještě teplé podávejte.',
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky se zelím a slaninou",
        "teaser": "Slovenská klasika z chlupatých knedlíků v prášku — halušky s kysaným zelím a vypečenou slaninou.",
        "title": "Strapačky se zelím a slaninou — recept z chlupatých knedlíků",
        "desc": "Strapačky z chlupatých knedlíků v prášku Jůzlová s kysaným zelím, jarní cibulkou a slaninou vypečenou na sádle. Vydatná slovenská klasika.",
        "product": "chlupate_knedliky",
        "meta": "Z chlupatých knedlíků Jůzlová",
        "ingredients": [
            '400 g chlupatých knedlíků v prášku',
            '400 g kysaného zelí',
            'svazek jarní cibulky',
            '100 g slaniny',
            'lžíce sádla',
        ],
        "steps": [
            'Chlupaté knedlíky v prášku smíchejte s vodou dle návodu. Nabobtnalé těsto protlačte cedníkem na halušky přímo do vroucí vody a vařte, dokud nevyplavou.',
            'Kysané zelí povařte v hrnci s vodou asi 10 minut; nevyvařenou vodu slijte.',
            'Na pánvi na sádle osmažte slaninu nakrájenou na menší kousky; když je lehce vysmažená, přidejte na kolečka nakrájenou jarní cibulku a po minutě odstavte.',
            'Halušky smíchejte se zelím a na talíři posypte slaninou s cibulkou.',
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe řezy s čokoládovým pudingem",
        "teaser": "Rádi byste pohostili návštěvu, ale nejste zrovna Jamie Oliver? Nepečené bebe řezy zvládne opravdu každý.",
        "title": "Bebe řezy s čokoládovým pudingem — nepečený recept",
        "desc": "Nepečené bebe řezy s čokoládovým pudingem podle Lucie Kůželové: sušenky, pudingový krém a šlehačka. Bez pečení.",
        "product": "kakao_holandskeho_typu",
        "meta": "Nepečený dezert · Podle Lucie Kůželové",
        "ingredients": [
            '4 balíčky sušenek BEBE: 2 světlé, 2 tmavé',
            '2 zakysané smetany',
            '1 smetana ke šlehání',
            '40 g vanilkového cukru',
            '150 g čokoládového pudingu (3 balení)',
            '1 litr mléka',
            'kakao holandského typu na posyp',
        ],
        "steps": [
            'Na plech poklaďte světlé bebe sušenky.',
            'Uvařte čokoládový puding dle návodu na obalu a nalijte jej na sušenky tak, aby se rovnoměrně rozprostřel.',
            'Na vrstvu pudingu poklaďte tmavé bebe sušenky.',
            'V míse vyšlehejte smetanu s vanilkovým cukrem do tuha, vmíchejte zakysanou smetanu a směs rozetřete na sušenky.',
            'Řez posypte tmavým kakaem a nechte v lednici odležet, nejlépe přes noc.',
        ],
        "notes": ['Tip: Máte-li po ruce jiný než čokoládový puding, experimentujte — řez chutná výborně i s vanilkovým pudingem a skořicovým posypem.'],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Bramborovo-tvarohové knedlíky s jahodami",
        "teaser": "Léto je tady a s ním i dozrávání jahod. Jednoduchý a rychlý recept, kterým za 20 minut potěšíte i největší mlsouny.",
        "title": "Bramborovo-tvarohové knedlíky s jahodami — recept za 20 minut",
        "desc": "Ovocné knedlíky z bramborového těsta Jůzlová s tvarohem a jahodami podle Lucie Kůželové. Hotové za 20 minut.",
        "product": "bramborove_knedliky",
        "meta": "20 minut · Podle Lucie Kůželové",
        "ingredients": [
            '250 g bramborových knedlíků v prášku',
            '250 g měkkého tvarohu (v kostce, ne ve vaničce)',
            'jahody (jako náplň i na ozdobu)',
            'cukr, máslo a tvaroh na ozdobu',
        ],
        "steps": [
            'Bramborové knedlíky v prášku smíchejte s vodou dle návodu a připravte vláčné těsto; zapracujte měkký tvaroh (lepivé těsto nevadí).',
            'Z těsta vytvarujte válec a nakrájejte jej na stejně velké části, aby se knedlíky vařily rovnoměrně.',
            'Každou část zakulaťte, dlaněmi vytvořte placičku, doprostřed zatlačte jahodu a zabalte.',
            'Knedlíky vařte v páře 5 minut — těsto se krásně uvaří a nerozvaří.',
            'Mezitím můžete povařit kousky jahod na ozdobu. Na talíři knedlíky dozdobte máslem, cukrem, jahodami nebo tvarohem.',
        ],
        "notes": [],
    },
    "rychle-venecky-ci-vetrnicky-recept": {
        "name": "Rychlé věnečky či větrníčky",
        "teaser": "Jedno odpalované těsto na věnečky i větrníčky: vyšší podíl másla a start na 250 °C. Asi 80 kousků na dvou plechách.",
        "title": "Rychlé věnečky či větrníčky z odpalovaného těsta — recept",
        "desc": "Rychlé věnečky a větrníčky z odpalovaného těsta: 250 ml vody, 90 g másla, 140 g hrubé mouky, 4 vejce. Příprava 45 min, pečení cca 15 min, asi 80 kousků.",
        "meta": "Příprava 45 min · Pečení cca 15 min · asi 80 kousků · 2 plechy",
        "ingredients": [
            "250 ml vody",
            "špetka soli",
            "90 g másla",
            "140 g hrubé mouky",
            "4 vejce",
            "tuk na vymazání plechů",
        ],
        "steps": [
            "Vodu, sůl a máslo přiveďte k varu.",
            "Stáhněte plamen a vmíchejte mouku najednou; míchejte, dokud se těsto neodlepí od stěn hrnce a nebude lepit.",
            "Odstavte a nechte mírně zchladnout.",
            "Troubu předehřejte na 250 °C.",
            "Po jednom zašlehejte vejce a stále míchejte, až je těsto hladké a mírně pružné.",
            "Na vymaštěné plechy stříkejte věnečky jako dva naskládané kroužky, nebo větrníčky jako malé kopečky.",
            "Pečte 5 minut na 250 °C, pak snižte na 200 °C a pečte dozlatova — zhruba dalších 5 minut na vyšší a 5 na střední teplotě. Troubu během pečení neotevírejte.",
            "Ještě horké ihned rozřízněte (skořápky se pak netrhají). Před plněním úplně vychlaďte.",
        ],
        "notes": [
            "Náplň je volná: nejjednodušší je oslazená šlehačka. K věnečkům se hodí vanilkový máslový krém a rumová poleva z receptu na věnečky, k větrníčkům vanilkový pudinkový krém, karamelová šlehačka a karamelová poleva z receptu na karamelové větrníky.",
            "Těsto má vyšší poměr másla k mouce (90 g : 140 g) a peče se s horkým startem 250 °C — proto rychleji a spolehlivěji vykoukne.",
        ],
    },
    "venecky-s-vanilkovym-kremem-recept": {
        "name": "Věnečky s vanilkovým krémem",
        "teaser": "Klasické věnečky z odpalovaného těsta s vanilkovým máslovým krémem a rumovou polevou. Asi 20 kousků.",
        "title": "Věnečky s vanilkovým krémem a rumovou polevou — recept",
        "desc": "Věnečky z odpalovaného těsta s vanilkovým máslovým krémem z pudinku a žloutků a s rumovou polevou. Asi 20 kousků.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 20 kousků · odpalované těsto, vanilkový krém, rumová poleva",
        "ingredients": [
            "Odpalované těsto: 320 ml vody",
            "100 g másla",
            "špetka soli",
            "235 g mouky",
            "4–5 vajec, přidávaných postupně",
            "Vanilkový máslový krém: 500 ml mléka",
            "2 sáčky vanilkového pudinku v prášku",
            "5 žloutků",
            "150 g cukru",
            "250 g změklého másla",
            "2 lžíce rumu (podle chuti)",
            "Rumová poleva: 300 g moučkového cukru",
            "2 lžíce rumu",
            "3 lžíce horkého mléka",
        ],
        "steps": [
            "Vodu, máslo a sůl přiveďte k varu. Odstavte, vmíchejte všechnu mouku a na mírném plameni 2–3 minuty vařte, dokud se těsto nesrazí do koule.",
            "Nechte zchladnout, až je jen vlažné. Postupně zašlehejte vejce, až těsto z lžíce padá v husté stuze.",
            "Na pečicí papír stříkejte kroužky o průměru 6–7 cm. Pečte 10 minut na 200 °C bez otevírání dvířek, pak snižte na 180 °C a pečte dalších 15–25 minut, až jsou věnečky sytě zlatavé a na omak suché.",
            "Úplně vychlaďte a ideálně nechte několik hodin nebo přes noc odkryté, aby skořápky zůstaly křupavé.",
            "Puding uvařte s mlékem, cukrem a žloutky za stálého míchání, dokud zhoustne (po přidání žloutků už nevařte naplno). Vychlaďte, na povrch přitiskněte fólii.",
            "Změklé máslo vyšlehejte do pěny, po lžících přidávejte vychladlý puding a šlehejte dohladka. Nakonec vmíchejte rum.",
            "Moučkový cukr, rum a horké mléko vyšlehejte do hladké, lité polevy.",
            "Věnečky rozřízněte vodorovně. Do spodní poloviny nastříkejte vydatně krém, přiklopte a vršek namočte do rumové polevy. Nechte ztuhnout.",
        ],
        "notes": [
            "Lehčí varianta: vynechte rumovou polevu, místo máslového krému použijte obyčejný pudinkový krém a navrch dejte šlehačku a moučkový cukr.",
        ],
    },
    "kremrole-recept": {
        "name": "Kremrole",
        "teaser": "Křehké trubičky plněné lesklým italským sněhem. Asi 35–40 kousků; budete potřebovat kovové trubičky na kremrole.",
        "title": "Kremrole z máslového těsta s italským sněhem — recept",
        "desc": "Kremrole z máslového těsta se smetanou, plněné italským sněhem. Asi 35–40 kousků, pečení 12–15 minut na 180–200 °C.",
        "meta": "Asi 35–40 kousků · pečení 12–15 min · kovové trubičky",
        "ingredients": [
            "Těsto: 350 g mouky",
            "250 g studeného másla (nebo Hery), nastrouhaného nebo nakrájeného",
            "125 ml smetany ke šlehání",
            "volitelně pro větší křehkost: 25 g smetany nahraďte zakysanou smetanou",
            "Italský sníh: 80 g bílků (asi 2 vejce)",
            "160 g cukru",
            "40 ml vody",
            "moučkový cukr na posyp",
        ],
        "steps": [
            "Mouku, máslo a smetanu zpracujte v hladké těsto — nepřehánějte to. Zabalte a nechte v lednici nejméně hodinu, klidně přes noc.",
            "Vyválejte na tenký plát, nakrájejte proužky 2 × 20 cm a každý oviňte kolem vymaštěné kovové trubičky, okraje mírně překládejte.",
            "Pečte na 180–200 °C dozlatova, asi 12–15 minut. Nechte mírně zchladnout a opatrně stáhněte z trubiček.",
            "Cukr s vodou zahřejte bez míchání na 115–120 °C (teploměr pomůže). Mezitím ušlehejte bílky do tuha.",
            "Za chodu mixéru tenkým pramínkem přilévejte horký sirup a šlehejte, dokud není sníh lesklý a jen vlažný. Krátce vychlaďte a stříkejte do trubiček z obou konců. Posypte moučkovým cukrem.",
        ],
        "notes": [
            "Nejjednodušší varianta: bílky se cukrem šlehejte přímo nad hrncem s mírně vroucí vodou (vodní lázeň), dokud nejsou lesklé a husté — bez teploměru, o něco méně stabilní, ale spolehlivě dobré.",
            "Trubičky můžete improvizovat z alobalu, pokud nemáte kovové formy.",
        ],
    },
    "minivetrnicky-recept": {
        "name": "Minivětrníčky",
        "teaser": "Malé větrníčky z odpalovaného těsta s máslovo-pudinkovým krémem s tvarohem a čokoládovou polevou. Asi 40–45 kousků.",
        "title": "Minivětrníčky s pudinkovým krémem a čokoládovou polevou — recept",
        "desc": "Minivětrníčky z odpalovaného těsta: 250 ml vody, 90 g másla, 160 g mouky, 4 vejce. Náplň z vanilkového pudinku, másla a tvarohu, vršek s čokoládovou polevou. Asi 40–45 kousků.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 40–45 kousků · pečení cca 20 min",
        "ingredients": [
            "Odpalované těsto: 250 ml vody",
            "špetka soli",
            "90 g másla",
            "160 g mouky",
            "1 lžička kypřicího prášku",
            "4 vejce",
            "Náplň: 0,5 l mléka",
            "2 sáčky vanilkového pudinku v prášku",
            "3 lžíce cukru",
            "250 g změklého másla",
            "125 g cukru",
            "vanilkový cukr",
            "2 lžičky rumu",
            "asi 150–200 g tučného tvarohu",
            "Poleva: hořká nebo mléčná čokoláda (s kouskem másla nebo oleje na lesk)",
        ],
        "steps": [
            "Vodu, máslo a sůl přiveďte k varu. Odstavte, vmíchejte mouku s kypřicím práškem dohladka a na mírném plameni míchejte, až těsto mírně zchladne.",
            "Po jednom zašlehejte vejce mixérem. Na pečicí papír stříkejte kopečky 2–3 cm (nebo je tvarujte dvěma lžícemi).",
            "Pečte na 200 °C asi 20 minut. Prvních 10 minut troubu neotevírejte.",
            "Puding uvařte a úplně vychlaďte (klidně o několik hodin dřív). Změklé máslo vyšlehejte s cukrem a vanilkovým cukrem do pěny, přidejte rum a po částech zašlehejte puding a tvaroh dohladka.",
            "Vychladlé větrníčky nařízněte do tří čtvrtin, nastříkejte náplň a vršek namočte nebo potřete rozpuštěnou čokoládou.",
        ],
        "notes": [
            "Letní, lehčí varianta: vynechte máslový krém i polevu — plňte oslazenou šlehačkou a kousky čerstvých jahod, posypte moučkovým cukrem.",
        ],
    },
    "karamelove-vetrniky-recept": {
        "name": "Karamelové větrníky",
        "teaser": "Větrníky s vanilkovým pudinkovým krémem, karamelovou šlehačkou a karamelovou polevou. Asi 24 středních kousků.",
        "title": "Karamelové větrníky s dvojím krémem — recept",
        "desc": "Karamelové větrníky z odpalovaného těsta: vanilkový pudinkový krém, karamelová šlehačka a karamelová poleva. Asi 24 středních kousků.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 24 středních kousků · karamelový krém raději den předem",
        "ingredients": [
            "Odpalované těsto: 250 ml vody",
            "100 g másla",
            "špetka soli",
            "160 g mouky",
            "4–5 vajec (pokojová teplota), rozšlehaných, přidávaných postupně",
            "½ lžičky kypřicího prášku",
            "Vanilkový pudinkový krém: 400 ml mléka",
            "1 sáček vanilkového pudinku v prášku",
            "3 lžíce cukru",
            "250 ml smetany ke šlehání (33 %), ušlehané do tuha",
            "Karamelová šlehačka: 150 g cukru",
            "250 ml smetany ke šlehání (33 %), studené, plus trochu na stažení karamelu",
            "špetka soli",
            "Karamelová poleva: 125 g cukru",
            "45 g másla",
            "75 ml smetany ke šlehání",
            "volitelně: 3–4 lžíce odložené karamelové šlehačky, zředěné trochou moučkového cukru",
        ],
        "steps": [
            "Vodu, máslo a sůl přiveďte k varu. Odstavte, vsypte všechnu mouku, důkladně zamíchejte a na mírném plameni 2–3 minuty vařte, dokud se těsto nesrazí do koule a na dně hrnce se neudělá tenký film.",
            "Těsto rozetřete po stěnách mísy, ať rychleji zchladne. Až je jen vlažné (horké by srazilo vejce), po troškách zašlehejte vejce na nízké otáčky. Přestaňte, když těsto z lžíce padá v hustém „V“ — všechno vejce nemusíte spotřebovat. Nakonec vmíchejte kypřicí prášek.",
            "Velkou hvězdicovou špičkou stříkejte na pečicí papír kola 4–5 cm, s velkými rozestupy. Pečte 10 minut na 200–220 °C, pak snižte na 170–180 °C a pečte dalších 15–20 minut, až jsou sytě zlatavé a pevné. Troubu během pečení neotevírejte — větrníky spadnou. Před plněním úplně vychlaďte.",
            "Puding uvařte s mlékem a cukrem podle sáčku a úplně vychlaďte (na povrch přitiskněte fólii). Až jsou puding i šlehačka studené, šlehačku do pudinku zapracujte.",
            "Cukr na sucho rozpusťte na pánvi (nemíchejte, jen otáčejte pánví) do sytě jantarové barvy. Odstavte, opatrně přilijte trochu smetany — bude to bouřlivě bublat — pak vmíchejte zbytek a špetku soli. Úplně vychlaďte, nechte v lednici několik hodin nebo přes noc a ušlehejte do tuha. 3–4 lžíce odložte na polevu.",
            "Cukr na polevu zkaramelizujte stejně, odstavte, vmíchejte máslo a smetanu do hladka a lesku. Nechte zchladnout, až poleva obalí lžíci, ale ještě se dá lít.",
            "Každý vychladlý větrník rozřízněte vodorovně a vršek nechte jako čepičku. Do spodku nastříkejte vanilkový krém, na něj kroužek karamelové šlehačky, přiklopte a přelijte nebo namočte do karamelové polevy. Před podáváním nechte v lednici aspoň 2 hodiny ztuhnout.",
        ],
        "notes": [
            "Vejce do odpalovaného těsta dávejte až ve vlažném stavu a po troškách — mouka nasákne pokaždé jinak, hotovost poznáte podle konzistence, ne podle toho, že spotřebujete všechno vejce.",
            "Troubu během pečení neotevírejte. Karamelovou šlehačku připravte den předem, ať stačí ztuhnout na šlehání.",
        ],
    },
    "irsky-sticky-toffee-pudding-recept": {
        "name": "Irský sticky toffee pudding",
        "teaser": "Vlhké datlové těsto s kakaem holandského typu a Baileys, přelité slanou toffee omáčkou. 6 porcí.",
        "title": "Irský sticky toffee pudding s kakaem a Baileys — recept",
        "desc": "Sticky toffee pudding podle Donala Skehana s kakaem holandského typu a 100 ml Baileys v těstě. 6 porcí, pečení 45–50 minut na 160 °C.",
        "product": "kakao_holandskeho_typu",
        "meta": "6 porcí · Pečení 45–50 min · 160 °C",
        "ingredients": [
            "Těsto: 125 g másla",
            "150 g světlého cukru muscovado",
            "1 lžíce zlatého sirupu (golden syrup)",
            "1 lžíce černé melasy (black treacle)",
            "2 velká vejce",
            "1 lžička vanilkového extraktu",
            "150 g samokypřící mouky",
            "60 g kakaa holandského typu",
            "150 g datlí medjool, nasekaných",
            "2 lžičky jedlé sody",
            "100 ml Baileys Irish Cream",
            "180 ml vody",
            "vanilková zmrzlina k podávání",
            "Toffee omáčka: 100 g másla (nesoleného)",
            "150 g tmavého cukru muscovado",
            "3 lžíce zlatého sirupu",
            "150 ml husté smetany (double cream)",
            "1 lžička vanilkového extraktu",
            "štědrá špetka mořské soli",
        ],
        "steps": [
            "Troubu předehřejte na 160 °C (140 °C horkovzduch). Vymažte zapékací mísu o průměru 20 cm.",
            "Máslo a cukr vyšlehejte do světlé pěny.",
            "Na nízké otáčky pomalu vmíchejte zlatý sirup, melasu, vejce a vanilku.",
            "Samokypřící mouku prosejte s kakaem a na nízké otáčky zapracujte do těsta.",
            "180 ml vody s nasekanými datlemi několik minut povařte, odstavte a vmíchejte Baileys a jedlou sodu — směs napění.",
            "Horkou datlovo-baileysovou směs zapracujte do kakaového těsta, vlijte do mísy a pečte 45–50 minut, až je pudink pevný a mírně pružný. Špejlí kontrolujte vlhké drobky, ne barvu — těsto je tmavé.",
            "Omáčka: máslo, cukr a zlatý sirup rozehřejte, až se cukr rozpustí. Přidejte smetanu, vanilku a sůl a 3 minuty mírně povařte, až zhoustne. Pro silnější irskou chuť na závěr mimo plotnu vmíchejte 1–2 lžíce Baileys (volitelné — alkohol se už neodpaří).",
            "Teplý pudink přelijte toffee omáčkou a podávejte s vanilkovou zmrzlinou.",
        ],
        "notes": [
            "Baileys se přidává až po povaření datlí s vodou, mimo plotnu — delší var by vyhnal alkohol a ztlumil chuť likéru.",
            "Vody je o 100 ml méně než v původním receptu (180 ml místo 280 ml), právě o množství přidaného Baileys, aby hydratace těsta a doba pečení zůstaly stejné.",
        ],
    },
}
