# Czech recipes — recovered from the last-live site (Wayback captures).
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Domácí perník",
        "teaser": "Hrníčkový perník, který si zamilujete pro snadnou přípravu i výbornou chuť. Nepotřebujete váhu — vystačíte si s hrnečkem.",
        "title": "Domácí perník — hrníčkový recept podle Jiřiny Jůzlové",
        "desc": "Domácí hrníčkový perník bez vážení: 10 minut přípravy, 20–25 minut pečení, 25–30 porcí. S vanilkovým pudinkem a kakaem holandského typu.",
        "product": "vanilkovy_pudink",
        "meta": "Příprava 10 min · Pečení 20–25 min · 25–30 porcí",
        "ingredients": [
            "3 hrnečky hladké mouky (hrneček = 200 ml)",
            "2 hrnečky cukru krystal",
            "1 hrneček oleje",
            "2 středně velká vejce",
            "2 vrchovaté polévkové lžíce vanilkového pudinku v prášku",
            "1 prášek do perníku",
            "½ prášku do pečiva",
            "250 ml mléka (1¼ hrnečku)",
            "kakao holandského typu dle chuti",
        ],
        "steps": [
            "Všechny ingredience nasypte do jedné nádoby a důkladně promíchejte mixérem, aby se netvořily hrudky.",
            "Těsto nalijte na vymaštěný plech vysypaný hrubou moukou.",
            "Pečte v troubě předehřáté na 180 °C 20 až 25 minut (podle výšky plechu).",
            "Hotový perník poznáte dřevěným párátkem — po zapíchnutí musí zůstat čisté, bez přilepeného těsta.",
        ],
        "notes": ["Tip: Do těsta můžete podle chuti přidat trochu rumu či rumového aroma, skořici, nahrubo nasekané vlašské ořechy nebo čokoládu."],
    },
    "slehackova-rolada-recept": {
        "name": "Šlehačková roláda",
        "teaser": "Lehký moučník za půl hodiny: kontrast nahořklého kakaa a jemně sladké šlehačky. Bez mouky, tedy i bez lepku.",
        "title": "Šlehačková roláda — bezlepkový recept s kakaem",
        "desc": "Šlehačková roláda bez mouky a bez lepku: 5 vajec, moučkový cukr, kakao holandského typu a šlehačka. Hotová za 30 minut.",
        "product": "kakao_holandskeho_typu",
        "meta": "Příprava cca 30 min · Bez lepku",
        "ingredients": [
            "5 vajec",
            "100 g moučkového cukru",
            "1 lžíce kakaa holandského typu",
            "1 smetana ke šlehání (případně ztužovač smetany)",
        ],
        "steps": [
            "Z bílků ušlehejte tuhý sníh, pak přidejte žloutky a moučkový cukr. Opatrným mísením vznikne hladké těsto.",
            "Nakonec přidejte kakao holandského typu — dodá sytou čokoládovou barvu a výraznou chuť.",
            "Připravte si pečicí papír lehce vymaštěný sádlem (poslouží i olej), aby šla roláda po upečení dobře sbalit.",
            "Pečte v troubě předehřáté na 180 °C asi 8 minut; troubu po celou dobu neotevírejte.",
            "Roládu nechte na plechu vychladnout a opatrně ji sejměte z papíru.",
            "Ušlehejte tuhou šlehačku, roládu potřete a zabalte. Zbylou šlehačkou ozdobte hřbet, na efekt přidejte čokoládové hobliny.",
        ],
        "notes": ["Tip: Roládu ozvláštníte oblíbeným ovocem — jahodami, malinami nebo banánem."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Hruškový koláč s vanilkovým pudinkem",
        "teaser": "Koláč, jehož přípravu si užijí i děti. Pečení baví dvakrát — při přípravě i při ochutnávání.",
        "title": "Hruškový koláč s vanilkovým pudinkem — recept Lucie Kůželové",
        "desc": "Hruškový koláč se zakysanou smetanou a vanilkovým pudinkem: 20 minut přípravy, 45 minut pečení, 8 porcí. Funguje i s jablky, malinami či broskvemi.",
        "product": "vanilkovy_pudink",
        "meta": "Příprava 20 min · Pečení 45 min · 8 porcí",
        "ingredients": [
            "2 vejce",
            "80 g rozehřátého másla",
            "150 g krystalového cukru",
            "200 g hladké mouky (lze kombinovat s celozrnnou nebo špaldovou)",
            "1 kypřicí prášek",
            "2 zakysané smetany",
            "1 smetana ke šlehání (30 %)",
            "40 g vanilkového pudinku v prášku",
            "5 hrušek (lze nahradit jablky, malinami, broskvemi — čerstvým i mraženým ovocem)",
        ],
        "steps": [
            "Smíchejte jedno vejce, máslo, 50 g cukru, mouku a kypřicí prášek. Těsto rukama vypracujte a vtlačte do koláčové formy vyložené pečicím papírem (drolivé těsto nevadí — vymačkejte je do formy).",
            "Okrájené hrušky nakrájejte na plátky a rozprostřete na těsto.",
            "V misce promíchejte zakysanou smetanu, šlehačku, pudink v prášku, 100 g cukru a druhé vejce; směs nalijte na koláč.",
            "Pečte uprostřed vyhřáté trouby na 180 °C asi 45 minut.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Šišky s mákem",
        "teaser": "Tradiční sladká večeře z bramborového těsta: šišky obalené v máku s cukrem, přelité rozpuštěným máslem.",
        "title": "Šišky s mákem z bramborového těsta — recept",
        "desc": "Pečené i vařené šišky s mákem z bramborového těsta Jůzlová: rychlá tradiční sladká večeře. Mák, cukr a rozpuštěné máslo.",
        "product": "bramborove_knedliky",
        "meta": "Z bramborového těsta Jůzlová",
        "ingredients": [
            "bramborové těsto Jůzlová (dle návodu na obalu)",
            "mletý mák",
            "moučkový cukr",
            "rozpuštěné máslo",
        ],
        "steps": [
            "Z bramborového těsta připraveného podle návodu vytvarujte šišky.",
            "Vhoďte je do vroucí osolené vody a vařte, dokud nevyplavou.",
            "Obalte v mletém máku smíchaném s cukrem a přelijte rozpuštěným máslem.",
        ],
        "notes": ["Plné znění původního receptu doplňujeme z archivu."],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky se zelím a slaninou",
        "teaser": "Slovenská klasika z bramborového těsta — strapačky s kysaným zelím a opečenou slaninou.",
        "title": "Strapačky se zelím a slaninou — recept z bramborového těsta",
        "desc": "Strapačky z bramborového těsta Jůzlová s kysaným zelím a výpečky ze slaniny. Vydatné jídlo podle slovenské tradice.",
        "product": "bramborove_knedliky",
        "meta": "Z bramborového těsta Jůzlová",
        "ingredients": [
            "bramborové těsto Jůzlová (dle návodu na obalu)",
            "kysané zelí",
            "uzená slanina",
            "cibule, sůl, pepř",
        ],
        "steps": [
            "Z bramborového těsta odkrajujte nebo protlačujte do vroucí vody malé noky (strapačky) a vařte, dokud nevyplavou.",
            "Slaninu nakrájejte na kostičky a vypečte dozlatova, přidejte cibuli a prohřáté kysané zelí.",
            "Strapačky smíchejte se zelím a slaninou a podávejte horké.",
        ],
        "notes": ["Plné znění původního receptu doplňujeme z archivu."],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe řezy s čokoládovým pudingem",
        "teaser": "Rádi byste pohostili návštěvu, ale nejste zrovna Jamie Oliver? Nepečené bebe řezy zvládne opravdu každý.",
        "title": "Bebe řezy s čokoládovým pudingem — nepečený recept",
        "desc": "Nepečené bebe řezy s kakaovým pudingem Jůzlová podle Lucie Kůželové: sušenky, pudingový krém a šlehačka. Bez pečení.",
        "product": "kakao_holandskeho_typu",
        "meta": "Nepečený dezert · Podle Lucie Kůželové",
        "ingredients": [
            "bebe sušenky",
            "kakaový puding Jůzlová (prášek)",
            "mléko a cukr dle návodu na pudink",
            "máslo",
            "smetana ke šlehání",
        ],
        "steps": [
            "Dno formy vyložte vrstvou bebe sušenek.",
            "Uvařte hustší kakaový puding, nechte mírně zchladnout a zašlehejte máslo.",
            "Krém rozetřete na sušenky, přiklopte další vrstvou sušenek a nechte v chladu ztuhnout.",
            "Před podáváním ozdobte šlehačkou.",
        ],
        "notes": ["Plné znění původního receptu doplňujeme z archivu."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Bramborovo-tvarohové knedlíky s jahodami",
        "teaser": "Léto je tady a s ním i dozrávání jahod. Jednoduchý a rychlý recept, kterým za 20 minut potěšíte i největší mlsouny.",
        "title": "Bramborovo-tvarohové knedlíky s jahodami — recept za 20 minut",
        "desc": "Ovocné knedlíky z bramborového těsta Jůzlová s tvarohem a jahodami podle Lucie Kůželové. Hotové za 20 minut.",
        "product": "bramborove_knedliky",
        "meta": "20 minut · Podle Lucie Kůželové",
        "ingredients": [
            "bramborové těsto Jůzlová (dle návodu na obalu)",
            "tvaroh",
            "čerstvé jahody",
            "moučkový cukr, rozpuštěné máslo",
        ],
        "steps": [
            "Do bramborového těsta zapracujte tvaroh.",
            "Z těsta vytvořte placičky, do každé zabalte jahodu a vytvarujte knedlíky.",
            "Vařte v osolené vodě, dokud knedlíky nevyplavou.",
            "Podávejte sypané cukrem, tvarohem a přelité rozpuštěným máslem.",
        ],
        "notes": ["Plné znění původního receptu doplňujeme z archivu."],
    },
}
