# Slovak recipes — translation of recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Domáci perník",
        "teaser": "Hrnčekový perník, ktorý si zamilujete pre jednoduchú prípravu aj výbornú chuť. Nepotrebujete váhu — vystačíte si s hrnčekom.",
        "title": "Domáci perník — hrnčekový recept podľa Jiřiny Jůzlovej",
        "desc": "Domáci hrnčekový perník bez váženia: 10 minút prípravy, 20–25 minút pečenia, 25–30 porcií. S vanilkovým pudingom a kakaom holandského typu.",
        "product": "vanilkovy_pudink",
        "meta": "Príprava 10 min · Pečenie 20–25 min · 25–30 porcií",
        "ingredients": [
            "3 hrnčeky hladkej múky (hrnček = 200 ml)",
            "2 hrnčeky kryštálového cukru",
            "1 hrnček oleja",
            "2 stredne veľké vajcia",
            "2 vrchovaté polievkové lyžice vanilkového pudingu v prášku",
            "1 prášok do perníka",
            "½ prášku do pečiva",
            "250 ml mlieka (1¼ hrnčeka)",
            "kakao holandského typu podľa chuti",
        ],
        "steps": [
            "Všetky ingrediencie nasypte do jednej nádoby a dôkladne premiešajte mixérom, aby sa netvorili hrudky.",
            "Cesto nalejte na vymastený plech vysypaný hrubou múkou.",
            "Pečte v rúre predhriatej na 180 °C 20 až 25 minút (podľa výšky plechu).",
            "Hotový perník spoznáte dreveným špáradlom — po zapichnutí musí zostať čisté, bez prilepeného cesta.",
        ],
        "notes": ["Tip: Do cesta môžete podľa chuti pridať trochu rumu či rumovej arómy, škoricu, nahrubo posekané vlašské orechy alebo čokoládu."],
    },
    "slehackova-rolada-recept": {
        "name": "Šľahačková roláda",
        "teaser": "Ľahký múčnik za pol hodiny: kontrast horkastého kakaa a jemne sladkej šľahačky. Bez múky, teda aj bez lepku.",
        "title": "Šľahačková roláda — bezlepkový recept s kakaom",
        "desc": "Šľahačková roláda bez múky a bez lepku: 5 vajec, práškový cukor, kakao holandského typu a šľahačka. Hotová za 30 minút.",
        "product": "kakao_holandskeho_typu",
        "meta": "Príprava cca 30 min · Bez lepku",
        "ingredients": [
            "5 vajec",
            "100 g práškového cukru",
            "1 lyžica kakaa holandského typu",
            "1 smotana na šľahanie (prípadne stužovač smotany)",
        ],
        "steps": [
            "Z bielkov vyšľahajte tuhý sneh, potom pridajte žĺtky a práškový cukor. Opatrným miešaním vznikne hladké cesto.",
            "Nakoniec pridajte kakao holandského typu — dodá sýtu čokoládovú farbu a výraznú chuť.",
            "Pripravte si papier na pečenie zľahka vymastený masťou (poslúži aj olej), aby sa roláda po upečení dala dobre zvinúť.",
            "Pečte v rúre predhriatej na 180 °C asi 8 minút; rúru počas pečenia neotvárajte.",
            "Roládu nechajte na plechu vychladnúť a opatrne ju odlepte z papiera.",
            "Vyšľahajte tuhú šľahačku, roládu potrite a zviňte. Zvyšnou šľahačkou ozdobte vrch, na efekt pridajte čokoládové hobliny.",
        ],
        "notes": ["Tip: Roládu ozvláštnite obľúbeným ovocím — jahodami, malinami alebo banánom."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Hruškový koláč s vanilkovým pudingom",
        "teaser": "Koláč, ktorého prípravu si užijú aj deti. Pečenie baví dvakrát — pri príprave aj pri ochutnávaní.",
        "title": "Hruškový koláč s vanilkovým pudingom podľa Lucie Kůželovej",
        "desc": "Hruškový koláč s kyslou smotanou a vanilkovým pudingom: 20 minút prípravy, 45 minút pečenia, 8 porcií. Funguje aj s jablkami, malinami či broskyňami.",
        "product": "vanilkovy_pudink",
        "meta": "Príprava 20 min · Pečenie 45 min · 8 porcií",
        "ingredients": [
            "2 vajcia",
            "80 g rozohriateho masla",
            "150 g kryštálového cukru",
            "200 g hladkej múky (možno kombinovať s celozrnnou alebo špaldovou)",
            "1 kypriaci prášok",
            "2 kyslé smotany",
            "1 smotana na šľahanie (30 %)",
            "40 g vanilkového pudingu v prášku",
            "5 hrušiek (možno nahradiť jablkami, malinami, broskyňami — čerstvým aj mrazeným ovocím)",
        ],
        "steps": [
            "Zmiešajte jedno vajce, maslo, 50 g cukru, múku a kypriaci prášok. Cesto rukami vypracujte a vtlačte do koláčovej formy vyloženej papierom na pečenie (drobivé cesto neprekáža — vytlačte ho do formy).",
            "Ošúpané hrušky nakrájajte na plátky a rozprestrite na cesto.",
            "V miske premiešajte kyslú smotanu, šľahačku, puding v prášku, 100 g cukru a druhé vajce; zmes nalejte na koláč.",
            "Pečte v strede vyhriatej rúry na 180 °C asi 45 minút.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Šúľance s makom",
        "teaser": "Tradičná sladká večera zo zemiakového cesta: šúľance obalené v maku s cukrom, preliate rozpusteným maslom.",
        "title": "Šúľance s makom zo zemiakového cesta — recept",
        "desc": "Pečené aj varené šúľance s makom zo zemiakového cesta Jůzlová: rýchla tradičná sladká večera. Mak, cukor a rozpustené maslo.",
        "product": "bramborove_knedliky",
        "meta": "Zo zemiakového cesta Jůzlová",
        "ingredients": [
            "zemiakové cesto Jůzlová (podľa návodu na obale)",
            "mletý mak",
            "práškový cukor",
            "rozpustené maslo",
        ],
        "steps": [
            "Zo zemiakového cesta pripraveného podľa návodu vytvarujte šúľance.",
            "Vhoďte ich do vriacej osolenej vody a varte, kým nevyplávajú.",
            "Obaľte v mletom maku zmiešanom s cukrom a prelejte rozpusteným maslom.",
        ],
        "notes": ["Plné znenie pôvodného receptu dopĺňame z archívu."],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky s kapustou a slaninou",
        "teaser": "Slovenská klasika zo zemiakového cesta — strapačky s kyslou kapustou a opečenou slaninou.",
        "title": "Strapačky s kyslou kapustou a slaninou — recept",
        "desc": "Strapačky zo zemiakového cesta Jůzlová s kyslou kapustou a výpekmi zo slaniny. Výdatné jedlo podľa slovenskej tradície.",
        "product": "bramborove_knedliky",
        "meta": "Zo zemiakového cesta Jůzlová",
        "ingredients": [
            "zemiakové cesto Jůzlová (podľa návodu na obale)",
            "kyslá kapusta",
            "údená slanina",
            "cibuľa, soľ, čierne korenie",
        ],
        "steps": [
            "Zo zemiakového cesta odkrajujte alebo pretláčajte do vriacej vody malé halušky (strapačky) a varte, kým nevyplávajú.",
            "Slaninu nakrájajte na kocky a vypečte dozlatista, pridajte cibuľu a prehriatu kyslú kapustu.",
            "Strapačky zmiešajte s kapustou a slaninou a podávajte horúce.",
        ],
        "notes": ["Plné znenie pôvodného receptu dopĺňame z archívu."],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe rezy s čokoládovým pudingom",
        "teaser": "Radi by ste pohostili návštevu, ale nie ste práve Jamie Oliver? Nepečené bebe rezy zvládne naozaj každý.",
        "title": "Bebe rezy s čokoládovým pudingom — nepečený recept",
        "desc": "Nepečené bebe rezy s kakaovým pudingom Jůzlová podľa Lucie Kůželovej: sušienky, pudingový krém a šľahačka. Bez pečenia.",
        "product": "kakao_holandskeho_typu",
        "meta": "Nepečený dezert · Podľa Lucie Kůželovej",
        "ingredients": [
            "bebe sušienky",
            "kakaový puding Jůzlová (prášok)",
            "mlieko a cukor podľa návodu na puding",
            "maslo",
            "smotana na šľahanie",
        ],
        "steps": [
            "Dno formy vyložte vrstvou bebe sušienok.",
            "Uvarte hustejší kakaový puding, nechajte mierne vychladnúť a zašľahajte maslo.",
            "Krém rozotrite na sušienky, priklopte ďalšou vrstvou sušienok a nechajte v chlade stuhnúť.",
            "Pred podávaním ozdobte šľahačkou.",
        ],
        "notes": ["Plné znenie pôvodného receptu dopĺňame z archívu."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Zemiakovo-tvarohové knedle s jahodami",
        "teaser": "Leto je tu a s ním aj dozrievanie jahôd. Jednoduchý a rýchly recept, ktorým za 20 minút potešíte aj najväčších maškrtníkov.",
        "title": "Zemiakovo-tvarohové knedle s jahodami — recept za 20 minút",
        "desc": "Ovocné knedle zo zemiakového cesta Jůzlová s tvarohom a jahodami podľa Lucie Kůželovej. Hotové za 20 minút.",
        "product": "bramborove_knedliky",
        "meta": "20 minút · Podľa Lucie Kůželovej",
        "ingredients": [
            "zemiakové cesto Jůzlová (podľa návodu na obale)",
            "tvaroh",
            "čerstvé jahody",
            "práškový cukor, rozpustené maslo",
        ],
        "steps": [
            "Do zemiakového cesta zapracujte tvaroh.",
            "Z cesta vytvorte placky, do každej zabaľte jahodu a vytvarujte knedle.",
            "Varte v osolenej vode, kým knedle nevyplávajú.",
            "Podávajte posypané cukrom, tvarohom a preliate rozpusteným maslom.",
        ],
        "notes": ["Plné znenie pôvodného receptu dopĺňame z archívu."],
    },
}
