# Slovak recipes — translation of recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Domáci perník",
        "teaser": "Hrnčekový perník, ktorý si zamilujete pre jednoduchú prípravu aj výbornú chuť. Nepotrebujete váhu — vystačíte si s hrnčekom.",
        "title": "Domáci perník — hrnčekový recept podľa Jiřiny Jůzlovej",
        "desc": "Domáci hrnčekový perník bez váženia: 10 minút prípravy, 20–25 minút pečenia, 25–30 porcií. S vanilkovým pudingom a kakaom holandského typu.",
        "product": "vanilkovy_pudink",
        "meta": "Príprava 10 min · Pečenie 20–25 min · 25–30 porcií",
        "ingredients": [
            "3 hrnčeky hladkej múky (hrnček = 200 ml)",
            "2 hrnčeky kryštálového cukru",
            "1 hrnček oleja",
            "2 stredne veľké vajcia",
            "2 vrchovaté polievkové lyžice vanilkového pudingu v prášku",
            "1 prášok do perníka",
            "½ prášku do pečiva",
            "250 ml mlieka (1¼ hrnčeka)",
            "kakao holandského typu podľa chuti",
        ],
        "steps": [
            "Všetky ingrediencie nasypte do jednej nádoby a dôkladne premiešajte mixérom, aby sa netvorili hrudky.",
            "Cesto nalejte na vymastený plech vysypaný hrubou múkou.",
            "Pečte v rúre predhriatej na 180 °C 20 až 25 minút (podľa výšky plechu).",
            "Hotový perník spoznáte dreveným špáradlom — po zapichnutí musí zostať čisté, bez prilepeného cesta.",
        ],
        "notes": ["Tip: Do cesta môžete podľa chuti pridať trochu rumu či rumovej arómy, škoricu, nahrubo posekané vlašské orechy alebo čokoládu."],
    },
    "slehackova-rolada-recept": {
        "name": "Šľahačková roláda",
        "teaser": "Ľahký múčnik za pol hodiny: kontrast horkastého kakaa a jemne sladkej šľahačky. Bez múky, teda aj bez lepku.",
        "title": "Šľahačková roláda — bezlepkový recept s kakaom",
        "desc": "Šľahačková roláda bez múky a bez lepku: 5 vajec, práškový cukor, kakao holandského typu a šľahačka. Hotová za 30 minút.",
        "product": "kakao_holandskeho_typu",
        "meta": "Príprava cca 30 min · Bez lepku",
        "ingredients": [
            "5 vajec",
            "100 g práškového cukru",
            "1 lyžica kakaa holandského typu",
            "1 smotana na šľahanie (prípadne stužovač smotany)",
        ],
        "steps": [
            "Z bielkov vyšľahajte tuhý sneh, potom pridajte žĺtky a práškový cukor. Opatrným miešaním vznikne hladké cesto.",
            "Nakoniec pridajte kakao holandského typu — dodá sýtu čokoládovú farbu a výraznú chuť.",
            "Pripravte si papier na pečenie zľahka vymastený masťou (poslúži aj olej), aby sa roláda po upečení dala dobre zvinúť.",
            "Pečte v rúre predhriatej na 180 °C asi 8 minút; rúru počas pečenia neotvárajte.",
            "Roládu nechajte na plechu vychladnúť a opatrne ju odlepte z papiera.",
            "Vyšľahajte tuhú šľahačku, roládu potrite a zviňte. Zvyšnou šľahačkou ozdobte vrch, na efekt pridajte čokoládové hobliny.",
        ],
        "notes": ["Tip: Roládu ozvláštnite obľúbeným ovocím — jahodami, malinami alebo banánom."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Hruškový koláč s vanilkovým pudingom",
        "teaser": "Koláč, ktorého prípravu si užijú aj deti. Pečenie baví dvakrát — pri príprave aj pri ochutnávaní.",
        "title": "Hruškový koláč s vanilkovým pudingom podľa Lucie Kůželovej",
        "desc": "Hruškový koláč s kyslou smotanou a vanilkovým pudingom: 20 minút prípravy, 45 minút pečenia, 8 porcií. Funguje aj s jablkami, malinami či broskyňami.",
        "product": "vanilkovy_pudink",
        "meta": "Príprava 20 min · Pečenie 45 min · 8 porcií",
        "ingredients": [
            "2 vajcia",
            "80 g rozohriateho masla",
            "150 g kryštálového cukru",
            "200 g hladkej múky (možno kombinovať s celozrnnou alebo špaldovou)",
            "1 kypriaci prášok",
            "2 kyslé smotany",
            "1 smotana na šľahanie (30 %)",
            "40 g vanilkového pudingu v prášku",
            "5 hrušiek (možno nahradiť jablkami, malinami, broskyňami — čerstvým aj mrazeným ovocím)",
        ],
        "steps": [
            "Zmiešajte jedno vajce, maslo, 50 g cukru, múku a kypriaci prášok. Cesto rukami vypracujte a vtlačte do koláčovej formy vyloženej papierom na pečenie (drobivé cesto neprekáža — vytlačte ho do formy).",
            "Ošúpané hrušky nakrájajte na plátky a rozprestrite na cesto.",
            "V miske premiešajte kyslú smotanu, šľahačku, puding v prášku, 100 g cukru a druhé vajce; zmes nalejte na koláč.",
            "Pečte v strede vyhriatej rúry na 180 °C asi 45 minút.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Šúľance s makom",
        "teaser": "Tradičná sladká večera zo zemiakového cesta: šúľance obalené v maku s cukrom, preliate rozpusteným maslom.",
        "title": "Šúľance s makom zo zemiakového cesta — recept",
        "desc": "Pečené šúľance s makom zo zemiakových knedieľ v prášku Jůzlová: dozlatista upečené, sparené a obalené v maku s cukrom a maslom.",
        "product": "bramborove_knedliky",
        "meta": "Zo zemiakového cesta Jůzlová",
        "ingredients": [
            "400 g zemiakových knedieľ v prášku",
            "100 g mletého maku",
            "2 polievkové lyžice práškového cukru (môže byť aj viac)",
            "2 polievkové lyžice rozpusteného masla",
        ],
        "steps": [
            "Zemiakové knedle v prášku zmiešajte s vodou podľa návodu a z cesta vytvarujte malé šúľance.",
            "Pečte na vymastenom plechu v strede rúry predhriatej na 200 °C; počas pečenia šúľance raz otočte, aby mali zlatistú farbu z oboch strán.",
            "Po upečení šúľance vhoďte do vriacej vody a na 5 minút sparte.",
            "Vložte ich do veľkej misy, posypte makom a cukrom, polejte maslom, premiešajte a ešte teplé podávajte.",
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky s kapustou a slaninou",
        "teaser": "Slovenská klasika z chlpatých knedieľ v prášku — halušky s kyslou kapustou a vypečenou slaninou.",
        "title": "Strapačky s kapustou a slaninou — recept z chlpatých knedieľ",
        "desc": "Strapačky z chlpatých knedieľ v prášku Jůzlová s kyslou kapustou, jarnou cibuľkou a slaninou vypečenou na masti. Výdatná slovenská klasika.",
        "product": "chlupate_knedliky",
        "meta": "Z chlpatých knedieľ Jůzlová",
        "ingredients": [
            "400 g chlpatých knedieľ v prášku",
            "400 g kyslej kapusty",
            "zväzok jarnej cibuľky",
            "100 g slaniny",
            "lyžica masti",
        ],
        "steps": [
            "Chlpaté knedle v prášku zmiešajte s vodou podľa návodu. Napučané cesto pretlačte cez cedník na halušky priamo do vriacej vody a varte, kým nevyplávajú.",
            "Kyslú kapustu povarte v hrnci s vodou asi 10 minút; nevyvarenú vodu zlejte.",
            "Na panvici na masti opražte slaninu nakrájanú na menšie kúsky; keď je zľahka vypražená, pridajte na kolieska nakrájanú jarnú cibuľku a po minúte odstavte.",
            "Halušky zmiešajte s kapustou a na tanieri posypte slaninou s cibuľkou.",
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe rezy s čokoládovým pudingom",
        "teaser": "Radi by ste pohostili návštevu, ale nie ste práve Jamie Oliver? Nepečené bebe rezy zvládne naozaj každý.",
        "title": "Bebe rezy s čokoládovým pudingom — nepečený recept",
        "desc": "Nepečené bebe rezy s čokoládovým pudingom podľa Lucie Kůželovej: keksy, pudingový krém a šľahačka. Bez pečenia.",
        "product": "kakao_holandskeho_typu",
        "meta": "Nepečený dezert · Podľa Lucie Kůželovej",
        "ingredients": [
            "4 balíčky keksov BEBE: 2 svetlé, 2 tmavé",
            "2 kyslé smotany",
            "1 smotana na šľahanie",
            "40 g vanilkového cukru",
            "150 g čokoládového pudingu (3 balenia)",
            "1 liter mlieka",
            "kakao holandského typu na posypanie",
        ],
        "steps": [
            "Na plech poukladajte svetlé bebe keksy.",
            "Uvarte čokoládový puding podľa návodu na obale a nalejte ho na keksy tak, aby sa rovnomerne rozprestrel.",
            "Na vrstvu pudingu poukladajte tmavé bebe keksy.",
            "V mise vyšľahajte smotanu s vanilkovým cukrom dotuha, primiešajte kyslú smotanu a zmes rozotrite na keksy.",
            "Rez posypte tmavým kakaom a nechajte v chladničke odležať, najlepšie cez noc.",
        ],
        "notes": ["Tip: Ak máte poruke iný než čokoládový puding, experimentujte — rez chutí výborne aj s vanilkovým pudingom a škoricovým posypom."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Zemiakovo-tvarohové knedle s jahodami",
        "teaser": "Leto je tu a s ním aj dozrievanie jahôd. Jednoduchý a rýchly recept, ktorým za 20 minút potešíte aj najväčších maškrtníkov.",
        "title": "Zemiakovo-tvarohové knedle s jahodami — recept za 20 minút",
        "desc": "Ovocné knedle zo zemiakového cesta Jůzlová s tvarohom a jahodami podľa Lucie Kůželovej. Hotové za 20 minút.",
        "product": "bramborove_knedliky",
        "meta": "20 minút · Podľa Lucie Kůželovej",
        "ingredients": [
            "250 g zemiakových knedieľ v prášku",
            "250 g mäkkého tvarohu (v kocke, nie vo vaničke)",
            "jahody (ako plnka aj na ozdobu)",
            "cukor, maslo a tvaroh na ozdobu",
        ],
        "steps": [
            "Zemiakové knedle v prášku zmiešajte s vodou podľa návodu a pripravte vláčne cesto; zapracujte mäkký tvaroh (lepivé cesto neprekáža).",
            "Z cesta vytvarujte valec a nakrájajte ho na rovnako veľké časti, aby sa knedle varili rovnomerne.",
            "Každú časť zaguľaťte, dlaňami vytvorte placku, do stredu zatlačte jahodu a zabaľte.",
            "Knedle varte v pare 5 minút — cesto sa krásne uvarí a nerozvarí.",
            "Medzitým môžete povariť kúsky jahôd na ozdobu. Na tanieri knedle dozdobte maslom, cukrom, jahodami alebo tvarohom.",
        ],
        "notes": [],
    },
    "rychle-venecky-ci-vetrnicky-recept": {
        "name": "Rýchle venčeky či veterníčky",
        "teaser": "Jedno odpaľované cesto na venčeky aj veterníčky: vyšší podiel masla a štart na 250 °C. Asi 80 kúskov na dvoch plechách.",
        "title": "Rýchle venčeky či veterníčky z odpaľovaného cesta — recept",
        "desc": "Rýchle venčeky a veterníčky z odpaľovaného cesta: 250 ml vody, 90 g masla, 140 g hrubej múky, 4 vajcia. Príprava 45 min, pečenie cca 15 min, asi 80 kúskov.",
        "meta": "Príprava 45 min · Pečenie cca 15 min · asi 80 kúskov · 2 plechy",
        "ingredients": [
            "250 ml vody",
            "štipka soli",
            "90 g masla",
            "140 g hrubej múky",
            "4 vajcia",
            "tuk na vymastenie plechov",
        ],
        "steps": [
            "Vodu, soľ a maslo priveďte k varu.",
            "Stiahnite plameň a vmiešajte múku naraz; miešajte, kým sa cesto neodlepí od stien hrnca a nebude lepiť.",
            "Odstavte a nechajte mierne schladnúť.",
            "Rúru predhrejte na 250 °C.",
            "Po jednom zašľahajte vajcia a stále miešajte, kým nie je cesto hladké a mierne pružné.",
            "Na vymastené plechy striekajte venčeky ako dva naskladané krúžky, alebo veterníčky ako malé kopčeky.",
            "Pečte 5 minút na 250 °C, potom znížte na 200 °C a pečte dozlata — zhruba ďalších 5 minút na vyššej a 5 na strednej teplote. Rúru počas pečenia neotvárajte.",
            "Ešte horúce ihneď rozrežte (škrupinky sa potom netrhajú). Pred plnením úplne vychlaďte.",
        ],
        "notes": [
            "Náplň je voľná: najjednoduchšia je osladená šľahačka. K venčekom sa hodí vanilkový maslový krém a rumová poleva z receptu na venčeky, k veterníčkom vanilkový pudingový krém, karamelová šľahačka a karamelová poleva z receptu na karamelové veterníky.",
            "Cesto má vyšší pomer masla k múke (90 g : 140 g) a pečie sa s horúcim štartom 250 °C — preto rýchlejšie a spoľahlivejšie vykukne.",
        ],
    },
    "venecky-s-vanilkovym-kremem-recept": {
        "name": "Venčeky s vanilkovým krémom",
        "teaser": "Klasické venčeky z odpaľovaného cesta s vanilkovým maslovým krémom a rumovou polevou. Asi 20 kúskov.",
        "title": "Venčeky s vanilkovým krémom a rumovou polevou — recept",
        "desc": "Venčeky z odpaľovaného cesta s vanilkovým maslovým krémom z pudingu a žĺtkov a s rumovou polevou. Asi 20 kúskov.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 20 kúskov · odpaľované cesto, vanilkový krém, rumová poleva",
        "ingredients": [
            "Odpaľované cesto: 320 ml vody",
            "100 g masla",
            "štipka soli",
            "235 g múky",
            "4–5 vajec, pridávaných postupne",
            "Vanilkový maslový krém: 500 ml mlieka",
            "2 vrecúška vanilkového pudingu v prášku",
            "5 žĺtkov",
            "150 g cukru",
            "250 g zmäknutého masla",
            "2 lyžice rumu (podľa chuti)",
            "Rumová poleva: 300 g práškového cukru",
            "2 lyžice rumu",
            "3 lyžice horúceho mlieka",
        ],
        "steps": [
            "Vodu, maslo a soľ priveďte k varu. Odstavte, vmiešajte všetku múku a na miernom plameni 2–3 minúty varte, kým sa cesto nezrazí do gule.",
            "Nechajte schladnúť, kým je len vlažné. Postupne zašľahajte vajcia, kým cesto z lyžice padá v hustej stuhe.",
            "Na papier na pečenie striekajte krúžky s priemerom 6–7 cm. Pečte 10 minút na 200 °C bez otvárania dvierok, potom znížte na 180 °C a pečte ďalších 15–25 minút, kým nie sú venčeky sýto zlatisté a na omak suché.",
            "Úplne vychlaďte a ideálne nechajte niekoľko hodín alebo cez noc odkryté, aby škrupinky ostali chrumkavé.",
            "Puding uvarte s mliekom, cukrom a žĺtkami za stáleho miešania, kým zahustne (po pridaní žĺtkov už nevarte naplno). Vychlaďte, na povrch pritlačte fóliu.",
            "Zmäknuté maslo vyšľahajte do peny, po lyžiciach pridávajte vychladnutý puding a šľahajte dohladka. Nakoniec vmiešajte rum.",
            "Práškový cukor, rum a horúce mlieko vyšľahajte do hladkej, liatej polevy.",
            "Venčeky rozrežte vodorovne. Do spodnej polovice nastriekajte výdatne krém, priklopte a vrch namočte do rumovej polevy. Nechajte stuhnúť.",
        ],
        "notes": [
            "Ľahšia varianta: vynechajte rumovú polevu, namiesto maslového krému použite obyčajný pudingový krém a navrch dajte šľahačku a práškový cukor.",
        ],
    },
    "kremrole-recept": {
        "name": "Kremrole",
        "teaser": "Krehké trubičky plnené lesklým talianskym snehom. Asi 35–40 kúskov; budete potrebovať kovové trubičky na kremrole.",
        "title": "Kremrole z maslového cesta s talianskym snehom — recept",
        "desc": "Kremrole z maslového cesta so smotanou, plnené talianskym snehom. Asi 35–40 kúskov, pečenie 12–15 minút na 180–200 °C.",
        "meta": "Asi 35–40 kúskov · pečenie 12–15 min · kovové trubičky",
        "ingredients": [
            "Cesto: 350 g múky",
            "250 g studeného masla (alebo Hery), nastrúhaného alebo nakrájaného",
            "125 ml smotany na šľahanie",
            "voliteľne pre väčšiu krehkosť: 25 g smotany nahraďte kyslou smotanou",
            "Taliansky sneh: 80 g bielkov (asi 2 vajcia)",
            "160 g cukru",
            "40 ml vody",
            "práškový cukor na posyp",
        ],
        "steps": [
            "Múku, maslo a smotanu spracujte v hladké cesto — nepreháňajte to. Zabaľte a nechajte v chladničke najmenej hodinu, kľudne cez noc.",
            "Vyvaľkajte na tenký plát, nakrájajte prúžky 2 × 20 cm a každý oviňte okolo vymastenej kovovej trubičky, okraje mierne prekladajte.",
            "Pečte na 180–200 °C dozlata, asi 12–15 minút. Nechajte mierne schladnúť a opatrne stiahnite z trubičiek.",
            "Cukor s vodou zohrejte bez miešania na 115–120 °C (teplomer pomôže). Medzitým ušľahajte bielky do tuha.",
            "Pri chode mixéra tenkým pramienkom prilejte horúci sirup a šľahajte, kým nie je sneh lesklý a len vlažný. Krátko vychlaďte a striekajte do trubičiek z oboch koncov. Posypte práškovým cukrom.",
        ],
        "notes": [
            "Najjednoduchšia varianta: bielky s cukrom šľahajte priamo nad hrncom s mierne vriacou vodou (vodný kúpeľ), kým nie sú lesklé a husté — bez teplomera, o niečo menej stabilné, ale spoľahlivo dobré.",
            "Trubičky môžete improvizovať z alobalu, ak nemáte kovové formy.",
        ],
    },
    "minivetrnicky-recept": {
        "name": "Miniveterníčky",
        "teaser": "Malé veterníčky z odpaľovaného cesta s maslovo-pudingovým krémom s tvarohom a čokoládovou polevou. Asi 40–45 kúskov.",
        "title": "Miniveterníčky s pudingovým krémom a čokoládovou polevou — recept",
        "desc": "Miniveterníčky z odpaľovaného cesta: 250 ml vody, 90 g masla, 160 g múky, 4 vajcia. Náplň z vanilkového pudingu, masla a tvarohu, vrch s čokoládovou polevou. Asi 40–45 kúskov.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 40–45 kúskov · pečenie cca 20 min",
        "ingredients": [
            "Odpaľované cesto: 250 ml vody",
            "štipka soli",
            "90 g masla",
            "160 g múky",
            "1 lyžička kypriaceho prášku",
            "4 vajcia",
            "Náplň: 0,5 l mlieka",
            "2 vrecúška vanilkového pudingu v prášku",
            "3 lyžice cukru",
            "250 g zmäknutého masla",
            "125 g cukru",
            "vanilkový cukor",
            "2 lyžičky rumu",
            "asi 150–200 g tučného tvarohu",
            "Poleva: horká alebo mliečna čokoláda (s kúskom masla alebo oleja na lesk)",
        ],
        "steps": [
            "Vodu, maslo a soľ priveďte k varu. Odstavte, vmiešajte múku s kypriacim práškom dohladka a na miernom plameni miešajte, kým cesto mierne neschladne.",
            "Po jednom zašľahajte vajcia mixérom. Na papier na pečenie striekajte kopčeky 2–3 cm (alebo ich tvarujte dvoma lyžicami).",
            "Pečte na 200 °C asi 20 minút. Prvých 10 minút rúru neotvárajte.",
            "Puding uvarte a úplne vychlaďte (kľudne o niekoľko hodín skôr). Zmäknuté maslo vyšľahajte s cukrom a vanilkovým cukrom do peny, pridajte rum a po častiach zašľahajte puding a tvaroh dohladka.",
            "Vychladnuté veterníčky narežte do troch štvrtín, nastriekajte náplň a vrch namočte alebo natrite rozpustenou čokoládou.",
        ],
        "notes": [
            "Letná, ľahšia varianta: vynechajte maslový krém aj polevu — plňte osladenou šľahačkou a kúskami čerstvých jahôd, posypte práškovým cukrom.",
        ],
    },
    "karamelove-vetrniky-recept": {
        "name": "Karamelové veterníky",
        "teaser": "Veterníky s vanilkovým pudingovým krémom, karamelovou šľahačkou a karamelovou polevou. Asi 24 stredných kúskov.",
        "title": "Karamelové veterníky s dvojakým krémom — recept",
        "desc": "Karamelové veterníky z odpaľovaného cesta: vanilkový pudingový krém, karamelová šľahačka a karamelová poleva. Asi 24 stredných kúskov.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 24 stredných kúskov · karamelový krém radšej deň vopred",
        "ingredients": [
            "Odpaľované cesto: 250 ml vody",
            "100 g masla",
            "štipka soli",
            "160 g múky",
            "4–5 vajec (izbová teplota), rozšľahaných, pridávaných postupne",
            "½ lyžičky kypriaceho prášku",
            "Vanilkový pudingový krém: 400 ml mlieka",
            "1 vrecúško vanilkového pudingu v prášku",
            "3 lyžice cukru",
            "250 ml smotany na šľahanie (33 %), ušľahanej do tuha",
            "Karamelová šľahačka: 150 g cukru",
            "250 ml smotany na šľahanie (33 %), studenej, plus trochu na stiahnutie karamelu",
            "štipka soli",
            "Karamelová poleva: 125 g cukru",
            "45 g masla",
            "75 ml smotany na šľahanie",
            "voliteľne: 3–4 lyžice odloženej karamelovej šľahačky, zriedenej trochou práškového cukru",
        ],
        "steps": [
            "Vodu, maslo a soľ priveďte k varu. Odstavte, vsypte všetku múku, dôkladne zamiešajte a na miernom plameni 2–3 minúty varte, kým sa cesto nezrazí do gule a na dne hrnca sa neurobí tenký film.",
            "Cesto rozotierajte po stenách misy, aby rýchlejšie schladlo. Keď je len vlažné (horúce by zrazilo vajcia), po troškách zašľahajte vajcia na nízke otáčky. Prestaňte, keď cesto z lyžice padá v hustom „V“ — všetko vajce nemusíte spotrebovať. Nakoniec vmiešajte kypriaci prášok.",
            "Veľkou hviezdicovou špičkou striekajte na papier na pečenie kolá 4–5 cm, s veľkými rozostupmi. Pečte 10 minút na 200–220 °C, potom znížte na 170–180 °C a pečte ďalších 15–20 minút, kým nie sú sýto zlatisté a pevné. Rúru počas pečenia neotvárajte — veterníky spadnú. Pred plnením úplne vychlaďte.",
            "Puding uvarte s mliekom a cukrom podľa vrecúška a úplne vychlaďte (na povrch pritlačte fóliu). Keď sú puding aj šľahačka studené, šľahačku do pudingu zapracujte.",
            "Cukor nasucho rozpustite na panvici (nemiešajte, len otáčajte panvicou) do sýto jantárovej farby. Odstavte, opatrne prilejte trochu smotany — bude to búrlivo bublinkovať — potom vmiešajte zvyšok a štipku soli. Úplne vychlaďte, nechajte v chladničke niekoľko hodín alebo cez noc a ušľahajte do tuha. 3–4 lyžice odložte na polevu.",
            "Cukor na polevu skaramelizujte rovnako, odstavte, vmiešajte maslo a smotanu do hladka a lesku. Nechajte schladnúť, kým poleva obalí lyžicu, ale ešte sa dá liať.",
            "Každý vychladnutý veterník rozrežte vodorovne a vrch nechajte ako čiapočku. Do spodku nastriekajte vanilkový krém, naň krúžok karamelovej šľahačky, priklopte a prelejte alebo namočte do karamelovej polevy. Pred podávaním nechajte v chladničke aspoň 2 hodiny stuhnúť.",
        ],
        "notes": [
            "Vajcia do odpaľovaného cesta dávajte až vo vlažnom stave a po troškách — múka nasiakne vždy inak, hotovosť spoznáte podľa konzistencie, nie podľa toho, že spotrebujete všetko vajce.",
            "Rúru počas pečenia neotvárajte. Karamelovú šľahačku pripravte deň vopred, aby stihla stuhnúť na šľahanie.",
        ],
    },
    "irsky-sticky-toffee-pudding-recept": {
        "name": "Írsky sticky toffee pudding",
        "teaser": "Vlhký datľový zákusok s kakaom holandského typu a Baileys, preliaty slanou toffee omáčkou. 6 porcií.",
        "title": "Írsky sticky toffee pudding s kakaom a Baileys — recept",
        "desc": "Sticky toffee pudding podľa Donala Skehana s kakaom holandského typu a 100 ml Baileys v ceste. 6 porcií, pečenie 45–50 minút na 160 °C.",
        "product": "kakao_holandskeho_typu",
        "meta": "6 porcií · Pečenie 45–50 min · 160 °C",
        "ingredients": [
            "Cesto: 125 g masla",
            "150 g svetlého cukru muscovado",
            "1 lyžica zlatého sirupu (golden syrup)",
            "1 lyžica čiernej melasy (black treacle)",
            "2 veľké vajcia",
            "1 lyžička vanilkového extraktu",
            "150 g samokypriacej múky",
            "60 g kakaa holandského typu",
            "150 g datlí medjool, posekaných",
            "2 lyžičky jedlej sódy",
            "100 ml Baileys Irish Cream",
            "180 ml vody",
            "vanilková zmrzlina na podávanie",
            "Toffee omáčka: 100 g masla (nesoleného)",
            "150 g tmavého cukru muscovado",
            "3 lyžice zlatého sirupu",
            "150 ml hustej smotany (double cream)",
            "1 lyžička vanilkového extraktu",
            "štedrá štipka morskej soli",
        ],
        "steps": [
            "Rúru predhrejte na 160 °C (140 °C horúcovzdušne). Vymastite zapekaciu misu s priemerom 20 cm.",
            "Maslo a cukor vyšľahajte do svetlej peny.",
            "Na nízke otáčky pomaly vmiešajte zlatý sirup, melasu, vajcia a vanilku.",
            "Samokypriacu múku preosejte s kakaom a na nízke otáčky zapracujte do cesta.",
            "180 ml vody s posekanými datľami niekoľko minút povarte, odstavte a vmiešajte Baileys a jedlú sódu — zmes napení.",
            "Horúcu datľovo-baileysovú zmes zapracujte do kakaového cesta, vlejte do misy a pečte 45–50 minút, kým je puding pevný a mierne pružný. Špajľou kontrolujte vlhké drobky, nie farbu — cesto je tmavé.",
            "Omáčka: maslo, cukor a zlatý sirup rozohrejte, kým sa cukor nerozpustí. Pridajte smotanu, vanilku a soľ a 3 minúty mierne povarte, kým zahustne. Pre silnejšiu írsku chuť na záver mimo plotny vmiešajte 1–2 lyžice Baileys (voliteľné — alkohol sa už neodparí).",
            "Teplý puding prelejte toffee omáčkou a podávajte s vanilkovou zmrzlinou.",
        ],
        "notes": [
            "Baileys sa pridáva až po povaření datlí s vodou, mimo plotny — dlhší var by vyhnal alkohol a stlmil chuť likéru.",
            "Vody je o 100 ml menej ako v pôvodnom recepte (180 ml namiesto 280 ml), práve o množstvo pridaného Baileys, aby hydratácia cesta a čas pečenia ostali rovnaké.",
        ],
    },
}
