# Deutsche Rezepte — Übersetzung von recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Hausgemachter Lebkuchen (Perník)",
        "teaser": "Tassen-Lebkuchen: Alle Zutaten messen Sie mit einer Tasse ab, eine Waage brauchen Sie nicht. In zehn Minuten ist der Teig im Ofen.",
        "title": "Lebkuchen (Perník) — Tassenrezept nach Jiřina Jůzlová",
        "desc": "Tassen-Lebkuchen ohne Abwiegen: 10 Minuten Zubereitung, 20–25 Minuten Backzeit, 25–30 Portionen. Mit Vanillepudding und Kakao holländischer Art.",
        "product": "vanilkovy_pudink",
        "meta": "Zubereitung 10 Min. · Backen 20–25 Min. · 25–30 Portionen",
        "ingredients": [
            "3 Tassen glattes Weizenmehl (Tasse = 200 ml)",
            "2 Tassen Kristallzucker",
            "1 Tasse Öl",
            "2 mittelgroße Eier",
            "2 gehäufte Esslöffel Vanillepuddingpulver",
            "1 Päckchen Lebkuchen-Backmischung (Gewürz mit Triebmittel)",
            "½ Päckchen Backpulver",
            "250 ml Milch (1¼ Tassen)",
            "Kakao holländischer Art nach Geschmack",
        ],
        "steps": [
            "Geben Sie alle Zutaten in eine Schüssel und verrühren Sie sie gründlich mit dem Mixer, damit keine Klümpchen bleiben.",
            "Gießen Sie den Teig auf ein gefettetes, mit griffigem Mehl bestäubtes Backblech.",
            "Backen Sie im auf 180 °C vorgeheizten Ofen 20 bis 25 Minuten (je nach Blechhöhe).",
            "Die Garprobe machen Sie mit einem Holzstäbchen: Es muss sauber herauskommen, ohne anhaftenden Teig.",
        ],
        "notes": ["Tipp: Nach Geschmack können Sie dem Teig etwas Rum oder Rumaroma, Zimt, grob gehackte Walnüsse oder Schokolade hinzufügen."],
    },
    "slehackova-rolada-recept": {
        "name": "Sahneroulade",
        "teaser": "Ein leichtes Dessert in einer halben Stunde: der Kontrast von herbem Kakao und zart gesüßter Schlagsahne. Ohne Mehl, also auch ohne Gluten.",
        "title": "Sahneroulade — glutenfreies Rezept mit Kakao",
        "desc": "Sahneroulade ohne Mehl und ohne Gluten: 5 Eier, Puderzucker, Kakao holländischer Art und Schlagsahne. Fertig in 30 Minuten.",
        "product": "kakao_holandskeho_typu",
        "meta": "Zubereitung ca. 30 Min. · Glutenfrei",
        "ingredients": [
            "5 Eier",
            "100 g Puderzucker",
            "1 Esslöffel Kakao holländischer Art",
            "1 Becher Schlagsahne (nach Belieben Sahnesteif)",
        ],
        "steps": [
            "Schlagen Sie das Eiweiß zu steifem Schnee, geben Sie dann die Eigelbe und den Puderzucker dazu. Durch vorsichtiges Unterheben entsteht ein glatter Teig.",
            "Geben Sie zuletzt den Kakao holländischer Art dazu — er sorgt für eine satte Schokoladenfarbe und kräftigen Geschmack.",
            "Bereiten Sie ein leicht mit Schmalz gefettetes Backpapier vor (Öl geht auch), damit sich die Roulade nach dem Backen gut aufrollen lässt.",
            "Backen Sie im auf 180 °C vorgeheizten Ofen etwa 8 Minuten; öffnen Sie den Ofen während der gesamten Zeit nicht.",
            "Lassen Sie die Roulade auf dem Blech abkühlen und lösen Sie sie vorsichtig vom Papier.",
            "Schlagen Sie die Sahne steif, bestreichen Sie die Roulade damit und rollen Sie sie auf. Verzieren Sie die Oberseite mit der restlichen Sahne, nach Belieben mit Schokoladenspänen.",
        ],
        "notes": ["Tipp: Verfeinern Sie die Roulade mit Ihrem Lieblingsobst — Erdbeeren, Himbeeren oder Banane."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Birnenkuchen mit Vanillepudding",
        "teaser": "Ein Kuchen, bei dem Kinder gern mithelfen. Die Freude kommt zweimal — beim Backen und beim Probieren.",
        "title": "Birnenkuchen mit Vanillepudding — Rezept von Lucie Kůželová",
        "desc": "Birnenkuchen mit Sauerrahm und Vanillepudding: 20 Minuten Zubereitung, 45 Minuten Backzeit, 8 Portionen. Gelingt auch mit Äpfeln, Himbeeren oder Pfirsichen.",
        "product": "vanilkovy_pudink",
        "meta": "Zubereitung 20 Min. · Backen 45 Min. · 8 Portionen",
        "ingredients": [
            "2 Eier",
            "80 g zerlassene Butter",
            "150 g Kristallzucker",
            "200 g glattes Weizenmehl (teilweise durch Vollkorn- oder Dinkelmehl ersetzbar)",
            "1 Päckchen Backpulver",
            "2 Becher Sauerrahm",
            "1 Becher Schlagsahne (30 %)",
            "40 g Vanillepuddingpulver",
            "5 Birnen (ersatzweise Äpfel, Himbeeren, Pfirsiche — frisches oder gefrorenes Obst)",
        ],
        "steps": [
            "Vermischen Sie ein Ei, die Butter, 50 g Zucker, das Mehl und das Backpulver. Kneten Sie den Teig mit den Händen und drücken Sie ihn in eine mit Backpapier ausgelegte Kuchenform. Krümelt der Teig, ist das kein Problem — einfach festdrücken.",
            "Schneiden Sie die geschälten Birnen in Spalten und verteilen Sie sie auf dem Teig.",
            "Verrühren Sie in einer Schüssel den Sauerrahm, die Schlagsahne, das Puddingpulver, 100 g Zucker und das zweite Ei; gießen Sie die Mischung über den Kuchen.",
            "Backen Sie in der Mitte des auf 180 °C vorgeheizten Ofens etwa 45 Minuten.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Mohnnudeln (šišky s mákem)",
        "teaser": "Ein traditionelles süßes Abendessen aus Kartoffelteig: Mohnnudeln, in Mohn und Zucker gewälzt und mit zerlassener Butter übergossen.",
        "title": "Mohnnudeln (šišky s mákem) aus Kartoffelteig — Rezept",
        "desc": "Gebackene Mohnnudeln (šišky s mákem) aus unserer Kartoffelknödel-Mischung: goldbraun gebacken, überbrüht und in Mohn mit Zucker und Butter gewälzt.",
        "product": "bramborove_knedliky",
        "meta": "Aus unserer Kartoffelknödel-Mischung",
        "ingredients": [
            "400 g Kartoffelknödel-Mischung",
            "100 g gemahlener Mohn",
            "2 Esslöffel Puderzucker (gern auch mehr)",
            "2 Esslöffel zerlassene Butter",
        ],
        "steps": [
            "Rühren Sie die Kartoffelknödel-Mischung nach Anleitung mit Wasser an und formen Sie aus dem Teig kleine Nudeln.",
            "Backen Sie sie auf einem gefetteten Blech in der Mitte des auf 200 °C vorgeheizten Ofens. Wenden Sie die Nudeln einmal, damit sie von beiden Seiten goldgelb werden.",
            "Geben Sie die Nudeln nach dem Backen in kochendes Wasser und brühen Sie sie 5 Minuten.",
            "Geben Sie sie in eine große Schüssel, bestreuen Sie sie mit Mohn und Zucker und übergießen Sie sie mit der Butter. Alles vermengen und noch warm servieren.",
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky mit Kraut und Speck",
        "teaser": "Ein slowakischer Klassiker aus unserer rohen Kartoffelknödel-Mischung — Halušky mit Sauerkraut und knusprig ausgebratenem Speck.",
        "title": "Strapačky mit Kraut und Speck — Rezept",
        "desc": "Strapačky aus unserer rohen Kartoffelknödel-Mischung mit Sauerkraut, Frühlingszwiebeln und in Schmalz ausgebratenem Speck. Ein deftiger slowakischer Klassiker.",
        "product": "chlupate_knedliky",
        "meta": "Aus der rohen Kartoffelknödel-Mischung (chlupaté knedlíky)",
        "ingredients": [
            "400 g rohe Kartoffelknödel-Mischung (chlupaté knedlíky)",
            "400 g Sauerkraut",
            "1 Bund Frühlingszwiebeln",
            "100 g Speck",
            "1 Esslöffel Schmalz",
        ],
        "steps": [
            "Rühren Sie die Mischung nach Anleitung mit Wasser an. Drücken Sie den gequollenen Teig durch ein Sieb direkt ins kochende Wasser und garen Sie die Halušky, bis sie an die Oberfläche steigen.",
            "Kochen Sie das Sauerkraut in einem Topf mit Wasser etwa 10 Minuten und gießen Sie das restliche Wasser ab.",
            "Braten Sie den klein geschnittenen Speck in einer Pfanne im Schmalz aus. Sobald er leicht knusprig ist, geben Sie die in Ringe geschnittenen Frühlingszwiebeln dazu und nehmen die Pfanne nach einer Minute vom Herd.",
            "Vermengen Sie die Halušky mit dem Kraut und bestreuen Sie sie auf dem Teller mit dem Speck und den Zwiebeln.",
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe-Schnitten mit Schokoladenpudding",
        "teaser": "Sie möchten Gäste bewirten, sind aber kein Jamie Oliver? Diese Bebe-Schnitten ohne Backen gelingen wirklich jedem.",
        "title": "Bebe-Schnitten mit Schokoladenpudding — ohne Backen",
        "desc": "Bebe-Schnitten ohne Backen mit Schokoladenpudding nach Lucie Kůželová: Kekse, Puddingcreme und Schlagsahne. Ganz ohne Ofen.",
        "product": "kakao_holandskeho_typu",
        "meta": "Dessert ohne Backen · Nach Lucie Kůželová",
        "ingredients": [
            "4 Päckchen Bebe-Kekse (2 helle, 2 dunkle)",
            "2 Becher saure Sahne",
            "1 Becher Schlagsahne",
            "40 g Vanillinzucker",
            "150 g unser Vanillepuddingpulver und 2 EL Kakaopulver holländischer Art",
            "1 Liter Milch",
            "Kakao holländischer Art zum Bestäuben",
        ],
        "steps": [
            "Legen Sie ein Blech mit den hellen Bebe-Keksen aus.",
            "Kochen Sie den Schokoladenpudding nach Packungsanleitung und gießen Sie ihn gleichmäßig über die Kekse.",
            "Legen Sie die dunklen Bebe-Kekse auf die Puddingschicht.",
            "Schlagen Sie die Sahne mit dem Vanillinzucker steif, heben Sie die saure Sahne unter und streichen Sie die Creme auf die Kekse.",
            "Bestäuben Sie die Schnitten mit dunklem Kakao und lassen Sie sie im Kühlschrank durchziehen, am besten über Nacht.",
        ],
        "notes": ["Tipp: Haben Sie gerade keinen Schokoladenpudding zur Hand, nehmen Sie Vanillepudding und bestäuben Sie die Schnitten mit Zimt — das schmeckt ebenso gut."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Kartoffel-Quark-Knödel mit Erdbeeren",
        "teaser": "Der Sommer ist da, und mit ihm reifen die Erdbeeren. Ein einfaches, schnelles Rezept, mit dem Sie in 20 Minuten auch die größten Naschkatzen verwöhnen.",
        "title": "Kartoffel-Quark-Knödel mit Erdbeeren — Rezept in 20 Minuten",
        "desc": "Fruchtknödel aus unserer Kartoffelknödel-Mischung mit Quark und Erdbeeren nach Lucie Kůželová. Fertig in 20 Minuten.",
        "product": "bramborove_knedliky",
        "meta": "20 Minuten · Nach Lucie Kůželová",
        "ingredients": [
            "250 g Kartoffelknödel-Mischung",
            "250 g weicher Quark (im Block, nicht im Becher)",
            "Erdbeeren (als Füllung und zum Garnieren)",
            "Zucker, Butter und Quark zum Garnieren",
        ],
        "steps": [
            "Rühren Sie die Kartoffelknödel-Mischung nach Anleitung mit Wasser zu einem geschmeidigen Teig an und arbeiten Sie den Quark ein. Klebt der Teig etwas, ist das kein Problem.",
            "Formen Sie aus dem Teig eine Rolle und schneiden Sie sie in gleich große Stücke, damit die Knödel gleichmäßig garen.",
            "Formen Sie jedes Stück zu einer Kugel, drücken Sie es flach, legen Sie eine Erdbeere in die Mitte und schließen Sie den Teig darüber.",
            "Dämpfen Sie die Knödel 5 Minuten — der Teig gart dabei schön durch, ohne zu zerfallen.",
            "In der Zwischenzeit können Sie Erdbeerstücke zum Garnieren kurz einkochen. Richten Sie die Knödel mit Butter, Zucker, Erdbeeren oder Quark an.",
        ],
        "notes": [],
    },
    "rychle-venecky-ci-vetrnicky-recept": {
        "name": "Schnelle Brandteigkränze oder Windbeutel",
        "teaser": "Ein Brandteig für Věnečky und Větrníčky: mehr Butter und ein Start bei 250 °C. Etwa 80 Stück auf zwei Blechen.",
        "title": "Schnelle Věnečky oder Větrníčky aus Brandteig — Rezept",
        "desc": "Schnelle tschechische Brandteigkränze und Windbeutel: 250 ml Wasser, 90 g Butter, 140 g grobes Mehl, 4 Eier. 45 Min. Zubereitung, ca. 15 Min. Backzeit, etwa 80 Stück.",
        "meta": "Zubereitung 45 Min. · Backen ca. 15 Min. · etwa 80 Stück · 2 Bleche",
        "ingredients": [
            "250 ml Wasser",
            "eine Prise Salz",
            "90 g Butter",
            "140 g griffiges Mehl (hrubá mouka; in Deutschland doppelgriffiges Mehl)",
            "4 Eier",
            "Fett zum Einfetten der Bleche",
        ],
        "steps": [
            "Wasser, Salz und Butter zum Kochen bringen.",
            "Die Hitze reduzieren und das Mehl auf einmal einrühren. Rühren, bis sich der Teig vom Topf löst und nicht mehr klebt.",
            "Vom Herd nehmen und leicht abkühlen lassen.",
            "Den Ofen auf 250 °C vorheizen.",
            "Die Eier nacheinander unter ständigem Rühren einarbeiten, bis der Teig glatt und leicht elastisch ist.",
            "Auf gefettete Bleche spritzen: zwei übereinanderliegende Ringe für Věnečky oder kleine Häufchen für Větrníčky.",
            "5 Minuten bei 250 °C backen, dann auf 200 °C senken und goldbraun backen — etwa 5 weitere Minuten bei hoher und 5 bei mittlerer Hitze. Den Ofen während des Backens nicht öffnen.",
            "Noch heiß sofort aufschneiden, dann reißen die Hüllen später nicht. Vor dem Füllen vollständig auskühlen lassen.",
        ],
        "notes": [
            "Die Füllung ist Ihnen überlassen; gezuckerte Schlagsahne ist am einfachsten. Zu den Kränzen passen Vanillebuttercreme und Rumguss aus dem Věnečky-Rezept, zu den Windbeuteln Vanillepuddingcreme, Karamellsahne und Karamellguss aus dem Karamell-Větrník-Rezept.",
            "Der Teig hat ein höheres Butter-Mehl-Verhältnis (90 g zu 140 g) und startet bei 250 °C — deshalb geht er schneller und zuverlässiger auf.",
        ],
    },
    "venecky-s-vanilkovym-kremem-recept": {
        "name": "Brandteigkränze mit Vanillecreme",
        "teaser": "Klassische Věnečky aus Brandteig mit Vanillebuttercreme und Rumguss. Etwa 20 Stück.",
        "title": "Věnečky mit Vanillecreme und Rumguss — Rezept",
        "desc": "Brandteig-Věnečky mit Vanillebuttercreme aus Puddingpulver und Eigelben, mit Rumguss. Etwa 20 Stück.",
        "product": "vanilkovy_pudink",
        "meta": "Etwa 20 Stück · Brandteig, Vanillecreme, Rumguss",
        "ingredients": [
            "Brandteig: 320 ml Wasser",
            "100 g Butter",
            "eine Prise Salz",
            "235 g Mehl",
            "4–5 Eier, nach und nach zugegeben",
            "Vanillebuttercreme: 500 ml Milch",
            "2 Päckchen Vanillepuddingpulver",
            "5 Eigelbe",
            "150 g Zucker",
            "250 g weiche Butter",
            "2 Esslöffel Rum (nach Geschmack)",
            "Rumguss: 300 g Puderzucker",
            "2 Esslöffel Rum",
            "3 Esslöffel heiße Milch",
        ],
        "steps": [
            "Wasser, Butter und Salz zum Kochen bringen. Vom Herd nehmen, das ganze Mehl einrühren und 2–3 Minuten bei kleiner Hitze kochen, bis sich der Teig zu einer Kugel zusammenzieht.",
            "Abkühlen lassen, bis der Teig nur noch lauwarm ist. Die Eier nach und nach einschlagen, bis der Teig vom Löffel in einem dicken Band fällt.",
            "Ringe von 6–7 cm Durchmesser auf Backpapier spritzen. 10 Minuten bei 200 °C backen, ohne die Tür zu öffnen. Dann auf 180 °C senken und weitere 15–25 Minuten backen, bis die Ringe satt goldbraun sind und sich trocken anfühlen.",
            "Vollständig auskühlen lassen, am besten einige Stunden oder über Nacht unbedeckt, damit die Hüllen knusprig bleiben.",
            "Den Pudding mit Milch, Zucker und Eigelben unter ständigem Rühren dick einkochen; nach Zugabe der Eigelbe nicht mehr stark kochen. Vollständig auskühlen lassen, dabei Frischhaltefolie direkt auf die Oberfläche drücken.",
            "Die weiche Butter schaumig schlagen, den erkalteten Pudding löffelweise zugeben und glatt schlagen. Zum Schluss den Rum unterrühren.",
            "Puderzucker, Rum und heiße Milch zu einem glatten, gießfähigen Guss verrühren.",
            "Die Ringe waagerecht aufschneiden. Die untere Hälfte großzügig mit Creme füllen, den Deckel aufsetzen und die Oberseite in den Rumguss tauchen. Den Guss fest werden lassen.",
        ],
        "notes": [
            "Leichtere Variante: den Rumguss weglassen, statt Buttercreme eine einfache Puddingcreme verwenden und mit Schlagsahne und Puderzucker abschließen.",
        ],
    },
    "kremrole-recept": {
        "name": "Schaumrollen (Kremrole)",
        "teaser": "Mürbe Röhrchen, gefüllt mit glänzendem italienischem Baiser. Etwa 35–40 Stück; Sie brauchen Schaumrollen-Formen aus Metall.",
        "title": "Schaumrollen (Kremrole) mit italienischem Baiser — Rezept",
        "desc": "Schaumrollen (Kremrole) aus Butterteig mit italienischem Baiser. Etwa 35–40 Stück, Backzeit 12–15 Minuten bei 180–200 °C.",
        "meta": "Etwa 35–40 Stück · Backen 12–15 Min. · Metallformen",
        "ingredients": [
            "Teig: 350 g Mehl",
            "250 g kalte Butter (oder Backmargarine), gerieben oder gewürfelt",
            "125 ml Schlagsahne",
            "optional, damit der Teig blättriger wird: 25 g der Sahne durch saure Sahne ersetzen",
            "Italienisches Baiser: 80 g Eiweiß (etwa 2 Eier)",
            "160 g Zucker",
            "40 ml Wasser",
            "Puderzucker zum Bestäuben",
        ],
        "steps": [
            "Mehl, Butter und Sahne zu einem glatten Teig verarbeiten — nicht überkneten. Einwickeln und mindestens 1 Stunde kühlen, auch über Nacht möglich.",
            "Dünn ausrollen, Streifen von 2 × 20 cm schneiden und jeden Streifen um eine gefettete Metallform wickeln; die Ränder dabei leicht überlappen lassen.",
            "Bei 180–200 °C goldbraun backen, etwa 12–15 Minuten. Leicht abkühlen lassen und vorsichtig von den Formen ziehen.",
            "Zucker und Wasser ohne Rühren auf 115–120 °C erhitzen (ein Zuckerthermometer hilft). Parallel das Eiweiß steif schlagen.",
            "Bei laufendem Mixer den heißen Sirup in einem dünnen Strahl einlaufen lassen und weiterschlagen, bis das Baiser glänzt und nur noch lauwarm ist. Kurz kühlen und die Röhrchen von beiden Enden füllen. Mit Puderzucker bestäuben.",
        ],
        "notes": [
            "Einfachste Variante: Eiweiß und Zucker über dem Wasserbad schlagen, bis die Masse glänzt und dick ist. Ohne Thermometer, etwas weniger stabil, aber verlässlich.",
            "Die Formen können Sie aus Alufolie improvisieren, wenn Sie keine Metallröhrchen haben.",
        ],
    },
    "minivetrnicky-recept": {
        "name": "Mini-Windbeutel (Minivětrníčky)",
        "teaser": "Kleine Větrníčky aus Brandteig mit Butter-Pudding-Quark-Creme und Schokoladenguss. Etwa 40–45 Stück.",
        "title": "Minivětrníčky mit Puddingcreme und Schokoladenguss — Rezept",
        "desc": "Minivětrníčky aus Brandteig: 250 ml Wasser, 90 g Butter, 160 g Mehl, 4 Eier. Füllung aus Vanillepudding, Butter und Quark, oben Schokoladenguss. Etwa 40–45 Stück.",
        "product": "vanilkovy_pudink",
        "meta": "Etwa 40–45 Stück · Backen ca. 20 Min.",
        "ingredients": [
            "Brandteig: 250 ml Wasser",
            "eine Prise Salz",
            "90 g Butter",
            "160 g Mehl",
            "1 Teelöffel Backpulver",
            "4 Eier",
            "Füllung: 500 ml Milch",
            "2 Päckchen Vanillepuddingpulver",
            "3 Esslöffel Zucker",
            "250 g weiche Butter",
            "125 g Zucker",
            "Vanillinzucker",
            "2 Teelöffel Rum",
            "etwa 150–200 g vollfetter Quark (tvaroh)",
            "Guss: Zartbitter- oder Milchschokolade (mit etwas Butter oder Öl für Glanz)",
        ],
        "steps": [
            "Wasser, Butter und Salz zum Kochen bringen. Vom Herd nehmen, Mehl und Backpulver glatt einrühren, dann kurz bei kleiner Hitze weiterrühren und den Teig leicht abkühlen lassen.",
            "Die Eier nacheinander mit dem Mixer einschlagen. Kleine Häufchen von 2–3 cm auf Backpapier spritzen; ohne Spritzbeutel geht es auch mit zwei Löffeln.",
            "Bei 200 °C etwa 20 Minuten backen. Die ersten 10 Minuten den Ofen nicht öffnen.",
            "Den Pudding kochen und vollständig auskühlen lassen, gern einige Stunden vorher. Die weiche Butter mit Zucker und Vanillinzucker schaumig schlagen, Rum zugeben, dann den erkalteten Pudding und den Quark portionsweise glatt unterheben.",
            "Die ausgekühlten Windbeutel zu drei Vierteln einschneiden, die Füllung hineinspritzen und die Oberseite in geschmolzene Schokolade tauchen oder bestreichen.",
        ],
        "notes": [
            "Leichtere Sommervariante: Buttercreme und Guss weglassen — mit gezuckerter Schlagsahne und frischen Erdbeerstücken füllen, mit Puderzucker bestäuben.",
        ],
    },
    "karamelove-vetrniky-recept": {
        "name": "Karamell-Windbeutel (Větrníky)",
        "teaser": "Větrníky mit Vanillepuddingcreme, Karamellsahne und Karamellguss. Etwa 24 mittlere Stück.",
        "title": "Karamell-Větrníky mit zweifacher Creme — Rezept",
        "desc": "Karamell-Větrníky aus Brandteig: Vanillepuddingcreme, Karamellsahne und Karamellguss. Etwa 24 mittlere Stück.",
        "product": "vanilkovy_pudink",
        "meta": "Etwa 24 mittlere Stück · Karamellsahne am Vortag zubereiten",
        "ingredients": [
            "Brandteig: 250 ml Wasser",
            "100 g Butter",
            "eine Prise Salz",
            "160 g Mehl",
            "4–5 Eier (Zimmertemperatur), verquirlt, nach und nach zugegeben",
            "½ Teelöffel Backpulver",
            "Vanillepuddingcreme: 400 ml Milch",
            "1 Päckchen Vanillepuddingpulver",
            "3 Esslöffel Zucker",
            "250 ml Schlagsahne (33 %), steif geschlagen",
            "Karamellsahne: 150 g Zucker",
            "250 ml Schlagsahne (33 %), kalt, plus ein Schuss zum Ablöschen",
            "eine Prise Salz",
            "Karamellguss: 125 g Zucker",
            "45 g Butter",
            "75 ml Schlagsahne",
            "optional: 3–4 Esslöffel der zurückgelegten Karamellsahne, mit etwas Puderzucker verrührt",
        ],
        "steps": [
            "Wasser, Butter und Salz zum Kochen bringen. Vom Herd nehmen, das ganze Mehl auf einmal zugeben, kräftig rühren, dann 2–3 Minuten bei kleiner Hitze kochen, bis sich der Teig zu einer Kugel zusammenzieht und ein dünner Film am Topfboden entsteht.",
            "Den Teig an den Schüsselwänden verstreichen, damit er schnell abkühlt. Erst wenn er nur noch lauwarm ist, die verquirlten Eier nach und nach auf niedriger Stufe einschlagen — heiß würde er die Eier stocken lassen. Aufhören, wenn der Teig vom Löffel in einem dicken „V“ fällt; Sie brauchen nicht unbedingt alle Eier. Zum Schluss das Backpulver unterheben.",
            "Mit einer großen Sterntülle 4–5 cm große Kreise mit Abstand auf Backpapier spritzen. 10 Minuten bei 200–220 °C backen, dann auf 170–180 °C senken und weitere 15–20 Minuten backen, bis sie satt goldbraun und fest sind. Den Ofen während des Backens nicht öffnen, sonst fallen die Windbeutel zusammen. Vor dem Füllen vollständig auskühlen lassen.",
            "Den Pudding mit Milch und Zucker nach Packungsanleitung kochen und vollständig auskühlen lassen; dabei Frischhaltefolie auf die Oberfläche drücken. Die steif geschlagene Sahne unterheben, sobald beides kalt ist.",
            "Den Zucker trocken in der Pfanne schmelzen — nicht rühren, nur schwenken —, bis er tief bernsteinfarben ist. Vom Herd nehmen, vorsichtig einen Schuss Sahne zugießen (es sprudelt heftig), dann den Rest und eine Prise Salz einrühren. Vollständig auskühlen lassen, mehrere Stunden oder über Nacht kühlen, dann steif schlagen. 3–4 Esslöffel für den Guss zurücklegen.",
            "Den Zucker für den Guss ebenso karamellisieren, vom Herd nehmen, Butter und Sahne glatt und glänzend einrühren. Abkühlen lassen, bis der Guss den Löffel überzieht, aber noch gießfähig ist.",
            "Jeden ausgekühlten Windbeutel waagerecht aufschneiden, den Deckel behalten. Unten Vanillepuddingcreme spritzen, darüber einen Kranz Karamellsahne, den Deckel aufsetzen und mit Karamellguss überziehen. Vor dem Servieren mindestens 2 Stunden kühlen, damit die Schichten fest werden.",
        ],
        "notes": [
            "Die Eier erst in den lauwarmen Brandteig geben, und zwar nach und nach: Mehl nimmt Flüssigkeit unterschiedlich auf. Die Konsistenz entscheidet, nicht die Zahl der Eier.",
            "Den Ofen während des Backens nicht öffnen. Die Karamellsahne am Vortag zubereiten, damit sie fest genug zum Schlagen wird.",
        ],
    },
    "irsky-sticky-toffee-pudding-recept": {
        "name": "Irischer Sticky-Toffee-Pudding",
        "teaser": "Feuchter Dattelpudding mit Kakao holländischer Art und Baileys, dazu salzige Toffeesauce. 6 Portionen.",
        "title": "Irischer Sticky-Toffee-Pudding mit Kakao und Baileys — Rezept",
        "desc": "Sticky-Toffee-Pudding nach Donal Skehan mit Kakao holländischer Art und 100 ml Baileys im Teig. 6 Portionen, 45–50 Minuten bei 160 °C.",
        "product": "kakao_holandskeho_typu",
        "meta": "6 Portionen · Backen 45–50 Min. · 160 °C",
        "ingredients": [
            "Pudding: 125 g Butter",
            "150 g heller Muscovadozucker",
            "1 Esslöffel Goldsirup (golden syrup)",
            "1 Esslöffel schwarze Melasse (black treacle)",
            "2 große Eier",
            "1 Teelöffel Vanilleextrakt",
            "150 g Mehl mit Backtriebmittel (self-raising flour)",
            "60 g Kakao holländischer Art",
            "150 g Medjool-Datteln, gehackt",
            "2 Teelöffel Natron",
            "100 ml Baileys Irish Cream",
            "180 ml Wasser",
            "Vanilleeis zum Servieren",
            "Toffeesauce: 100 g ungesalzene Butter",
            "150 g dunkler Muscovadozucker",
            "3 Esslöffel Goldsirup",
            "150 ml Doppelrahm (double cream)",
            "1 Teelöffel Vanilleextrakt",
            "eine großzügige Prise Meersalz",
        ],
        "steps": [
            "Den Ofen auf 160 °C (140 °C Umluft) vorheizen. Eine runde Auflaufform von 20 cm einfetten.",
            "Butter und Zucker hell und schaumig schlagen.",
            "Auf niedriger Stufe langsam Goldsirup, Melasse, Eier und Vanille unterrühren.",
            "Mehl und Kakao sieben und auf niedriger Stufe unterheben.",
            "Die 180 ml Wasser mit den gehackten Datteln einige Minuten köcheln lassen, vom Herd nehmen, dann Baileys und Natron einrühren — die Mischung schäumt auf.",
            "Die heiße Dattel-Baileys-Mischung unter den Kakao-Teig heben, in die Form gießen und 45–50 Minuten backen, bis der Pudding fest und leicht federnd ist. Mit einem Holzstäbchen auf feuchte Krümel prüfen, nicht nach der Farbe — der Teig ist dunkel.",
            "Sauce: Butter, Zucker und Goldsirup schmelzen, bis sich der Zucker auflöst. Rahm, Vanille und Salz zugeben und 3 Minuten köcheln lassen, bis die Sauce dick wird. Für mehr Likörgeschmack zum Schluss, vom Herd genommen, 1–2 Esslöffel Baileys unterrühren (optional; der Alkohol verdampft dann nicht mehr).",
            "Den warmen Pudding mit Toffeesauce übergießen und mit Vanilleeis servieren.",
        ],
        "notes": [
            "Der Baileys kommt erst nach dem Köcheln der Datteln dazu, vom Herd genommen — längeres Kochen würde den Alkohol vertreiben und den Likörgeschmack dämpfen.",
            "Das Rezept enthält 100 ml weniger Wasser als das Original (180 ml statt 280 ml) — genau die Menge des Baileys. So bleiben Flüssigkeitsanteil und Backzeit gleich.",
        ],
    },
}
