# Deutsche Rezepte — Übersetzung von recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Hausgemachter Lebkuchen (Perník)",
        "teaser": "Tassen-Lebkuchen, den Sie für die einfache Zubereitung und den köstlichen Geschmack lieben werden. Keine Waage nötig — eine Tasse genügt.",
        "title": "Lebkuchen (Perník) — Tassenrezept nach Jiřina Jůzlová",
        "desc": "Tassen-Lebkuchen ohne Abwiegen: 10 Minuten Zubereitung, 20–25 Minuten Backzeit, 25–30 Portionen. Mit Vanillepudding und Kakao holländischer Art.",
        "product": "vanilkovy_pudink",
        "meta": "Zubereitung 10 Min. · Backen 20–25 Min. · 25–30 Portionen",
        "ingredients": [
            "3 Tassen glattes Mehl (Tasse = 200 ml)",
            "2 Tassen Kristallzucker",
            "1 Tasse Öl",
            "2 mittelgroße Eier",
            "2 gehäufte Esslöffel Vanillepuddingpulver",
            "1 Päckchen Lebkuchen-Backmischung (Gewürz-Triebmittel)",
            "½ Päckchen Backpulver",
            "250 ml Milch (1¼ Tassen)",
            "Kakao holländischer Art nach Geschmack",
        ],
        "steps": [
            "Geben Sie alle Zutaten in eine Schüssel und vermischen Sie sie gründlich mit dem Mixer, damit sich keine Klümpchen bilden.",
            "Gießen Sie den Teig auf ein gefettetes, mit grobem Mehl bestäubtes Backblech.",
            "Backen Sie im auf 180 °C vorgeheizten Ofen 20 bis 25 Minuten (je nach Blechhöhe).",
            "Ob der Lebkuchen fertig ist, prüfen Sie mit einem Holzstäbchen — nach dem Einstechen muss es sauber bleiben, ohne anhaftenden Teig.",
        ],
        "notes": ["Tipp: Nach Geschmack können Sie dem Teig etwas Rum oder Rumaroma, Zimt, grob gehackte Walnüsse oder Schokolade hinzufügen."],
    },
    "slehackova-rolada-recept": {
        "name": "Sahneroulade",
        "teaser": "Ein leichtes Dessert in einer halben Stunde: der Kontrast von herbem Kakao und zart gesüßter Schlagsahne. Ohne Mehl, also auch ohne Gluten.",
        "title": "Sahneroulade — glutenfreies Rezept mit Kakao",
        "desc": "Sahneroulade ohne Mehl und ohne Gluten: 5 Eier, Puderzucker, Kakao holländischer Art und Schlagsahne. Fertig in 30 Minuten.",
        "product": "kakao_holandskeho_typu",
        "meta": "Zubereitung ca. 30 Min. · Glutenfrei",
        "ingredients": [
            "5 Eier",
            "100 g Puderzucker",
            "1 Esslöffel Kakao holländischer Art",
            "1 Becher Schlagsahne (nach Belieben Sahnesteif)",
        ],
        "steps": [
            "Schlagen Sie das Eiweiß zu steifem Schnee, geben Sie dann die Eigelbe und den Puderzucker dazu. Durch vorsichtiges Unterheben entsteht ein glatter Teig.",
            "Fügen Sie zuletzt den Kakao holländischer Art hinzu — er sorgt für eine satte Schokoladenfarbe und einen kräftigen Geschmack.",
            "Bereiten Sie ein leicht mit Schmalz gefettetes Backpapier vor (Öl geht auch), damit sich die Roulade nach dem Backen gut aufrollen lässt.",
            "Backen Sie im auf 180 °C vorgeheizten Ofen etwa 8 Minuten; öffnen Sie den Ofen während der gesamten Zeit nicht.",
            "Lassen Sie die Roulade auf dem Blech abkühlen und lösen Sie sie vorsichtig vom Papier.",
            "Schlagen Sie die Sahne steif, bestreichen Sie die Roulade damit und rollen Sie sie auf. Verzieren Sie den Rücken mit der restlichen Sahne, für den Effekt mit Schokoladenspänen.",
        ],
        "notes": ["Tipp: Verfeinern Sie die Roulade mit Ihrem Lieblingsobst — Erdbeeren, Himbeeren oder Banane."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Birnenkuchen mit Vanillepudding",
        "teaser": "Ein Kuchen, dessen Zubereitung auch Kindern Spaß macht. Backen macht doppelt Freude — beim Zubereiten und beim Probieren.",
        "title": "Birnenkuchen mit Vanillepudding — Rezept von Lucie Kůželová",
        "desc": "Birnenkuchen mit Sauerrahm und Vanillepudding: 20 Minuten Zubereitung, 45 Minuten Backzeit, 8 Portionen. Gelingt auch mit Äpfeln, Himbeeren oder Pfirsichen.",
        "product": "vanilkovy_pudink",
        "meta": "Zubereitung 20 Min. · Backen 45 Min. · 8 Portionen",
        "ingredients": [
            "2 Eier",
            "80 g zerlassene Butter",
            "150 g Kristallzucker",
            "200 g glattes Mehl (lässt sich mit Vollkorn- oder Dinkelmehl kombinieren)",
            "1 Päckchen Backpulver",
            "2 Becher Sauerrahm",
            "1 Becher Schlagsahne (30 %)",
            "40 g Vanillepuddingpulver",
            "5 Birnen (ersatzweise Äpfel, Himbeeren, Pfirsiche — frisches oder gefrorenes Obst)",
        ],
        "steps": [
            "Vermischen Sie ein Ei, die Butter, 50 g Zucker, das Mehl und das Backpulver. Kneten Sie den Teig mit den Händen und drücken Sie ihn in eine mit Backpapier ausgelegte Kuchenform (ein krümeliger Teig ist kein Problem — drücken Sie ihn einfach in die Form).",
            "Schneiden Sie die geschälten Birnen in Spalten und verteilen Sie sie auf dem Teig.",
            "Verrühren Sie in einer Schüssel den Sauerrahm, die Schlagsahne, das Puddingpulver, 100 g Zucker und das zweite Ei; gießen Sie die Mischung über den Kuchen.",
            "Backen Sie in der Mitte des auf 180 °C vorgeheizten Ofens etwa 45 Minuten.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Mohnnudeln (šišky s mákem)",
        "teaser": "Ein traditionelles süßes Abendessen aus Kartoffelteig: Mohnnudeln in Mohn und Zucker gewälzt, mit zerlassener Butter übergossen.",
        "title": "Mohnnudeln (šišky s mákem) aus Kartoffelteig — Rezept",
        "desc": "Gebackene Mohnnudeln (šišky s mákem) aus Jůzlová Kartoffelknödelpulver: goldbraun gebacken, überbrüht und in Mohn mit Zucker und Butter gewälzt.",
        "product": "bramborove_knedliky",
        "meta": "Aus Jůzlová Kartoffelteig",
        "ingredients": [
            "400 g Kartoffelknödelpulver",
            "100 g gemahlener Mohn",
            "2 Esslöffel Puderzucker (gern auch mehr)",
            "2 Esslöffel zerlassene Butter",
        ],
        "steps": [
            "Vermischen Sie das Kartoffelknödelpulver nach Anleitung mit Wasser und formen Sie aus dem Teig kleine Nudeln.",
            "Backen Sie sie auf einem gefetteten Blech in der Mitte des auf 200 °C vorgeheizten Ofens; wenden Sie die Nudeln während des Backens einmal, damit sie von beiden Seiten goldgelb werden.",
            "Geben Sie die Nudeln nach dem Backen in kochendes Wasser und brühen Sie sie 5 Minuten.",
            "Geben Sie sie in eine große Schüssel, bestreuen Sie sie mit Mohn und Zucker, übergießen Sie sie mit der Butter, vermengen Sie alles und servieren Sie sie noch warm.",
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky mit Kraut und Speck",
        "teaser": "Ein slowakischer Klassiker aus Chlupaté-Knödel-Pulver — Halušky mit Sauerkraut und knusprig ausgebratenem Speck.",
        "title": "Strapačky mit Kraut und Speck — aus Chlupaté-Knödel-Pulver",
        "desc": "Strapačky aus Jůzlová Chlupaté-Knödel-Pulver mit Sauerkraut, Frühlingszwiebeln und in Schmalz ausgebratenem Speck. Ein deftiger slowakischer Klassiker.",
        "product": "chlupate_knedliky",
        "meta": "Aus Jůzlová Chlupaté-Knödeln",
        "ingredients": [
            "400 g Chlupaté-Knödel-Pulver",
            "400 g Sauerkraut",
            "1 Bund Frühlingszwiebeln",
            "100 g Speck",
            "1 Esslöffel Schmalz",
        ],
        "steps": [
            "Vermischen Sie das Chlupaté-Knödel-Pulver nach Anleitung mit Wasser. Drücken Sie den gequollenen Teig durch ein Sieb als Halušky direkt in kochendes Wasser und garen Sie sie, bis sie an die Oberfläche steigen.",
            "Kochen Sie das Sauerkraut in einem Topf mit Wasser etwa 10 Minuten; gießen Sie das nicht verkochte Wasser ab.",
            "Braten Sie den in kleine Stücke geschnittenen Speck in einer Pfanne im Schmalz aus; wenn er leicht knusprig ist, geben Sie die in Ringe geschnittenen Frühlingszwiebeln dazu und nehmen Sie die Pfanne nach einer Minute vom Herd.",
            "Vermengen Sie die Halušky mit dem Kraut und bestreuen Sie sie auf dem Teller mit dem Speck und den Zwiebeln.",
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe-Schnitten mit Schokoladenpudding",
        "teaser": "Sie möchten Gäste bewirten, sind aber kein Jamie Oliver? Diese Bebe-Schnitten ohne Backen gelingen wirklich jedem.",
        "title": "Bebe-Schnitten mit Schokoladenpudding — ohne Backen",
        "desc": "Bebe-Schnitten ohne Backen mit Jůzlová Kakaopudding nach Lucie Kůželová: Kekse, Puddingcreme und Schlagsahne. Ganz ohne Ofen.",
        "product": "kakao_holandskeho_typu",
        "meta": "Dessert ohne Backen · Nach Lucie Kůželová",
        "ingredients": [
            "4 Päckchen BEBE-Kekse: 2 helle, 2 dunkle",
            "2 Becher saure Sahne",
            "1 Becher Schlagsahne",
            "40 g Vanillezucker",
            "150 g Schokoladenpuddingpulver (3 Beutel)",
            "1 Liter Milch",
            "Kakao holländischer Art zum Bestäuben",
        ],
        "steps": [
            "Legen Sie ein Blech mit den hellen Bebe-Keksen aus.",
            "Kochen Sie den Schokoladenpudding nach Packungsanleitung und gießen Sie ihn gleichmäßig über die Kekse.",
            "Legen Sie die dunklen Bebe-Kekse auf die Puddingschicht.",
            "Schlagen Sie die Schlagsahne mit dem Vanillezucker steif, heben Sie die saure Sahne unter und streichen Sie die Mischung auf die Kekse.",
            "Bestäuben Sie die Schnitten mit dunklem Kakao und lassen Sie sie im Kühlschrank durchziehen, am besten über Nacht.",
        ],
        "notes": ["Tipp: Haben Sie einen anderen als Schokoladenpudding zur Hand, experimentieren Sie — die Schnitten schmecken auch mit Vanillepudding und Zimtbestäubung ausgezeichnet."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Kartoffel-Quark-Knödel mit Erdbeeren",
        "teaser": "Der Sommer ist da und mit ihm reifen die Erdbeeren. Ein einfaches, schnelles Rezept, mit dem Sie in 20 Minuten auch die größten Naschkatzen verwöhnen.",
        "title": "Kartoffel-Quark-Knödel mit Erdbeeren — Rezept in 20 Minuten",
        "desc": "Fruchtknödel aus Jůzlová Kartoffelteig mit Quark und Erdbeeren nach Lucie Kůželová. Fertig in 20 Minuten.",
        "product": "bramborove_knedliky",
        "meta": "20 Minuten · Nach Lucie Kůželová",
        "ingredients": [
            "250 g Kartoffelknödelpulver",
            "250 g weicher Quark (im Block, nicht im Becher)",
            "Erdbeeren (als Füllung und zum Garnieren)",
            "Zucker, Butter und Quark zum Garnieren",
        ],
        "steps": [
            "Vermischen Sie das Kartoffelknödelpulver nach Anleitung mit Wasser zu einem geschmeidigen Teig; arbeiten Sie den weichen Quark ein (ein klebriger Teig ist kein Problem).",
            "Formen Sie aus dem Teig eine Rolle und schneiden Sie sie in gleich große Stücke, damit die Knödel gleichmäßig garen.",
            "Runden Sie jedes Stück ab, drücken Sie es mit den Handflächen zu einem Fladen, drücken Sie eine Erdbeere in die Mitte und verschließen Sie den Teig darum.",
            "Dämpfen Sie die Knödel 5 Minuten — der Teig gart dabei schön durch, ohne zu zerfallen.",
            "In der Zwischenzeit können Sie Erdbeerstücke zum Garnieren kurz einkochen. Garnieren Sie die Knödel auf dem Teller mit Butter, Zucker, Erdbeeren oder Quark.",
        ],
        "notes": [],
    },
}
