# Czech recipes — recovered from the last-live site (Wayback captures).
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Domácí perník",
        "teaser": "Hrníčkový perník, který si zamilujete pro snadnou přípravu i výbornou chuť. Nepotřebujete váhu — vystačíte si s hrnečkem.",
        "title": "Domácí perník — hrníčkový recept podle Jiřiny Jůzlové",
        "desc": "Domácí hrníčkový perník bez vážení: 10 minut přípravy, 20–25 minut pečení, 25–30 porcí. S vanilkovým pudinkem a kakaem holandského typu.",
        "product": "vanilkovy_pudink",
        "meta": "Příprava 10 min · Pečení 20–25 min · 25–30 porcí",
        "ingredients": [
            "3 hrnečky hladké mouky (hrneček = 200 ml)",
            "2 hrnečky cukru krystal",
            "1 hrneček oleje",
            "2 středně velká vejce",
            "2 vrchovaté polévkové lžíce vanilkového pudinku v prášku",
            "1 prášek do perníku",
            "½ prášku do pečiva",
            "250 ml mléka (1¼ hrnečku)",
            "kakao holandského typu dle chuti",
        ],
        "steps": [
            "Všechny ingredience nasypte do jedné nádoby a důkladně promíchejte mixérem, aby se netvořily hrudky.",
            "Těsto nalijte na vymaštěný plech vysypaný hrubou moukou.",
            "Pečte v troubě předehřáté na 180 °C 20 až 25 minut (podle výšky plechu).",
            "Hotový perník poznáte dřevěným párátkem — po zapíchnutí musí zůstat čisté, bez přilepeného těsta.",
        ],
        "notes": ["Tip: Do těsta můžete podle chuti přidat trochu rumu či rumového aroma, skořici, nahrubo nasekané vlašské ořechy nebo čokoládu."],
    },
    "slehackova-rolada-recept": {
        "name": "Šlehačková roláda",
        "teaser": "Lehký moučník za půl hodiny: kontrast nahořklého kakaa a jemně sladké šlehačky. Bez mouky, tedy i bez lepku.",
        "title": "Šlehačková roláda — bezlepkový recept s kakaem",
        "desc": "Šlehačková roláda bez mouky a bez lepku: 5 vajec, moučkový cukr, kakao holandského typu a šlehačka. Hotová za 30 minut.",
        "product": "kakao_holandskeho_typu",
        "meta": "Příprava cca 30 min · Bez lepku",
        "ingredients": [
            "5 vajec",
            "100 g moučkového cukru",
            "1 lžíce kakaa holandského typu",
            "1 smetana ke šlehání (případně ztužovač smetany)",
        ],
        "steps": [
            "Z bílků ušlehejte tuhý sníh, pak přidejte žloutky a moučkový cukr. Opatrným mísením vznikne hladké těsto.",
            "Nakonec přidejte kakao holandského typu — dodá sytou čokoládovou barvu a výraznou chuť.",
            "Připravte si pečicí papír lehce vymaštěný sádlem (poslouží i olej), aby šla roláda po upečení dobře sbalit.",
            "Pečte v troubě předehřáté na 180 °C asi 8 minut; troubu po celou dobu neotevírejte.",
            "Roládu nechte na plechu vychladnout a opatrně ji sejměte z papíru.",
            "Ušlehejte tuhou šlehačku, roládu potřete a zabalte. Zbylou šlehačkou ozdobte hřbet, na efekt přidejte čokoládové hobliny.",
        ],
        "notes": ["Tip: Roládu ozvláštníte oblíbeným ovocem — jahodami, malinami nebo banánem."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Hruškový koláč s vanilkovým pudinkem",
        "teaser": "Koláč, jehož přípravu si užijí i děti. Pečení baví dvakrát — při přípravě i při ochutnávání.",
        "title": "Hruškový koláč s vanilkovým pudinkem — recept Lucie Kůželové",
        "desc": "Hruškový koláč se zakysanou smetanou a vanilkovým pudinkem: 20 minut přípravy, 45 minut pečení, 8 porcí. Funguje i s jablky, malinami či broskvemi.",
        "product": "vanilkovy_pudink",
        "meta": "Příprava 20 min · Pečení 45 min · 8 porcí",
        "ingredients": [
            "2 vejce",
            "80 g rozehřátého másla",
            "150 g krystalového cukru",
            "200 g hladké mouky (lze kombinovat s celozrnnou nebo špaldovou)",
            "1 kypřicí prášek",
            "2 zakysané smetany",
            "1 smetana ke šlehání (30 %)",
            "40 g vanilkového pudinku v prášku",
            "5 hrušek (lze nahradit jablky, malinami, broskvemi — čerstvým i mraženým ovocem)",
        ],
        "steps": [
            "Smíchejte jedno vejce, máslo, 50 g cukru, mouku a kypřicí prášek. Těsto rukama vypracujte a vtlačte do koláčové formy vyložené pečicím papírem (drolivé těsto nevadí — vymačkejte je do formy).",
            "Okrájené hrušky nakrájejte na plátky a rozprostřete na těsto.",
            "V misce promíchejte zakysanou smetanu, šlehačku, pudink v prášku, 100 g cukru a druhé vejce; směs nalijte na koláč.",
            "Pečte uprostřed vyhřáté trouby na 180 °C asi 45 minut.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Šišky s mákem",
        "teaser": "Tradiční sladká večeře z bramborového těsta: šišky obalené v máku s cukrem, přelité rozpuštěným máslem.",
        "title": "Šišky s mákem z bramborového těsta — recept",
        "desc": "Pečené šišky s mákem z bramborových knedlíků v prášku Jůzlová: dozlatova upečené, spařené a obalené v máku s cukrem a máslem.",
        "product": "bramborove_knedliky",
        "meta": "Z bramborového těsta Jůzlová",
        "ingredients": [
            '400 g bramborových knedlíků v prášku',
            '100 g mletého máku',
            '2 polévkové lžíce moučkového cukru (může být více)',
            '2 polévkové lžíce rozpuštěného másla',
        ],
        "steps": [
            'Bramborové knedlíky v prášku smíchejte s vodou dle návodu a z těsta vytvarujte malé šišky.',
            'Pečte na vymaštěném plechu uprostřed trouby předehřáté na 200 °C; v průběhu pečení šišky jednou otočte, aby měly zlatavou barvu z obou stran.',
            'Po upečení šišky vhoďte do vroucí vody a na 5 minut spařte.',
            'Vložte je do velké mísy, posypte mákem a cukrem, polijte máslem, promíchejte a ještě teplé podávejte.',
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky se zelím a slaninou",
        "teaser": "Slovenská klasika z chlupatých knedlíků v prášku — halušky s kysaným zelím a vypečenou slaninou.",
        "title": "Strapačky se zelím a slaninou — recept z chlupatých knedlíků",
        "desc": "Strapačky z chlupatých knedlíků v prášku Jůzlová s kysaným zelím, jarní cibulkou a slaninou vypečenou na sádle. Vydatná slovenská klasika.",
        "product": "chlupate_knedliky",
        "meta": "Z chlupatých knedlíků Jůzlová",
        "ingredients": [
            '400 g chlupatých knedlíků v prášku',
            '400 g kysaného zelí',
            'svazek jarní cibulky',
            '100 g slaniny',
            'lžíce sádla',
        ],
        "steps": [
            'Chlupaté knedlíky v prášku smíchejte s vodou dle návodu. Nabobtnalé těsto protlačte cedníkem na halušky přímo do vroucí vody a vařte, dokud nevyplavou.',
            'Kysané zelí povařte v hrnci s vodou asi 10 minut; nevyvařenou vodu slijte.',
            'Na pánvi na sádle osmažte slaninu nakrájenou na menší kousky; když je lehce vysmažená, přidejte na kolečka nakrájenou jarní cibulku a po minutě odstavte.',
            'Halušky smíchejte se zelím a na talíři posypte slaninou s cibulkou.',
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe řezy s čokoládovým pudingem",
        "teaser": "Rádi byste pohostili návštěvu, ale nejste zrovna Jamie Oliver? Nepečené bebe řezy zvládne opravdu každý.",
        "title": "Bebe řezy s čokoládovým pudingem — nepečený recept",
        "desc": "Nepečené bebe řezy s čokoládovým pudingem podle Lucie Kůželové: sušenky, pudingový krém a šlehačka. Bez pečení.",
        "product": "kakao_holandskeho_typu",
        "meta": "Nepečený dezert · Podle Lucie Kůželové",
        "ingredients": [
            '4 balíčky sušenek BEBE: 2 světlé, 2 tmavé',
            '2 zakysané smetany',
            '1 smetana ke šlehání',
            '40 g vanilkového cukru',
            '150 g čokoládového pudingu (3 balení)',
            '1 litr mléka',
            'kakao holandského typu na posyp',
        ],
        "steps": [
            'Na plech poklaďte světlé bebe sušenky.',
            'Uvařte čokoládový puding dle návodu na obalu a nalijte jej na sušenky tak, aby se rovnoměrně rozprostřel.',
            'Na vrstvu pudingu poklaďte tmavé bebe sušenky.',
            'V míse vyšlehejte smetanu s vanilkovým cukrem do tuha, vmíchejte zakysanou smetanu a směs rozetřete na sušenky.',
            'Řez posypte tmavým kakaem a nechte v lednici odležet, nejlépe přes noc.',
        ],
        "notes": ['Tip: Máte-li po ruce jiný než čokoládový puding, experimentujte — řez chutná výborně i s vanilkovým pudingem a skořicovým posypem.'],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Bramborovo-tvarohové knedlíky s jahodami",
        "teaser": "Léto je tady a s ním i dozrávání jahod. Jednoduchý a rychlý recept, kterým za 20 minut potěšíte i největší mlsouny.",
        "title": "Bramborovo-tvarohové knedlíky s jahodami — recept za 20 minut",
        "desc": "Ovocné knedlíky z bramborového těsta Jůzlová s tvarohem a jahodami podle Lucie Kůželové. Hotové za 20 minut.",
        "product": "bramborove_knedliky",
        "meta": "20 minut · Podle Lucie Kůželové",
        "ingredients": [
            '250 g bramborových knedlíků v prášku',
            '250 g měkkého tvarohu (v kostce, ne ve vaničce)',
            'jahody (jako náplň i na ozdobu)',
            'cukr, máslo a tvaroh na ozdobu',
        ],
        "steps": [
            'Bramborové knedlíky v prášku smíchejte s vodou dle návodu a připravte vláčné těsto; zapracujte měkký tvaroh (lepivé těsto nevadí).',
            'Z těsta vytvarujte válec a nakrájejte jej na stejně velké části, aby se knedlíky vařily rovnoměrně.',
            'Každou část zakulaťte, dlaněmi vytvořte placičku, doprostřed zatlačte jahodu a zabalte.',
            'Knedlíky vařte v páře 5 minut — těsto se krásně uvaří a nerozvaří.',
            'Mezitím můžete povařit kousky jahod na ozdobu. Na talíři knedlíky dozdobte máslem, cukrem, jahodami nebo tvarohem.',
        ],
        "notes": [],
    },
}
