# Slovak recipes — translation of recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Domáci perník",
        "teaser": "Hrnčekový perník: jednoduchá príprava, výrazná chuť. Nepotrebujete váhu — vystačíte si s hrnčekom.",
        "title": "Domáci perník — hrnčekový recept podľa Jiřiny Jůzlovej",
        "desc": "Domáci hrnčekový perník bez váženia: 10 minút prípravy, 20–25 minút pečenia, 25–30 porcií. S vanilkovým pudingom a kakaom holandského typu.",
        "product": "vanilkovy_pudink",
        "meta": "Príprava 10 min · Pečenie 20–25 min · 25–30 porcií",
        "ingredients": [
            "3 hrnčeky hladkej múky (hrnček = 200 ml)",
            "2 hrnčeky kryštálového cukru",
            "1 hrnček oleja",
            "2 stredne veľké vajcia",
            "2 vrchovaté polievkové lyžice vanilkového pudingu v prášku",
            "1 prášok do perníka",
            "½ kypriaceho prášku",
            "250 ml mlieka (1¼ hrnčeka)",
            "kakao holandského typu podľa chuti",
        ],
        "steps": [
            "Všetky suroviny dajte do jednej misy a dôkladne premiešajte mixérom, aby sa netvorili hrudky.",
            "Cesto nalejte na vymastený plech vysypaný hrubou múkou.",
            "Pečte v rúre predhriatej na 180 °C 20 až 25 minút (podľa výšky plechu).",
            "Či je perník hotový, zistíte dreveným špáradlom — po zapichnutí musí zostať čisté, bez prilepeného cesta.",
        ],
        "notes": ["Tip: Do cesta môžete podľa chuti pridať trochu rumu či rumovej arómy, škoricu, nahrubo posekané vlašské orechy alebo čokoládu."],
    },
    "slehackova-rolada-recept": {
        "name": "Šľahačková roláda",
        "teaser": "Ľahký múčnik za pol hodiny: kontrast horkastého kakaa a jemne sladkej šľahačky. Bez múky, teda aj bez lepku.",
        "title": "Šľahačková roláda — bezlepkový recept s kakaom",
        "desc": "Šľahačková roláda bez múky a bez lepku: 5 vajec, práškový cukor, kakao holandského typu a šľahačka. Pečenie 8 minút na 180 °C, hotová za 30 minút.",
        "product": "kakao_holandskeho_typu",
        "meta": "Príprava cca 30 min · Bez lepku",
        "ingredients": [
            "5 vajec",
            "100 g práškového cukru",
            "1 lyžica kakaa holandského typu",
            "1 smotana na šľahanie (prípadne aj stužovač šľahačky)",
        ],
        "steps": [
            "Z bielkov vyšľahajte tuhý sneh, potom pridajte žĺtky a práškový cukor. Opatrným miešaním vznikne hladké cesto.",
            "Nakoniec pridajte kakao holandského typu — dodá sýtu čokoládovú farbu a výraznú chuť.",
            "Pripravte si papier na pečenie zľahka vymastený masťou (poslúži aj olej), aby sa roláda po upečení dala dobre zvinúť.",
            "Pečte v rúre predhriatej na 180 °C asi 8 minút; rúru počas pečenia neotvárajte.",
            "Roládu nechajte na plechu vychladnúť a opatrne ju odlepte z papiera.",
            "Vyšľahajte tuhú šľahačku, roládu potrite a zviňte. Zvyšnou šľahačkou ozdobte vrch a pridajte čokoládové hobliny.",
        ],
        "notes": ["Tip: Roládu ozvláštnite obľúbeným ovocím — jahodami, malinami alebo banánom."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Hruškový koláč s vanilkovým pudingom",
        "teaser": "Koláč, ktorý s vami zvládnu upiecť aj deti. Baví dvakrát — pri príprave aj pri ochutnávaní.",
        "title": "Hruškový koláč s vanilkovým pudingom podľa Lucie Kůželovej",
        "desc": "Hruškový koláč s kyslou smotanou a vanilkovým pudingom: 20 minút prípravy, 45 minút pečenia, 8 porcií. Funguje aj s jablkami, malinami či broskyňami.",
        "product": "vanilkovy_pudink",
        "meta": "Príprava 20 min · Pečenie 45 min · 8 porcií",
        "ingredients": [
            "2 vajcia",
            "80 g zmäknutého masla",
            "150 g kryštálového cukru",
            "200 g hladkej múky (možno kombinovať s celozrnnou alebo špaldovou)",
            "1 kypriaci prášok",
            "2 kyslé smotany",
            "1 smotana na šľahanie (30 %)",
            "40 g vanilkového pudingu v prášku",
            "5 hrušiek (možno nahradiť jablkami, malinami, broskyňami — čerstvým aj mrazeným ovocím)",
        ],
        "steps": [
            "Zmiešajte jedno vajce, maslo, 50 g cukru, múku a kypriaci prášok. Cesto vypracujte rukami a vtlačte do koláčovej formy vyloženej papierom na pečenie. Ak sa drobí, neprekáža — jednoducho ho do formy vytlačte.",
            "Ošúpané hrušky nakrájajte na plátky a rozprestrite na cesto.",
            "V miske premiešajte kyslú smotanu, šľahačku, puding v prášku, 100 g cukru a druhé vajce; zmes nalejte na koláč.",
            "Pečte v strede rúry predhriatej na 180 °C asi 45 minút.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Šúľance s makom",
        "teaser": "Tradičná sladká večera zo zemiakového cesta: šúľance obalené v maku s cukrom, preliate rozpusteným maslom.",
        "title": "Šúľance s makom zo zemiakového cesta — recept",
        "desc": "Pečené šúľance s makom z našich zemiakových knedieľ v prášku: 400 g zmesi, pečenie na 200 °C, 5 minút sparenia a obaľovanie v maku s cukrom a maslom.",
        "product": "bramborove_knedliky",
        "meta": "Z nášho zemiakového cesta",
        "ingredients": [
            "400 g zemiakových knedieľ v prášku",
            "100 g mletého maku",
            "2 polievkové lyžice práškového cukru (môže byť aj viac)",
            "2 polievkové lyžice rozpusteného masla",
        ],
        "steps": [
            "Zemiakové knedle v prášku zmiešajte s vodou podľa návodu a z cesta vytvarujte malé šúľance.",
            "Pečte na vymastenom plechu v strede rúry predhriatej na 200 °C; počas pečenia šúľance raz otočte, aby mali zlatistú farbu z oboch strán.",
            "Upečené šúľance vhoďte do vriacej vody a 5 minút sparte.",
            "Vložte ich do veľkej misy, posypte makom a cukrom, polejte maslom, premiešajte a ešte teplé podávajte.",
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky s kapustou a slaninou",
        "teaser": "Slovenská klasika z chlpatých knedieľ v prášku — halušky s kyslou kapustou a vypečenou slaninou.",
        "title": "Strapačky s kapustou a slaninou — recept z chlpatých knedieľ",
        "desc": "Strapačky z našich chlpatých knedieľ v prášku s kyslou kapustou, jarnou cibuľkou a slaninou vypečenou na masti. Výdatná slovenská klasika.",
        "product": "chlupate_knedliky",
        "meta": "Z našich chlpatých knedieľ",
        "ingredients": [
            "400 g chlpatých knedieľ v prášku",
            "400 g kyslej kapusty",
            "zväzok jarnej cibuľky",
            "100 g slaniny",
            "lyžica masti",
        ],
        "steps": [
            "Chlpaté knedle v prášku zmiešajte s vodou podľa návodu. Napučané cesto pretlačte cez cedník na halušky priamo do vriacej vody a varte, kým nevyplávajú.",
            "Kyslú kapustu povarte v hrnci s vodou asi 10 minút; zvyšnú vodu zlejte.",
            "Na panvici na masti opražte slaninu nakrájanú na menšie kúsky; keď je zľahka vypražená, pridajte na kolieska nakrájanú jarnú cibuľku a po minúte odstavte.",
            "Halušky zmiešajte s kapustou a na tanieri posypte slaninou s cibuľkou.",
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe rezy s čokoládovým pudingom",
        "teaser": "Radi by ste pohostili návštevu, ale nie ste práve Jamie Oliver? Nepečené bebe rezy zvládne naozaj každý.",
        "title": "Bebe rezy s čokoládovým pudingom — nepečený recept",
        "desc": "Nepečené bebe rezy s čokoládovým pudingom podľa Lucie Kůželovej: 4 balíčky keksov, puding z litra mlieka, šľahačka s kyslou smotanou. Odležať cez noc.",
        "product": "kakao_holandskeho_typu",
        "meta": "Nepečený dezert · Podľa Lucie Kůželovej",
        "ingredients": [
            "4 balíčky keksov BEBE: 2 svetlé, 2 tmavé",
            "2 kyslé smotany",
            "1 smotana na šľahanie",
            "40 g vanilkového cukru",
            "150 g nášho vanilkového pudingu a 2 lyžice kakaa holandského typu",
            "1 liter mlieka",
            "kakao holandského typu na posypanie",
        ],
        "steps": [
            "Na plech poukladajte svetlé bebe keksy.",
            "Uvarte čokoládový puding podľa návodu na obale a nalejte ho na keksy tak, aby sa rovnomerne rozprestrel.",
            "Na vrstvu pudingu poukladajte tmavé bebe keksy.",
            "V mise vyšľahajte smotanu s vanilkovým cukrom dotuha, primiešajte kyslú smotanu a zmes rozotrite na keksy.",
            "Rez posypte tmavým kakaom a nechajte v chladničke odležať, ideálne cez noc.",
        ],
        "notes": ["Tip: Ak máte poruke iný ako čokoládový puding, experimentujte — rezy chutia výborne aj s vanilkovým pudingom a škoricou."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Zemiakovo-tvarohové knedle s jahodami",
        "teaser": "Leto je tu a s ním aj dozrievanie jahôd. Jednoduchý a rýchly recept, ktorým za 20 minút potešíte aj najväčších maškrtníkov.",
        "title": "Zemiakovo-tvarohové knedle s jahodami — recept za 20 minút",
        "desc": "Ovocné knedle z nášho zemiakového cesta s tvarohom a jahodami podľa Lucie Kůželovej: 250 g zmesi, 250 g tvarohu, 5 minút v pare. Hotové za 20 minút.",
        "product": "bramborove_knedliky",
        "meta": "20 minút · Podľa Lucie Kůželovej",
        "ingredients": [
            "250 g zemiakových knedieľ v prášku",
            "250 g mäkkého tvarohu (v kocke, nie vo vaničke)",
            "jahody (ako plnka aj na ozdobu)",
            "cukor, maslo a tvaroh na ozdobu",
        ],
        "steps": [
            "Zemiakové knedle v prášku zmiešajte s vodou podľa návodu a pripravte vláčne cesto; zapracujte mäkký tvaroh (lepivé cesto neprekáža).",
            "Z cesta vytvarujte valec a nakrájajte ho na rovnako veľké časti, aby sa knedle varili rovnomerne.",
            "Každý kúsok zaguľaťte, dlaňami sploštite na placku, do stredu vložte jahodu a zabaľte.",
            "Knedle varte v pare 5 minút — cesto sa krásne uvarí a nerozvarí.",
            "Medzitým môžete povariť kúsky jahôd na ozdobu. Na tanieri knedle dozdobte maslom, cukrom, jahodami alebo tvarohom.",
        ],
        "notes": [],
    },
    "rychle-venecky-ci-vetrnicky-recept": {
        "name": "Rýchle venčeky či veterníčky",
        "teaser": "Jedno odpaľované cesto na venčeky aj veterníčky: vyšší podiel masla a štart na 250 °C. Asi 80 kúskov na dvoch plechách.",
        "title": "Rýchle venčeky či veterníčky z odpaľovaného cesta — recept",
        "desc": "Rýchle venčeky a veterníčky z odpaľovaného cesta: 250 ml vody, 90 g masla, 140 g hrubej múky, 4 vajcia. Príprava 45 min, pečenie cca 15 min, asi 80 kúskov.",
        "meta": "Príprava 45 min · Pečenie cca 15 min · asi 80 kúskov · 2 plechy",
        "ingredients": [
            "250 ml vody",
            "štipka soli",
            "90 g masla",
            "140 g hrubej múky",
            "4 vajcia",
            "tuk na vymastenie plechov",
        ],
        "steps": [
            "Vodu, soľ a maslo priveďte k varu.",
            "Stiahnite plameň a naraz vmiešajte múku; miešajte, kým sa cesto neodlepuje od stien hrnca a prestane lepiť.",
            "Odstavte a nechajte mierne schladnúť.",
            "Rúru predhrejte na 250 °C.",
            "Po jednom zašľahajte vajcia a stále miešajte, kým nie je cesto hladké a mierne pružné.",
            "Na vymastené plechy striekajte venčeky ako dva krúžky na sebe alebo veterníčky ako malé kopčeky.",
            "Pečte 5 minút na 250 °C, potom znížte na 200 °C a pečte dozlata — zhruba ďalších 5 minút na vyššej a 5 na strednej teplote. Rúru počas pečenia neotvárajte.",
            "Ešte horúce ihneď rozrežte (škrupinky sa potom netrhajú). Pred plnením úplne vychlaďte.",
        ],
        "notes": [
            "Náplň je voľná: najjednoduchšia je osladená šľahačka. K venčekom sa hodí vanilkový maslový krém a rumová poleva z receptu na venčeky, k veterníčkom vanilkový pudingový krém, karamelová šľahačka a karamelová poleva z receptu na karamelové veterníky.",
            "Cesto má vyšší pomer masla k múke (90 g : 140 g) a pečie sa s horúcim štartom 250 °C — preto rýchlejšie a spoľahlivejšie nabehne.",
        ],
    },
    "venecky-s-vanilkovym-kremem-recept": {
        "name": "Venčeky s vanilkovým krémom",
        "teaser": "Klasické venčeky z odpaľovaného cesta s vanilkovým maslovým krémom a rumovou polevou. Asi 20 kúskov.",
        "title": "Venčeky s vanilkovým krémom a rumovou polevou — recept",
        "desc": "Venčeky z odpaľovaného cesta s vanilkovým maslovým krémom z pudingu a žĺtkov a s rumovou polevou. Pečenie 10 minút na 200 °C a 15–25 minút na 180 °C. Asi 20 kúskov.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 20 kúskov · odpaľované cesto, vanilkový krém, rumová poleva",
        "ingredients": [
            "Odpaľované cesto: 320 ml vody",
            "100 g masla",
            "štipka soli",
            "235 g múky",
            "4–5 vajec, pridávaných postupne",
            "Vanilkový maslový krém: 500 ml mlieka",
            "80 g nášho vanilkového pudingu v prášku",
            "5 žĺtkov",
            "150 g cukru",
            "250 g zmäknutého masla",
            "2 lyžice rumu (podľa chuti)",
            "Rumová poleva: 300 g práškového cukru",
            "2 lyžice rumu",
            "3 lyžice horúceho mlieka",
        ],
        "steps": [
            "Vodu, maslo a soľ priveďte k varu. Odstavte, vmiešajte všetku múku a na miernom plameni 2–3 minúty varte, kým sa cesto nespojí do gule.",
            "Nechajte vychladnúť na vlažné. Postupne zašľahajte vajcia, kým cesto z lyžice nepadá v hustom páse.",
            "Na papier na pečenie striekajte krúžky s priemerom 6–7 cm. Pečte 10 minút na 200 °C bez otvárania dvierok, potom znížte na 180 °C a pečte ďalších 15–25 minút, kým nie sú venčeky sýto zlatisté a na omak suché.",
            "Úplne vychlaďte a ideálne nechajte niekoľko hodín alebo cez noc odkryté, aby škrupinky ostali chrumkavé.",
            "Puding uvarte s mliekom, cukrom a žĺtkami za stáleho miešania, kým nezhustne (po pridaní žĺtkov už nevarte naplno). Vychlaďte, na povrch pritlačte fóliu.",
            "Zmäknuté maslo vyšľahajte do peny, po lyžiciach pridávajte vychladnutý puding a šľahajte dohladka. Nakoniec vmiešajte rum.",
            "Práškový cukor, rum a horúce mlieko vyšľahajte do hladkej tekutej polevy.",
            "Venčeky rozrežte vodorovne. Do spodnej polovice nastriekajte výdatne krém, priklopte a vrch namočte do rumovej polevy. Nechajte stuhnúť.",
        ],
        "notes": [
            "Ľahší variant: vynechajte rumovú polevu, namiesto maslového krému použite obyčajný pudingový krém a navrch dajte šľahačku a práškový cukor.",
        ],
    },
    "kremrole-recept": {
        "name": "Kremrole",
        "teaser": "Krehké trubičky plnené lesklým talianskym snehom. Asi 35–40 kúskov; budete potrebovať kovové trubičky na kremrole.",
        "title": "Kremrole z maslového cesta s talianskym snehom — recept",
        "desc": "Kremrole z maslového cesta so smotanou, plnené talianskym snehom zo sirupu 115–120 °C. Asi 35–40 kúskov, pečenie 12–15 minút na 180–200 °C, kovové trubičky.",
        "meta": "Asi 35–40 kúskov · pečenie 12–15 min · kovové trubičky",
        "ingredients": [
            "Cesto: 350 g múky",
            "250 g studeného masla (alebo Hery), nastrúhaného alebo nakrájaného",
            "125 ml smotany na šľahanie",
            "voliteľne pre väčšiu krehkosť: 25 g smotany nahraďte kyslou smotanou",
            "Taliansky sneh: 80 g bielkov (asi 2 vajcia)",
            "160 g cukru",
            "40 ml vody",
            "práškový cukor na posyp",
        ],
        "steps": [
            "Múku, maslo a smotanu spracujte na hladké cesto — nemieste ho príliš dlho. Zabaľte a nechajte v chladničke aspoň hodinu, pokojne aj cez noc.",
            "Vyvaľkajte na tenký plát, nakrájajte pásiky 2 × 20 cm a každý oviňte okolo vymastenej kovovej trubičky tak, aby sa okraje mierne prekrývali.",
            "Pečte na 180–200 °C dozlata, asi 12–15 minút. Nechajte mierne schladnúť a opatrne stiahnite z trubičiek.",
            "Cukor s vodou zohrejte bez miešania na 115–120 °C (teplomer pomôže). Medzitým ušľahajte bielky do tuha.",
            "Za stáleho šľahania prilievajte horúci sirup tenkým prúdom a šľahajte, kým sneh nie je lesklý a len vlažný. Krátko vychlaďte a striekajte do trubičiek z oboch koncov. Posypte práškovým cukrom.",
        ],
        "notes": [
            "Najjednoduchší variant: bielky s cukrom šľahajte priamo nad hrncom s mierne vriacou vodou (vo vodnom kúpeli), kým nie sú lesklé a husté — bez teplomera, o niečo menej stabilný, ale spoľahlivý.",
            "Trubičky môžete improvizovať z alobalu, ak nemáte kovové formy.",
        ],
    },
    "minivetrnicky-recept": {
        "name": "Miniveterníčky",
        "teaser": "Malé veterníčky z odpaľovaného cesta s maslovo-pudingovým krémom s tvarohom a čokoládovou polevou. Asi 40–45 kúskov.",
        "title": "Miniveterníčky s pudingovým krémom — recept",
        "desc": "Miniveterníčky z odpaľovaného cesta: 250 ml vody, 90 g masla, 160 g múky, 4 vajcia. Náplň z vanilkového pudingu, masla a tvarohu, čokoládová poleva. 40–45 kúskov.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 40–45 kúskov · pečenie cca 20 min",
        "ingredients": [
            "Odpaľované cesto: 250 ml vody",
            "štipka soli",
            "90 g masla",
            "160 g múky",
            "1 lyžička kypriaceho prášku",
            "4 vajcia",
            "Náplň: 0,5 l mlieka",
            "80 g nášho vanilkového pudingu v prášku",
            "3 lyžice cukru",
            "250 g zmäknutého masla",
            "125 g cukru",
            "vanilkový cukor",
            "2 lyžičky rumu",
            "asi 150–200 g tučného tvarohu",
            "Poleva: horká alebo mliečna čokoláda (s kúskom masla alebo oleja na lesk)",
        ],
        "steps": [
            "Vodu, maslo a soľ priveďte k varu. Odstavte, vmiešajte múku s kypriacim práškom dohladka a ešte chvíľu miešajte na miernom plameni. Potom nechajte mierne vychladnúť.",
            "Po jednom zašľahajte vajcia mixérom. Na papier na pečenie striekajte kopčeky 2–3 cm (alebo ich tvarujte dvoma lyžicami).",
            "Pečte na 200 °C asi 20 minút. Prvých 10 minút rúru neotvárajte.",
            "Puding uvarte a úplne vychlaďte (pokojne aj niekoľko hodín vopred). Zmäknuté maslo vyšľahajte s cukrom a vanilkovým cukrom do peny, pridajte rum a po častiach zašľahajte puding a tvaroh dohladka.",
            "Vychladnuté veterníčky narežte do troch štvrtín, nastriekajte náplň a vrch namočte alebo natrite rozpustenou čokoládou.",
        ],
        "notes": [
            "Letný, ľahší variant: vynechajte maslový krém aj polevu — plňte osladenou šľahačkou a kúskami čerstvých jahôd, posypte práškovým cukrom.",
        ],
    },
    "karamelove-vetrniky-recept": {
        "name": "Karamelové veterníky",
        "teaser": "Veterníky s vanilkovým pudingovým krémom, karamelovou šľahačkou a karamelovou polevou. Asi 24 stredných kúskov.",
        "title": "Karamelové veterníky s dvojakým krémom — recept",
        "desc": "Karamelové veterníky z odpaľovaného cesta: vanilkový pudingový krém, karamelová šľahačka a karamelová poleva. Šľahačku pripravte deň vopred. Asi 24 stredných kúskov.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 24 stredných kúskov · karamelový krém radšej deň vopred",
        "ingredients": [
            "Odpaľované cesto: 250 ml vody",
            "100 g masla",
            "štipka soli",
            "160 g múky",
            "4–5 vajec (izbová teplota), rozšľahaných, pridávaných postupne",
            "½ lyžičky kypriaceho prášku",
            "Vanilkový pudingový krém: 400 ml mlieka",
            "40 g nášho vanilkového pudingu v prášku",
            "3 lyžice cukru",
            "250 ml smotany na šľahanie (33 %), ušľahanej do tuha",
            "Karamelová šľahačka: 150 g cukru",
            "250 ml smotany na šľahanie (33 %), studenej, plus trochu na stiahnutie karamelu",
            "štipka soli",
            "Karamelová poleva: 125 g cukru",
            "45 g masla",
            "75 ml smotany na šľahanie",
            "voliteľne: 3–4 lyžice odloženej karamelovej šľahačky, zriedenej trochou práškového cukru",
        ],
        "steps": [
            "Vodu, maslo a soľ priveďte k varu. Odstavte, vsypte všetku múku, dôkladne zamiešajte a na miernom plameni 2–3 minúty varte, kým sa cesto nespojí do gule a na dne hrnca sa nevytvorí tenký film.",
            "Cesto roztierajte po stenách misy, aby rýchlejšie vychladlo. Keď je len vlažné (horúce by vajcia zrazilo), po troškách ich zašľahajte na nízkych otáčkach. Prestaňte, keď cesto z lyžice padá v hustom „V“ — všetky vajcia nemusíte spotrebovať. Nakoniec vmiešajte kypriaci prášok.",
            "Veľkou hviezdicovou špičkou striekajte na papier na pečenie kruhy s priemerom 4–5 cm, s veľkými rozstupmi. Pečte 10 minút na 200–220 °C, potom znížte na 170–180 °C a pečte ďalších 15–20 minút, kým nie sú sýto zlatisté a pevné. Rúru počas pečenia neotvárajte, inak veterníky spadnú. Pred plnením úplne vychlaďte.",
            "Puding uvarte s mliekom a cukrom podľa návodu na obale a úplne vychlaďte (na povrch pritlačte fóliu). Keď sú puding aj šľahačka studené, šľahačku do pudingu zapracujte.",
            "Cukor nasucho rozpustite na panvici (nemiešajte, len otáčajte panvicou) do sýto jantárovej farby. Odstavte, opatrne prilejte trochu smotany — bude prudko bublať — potom vmiešajte zvyšok a štipku soli. Úplne vychlaďte, nechajte v chladničke niekoľko hodín alebo cez noc a ušľahajte do tuha. 3–4 lyžice odložte na polevu.",
            "Cukor na polevu skaramelizujte rovnako, odstavte a vmiešajte maslo a smotanu, kým poleva nie je hladká a lesklá. Nechajte schladnúť, kým poleva obalí lyžicu, ale ešte sa dá liať.",
            "Každý vychladnutý veterník rozrežte vodorovne a vrch nechajte ako čiapočku. Do spodku nastriekajte vanilkový krém, naň krúžok karamelovej šľahačky, priklopte a prelejte alebo namočte do karamelovej polevy. Pred podávaním nechajte v chladničke aspoň 2 hodiny stuhnúť.",
        ],
        "notes": [
            "Vajcia do odpaľovaného cesta pridávajte, až keď je vlažné, a po troškách — múka nasiakne vždy inak. Správnu hustotu spoznáte podľa konzistencie, nie podľa toho, že ste spotrebovali všetky vajcia.",
            "Rúru počas pečenia neotvárajte. Karamelovú šľahačku pripravte deň vopred, aby stihla stuhnúť na šľahanie.",
        ],
    },
    "vetrnicky-s-vanilkovym-kremem-recept": {
        "name": "Veterníčky s vanilkovým krémom",
        "teaser": "Malé veterníčky striekané hviezdičkou, plnené vanilkovým maslovým krémom a namáčané v bielej cukrovej poleve. Asi 30 kúskov.",
        "title": "Veterníčky s vanilkovým krémom a cukrovou polevou — recept",
        "desc": "Veterníčky z odpaľovaného cesta (125 ml mlieka, 125 ml vody, 100 g masla, 150 g múky, 4–5 vajec) s vanilkovým maslovým krémom a bielou cukrovou polevou. Asi 30 kúskov, pečenie 10 min na 220 °C a 15–20 min na 180 °C.",
        "product": "vanilkovy_pudink",
        "meta": "Asi 30 kúskov · Pečenie 25–30 min · krém a poleva",
        "ingredients": [
            "Odpaľované cesto: 125 ml mlieka",
            "125 ml vody",
            "100 g masla",
            "štipka soli",
            "150 g hladkej múky",
            "4–5 vajec izbovej teploty, rozšľahaných",
            "Vanilkový maslový krém: 500 ml mlieka",
            "80 g nášho vanilkového pudingu v prášku",
            "2 žĺtky",
            "80 g kryštálového cukru",
            "200 g zmäknutého masla",
            "1–2 lyžice rumu (podľa chuti)",
            "Cukrová poleva: 250 g práškového cukru",
            "1 lyžica citrónovej šťavy",
            "1 lyžica rumu",
            "2–3 lyžice horúcej vody",
        ],
        "steps": [
            "Krém začnite ako prvý, musí úplne vychladnúť. Puding rozmiešajte v 100 ml studeného mlieka so žĺtkami. Zvyšné mlieko s cukrom priveďte do varu, za stáleho miešania vlejte pudingovú zmes a varte na miernom ohni 1–2 minúty, kým nezhustne. Prelejte do misy, na povrch pritlačte fóliu a nechajte vychladnúť na izbovú teplotu.",
            "Mlieko, vodu, maslo a soľ priveďte do varu. Stiahnite plameň, vsypte všetku múku naraz a miešajte 2–3 minúty, kým sa cesto nespojí do hladkej gule a na dne hrnca nezostane tenký povlak.",
            "Cesto preložte do misy a nechajte 5–10 minút vychladnúť, kým nie je len vlažné. Po jednom zašľahajte vajcia. Posledné vajce pridávajte po troškách: cesto je hotové, keď zo stierky padá v hustom, lesklom „V“. Všetky vajcia minúť nemusíte.",
            "Rúru predhrejte na 220 °C (horný a spodný ohrev). Cesto dajte do vrecka s veľkou hviezdicovou špičkou a na plech s papierom na pečenie striekajte ružice s priemerom 4–5 cm s rozostupmi asi 3 cm.",
            "Pečte 10 minút na 220 °C, potom znížte na 180 °C a pečte ešte 15–20 minút, kým nie sú veterníčky sýto zlatisté a ľahké. Rúru prvých 20 minút neotvárajte, inak veterníčky spadnú.",
            "Ešte teplé veterníčky rozrežte vodorovne nožom so zúbkami a nechajte úplne vychladnúť na mriežke.",
            "Zmäknuté maslo šľahajte 3–4 minúty do svetlej peny. Po lyžiciach pridávajte vychladnutý puding rovnakej teploty a šľahajte dohladka. Nakoniec vmiešajte rum.",
            "Práškový cukor preosejte a vymiešajte s citrónovou šťavou, rumom a horúcou vodou do hustej polevy, ktorá pomaly steká z lyžice.",
            "Do spodných polovíc nastriekajte krém hviezdicovou špičkou tak, aby presahoval okraj. Vrchy namočte do polevy, nechajte odkvapkať a priklopte. Pred podávaním nechajte v chlade aspoň hodinu stuhnúť.",
        ],
        "notes": [
            "Poleva zostane biela vďaka citrónovej šťave. Keď je príliš hustá, pridajte po kvapkách horúcu vodu. Keď je riedka, prisypte práškový cukor.",
            "Maslo a puding musia mať rovnakú teplotu. Studený puding v teplom masle krém zrazí.",
            "Ľahšia varianta: do hotového krému vmiešajte 150 ml vyšľahanej smotany na šľahanie. Takéto veterníčky vydržia v chladničke len do druhého dňa.",
            "Neplnené veterníčky vydržia v uzavretej dóze 2 dni. Plňte ich najneskôr niekoľko hodín pred podávaním, aby zostali chrumkavé.",
        ],
        "gallery": [
            ("vetrnicky-s-vanilkovym-kremem-rez.webp", "Rozkrojený veterníček: dutá škrupina z odpaľovaného cesta plná vanilkového krému"),
            ("vetrnicky-s-vanilkovym-kremem-postup.webp", "Ružice odpaľovaného cesta nastriekané hviezdicovou špičkou na plechu pred pečením"),
        ],
    },
    "irsky-sticky-toffee-pudding-recept": {
        "name": "Írsky sticky toffee pudding",
        "teaser": "Vlhký datľový zákusok s kakaom holandského typu a Baileys, preliaty slanou toffee omáčkou. 6 porcií.",
        "title": "Írsky sticky toffee pudding s kakaom a Baileys — recept",
        "desc": "Sticky toffee pudding podľa Donala Skehana s kakaom holandského typu a 100 ml Baileys v ceste. 6 porcií, pečenie 45–50 minút na 160 °C.",
        "product": "kakao_holandskeho_typu",
        "meta": "6 porcií · Pečenie 45–50 min · 160 °C",
        "ingredients": [
            "Cesto: 125 g masla",
            "150 g svetlého cukru muscovado",
            "1 lyžica zlatého sirupu (golden syrup)",
            "1 lyžica čiernej melasy (black treacle)",
            "2 veľké vajcia",
            "1 lyžička vanilkového extraktu",
            "150 g samokypriacej múky",
            "60 g kakaa holandského typu",
            "150 g datlí medjool, posekaných",
            "2 lyžičky jedlej sódy",
            "100 ml Baileys Irish Cream",
            "180 ml vody",
            "vanilková zmrzlina na podávanie",
            "Toffee omáčka: 100 g masla (nesoleného)",
            "150 g tmavého cukru muscovado",
            "3 lyžice zlatého sirupu",
            "150 ml hustej smotany (double cream)",
            "1 lyžička vanilkového extraktu",
            "štedrá štipka morskej soli",
        ],
        "steps": [
            "Rúru predhrejte na 160 °C (140 °C horúcovzdušne). Vymastite zapekaciu misu s priemerom 20 cm.",
            "Maslo a cukor vyšľahajte do svetlej peny.",
            "Na nízke otáčky pomaly vmiešajte zlatý sirup, melasu, vajcia a vanilku.",
            "Samokypriacu múku preosejte s kakaom a na nízke otáčky zapracujte do cesta.",
            "180 ml vody s posekanými datľami niekoľko minút povarte, odstavte a vmiešajte Baileys a jedlú sódu — zmes spení.",
            "Horúcu datľovo-baileysovú zmes zapracujte do kakaového cesta, vlejte do misy a pečte 45–50 minút, kým je puding pevný a mierne pružný. Špajdľou skontrolujte, či sa nelepia vlhké omrvinky; farbou sa neriaďte — cesto je tmavé.",
            "Omáčka: maslo, cukor a zlatý sirup rozohrejte, kým sa cukor nerozpustí. Pridajte smotanu, vanilku a soľ a 3 minúty mierne povarte, kým zahustne. Pre silnejšiu írsku chuť na záver mimo plotny vmiešajte 1–2 lyžice Baileys (voliteľné — alkohol sa už neodparí).",
            "Teplý puding prelejte toffee omáčkou a podávajte s vanilkovou zmrzlinou.",
        ],
        "notes": [
            "Baileys sa pridáva až po povarení datlí s vodou, mimo plotne — dlhší var by vyhnal alkohol a stlmil chuť likéru.",
            "Vody je o 100 ml menej ako v pôvodnom recepte (180 ml namiesto 280 ml), práve o množstvo pridaného Baileys, aby hydratácia cesta a čas pečenia ostali rovnaké.",
        ],
    },
}
