# Deutsche Rezepte — Übersetzung von recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Hausgemachter Lebkuchen (Perník)",
        "teaser": "Tassen-Lebkuchen, den Sie für die einfache Zubereitung und den köstlichen Geschmack lieben werden. Keine Waage nötig — eine Tasse genügt.",
        "title": "Lebkuchen (Perník) — Tassenrezept nach Jiřina Jůzlová",
        "desc": "Tassen-Lebkuchen ohne Abwiegen: 10 Minuten Zubereitung, 20–25 Minuten Backzeit, 25–30 Portionen. Mit Vanillepudding und Kakao holländischer Art.",
        "product": "vanilkovy_pudink",
        "meta": "Zubereitung 10 Min. · Backen 20–25 Min. · 25–30 Portionen",
        "ingredients": [
            "3 Tassen glattes Mehl (Tasse = 200 ml)",
            "2 Tassen Kristallzucker",
            "1 Tasse Öl",
            "2 mittelgroße Eier",
            "2 gehäufte Esslöffel Vanillepuddingpulver",
            "1 Päckchen Lebkuchen-Backmischung (Gewürz-Triebmittel)",
            "½ Päckchen Backpulver",
            "250 ml Milch (1¼ Tassen)",
            "Kakao holländischer Art nach Geschmack",
        ],
        "steps": [
            "Geben Sie alle Zutaten in eine Schüssel und vermischen Sie sie gründlich mit dem Mixer, damit sich keine Klümpchen bilden.",
            "Gießen Sie den Teig auf ein gefettetes, mit grobem Mehl bestäubtes Backblech.",
            "Backen Sie im auf 180 °C vorgeheizten Ofen 20 bis 25 Minuten (je nach Blechhöhe).",
            "Ob der Lebkuchen fertig ist, prüfen Sie mit einem Holzstäbchen — nach dem Einstechen muss es sauber bleiben, ohne anhaftenden Teig.",
        ],
        "notes": ["Tipp: Nach Geschmack können Sie dem Teig etwas Rum oder Rumaroma, Zimt, grob gehackte Walnüsse oder Schokolade hinzufügen."],
    },
    "slehackova-rolada-recept": {
        "name": "Sahneroulade",
        "teaser": "Ein leichtes Dessert in einer halben Stunde: der Kontrast von herbem Kakao und zart gesüßter Schlagsahne. Ohne Mehl, also auch ohne Gluten.",
        "title": "Sahneroulade — glutenfreies Rezept mit Kakao",
        "desc": "Sahneroulade ohne Mehl und ohne Gluten: 5 Eier, Puderzucker, Kakao holländischer Art und Schlagsahne. Fertig in 30 Minuten.",
        "product": "kakao_holandskeho_typu",
        "meta": "Zubereitung ca. 30 Min. · Glutenfrei",
        "ingredients": [
            "5 Eier",
            "100 g Puderzucker",
            "1 Esslöffel Kakao holländischer Art",
            "1 Becher Schlagsahne (nach Belieben Sahnesteif)",
        ],
        "steps": [
            "Schlagen Sie das Eiweiß zu steifem Schnee, geben Sie dann die Eigelbe und den Puderzucker dazu. Durch vorsichtiges Unterheben entsteht ein glatter Teig.",
            "Fügen Sie zuletzt den Kakao holländischer Art hinzu — er sorgt für eine satte Schokoladenfarbe und einen kräftigen Geschmack.",
            "Bereiten Sie ein leicht mit Schmalz gefettetes Backpapier vor (Öl geht auch), damit sich die Roulade nach dem Backen gut aufrollen lässt.",
            "Backen Sie im auf 180 °C vorgeheizten Ofen etwa 8 Minuten; öffnen Sie den Ofen während der gesamten Zeit nicht.",
            "Lassen Sie die Roulade auf dem Blech abkühlen und lösen Sie sie vorsichtig vom Papier.",
            "Schlagen Sie die Sahne steif, bestreichen Sie die Roulade damit und rollen Sie sie auf. Verzieren Sie den Rücken mit der restlichen Sahne, für den Effekt mit Schokoladenspänen.",
        ],
        "notes": ["Tipp: Verfeinern Sie die Roulade mit Ihrem Lieblingsobst — Erdbeeren, Himbeeren oder Banane."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Birnenkuchen mit Vanillepudding",
        "teaser": "Ein Kuchen, dessen Zubereitung auch Kindern Spaß macht. Backen macht doppelt Freude — beim Zubereiten und beim Probieren.",
        "title": "Birnenkuchen mit Vanillepudding — Rezept von Lucie Kůželová",
        "desc": "Birnenkuchen mit Sauerrahm und Vanillepudding: 20 Minuten Zubereitung, 45 Minuten Backzeit, 8 Portionen. Gelingt auch mit Äpfeln, Himbeeren oder Pfirsichen.",
        "product": "vanilkovy_pudink",
        "meta": "Zubereitung 20 Min. · Backen 45 Min. · 8 Portionen",
        "ingredients": [
            "2 Eier",
            "80 g zerlassene Butter",
            "150 g Kristallzucker",
            "200 g glattes Mehl (lässt sich mit Vollkorn- oder Dinkelmehl kombinieren)",
            "1 Päckchen Backpulver",
            "2 Becher Sauerrahm",
            "1 Becher Schlagsahne (30 %)",
            "40 g Vanillepuddingpulver",
            "5 Birnen (ersatzweise Äpfel, Himbeeren, Pfirsiche — frisches oder gefrorenes Obst)",
        ],
        "steps": [
            "Vermischen Sie ein Ei, die Butter, 50 g Zucker, das Mehl und das Backpulver. Kneten Sie den Teig mit den Händen und drücken Sie ihn in eine mit Backpapier ausgelegte Kuchenform (ein krümeliger Teig ist kein Problem — drücken Sie ihn einfach in die Form).",
            "Schneiden Sie die geschälten Birnen in Spalten und verteilen Sie sie auf dem Teig.",
            "Verrühren Sie in einer Schüssel den Sauerrahm, die Schlagsahne, das Puddingpulver, 100 g Zucker und das zweite Ei; gießen Sie die Mischung über den Kuchen.",
            "Backen Sie in der Mitte des auf 180 °C vorgeheizten Ofens etwa 45 Minuten.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Mohnnudeln (šišky s mákem)",
        "teaser": "Ein traditionelles süßes Abendessen aus Kartoffelteig: Mohnnudeln in Mohn und Zucker gewälzt, mit zerlassener Butter übergossen.",
        "title": "Mohnnudeln (šišky s mákem) aus Kartoffelteig — Rezept",
        "desc": "Mohnnudeln (šišky s mákem) aus Jůzlová Kartoffelteig: ein schnelles, traditionelles süßes Abendessen mit Mohn, Zucker und zerlassener Butter.",
        "product": "bramborove_knedliky",
        "meta": "Aus Jůzlová Kartoffelteig",
        "ingredients": [
            "Jůzlová Kartoffelteig (nach Packungsanleitung)",
            "gemahlener Mohn",
            "Puderzucker",
            "zerlassene Butter",
        ],
        "steps": [
            "Formen Sie aus dem nach Anleitung zubereiteten Kartoffelteig kleine Nudeln (šišky).",
            "Geben Sie sie in kochendes Salzwasser und garen Sie sie, bis sie an die Oberfläche steigen.",
            "Wälzen Sie sie in gemahlenem Mohn mit Zucker und übergießen Sie sie mit zerlassener Butter.",
        ],
        "notes": ["Das vollständige Originalrezept wird aus dem Archiv ergänzt."],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky mit Kraut und Speck",
        "teaser": "Ein slowakischer Klassiker aus Kartoffelteig — Strapačky mit Sauerkraut und knusprig gebratenem Speck.",
        "title": "Strapačky mit Sauerkraut und Speck — Kartoffelteig-Rezept",
        "desc": "Strapačky aus Jůzlová Kartoffelteig mit Sauerkraut und knusprigem Speck. Ein deftiges Gericht nach slowakischer Tradition.",
        "product": "bramborove_knedliky",
        "meta": "Aus Jůzlová Kartoffelteig",
        "ingredients": [
            "Jůzlová Kartoffelteig (nach Packungsanleitung)",
            "Sauerkraut",
            "geräucherter Speck",
            "Zwiebel, Salz, Pfeffer",
        ],
        "steps": [
            "Schneiden oder drücken Sie aus dem Kartoffelteig kleine Nocken (Strapačky) in kochendes Wasser und garen Sie sie, bis sie an die Oberfläche steigen.",
            "Schneiden Sie den Speck in Würfel und braten Sie ihn goldbraun aus; geben Sie die Zwiebel und das erwärmte Sauerkraut dazu.",
            "Vermengen Sie die Strapačky mit Kraut und Speck und servieren Sie sie heiß.",
        ],
        "notes": ["Das vollständige Originalrezept wird aus dem Archiv ergänzt."],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe-Schnitten mit Schokoladenpudding",
        "teaser": "Sie möchten Gäste bewirten, sind aber kein Jamie Oliver? Diese Bebe-Schnitten ohne Backen gelingen wirklich jedem.",
        "title": "Bebe-Schnitten mit Schokoladenpudding — ohne Backen",
        "desc": "Bebe-Schnitten ohne Backen mit Jůzlová Kakaopudding nach Lucie Kůželová: Kekse, Puddingcreme und Schlagsahne. Ganz ohne Ofen.",
        "product": "kakao_holandskeho_typu",
        "meta": "Dessert ohne Backen · Nach Lucie Kůželová",
        "ingredients": [
            "Bebe-Kekse (Butterkekse)",
            "Jůzlová Kakaopudding (Pulver)",
            "Milch und Zucker nach Puddinganleitung",
            "Butter",
            "Schlagsahne",
        ],
        "steps": [
            "Legen Sie den Boden einer Form mit einer Schicht Bebe-Kekse aus.",
            "Kochen Sie einen etwas festeren Kakaopudding, lassen Sie ihn leicht abkühlen und schlagen Sie die Butter unter.",
            "Streichen Sie die Creme auf die Kekse, decken Sie sie mit einer weiteren Keksschicht ab und lassen Sie alles im Kühlen fest werden.",
            "Verzieren Sie die Schnitten vor dem Servieren mit Schlagsahne.",
        ],
        "notes": ["Das vollständige Originalrezept wird aus dem Archiv ergänzt."],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Kartoffel-Quark-Knödel mit Erdbeeren",
        "teaser": "Der Sommer ist da und mit ihm reifen die Erdbeeren. Ein einfaches, schnelles Rezept, mit dem Sie in 20 Minuten auch die größten Naschkatzen verwöhnen.",
        "title": "Kartoffel-Quark-Knödel mit Erdbeeren — Rezept in 20 Minuten",
        "desc": "Fruchtknödel aus Jůzlová Kartoffelteig mit Quark und Erdbeeren nach Lucie Kůželová. Fertig in 20 Minuten.",
        "product": "bramborove_knedliky",
        "meta": "20 Minuten · Nach Lucie Kůželová",
        "ingredients": [
            "Jůzlová Kartoffelteig (nach Packungsanleitung)",
            "Quark",
            "frische Erdbeeren",
            "Puderzucker, zerlassene Butter",
        ],
        "steps": [
            "Arbeiten Sie den Quark in den Kartoffelteig ein.",
            "Formen Sie aus dem Teig kleine Fladen, wickeln Sie in jeden eine Erdbeere ein und formen Sie Knödel.",
            "Kochen Sie sie in Salzwasser, bis die Knödel an die Oberfläche steigen.",
            "Servieren Sie sie mit Zucker und Quark bestreut und mit zerlassener Butter übergossen.",
        ],
        "notes": ["Das vollständige Originalrezept wird aus dem Archiv ergänzt."],
    },
}
