# English recipes — translation of recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Homemade gingerbread (perník)",
        "teaser": "Cup-measure gingerbread you’ll love for its easy preparation and great taste. No scales needed — a mug is enough.",
        "title": "Homemade Czech gingerbread — Jiřina Jůzlová’s cup recipe",
        "desc": "Czech cup-measure gingerbread with no weighing: 10 minutes prep, 20–25 minutes baking, 25–30 servings. With vanilla pudding powder and Dutch-process cocoa.",
        "product": "vanilkovy_pudink",
        "meta": "Prep 10 min · Bake 20–25 min · 25–30 servings",
        "ingredients": [
            "3 cups plain flour (cup = 200 ml)",
            "2 cups granulated sugar",
            "1 cup oil",
            "2 medium eggs",
            "2 heaped tablespoons vanilla pudding powder",
            "1 sachet gingerbread spice-leavening mix",
            "½ sachet baking powder",
            "250 ml milk (1¼ cups)",
            "Dutch-process cocoa to taste",
        ],
        "steps": [
            "Put all the ingredients into one bowl and mix thoroughly with an electric mixer so no lumps form.",
            "Pour the batter onto a greased baking tray dusted with coarse flour.",
            "Bake in an oven preheated to 180 °C for 20–25 minutes (depending on tray depth).",
            "Test with a wooden toothpick — it should come out clean, with no batter sticking.",
        ],
        "notes": ["Tip: add a little rum or rum flavouring, cinnamon, roughly chopped walnuts or chocolate to the batter."],
    },
    "slehackova-rolada-recept": {
        "name": "Whipped cream roulade",
        "teaser": "A light dessert in half an hour: the contrast of slightly bitter cocoa and gently sweet whipped cream. No flour — so no gluten either.",
        "title": "Whipped cream roulade — gluten-free cocoa recipe",
        "desc": "Flourless, gluten-free whipped cream roulade: 5 eggs, icing sugar, Dutch-process cocoa and whipping cream. Done in 30 minutes.",
        "product": "kakao_holandskeho_typu",
        "meta": "About 30 min · Gluten-free",
        "ingredients": [
            "5 eggs",
            "100 g icing sugar",
            "1 tablespoon Dutch-process cocoa",
            "1 carton whipping cream (cream stiffener optional)",
        ],
        "steps": [
            "Whisk the egg whites to stiff peaks, then add the yolks and icing sugar. Fold gently into a smooth batter.",
            "Finally add the Dutch-process cocoa — it gives a deep chocolate colour and pronounced taste.",
            "Prepare baking paper lightly greased with lard (oil works too) so the roulade rolls up easily after baking.",
            "Bake at 180 °C for about 8 minutes; don’t open the oven while it bakes.",
            "Let the sponge cool on the tray, then carefully peel off the paper.",
            "Whip the cream stiff, spread it over the sponge and roll it up. Decorate the top with the remaining cream and chocolate shavings.",
        ],
        "notes": ["Tip: vary the roulade with your favourite fruit — strawberries, raspberries or banana."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Pear cake with vanilla pudding",
        "teaser": "A cake your children will enjoy making with you. Baking is fun twice — once preparing, once tasting.",
        "title": "Pear cake with vanilla pudding — Lucie Kůželová’s recipe",
        "desc": "Pear cake with sour cream and vanilla pudding: 20 minutes prep, 45 minutes baking, 8 servings. Works with apples, raspberries or peaches too.",
        "product": "vanilkovy_pudink",
        "meta": "Prep 20 min · Bake 45 min · 8 servings",
        "ingredients": [
            "2 eggs",
            "80 g melted butter",
            "150 g granulated sugar",
            "200 g plain flour (can be mixed with wholemeal or spelt)",
            "1 sachet baking powder",
            "2 cartons sour cream",
            "1 carton whipping cream (30%)",
            "40 g vanilla pudding powder",
            "5 pears (or apples, raspberries, peaches — fresh or frozen fruit)",
        ],
        "steps": [
            "Mix one egg, the butter, 50 g sugar, flour and baking powder. Work the dough by hand and press it into a cake tin lined with baking paper (a crumbly dough is fine — just press it in).",
            "Peel the pears, slice them and spread over the dough.",
            "In a bowl combine the sour cream, whipping cream, pudding powder, 100 g sugar and the second egg; pour over the cake.",
            "Bake in the middle of an oven preheated to 180 °C for about 45 minutes.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Poppy-seed rolls (šišky s mákem)",
        "teaser": "A traditional sweet supper from potato dough: rolls coated in poppy seeds and sugar, drizzled with melted butter.",
        "title": "Potato-dough poppy-seed rolls — recipe",
        "desc": "Poppy-seed rolls (šišky) from Jůzlová potato dough: a quick traditional sweet supper with ground poppy seeds, sugar and melted butter.",
        "product": "bramborove_knedliky",
        "meta": "From Jůzlová potato dough",
        "ingredients": [
            '400 g potato dumpling powder',
            '100 g ground poppy seeds',
            '2 tablespoons icing sugar (or more)',
            '2 tablespoons melted butter',
        ],
        "steps": [
            'Mix the potato dumpling powder with water per the instructions and shape small rolls from the dough.',
            'Bake on a greased tray in the middle of an oven preheated to 200 °C; turn once during baking so both sides turn golden.',
            'After baking, drop the rolls into boiling water and scald for 5 minutes.',
            'Put them in a large bowl, dust with poppy seeds and sugar, pour over the butter, toss and serve warm.',
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky with cabbage and bacon",
        "teaser": "A Slovak classic from hairy-dumpling mix — halušky with sauerkraut and crispy bacon.",
        "title": "Strapačky with sauerkraut and bacon — bosáky mix recipe",
        "desc": "Strapačky from Jůzlová hairy-dumpling powder with sauerkraut, spring onion and bacon fried in lard. A hearty Slovak classic.",
        "product": "chlupate_knedliky",
        "meta": "From Jůzlová hairy-dumpling mix",
        "ingredients": [
            '400 g hairy dumpling (bosáky) powder',
            '400 g sauerkraut',
            'a bunch of spring onions',
            '100 g bacon',
            'a spoonful of lard',
        ],
        "steps": [
            'Mix the hairy dumpling powder with water per the instructions. Press the swollen dough through a colander straight into boiling water and cook the halušky until they float.',
            "Boil the sauerkraut in a pot of water for about 10 minutes; drain any water that hasn’t boiled off.",
            'Fry diced bacon in lard; once lightly crisped, add sliced spring onion and take the pan off the heat after a minute.',
            'Mix the halušky with the cabbage and top each plate with the bacon and onion.',
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe biscuit slices with chocolate pudding",
        "teaser": "Want to treat your guests but you’re no Jamie Oliver? These no-bake biscuit slices are for everyone.",
        "title": "Bebe biscuit slices with chocolate pudding — no-bake recipe",
        "desc": "No-bake bebe biscuit slices with Jůzlová cocoa pudding, after Lucie Kůželová: biscuits, pudding cream and whipped cream. No oven needed.",
        "product": "kakao_holandskeho_typu",
        "meta": "No-bake dessert · After Lucie Kůželová",
        "ingredients": [
            '4 packs of BEBE biscuits: 2 plain, 2 dark',
            '2 cartons sour cream',
            '1 carton whipping cream',
            '40 g vanilla sugar',
            '150 g chocolate pudding powder (3 sachets)',
            '1 litre milk',
            'Dutch-process cocoa for dusting',
        ],
        "steps": [
            'Line a tray with the plain bebe biscuits.',
            'Cook the chocolate pudding per the pack instructions and pour it evenly over the biscuits.',
            'Lay the dark bebe biscuits over the pudding layer.',
            'Whip the cream with the vanilla sugar until stiff, fold in the sour cream and spread the mixture over the biscuits.',
            'Dust with dark cocoa and let it rest in the fridge, ideally overnight.',
        ],
        "notes": ['Tip: if you have a different pudding on hand, experiment — the slices are excellent with vanilla pudding and a cinnamon dusting.'],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Potato-and-curd dumplings with strawberries",
        "teaser": "Summer is here, and with it ripening strawberries. A simple 20-minute recipe that delights the sweetest tooth.",
        "title": "Potato-curd dumplings with strawberries — 20-minute recipe",
        "desc": "Fruit dumplings from Jůzlová potato dough with curd cheese and strawberries, after Lucie Kůželová. Ready in 20 minutes.",
        "product": "bramborove_knedliky",
        "meta": "20 minutes · After Lucie Kůželová",
        "ingredients": [
            '250 g potato dumpling powder',
            '250 g soft curd cheese (the block kind, not the tub)',
            'strawberries (for filling and garnish)',
            'sugar, butter and curd for garnish',
        ],
        "steps": [
            'Mix the potato dumpling powder with water per the instructions into a supple dough; work in the curd cheese (a sticky dough is fine).',
            'Shape the dough into a log and cut equal pieces so the dumplings cook evenly.',
            'Round each piece, press into a disc, push a strawberry into the middle and wrap it up.',
            'Steam the dumplings for 5 minutes — steaming cooks the dough through without it falling apart.',
            'Meanwhile simmer some strawberry pieces for a garnish. Serve topped with butter, sugar, strawberries or curd.',
        ],
        "notes": [],
    },
}
