# English recipes — translation of recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Homemade gingerbread (perník)",
        "teaser": "Cup-measure gingerbread that is easy to make and easy to like. No scales needed — a mug is enough.",
        "title": "Homemade Czech gingerbread — Jiřina Jůzlová’s cup recipe",
        "desc": "Czech cup-measure gingerbread with no weighing: 10 minutes prep, 20–25 minutes baking, 25–30 servings. With vanilla pudding powder and Dutch-process cocoa.",
        "product": "vanilkovy_pudink",
        "meta": "Prep 10 min · Bake 20–25 min · 25–30 servings",
        "ingredients": [
            "3 cups plain flour (cup = 200 ml)",
            "2 cups granulated sugar",
            "1 cup oil",
            "2 medium eggs",
            "2 heaped tablespoons vanilla pudding powder",
            "1 pack (about 20 g) gingerbread spice with raising agent",
            "6 g baking powder (about 1½ teaspoons)",
            "250 ml milk (1¼ cups)",
            "Dutch-process cocoa to taste",
        ],
        "steps": [
            "Put all the ingredients into one bowl and mix thoroughly with an electric mixer until no lumps remain.",
            "Pour the batter onto a greased baking tray dusted with coarse flour.",
            "Bake in an oven preheated to 180 °C for 20–25 minutes (depending on tray depth).",
            "Test with a wooden skewer: it should come out clean, with no batter sticking to it.",
        ],
        "notes": ["Tip: add a little rum or rum flavouring, cinnamon, roughly chopped walnuts or chocolate to the batter."],
    },
    "slehackova-rolada-recept": {
        "name": "Whipped cream roulade",
        "teaser": "A light dessert in half an hour: slightly bitter cocoa against gently sweet whipped cream. No flour, so no gluten either.",
        "title": "Whipped cream roulade — gluten-free cocoa recipe",
        "desc": "Gluten-free whipped cream roulade: 5 eggs, 100 g icing sugar, a spoonful of Dutch-process cocoa and whipping cream. Baked 8 minutes at 180 °C, done in 30.",
        "product": "kakao_holandskeho_typu",
        "meta": "About 30 min · Gluten-free",
        "ingredients": [
            "5 eggs",
            "100 g icing sugar",
            "1 tablespoon Dutch-process cocoa",
            "1 carton whipping cream (cream stiffener optional)",
        ],
        "steps": [
            "Whisk the egg whites to stiff peaks, then add the yolks and icing sugar. Fold gently into a smooth batter.",
            "Finally add the Dutch-process cocoa — it gives a deep chocolate colour and a pronounced taste.",
            "Line a tray with baking paper lightly greased with lard (oil works too), so the roulade rolls up easily after baking.",
            "Bake at 180 °C for about 8 minutes; don’t open the oven while it bakes.",
            "Let the sponge cool on the tray, then carefully peel off the paper.",
            "Whip the cream until stiff, spread it over the sponge and roll it up. Decorate the top with the remaining cream and chocolate shavings.",
        ],
        "notes": ["Tip: vary the roulade with your favourite fruit — strawberries, raspberries or banana."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Pear cake with vanilla pudding",
        "teaser": "A cake your children will enjoy making with you. The fun comes twice: once in the making, once in the eating.",
        "title": "Pear cake with vanilla pudding — Lucie Kůželová’s recipe",
        "desc": "Pear cake with sour cream and vanilla pudding: 20 minutes prep, 45 minutes baking, 8 servings. Works with apples, raspberries or peaches too.",
        "product": "vanilkovy_pudink",
        "meta": "Prep 20 min · Bake 45 min · 8 servings",
        "ingredients": [
            "2 eggs",
            "80 g melted butter",
            "150 g granulated sugar",
            "200 g plain flour (can be mixed with wholemeal or spelt)",
            "12 g baking powder (about 1 tablespoon)",
            "2 cartons sour cream",
            "1 carton whipping cream (30 %)",
            "40 g vanilla pudding powder",
            "5 pears (or apples, raspberries or peaches, fresh or frozen)",
        ],
        "steps": [
            "Mix one egg, the butter, 50 g of the sugar, the flour and the baking powder. Work the dough by hand and press it into a cake tin lined with baking paper (a crumbly dough is fine; just press it in).",
            "Peel the pears, slice them and spread over the dough.",
            "In a bowl, combine the sour cream, whipping cream, pudding powder, the remaining 100 g of sugar and the second egg. Pour it over the pears.",
            "Bake in the middle of an oven preheated to 180 °C for about 45 minutes.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Poppy-seed rolls (šišky s mákem)",
        "teaser": "A traditional sweet supper from potato dough: rolls coated in poppy seeds and sugar, drizzled with melted butter.",
        "title": "Potato-dough poppy-seed rolls — recipe",
        "desc": "Poppy-seed rolls (šišky) made from our potato dumpling mix: a quick, traditional sweet supper with ground poppy seeds, sugar and melted butter.",
        "product": "bramborove_knedliky",
        "meta": "Made with our potato dumpling mix",
        "ingredients": [
            '400 g potato dumpling mix',
            '100 g ground poppy seeds',
            '2 tablespoons icing sugar (or more)',
            '2 tablespoons melted butter',
        ],
        "steps": [
            'Mix the potato dumpling mix with water as directed on the bag and shape the dough into small rolls.',
            'Bake on a greased tray in the middle of an oven preheated to 200 °C, turning them once so both sides turn golden.',
            'After baking, drop the rolls into boiling water and let them boil for 5 minutes.',
            'Tip them into a large bowl, sprinkle with the poppy seeds and sugar, pour over the butter, toss and serve warm.',
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky with cabbage and bacon",
        "teaser": "A Slovak classic made from our raw-potato dumpling mix: halušky with sauerkraut and crisp bacon.",
        "title": "Strapačky with sauerkraut and bacon — bosáky mix recipe",
        "desc": "Strapačky made from our raw-potato dumpling mix (chlupaté knedlíky), with sauerkraut, spring onion and bacon fried in lard. A hearty Slovak classic.",
        "product": "chlupate_knedliky",
        "meta": "Made with our raw-potato dumpling mix",
        "ingredients": [
            '400 g raw-potato dumpling mix (bosáky)',
            '400 g sauerkraut',
            'a bunch of spring onions',
            '100 g bacon',
            'a spoonful of lard',
        ],
        "steps": [
            'Mix the dumpling mix with water as directed on the bag. Once the dough has swelled, press it through a colander straight into boiling water and cook the halušky until they float.',
            "Simmer the sauerkraut in a pan of water for about 10 minutes, then drain off any remaining water.",
            'Fry the diced bacon in the lard. Once it is lightly crisp, add the sliced spring onion and take the pan off the heat after a minute.',
            'Mix the halušky with the sauerkraut and top each plate with the bacon and onion.',
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe biscuit slices with chocolate pudding",
        "teaser": "Want to treat your guests but you’re no Jamie Oliver? These no-bake biscuit slices are for everyone.",
        "title": "Bebe biscuit slices with chocolate pudding — no-bake recipe",
        "desc": "No-bake bebe biscuit slices with chocolate pudding, after Lucie Kůželová: biscuits, chocolate pudding, sour cream and whipped cream. No oven; rest overnight.",
        "product": "kakao_holandskeho_typu",
        "meta": "No-bake dessert · After Lucie Kůželová",
        "ingredients": [
            '4 packs of BEBE biscuits: 2 plain, 2 dark',
            '2 cartons sour cream',
            '1 carton whipping cream',
            '40 g vanilla sugar',
            '150 g of our vanilla pudding powder and 2 tablespoons Dutch-process cocoa',
            '1 litre milk',
            'Dutch-process cocoa for dusting',
        ],
        "steps": [
            'Line a tray with the plain bebe biscuits.',
            'Cook the chocolate pudding as directed on the pack and pour it evenly over the biscuits.',
            'Lay the dark bebe biscuits over the pudding layer.',
            'Whip the cream with the vanilla sugar until stiff, fold in the sour cream and spread the mixture over the biscuits.',
            'Dust with the cocoa and leave to set in the fridge, ideally overnight.',
        ],
        "notes": ['Tip: if you have a different pudding to hand, experiment — the slices also work well with vanilla pudding and a dusting of cinnamon.'],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Potato-and-curd dumplings with strawberries",
        "teaser": "Summer brings ripe strawberries. A simple 20-minute recipe for anyone with a sweet tooth.",
        "title": "Potato-curd dumplings with strawberries — 20-minute recipe",
        "desc": "Fruit dumplings made from our potato dumpling mix and curd cheese, filled with strawberries, after Lucie Kůželová. Steamed for 5 minutes, ready in 20.",
        "product": "bramborove_knedliky",
        "meta": "20 minutes · After Lucie Kůželová",
        "ingredients": [
            '250 g potato dumpling mix',
            '250 g soft curd cheese (the block kind, not the tub)',
            'strawberries (for filling and garnish)',
            'sugar, butter and curd cheese, to serve',
        ],
        "steps": [
            'Mix the potato dumpling mix with water as directed on the bag to make a supple dough, then work in the curd cheese (a sticky dough is fine).',
            'Shape the dough into a log and cut it into equal pieces so the dumplings cook evenly.',
            'Roll each piece into a ball, press it into a disc, put a strawberry in the middle and seal the dough around it.',
            'Steam the dumplings for 5 minutes — steaming cooks the dough through without it falling apart.',
            'Meanwhile, simmer a few strawberry pieces for the topping. Serve with butter, sugar, strawberries or curd cheese.',
        ],
        "notes": [],
    },
    "rychle-venecky-ci-vetrnicky-recept": {
        "name": "Quick choux wreaths or puffs",
        "teaser": "One choux pastry for both věnečky and větrníčky: extra butter and a 250 °C start. About 80 pieces on two trays.",
        "title": "Quick choux wreaths or puffs — recipe",
        "desc": "Quick Czech věnečky and větrníčky from choux pastry: 250 ml water, 90 g butter, 140 g coarse flour, 4 eggs. 45 min prep, about 15 min baking, around 80 pieces.",
        "meta": "Prep 45 min · Bake about 15 min · about 80 pieces · 2 trays",
        "ingredients": [
            "250 ml water",
            "a pinch of salt",
            "90 g butter",
            "140 g coarse flour (hrubá mouka)",
            "4 eggs",
            "fat, for greasing the trays",
        ],
        "steps": [
            "Bring the water, salt and butter to a boil.",
            "Reduce the heat and stir in the flour all at once; mix until the dough pulls cleanly away from the pan and is no longer sticky.",
            "Take it off the heat and let it cool slightly.",
            "Preheat the oven to 250 °C.",
            "Beat in the eggs one at a time, mixing continuously, until the batter is smooth and slightly elastic.",
            "Pipe onto the greased trays: two stacked rings for věnečky, or small round mounds for větrníčky.",
            "Bake at 250 °C for 5 minutes, then reduce to 200 °C and bake until golden — roughly 5 more minutes at the higher heat, then 5 at the lower. Do not open the oven door while baking.",
            "Slice them straight away while still hot (this stops the shells tearing later). Cool completely before filling.",
        ],
        "notes": [
            "The filling is up to you: sweetened whipped cream is the simplest. For věnečky use the vanilla buttercream and rum glaze from the wreath recipe; for větrníčky use the vanilla pudding cream, caramel whipped cream and caramel glaze from the caramel větrník recipe.",
            "This dough uses a higher butter-to-flour ratio (90 g : 140 g) and a hot 250 °C start, which is why it puffs faster and more reliably.",
        ],
    },
    "venecky-s-vanilkovym-kremem-recept": {
        "name": "Choux wreaths with vanilla cream",
        "teaser": "Classic věnečky from choux pastry with vanilla buttercream and rum glaze. About 20 pieces.",
        "title": "Czech věnečky with vanilla cream and rum glaze — recipe",
        "desc": "Choux-pastry věnečky with a vanilla buttercream made from pudding powder and egg yolks, finished with a rum glaze. About 20 pieces; bake at 200 then 180 °C.",
        "product": "vanilkovy_pudink",
        "meta": "About 20 pieces · choux pastry, vanilla cream, rum glaze",
        "ingredients": [
            "Choux pastry: 320 ml water",
            "100 g butter",
            "a pinch of salt",
            "235 g flour",
            "4–5 eggs, added gradually",
            "Vanilla buttercream: 500 ml milk",
            "80 g of our vanilla pudding powder",
            "5 egg yolks",
            "150 g sugar",
            "250 g softened butter",
            "2 tablespoons rum (optional)",
            "Rum glaze: 300 g icing sugar",
            "2 tablespoons rum",
            "3 tablespoons hot milk",
        ],
        "steps": [
            "Bring the water, butter and salt to a boil. Take off the heat, stir in all the flour, then cook for 2–3 minutes over a low heat until it comes together in a ball.",
            "Cool until just warm. Beat in the eggs a little at a time until the dough falls from a spoon in a thick ribbon.",
            "Pipe 6–7 cm rings onto baking paper. Bake at 200 °C for 10 minutes without opening the door, then reduce to 180 °C for another 15–25 minutes until deep golden and dry to the touch.",
            "Cool completely, then ideally leave uncovered for a few hours or overnight so the shells stay crisp.",
            "Cook the pudding with the milk, sugar and yolks, stirring constantly, until thickened (do not let it boil hard once the yolks are in). Cool completely, pressing cling film onto the surface.",
            "Beat the softened butter until fluffy, then add the cooled pudding a spoonful at a time until smooth and light. Stir in the rum.",
            "Whisk the icing sugar, rum and hot milk to a smooth, pourable glaze.",
            "Slice the rings horizontally. Pipe the buttercream generously onto the bottom halves, replace the tops and dip them in the rum glaze. Leave to set.",
        ],
        "notes": [
            "Lighter variant: skip the rum glaze, use a plain pudding cream instead of buttercream, and top with whipped cream and a dusting of icing sugar.",
        ],
    },
    "kremrole-recept": {
        "name": "Cream horns (kremrole)",
        "teaser": "Flaky pastry tubes filled with glossy Italian meringue. About 35–40 pieces; you will need metal cream-horn tubes.",
        "title": "Czech kremrole with Italian meringue — recipe",
        "desc": "Czech kremrole: butter-pastry cream horns wound on metal tubes and filled with glossy Italian meringue. About 35–40 pieces; bake 12–15 minutes at 180–200 °C.",
        "meta": "About 35–40 pieces · bake 12–15 min · metal tubes",
        "ingredients": [
            "Dough: 350 g flour",
            "250 g cold butter (or Hera shortening), grated or cubed",
            "125 ml whipping cream",
            "optional, for extra flakiness: swap 25 g of the cream for sour cream",
            "Italian meringue: 80 g egg whites (about 2 eggs)",
            "160 g sugar",
            "40 ml water",
            "icing sugar, for dusting",
        ],
        "steps": [
            "Work the flour, butter and cream into a smooth dough — don’t overwork it. Wrap and chill for at least 1 hour (overnight is fine).",
            "Roll into a thin sheet, cut into 2 cm × 20 cm strips, and wind each strip around a greased metal tube, overlapping the edges slightly.",
            "Bake at 180–200 °C until golden, about 12–15 minutes. Cool slightly before easing them off the tubes.",
            "Heat the sugar and water to 115–120 °C without stirring (a sugar thermometer helps). Meanwhile, whip the egg whites to stiff peaks.",
            "With the mixer running, drizzle in the hot syrup in a thin stream, then keep beating until the meringue is glossy and only slightly warm. Chill briefly, then pipe into the cooled shells from both ends. Dust with icing sugar.",
        ],
        "notes": [
            "Simplest version: whisk the egg whites with the sugar over a pan of simmering water (bain-marie) until glossy and thick. No thermometer needed; slightly less stable, but reliably good.",
            "You can improvise tubes from foil if you have no metal cream-horn moulds.",
        ],
    },
    "minivetrnicky-recept": {
        "name": "Mini choux buns (minivětrníčky)",
        "teaser": "Mini větrníčky from choux pastry with a butter, pudding and curd cream and a chocolate glaze. About 40–45 pieces.",
        "title": "Mini větrníčky with pudding cream and chocolate glaze — recipe",
        "desc": "Mini větrníčky from choux pastry, filled with a vanilla pudding, butter and curd cream and dipped in chocolate. About 40–45 pieces; bake 20 minutes at 200 °C.",
        "product": "vanilkovy_pudink",
        "meta": "About 40–45 pieces · bake about 20 min",
        "ingredients": [
            "Choux pastry: 250 ml water",
            "a pinch of salt",
            "90 g butter",
            "160 g flour",
            "1 teaspoon baking powder",
            "4 eggs",
            "Filling: 0.5 l milk",
            "80 g of our vanilla pudding powder",
            "3 tablespoons sugar",
            "250 g softened butter",
            "125 g sugar",
            "vanilla sugar",
            "2 teaspoons rum",
            "about 150–200 g full-fat curd cheese (tvaroh)",
            "Glaze: dark or milk chocolate (with a little butter or oil for shine)",
        ],
        "steps": [
            "Bring the water, butter and salt to a boil. Off the heat, stir in the flour and baking powder until smooth, then stir over a low heat until the dough comes together. Let it cool slightly.",
            "Beat in the eggs one at a time with a mixer. Pipe small 2–3 cm mounds onto baking paper (two spoons work if you have no piping bag).",
            "Bake at 200 °C for about 20 minutes. Do not open the oven for the first 10 minutes.",
            "Cook the pudding and cool it completely (a few hours ahead is fine). Beat the softened butter with the sugar and vanilla sugar until fluffy, add the rum, then fold in the cooled pudding and curd a little at a time until smooth.",
            "Split the cooled buns three-quarters of the way through, pipe in the filling, and dip or coat the top with melted chocolate.",
        ],
        "notes": [
            "Lighter summer alternative: skip the buttercream and glaze — fill with sweetened whipped cream and fresh strawberry pieces, and dust with icing sugar.",
        ],
    },
    "karamelove-vetrniky-recept": {
        "name": "Caramel větrníky",
        "teaser": "Větrníky with vanilla pudding cream, caramel whipped cream and caramel glaze. About 24 medium pieces.",
        "title": "Caramel větrníky with two creams — recipe",
        "desc": "Caramel větrníky from choux pastry: vanilla pudding cream, caramel whipped cream and caramel glaze. About 24 medium pieces; make the caramel cream a day ahead.",
        "product": "vanilkovy_pudink",
        "meta": "About 24 medium pieces · make the caramel cream a day ahead",
        "ingredients": [
            "Choux pastry: 250 ml water",
            "100 g butter",
            "a pinch of salt",
            "160 g flour",
            "4–5 eggs (room temperature), whisked, added gradually",
            "½ teaspoon baking powder",
            "Vanilla pudding cream: 400 ml milk",
            "40 g of our vanilla pudding powder",
            "3 tablespoons sugar",
            "250 ml whipping cream (33 %), whipped until stiff",
            "Caramel whipped cream: 150 g sugar",
            "250 ml whipping cream (33 %), cold, plus a splash more to deglaze",
            "a pinch of salt",
            "Caramel glaze: 125 g sugar",
            "45 g butter",
            "75 ml whipping cream",
            "optional: 3–4 tablespoons of the reserved caramel cream, thinned with a little icing sugar",
        ],
        "steps": [
            "Bring the water, butter and salt to a boil. Remove from the heat, add all the flour at once and stir vigorously, then return to a low heat for 2–3 minutes until the dough comes together in a ball and a thin film forms on the base of the pan.",
            "Spread the dough around the sides of a mixing bowl to cool it quickly. Once it is only warm (hot dough would scramble the eggs), beat in the whisked eggs a little at a time on a low speed. Stop when the dough falls off a spoon in a thick “V” — you may not need all the egg. Fold in the baking powder last.",
            "Pipe 4–5 cm rounds onto baking paper with a large star nozzle, spaced well apart. Bake at 200–220 °C for 10 minutes, then reduce to 170–180 °C for another 15–20 minutes until deep golden and firm. Do not open the oven door during baking — the buns will collapse. Cool completely before filling.",
            "Cook the pudding with the milk and sugar as directed on the packet, then cool completely (press cling film onto the surface). Fold in the whipped cream once both are cold.",
            "Melt the sugar in a dry pan (no stirring, just swirling) until deep amber. Off the heat, carefully pour in a splash of the cream — it will bubble violently — then stir in the rest and a pinch of salt. Cool completely, chill for several hours or overnight, then whip to stiff peaks. Reserve 3–4 tablespoons for the glaze.",
            "Caramelise the sugar for the glaze the same way, take it off the heat, then stir in the butter and then the cream until smooth and glossy. Cool until it coats the back of a spoon but is still pourable.",
            "Slice each cooled bun horizontally, keeping the top as a cap. Pipe a base of vanilla pudding cream, then a swirl of caramel whipped cream, replace the cap and dip it in or spoon over the caramel glaze. Chill for at least 2 hours before serving so the layers set.",
        ],
        "notes": [
            "Add the eggs to the choux only once it has cooled to warm, and add them gradually. Flour absorbs liquid differently from batch to batch, so judge by texture, not by using up all the egg.",
            "Never open the oven while baking. Make the caramel cream a day ahead so it has time to firm up enough to whip.",
        ],
    },
    "irsky-sticky-toffee-pudding-recept": {
        "name": "Irish sticky toffee pudding",
        "teaser": "A moist date pudding with Dutch-process cocoa and Baileys, finished with a salted toffee sauce. Serves 6.",
        "title": "Irish sticky toffee pudding with cocoa and Baileys — recipe",
        "desc": "Sticky toffee pudding after Donal Skehan, with Dutch-process cocoa and 100 ml Baileys in the batter. Serves 6, bake 45–50 minutes at 160 °C.",
        "product": "kakao_holandskeho_typu",
        "meta": "Serves 6 · Bake 45–50 min · 160 °C",
        "ingredients": [
            "Pudding: 125 g butter",
            "150 g light muscovado sugar",
            "1 tablespoon golden syrup",
            "1 tablespoon black treacle",
            "2 large eggs",
            "1 teaspoon vanilla extract",
            "150 g self-raising flour",
            "60 g Dutch-process cocoa",
            "150 g Medjool dates, chopped",
            "2 teaspoons bicarbonate of soda",
            "100 ml Baileys Irish Cream",
            "180 ml water",
            "vanilla ice cream, for serving",
            "Toffee sauce: 100 g unsalted butter",
            "150 g dark muscovado sugar",
            "3 tablespoons golden syrup",
            "150 ml double cream",
            "1 teaspoon vanilla extract",
            "a generous pinch of sea salt",
        ],
        "steps": [
            "Heat the oven to 160 °C (140 °C fan). Grease a 20 cm round ovenproof dish.",
            "Beat the butter and sugar until light and fluffy.",
            "Slowly mix in the golden syrup, treacle, eggs and vanilla on a low speed.",
            "Sift the self-raising flour and cocoa together, then fold into the mixture on low speed.",
            "Simmer the 180 ml water with the chopped dates for a few minutes, take off the heat, then stir in the Baileys and the bicarbonate of soda — it will foam up.",
            "Fold the hot date and Baileys mixture into the batter, pour into the prepared dish and bake for 45–50 minutes, until firm and slightly springy. Test with a skewer, looking for a few moist crumbs, rather than judging by colour: the batter is dark.",
            "For the sauce: melt the butter, sugar and golden syrup until the sugar dissolves. Add the cream, vanilla and salt, and simmer for 3 minutes until thickened. For extra Irish flavour, stir 1–2 tablespoons of Baileys into the finished sauce off the heat (optional; the alcohol won’t cook off once the pan is off the heat).",
            "Drizzle the toffee sauce over the warm pudding and serve with vanilla ice cream.",
        ],
        "notes": [
            "The Baileys goes in after the dates have simmered, off the heat; prolonged boiling would drive off the alcohol and mute the cream-liqueur taste.",
            "The water is 100 ml less than in the original recipe (180 ml instead of 280 ml), matching the Baileys added, so the batter’s hydration and the baking time stay the same.",
        ],
    },
}
