# English recipes — translation of recipes_cs.py.
RECIPES = {
    "domaci-pernik-recept-podle-jirina-juzlova": {
        "name": "Homemade gingerbread (perník)",
        "teaser": "Cup-measure gingerbread you’ll love for its easy preparation and great taste. No scales needed — a mug is enough.",
        "title": "Homemade Czech gingerbread — Jiřina Jůzlová’s cup recipe",
        "desc": "Czech cup-measure gingerbread with no weighing: 10 minutes prep, 20–25 minutes baking, 25–30 servings. With vanilla pudding powder and Dutch-process cocoa.",
        "product": "vanilkovy_pudink",
        "meta": "Prep 10 min · Bake 20–25 min · 25–30 servings",
        "ingredients": [
            "3 cups plain flour (cup = 200 ml)",
            "2 cups granulated sugar",
            "1 cup oil",
            "2 medium eggs",
            "2 heaped tablespoons vanilla pudding powder",
            "1 sachet gingerbread spice-leavening mix",
            "½ sachet baking powder",
            "250 ml milk (1¼ cups)",
            "Dutch-process cocoa to taste",
        ],
        "steps": [
            "Put all the ingredients into one bowl and mix thoroughly with an electric mixer so no lumps form.",
            "Pour the batter onto a greased baking tray dusted with coarse flour.",
            "Bake in an oven preheated to 180 °C for 20–25 minutes (depending on tray depth).",
            "Test with a wooden toothpick — it should come out clean, with no batter sticking.",
        ],
        "notes": ["Tip: add a little rum or rum flavouring, cinnamon, roughly chopped walnuts or chocolate to the batter."],
    },
    "slehackova-rolada-recept": {
        "name": "Whipped cream roulade",
        "teaser": "A light dessert in half an hour: the contrast of slightly bitter cocoa and gently sweet whipped cream. No flour — so no gluten either.",
        "title": "Whipped cream roulade — gluten-free cocoa recipe",
        "desc": "Flourless, gluten-free whipped cream roulade: 5 eggs, icing sugar, Dutch-process cocoa and whipping cream. Done in 30 minutes.",
        "product": "kakao_holandskeho_typu",
        "meta": "About 30 min · Gluten-free",
        "ingredients": [
            "5 eggs",
            "100 g icing sugar",
            "1 tablespoon Dutch-process cocoa",
            "1 carton whipping cream (cream stiffener optional)",
        ],
        "steps": [
            "Whisk the egg whites to stiff peaks, then add the yolks and icing sugar. Fold gently into a smooth batter.",
            "Finally add the Dutch-process cocoa — it gives a deep chocolate colour and pronounced taste.",
            "Prepare baking paper lightly greased with lard (oil works too) so the roulade rolls up easily after baking.",
            "Bake at 180 °C for about 8 minutes; don’t open the oven while it bakes.",
            "Let the sponge cool on the tray, then carefully peel off the paper.",
            "Whip the cream stiff, spread it over the sponge and roll it up. Decorate the top with the remaining cream and chocolate shavings.",
        ],
        "notes": ["Tip: vary the roulade with your favourite fruit — strawberries, raspberries or banana."],
    },
    "hruskovy-kolac-s-vanilkovym-pudinkem-recept": {
        "name": "Pear cake with vanilla pudding",
        "teaser": "A cake your children will enjoy making with you. Baking is fun twice — once preparing, once tasting.",
        "title": "Pear cake with vanilla pudding — Lucie Kůželová’s recipe",
        "desc": "Pear cake with sour cream and vanilla pudding: 20 minutes prep, 45 minutes baking, 8 servings. Works with apples, raspberries or peaches too.",
        "product": "vanilkovy_pudink",
        "meta": "Prep 20 min · Bake 45 min · 8 servings",
        "ingredients": [
            "2 eggs",
            "80 g melted butter",
            "150 g granulated sugar",
            "200 g plain flour (can be mixed with wholemeal or spelt)",
            "1 sachet baking powder",
            "2 cartons sour cream",
            "1 carton whipping cream (30%)",
            "40 g vanilla pudding powder",
            "5 pears (or apples, raspberries, peaches — fresh or frozen fruit)",
        ],
        "steps": [
            "Mix one egg, the butter, 50 g sugar, flour and baking powder. Work the dough by hand and press it into a cake tin lined with baking paper (a crumbly dough is fine — just press it in).",
            "Peel the pears, slice them and spread over the dough.",
            "In a bowl combine the sour cream, whipping cream, pudding powder, 100 g sugar and the second egg; pour over the cake.",
            "Bake in the middle of an oven preheated to 180 °C for about 45 minutes.",
        ],
        "notes": [],
    },
    "sisky-s-makem-recept": {
        "name": "Poppy-seed rolls (šišky s mákem)",
        "teaser": "A traditional sweet supper from potato dough: rolls coated in poppy seeds and sugar, drizzled with melted butter.",
        "title": "Potato-dough poppy-seed rolls — recipe",
        "desc": "Poppy-seed rolls (šišky) from Jůzlová potato dough: a quick traditional sweet supper with ground poppy seeds, sugar and melted butter.",
        "product": "bramborove_knedliky",
        "meta": "From Jůzlová potato dough",
        "ingredients": [
            '400 g potato dumpling powder',
            '100 g ground poppy seeds',
            '2 tablespoons icing sugar (or more)',
            '2 tablespoons melted butter',
        ],
        "steps": [
            'Mix the potato dumpling powder with water per the instructions and shape small rolls from the dough.',
            'Bake on a greased tray in the middle of an oven preheated to 200 °C; turn once during baking so both sides turn golden.',
            'After baking, drop the rolls into boiling water and scald for 5 minutes.',
            'Put them in a large bowl, dust with poppy seeds and sugar, pour over the butter, toss and serve warm.',
        ],
        "notes": [],
    },
    "strapacky-se-zelim-a-slaninou-recept": {
        "name": "Strapačky with cabbage and bacon",
        "teaser": "A Slovak classic from hairy-dumpling mix — halušky with sauerkraut and crispy bacon.",
        "title": "Strapačky with sauerkraut and bacon — bosáky mix recipe",
        "desc": "Strapačky from Jůzlová hairy-dumpling powder with sauerkraut, spring onion and bacon fried in lard. A hearty Slovak classic.",
        "product": "chlupate_knedliky",
        "meta": "From Jůzlová hairy-dumpling mix",
        "ingredients": [
            '400 g hairy dumpling (bosáky) powder',
            '400 g sauerkraut',
            'a bunch of spring onions',
            '100 g bacon',
            'a spoonful of lard',
        ],
        "steps": [
            'Mix the hairy dumpling powder with water per the instructions. Press the swollen dough through a colander straight into boiling water and cook the halušky until they float.',
            "Boil the sauerkraut in a pot of water for about 10 minutes; drain any water that hasn’t boiled off.",
            'Fry diced bacon in lard; once lightly crisped, add sliced spring onion and take the pan off the heat after a minute.',
            'Mix the halušky with the cabbage and top each plate with the bacon and onion.',
        ],
        "notes": [],
    },
    "podle-lucie-kuzelovebebe-rezy-s-cokoladovym-pudingem": {
        "name": "Bebe biscuit slices with chocolate pudding",
        "teaser": "Want to treat your guests but you’re no Jamie Oliver? These no-bake biscuit slices are for everyone.",
        "title": "Bebe biscuit slices with chocolate pudding — no-bake recipe",
        "desc": "No-bake bebe biscuit slices with chocolate pudding, after Lucie Kůželová: biscuits, pudding cream and whipped cream. No oven needed.",
        "product": "kakao_holandskeho_typu",
        "meta": "No-bake dessert · After Lucie Kůželová",
        "ingredients": [
            '4 packs of BEBE biscuits: 2 plain, 2 dark',
            '2 cartons sour cream',
            '1 carton whipping cream',
            '40 g vanilla sugar',
            '150 g chocolate pudding powder (3 sachets)',
            '1 litre milk',
            'Dutch-process cocoa for dusting',
        ],
        "steps": [
            'Line a tray with the plain bebe biscuits.',
            'Cook the chocolate pudding per the pack instructions and pour it evenly over the biscuits.',
            'Lay the dark bebe biscuits over the pudding layer.',
            'Whip the cream with the vanilla sugar until stiff, fold in the sour cream and spread the mixture over the biscuits.',
            'Dust with dark cocoa and let it rest in the fridge, ideally overnight.',
        ],
        "notes": ['Tip: if you have a different pudding on hand, experiment — the slices are excellent with vanilla pudding and a cinnamon dusting.'],
    },
    "bramborovo-tvarohove-knedliky-s-jahodami": {
        "name": "Potato-and-curd dumplings with strawberries",
        "teaser": "Summer is here, and with it ripening strawberries. A simple 20-minute recipe that delights the sweetest tooth.",
        "title": "Potato-curd dumplings with strawberries — 20-minute recipe",
        "desc": "Fruit dumplings from Jůzlová potato dough with curd cheese and strawberries, after Lucie Kůželová. Ready in 20 minutes.",
        "product": "bramborove_knedliky",
        "meta": "20 minutes · After Lucie Kůželová",
        "ingredients": [
            '250 g potato dumpling powder',
            '250 g soft curd cheese (the block kind, not the tub)',
            'strawberries (for filling and garnish)',
            'sugar, butter and curd for garnish',
        ],
        "steps": [
            'Mix the potato dumpling powder with water per the instructions into a supple dough; work in the curd cheese (a sticky dough is fine).',
            'Shape the dough into a log and cut equal pieces so the dumplings cook evenly.',
            'Round each piece, press into a disc, push a strawberry into the middle and wrap it up.',
            'Steam the dumplings for 5 minutes — steaming cooks the dough through without it falling apart.',
            'Meanwhile simmer some strawberry pieces for a garnish. Serve topped with butter, sugar, strawberries or curd.',
        ],
        "notes": [],
    },
    "rychle-venecky-ci-vetrnicky-recept": {
        "name": "Quick choux wreaths or puffs",
        "teaser": "One choux pastry for both věnečky and větrníčky: extra butter and a 250 °C start. About 80 pieces on two trays.",
        "title": "Quick choux wreaths or puffs — recipe",
        "desc": "Quick Czech věnečky and větrníčky from choux pastry: 250 ml water, 90 g butter, 140 g coarse flour, 4 eggs. 45 min prep, about 15 min baking, around 80 pieces.",
        "meta": "Prep 45 min · Bake about 15 min · about 80 pieces · 2 trays",
        "ingredients": [
            "250 ml water",
            "a pinch of salt",
            "90 g butter",
            "140 g coarse flour (hrubá mouka)",
            "4 eggs",
            "fat, for greasing the trays",
        ],
        "steps": [
            "Bring the water, salt and butter to a boil.",
            "Reduce the heat and stir in the flour all at once; mix until the dough pulls cleanly away from the pan and is no longer sticky.",
            "Take it off the heat and let it cool slightly.",
            "Preheat the oven to 250 °C.",
            "Beat in the eggs one at a time, mixing continuously, until the batter is smooth and slightly elastic.",
            "Pipe onto greased trays: wreaths as two stacked rings for věnečky, or small round mounds for větrníčky.",
            "Bake at 250 °C for 5 minutes, then reduce to 200 °C and bake until golden — roughly 5 more minutes at the higher heat and 5 at the moderate heat. Do not open the oven door while baking.",
            "Slice immediately while still hot (this keeps the shells from tearing later). Cool completely before filling.",
        ],
        "notes": [
            "The filling is left open: sweetened whipped cream is the simplest. For věnečky use the vanilla buttercream and rum glaze from the wreath recipe; for větrníčky use the vanilla pudding cream, caramel whipped cream and caramel glaze from the caramel větrník recipe.",
            "This dough uses a higher butter-to-flour ratio (90 g : 140 g) and a hot 250 °C start, which is why it puffs faster and more reliably.",
        ],
    },
    "venecky-s-vanilkovym-kremem-recept": {
        "name": "Choux wreaths with vanilla cream",
        "teaser": "Classic věnečky from choux pastry with vanilla buttercream and rum glaze. About 20 pieces.",
        "title": "Czech věnečky with vanilla cream and rum glaze — recipe",
        "desc": "Choux-pastry věnečky with vanilla buttercream made from pudding powder and egg yolks, finished with rum glaze. About 20 pieces.",
        "product": "vanilkovy_pudink",
        "meta": "About 20 pieces · choux pastry, vanilla cream, rum glaze",
        "ingredients": [
            "Choux pastry: 320 ml water",
            "100 g butter",
            "a pinch of salt",
            "235 g flour",
            "4–5 eggs, added gradually",
            "Vanilla buttercream: 500 ml milk",
            "2 sachets vanilla pudding powder",
            "5 egg yolks",
            "150 g sugar",
            "250 g softened butter",
            "2 tablespoons rum (optional)",
            "Rum glaze: 300 g icing sugar",
            "2 tablespoons rum",
            "3 tablespoons hot milk",
        ],
        "steps": [
            "Bring the water, butter and salt to a boil. Take off the heat, stir in all the flour, then cook 2–3 minutes on low heat until it pulls into a ball.",
            "Cool until just warm. Beat in the eggs a little at a time until the dough falls from a spoon in a thick ribbon.",
            "Pipe 6–7 cm rings onto baking paper. Bake at 200 °C for 10 minutes without opening the door, then reduce to 180 °C for another 15–25 minutes until deep golden and dry to the touch.",
            "Cool completely, then ideally leave uncovered for a few hours or overnight so the shells stay crisp.",
            "Cook the pudding with the milk, sugar and yolks, stirring constantly, until thickened (do not let it boil hard once the yolks are in). Cool completely, pressing cling film onto the surface.",
            "Beat the softened butter until fluffy, then add the cooled pudding a spoonful at a time until smooth and light. Stir in the rum.",
            "Whisk the icing sugar, rum and hot milk to a smooth, pourable glaze.",
            "Slice the rings horizontally. Pipe the buttercream generously into the bottom half, replace the top, and dip the top in rum glaze. Let it set.",
        ],
        "notes": [
            "Lighter variant: skip the rum glaze, use a plain pudding cream instead of buttercream, and top with whipped cream and a dusting of icing sugar.",
        ],
    },
    "kremrole-recept": {
        "name": "Cream horns (kremrole)",
        "teaser": "Flaky pastry tubes filled with glossy Italian meringue. About 35–40 pieces; you will need metal cream-horn tubes.",
        "title": "Czech kremrole with Italian meringue — recipe",
        "desc": "Butter-pastry cream horns filled with Italian meringue. About 35–40 pieces, bake 12–15 minutes at 180–200 °C.",
        "meta": "About 35–40 pieces · bake 12–15 min · metal tubes",
        "ingredients": [
            "Dough: 350 g flour",
            "250 g cold butter (or Hera shortening), grated or cubed",
            "125 ml whipping cream",
            "optional, for extra flakiness: swap 25 g of the cream for sour cream",
            "Italian meringue: 80 g egg whites (about 2 eggs)",
            "160 g sugar",
            "40 ml water",
            "icing sugar, for dusting",
        ],
        "steps": [
            "Work the flour, butter and cream into a smooth dough — don’t overwork it. Wrap and chill at least 1 hour (overnight is fine).",
            "Roll into a thin sheet, cut into 2 cm × 20 cm strips, and wind each strip around a greased metal tube, overlapping the edges slightly.",
            "Bake at 180–200 °C until golden, about 12–15 minutes. Cool slightly before easing off the tubes.",
            "Heat the sugar and water to 115–120 °C without stirring (a sugar thermometer helps). Meanwhile whip the egg whites to stiff peaks.",
            "With the mixer running, drizzle in the hot syrup in a thin stream, then keep beating until the meringue is glossy and only slightly warm. Chill briefly, then pipe into the cooled shells from both ends. Dust with icing sugar.",
        ],
        "notes": [
            "Simplest version: whip the egg whites with the sugar directly over a pot of simmering water (bain-marie) until glossy and thick — no thermometer needed, slightly less stable but reliably good.",
            "You can improvise tubes from foil if you have no metal cream-horn moulds.",
        ],
    },
    "minivetrnicky-recept": {
        "name": "Mini choux buns (minivětrníčky)",
        "teaser": "Mini větrníčky from choux pastry with a butter-pudding-curd cream and chocolate glaze. About 40–45 pieces.",
        "title": "Mini větrníčky with pudding cream and chocolate glaze — recipe",
        "desc": "Mini větrníčky from choux pastry: 250 ml water, 90 g butter, 160 g flour, 4 eggs. Filling of vanilla pudding, butter and curd, topped with chocolate glaze. About 40–45 pieces.",
        "product": "vanilkovy_pudink",
        "meta": "About 40–45 pieces · bake about 20 min",
        "ingredients": [
            "Choux pastry: 250 ml water",
            "a pinch of salt",
            "90 g butter",
            "160 g flour",
            "1 teaspoon baking powder",
            "4 eggs",
            "Filling: 0.5 l milk",
            "2 sachets vanilla pudding powder",
            "3 tablespoons sugar",
            "250 g softened butter",
            "125 g sugar",
            "vanilla sugar",
            "2 teaspoons rum",
            "about 150–200 g full-fat curd cheese (tvaroh)",
            "Glaze: dark or milk chocolate (with a little butter or oil for shine)",
        ],
        "steps": [
            "Bring the water, butter and salt to a boil. Off the heat, stir in the flour and baking powder until smooth, then stir over low heat until the dough cools slightly.",
            "Beat in the eggs one at a time with a mixer. Pipe small 2–3 cm mounds onto baking paper (two spoons work if you have no piping bag).",
            "Bake at 200 °C for about 20 minutes. Do not open the oven for the first 10 minutes.",
            "Cook the pudding and cool it completely (a few hours ahead is fine). Beat the softened butter with the sugar and vanilla sugar until fluffy, add the rum, then fold in the cooled pudding and curd a little at a time until smooth.",
            "Split the cooled buns three-quarters of the way through, pipe in the filling, and dip or coat the top with melted chocolate.",
        ],
        "notes": [
            "Lighter summer alternative: skip the buttercream and glaze — fill with sweetened whipped cream and fresh strawberry pieces, dust with icing sugar.",
        ],
    },
    "karamelove-vetrniky-recept": {
        "name": "Caramel větrníky",
        "teaser": "Větrníky with vanilla pudding cream, caramel whipped cream and caramel glaze. About 24 medium pieces.",
        "title": "Caramel větrníky with two creams — recipe",
        "desc": "Caramel větrníky from choux pastry: vanilla pudding cream, caramel whipped cream and caramel glaze. About 24 medium pieces.",
        "product": "vanilkovy_pudink",
        "meta": "About 24 medium pieces · make the caramel cream a day ahead",
        "ingredients": [
            "Choux pastry: 250 ml water",
            "100 g butter",
            "a pinch of salt",
            "160 g flour",
            "4–5 eggs (room temperature), whisked, added gradually",
            "½ teaspoon baking powder",
            "Vanilla pudding cream: 400 ml milk",
            "1 sachet vanilla pudding powder",
            "3 tablespoons sugar",
            "250 ml whipping cream (33%), whipped stiff",
            "Caramel whipped cream: 150 g sugar",
            "250 ml whipping cream (33%), cold, plus a splash more to deglaze",
            "a pinch of salt",
            "Caramel glaze: 125 g sugar",
            "45 g butter",
            "75 ml whipping cream",
            "optional: 3–4 tablespoons of the reserved caramel cream, thinned with a little icing sugar",
        ],
        "steps": [
            "Bring the water, butter and salt to a boil. Remove from the heat, add all the flour at once, stir vigorously, then return to low heat 2–3 minutes until the dough pulls into a ball and a thin film forms on the pot bottom.",
            "Spread the dough around the sides of a mixing bowl to cool it quickly. Once only warm (not hot — eggs will scramble), beat in the whisked eggs a little at a time on low speed. Stop when the dough falls off a spoon in a thick “V” — you may not need all the egg. Fold in the baking powder last.",
            "Pipe 4–5 cm rounds onto baking paper with a large star tip, spaced well apart. Bake at 200–220 °C for 10 minutes, then reduce to 170–180 °C for another 15–20 minutes until deep golden and firm. Do not open the oven door during baking — the buns will collapse. Cool completely before filling.",
            "Cook the pudding with the milk and sugar per the packet; cool completely (press cling film onto the surface). Fold in the whipped cream once both are cold.",
            "Melt the sugar dry in a pan (no stirring, just swirl) until deep amber. Off the heat, carefully pour in a splash of the cream — it will bubble violently — then stir in the rest and a pinch of salt. Cool completely, chill several hours or overnight, then whip to stiff peaks. Reserve 3–4 tablespoons for the glaze.",
            "Caramelize the glaze sugar the same way, remove from the heat, stir in the butter then the cream until smooth and glossy. Cool until it coats the back of a spoon but is still pourable.",
            "Slice each cooled bun horizontally, keeping the top as a cap. Pipe a base of vanilla pudding cream, a swirl of caramel whipped cream on top, replace the cap and dip or spoon the caramel glaze over. Chill at least 2 hours before serving so the layers set.",
        ],
        "notes": [
            "Add eggs to the choux only once it has cooled to warm, and add them gradually — flour absorbs liquid differently batch to batch, so judge doneness by texture, not by using all the egg.",
            "Never open the oven while baking. Make the caramel cream a day ahead so it has time to firm up enough to whip.",
        ],
    },
    "irsky-sticky-toffee-pudding-recept": {
        "name": "Irish sticky toffee pudding",
        "teaser": "A moist date pudding with Dutch-process cocoa and Baileys, finished with a salty toffee sauce. Serves 6.",
        "title": "Irish sticky toffee pudding with cocoa and Baileys — recipe",
        "desc": "Sticky toffee pudding after Donal Skehan, with Dutch-process cocoa and 100 ml Baileys in the batter. Serves 6, bake 45–50 minutes at 160 °C.",
        "product": "kakao_holandskeho_typu",
        "meta": "Serves 6 · Bake 45–50 min · 160 °C",
        "ingredients": [
            "Pudding: 125 g butter",
            "150 g light muscovado sugar",
            "1 tablespoon golden syrup",
            "1 tablespoon black treacle",
            "2 large eggs",
            "1 teaspoon vanilla extract",
            "150 g self-raising flour",
            "60 g Dutch-process cocoa",
            "150 g Medjool dates, chopped",
            "2 teaspoons bicarbonate of soda",
            "100 ml Baileys Irish Cream",
            "180 ml water",
            "vanilla ice cream, for serving",
            "Toffee sauce: 100 g unsalted butter",
            "150 g dark muscovado sugar",
            "3 tablespoons golden syrup",
            "150 ml double cream",
            "1 teaspoon vanilla extract",
            "a generous pinch of sea salt",
        ],
        "steps": [
            "Heat the oven to 160 °C (140 °C fan). Grease a 20 cm round ovenproof dish.",
            "Beat the butter and sugar until light and fluffy.",
            "Mix in the golden syrup, treacle, eggs and vanilla, slowly, on low speed.",
            "Sift the self-raising flour and cocoa together, then fold into the mixture on low speed.",
            "Simmer the 180 ml water with the chopped dates for a few minutes, take off the heat, then stir in the Baileys and the bicarbonate of soda — it will foam up.",
            "Fold the hot date-Baileys mixture into the flour-cocoa batter, pour into the prepared dish, and bake 45–50 minutes, until firm and slightly springy. Check with a skewer for a few moist crumbs rather than judging by colour — the batter is dark.",
            "For the sauce: melt the butter, sugar and golden syrup until the sugar dissolves. Add the cream, vanilla and salt, and simmer 3 minutes until thickened. For extra Irish flavour, stir 1–2 tablespoons of Baileys into the sauce off the heat at the end (optional — the alcohol will not cook off once the sauce is off the heat).",
            "Drizzle the toffee sauce over the warm pudding and serve with vanilla ice cream.",
        ],
        "notes": [
            "The Baileys goes in after the date-water simmer, off the heat — prolonged boiling would drive off the alcohol and mute the cream-liqueur taste.",
            "The water is 100 ml less than the original recipe (180 ml instead of 280 ml), matching the Baileys added so the batter hydration — and the bake time — stay the same.",
        ],
    },
}
